### ISSUE TITLE
TooManyRequestsException: Too Many Requests

### ISSUE THREAD

**Issue by yzarubin** [aws/aws-sdk-js#1014]
I'm constantly getting `TooManyRequestsException: Too Many Requests` when using the APIGateway methods, and it does not appear the SDK is retrying the requests. Below are the logs from tests.
```
  apigateway.test
Cleaning up apis
[AWS apigateway 200 0.808s 0 retries] getRestApis({})
    getAPIByName
[AWS apigateway 200 0.412s 0 retries] getRestApis({})
      ✓ should return null (414ms)
    createAPI
[AWS apigateway 201 0.599s 0 retries] createRestApi({ name: 'corsair_test_1465312520495',
  description: 'corsair_int_test_createAPI' })
[AWS apigateway 202 0.921s 0 retries] deleteRestApi({ restApiId: 'cgm3zjcbp8' })
[AWS apigateway 200 0.406s 0 retries] getRestApis({})
      ✓ should create an API and delete it (2933ms)
    updateOrCreateAPI
[AWS apigateway 200 0.421s 0 retries] getRestApis({})
[AWS apigateway 429 0.403s 0 retries] createRestApi({ name: 'corsair_test_1465312523931',
  description: 'corsair_int_test_updateOrCreateAPI' })

     TooManyRequestsException: Too Many Requests
      at Object.extractError (node_modules/aws-sdk/lib/protocol/json.js:43:27)
      at Request.extractError (node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:105:20)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:615:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:617:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:615:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
```

**Comment by yzarubin** [comment]
I should note that the behavior is non-deterministic (sometimes the tests pass), and it consistently happens in the scenario where I call `getRestApis()` followed by a `createRestApi()` or `deleteRestApi`.

**Comment by chrisradek** [comment]
@yzarubin 
Thanks for creating this issue. The SDK will automatically retry when the status code returned in the response is >= 500, or the error code matches a defined list:
https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L367

I can reach out to the API Gateway team to find out if they want built in retry support for this type of error. Their docs seem to suggest they would:
https://docs.aws.amazon.com/apigateway/api-reference/handling-errors/

As a work-around, there is a way to make additional errors retryable. Instead of passing in a callback to your operation, you can grab a reference to an AWS.Request object and bind a callback to the extractError event. In this callback, you can set the error to retryable.

Quick example:
```javascript
var req = apigateway.createRestApi(params);
req.on('extractError', function(response) {
  var error = response.error;
  if (error.code === 'TooManyRequestsException') {
    error.retryable = true;
  }
});
//Add custom retry delay as well
req.on('retry', function(response) {
  var error = response.error;
  if (error.code === 'TooManyRequestsException') {
    // override retry delay to be 1 second
    error.retryDelay = 1000;
  }
});
req.send(function(err, data) {});
```

**Comment by mvayngrib** [comment]
i just hit this, putRestApi returns TooManyRequestsException no matter how many times I retry it, with a simple 5-second backoff.

**Comment by albinekb** [comment]
I'm also hitting this, deploying 3x parallel will always give me `TooManyRequestsException`, I think the rate limit is a bit too tight.
