### ISSUE TITLE
error while accessing aws s3 bucket

### ISSUE THREAD

**Issue by skk2142** [aws/aws-sdk-js#1022]
* node version: **v6.2.0**:
* OS version: **Linux surajPC 4.2.0-36-generic #42~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux**:

I'm using the code below
```javascript
//this code in fileA.js
var aws = require('aws-sdk'),
  http = require('http'),
  fs = require('fs'),
  path = require('path'),
  express = require('express');

var app = new express();

var config_path = path.join(__dirname, '../auth.json');

aws.config.loadFromPath(config_path);
var s3 = new aws.S3();

app.get('/buckets', function (req, res) {
  s3.listBuckets(function (err, data) {
    res.json(data);
  });
});

module.exports = app;

//Then I call this module in another file
var app = require('./fileA'),
  http = require('http');

http.createServer(app).listen(3000, function(){
  console.log('Server listening on port 3000');
});
```
Once I access the localhost:3000/buckets, I get the following error:
```sh
TypeError: Cannot read property 'length' of null
    at Object.AWS.util.buffer.concat (/home/suraj/Desktop/server/node_modules/aws-sdk/lib/util.js:116:29)
    at Request.HTTP_DONE (/home/suraj/Desktop/server/node_modules/aws-sdk/lib/event_listeners.js:214:36)
    at Request.callListeners (/home/suraj/Desktop/server/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
    at Request.emit (/home/suraj/Desktop/server/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
    at Request.emitEvent (/home/suraj/Desktop/server/node_modules/aws-sdk/lib/request.js:408:10)
    at IncomingMessage.onEnd (/home/suraj/Desktop/server/node_modules/aws-sdk/lib/event_listeners.js:184:26)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```
I'm not sure if this has anything to do with the warning I get when I npm install aws -sdk
```sh
npm WARN amazons3@0.0.0 No repository field.
npm WARN amazons3@0.0.0 license should be a valid SPDX license expression
```

**Comment by LiuJoyceC** [comment]
Hi @skk2142 
Could you tell us what version of the aws-sdk you are using? The line numbers from your stack trace don't match up with the latest version (`2.3.19`).
It looks like the error is coming from the line `length += buffers[i].length` because `buffers`, an array of Buffer instances, contains at least one `null` instead of a Buffer. The `buffers` comes from the response (`resp.httpResponse.buffers` from the `HTTP_DONE` event listener). I'll need to investigate why this array contains a `null`.

**Comment by skk2142** [comment]
Never mind, I was using a very old version. The current version works fine.

**Comment by LiuJoyceC** [comment]
I'm glad everything is working for you with the updated version!
