### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by shesko** [aws/aws-sdk-js#1026]
Hello,
I get the following error when I try to call the listBuckets function 

```
/Users/ShEsKo/Desktop/S3/node_modules/aws-sdk/lib/sequential_executor.js:261
        throw err;
        ^

TypeError: Cannot read property 'length' of null
    at Object.AWS.util.buffer.concat (/Users/ShEsKo/Desktop/S3/node_modules/aws-sdk/lib/util.js:116:29)
    at Request.HTTP_DONE (/Users/ShEsKo/Desktop/S3/node_modules/aws-sdk/lib/event_listeners.js:214:36)
    at Request.callListeners (/Users/ShEsKo/Desktop/S3/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
    at Request.emit (/Users/ShEsKo/Desktop/S3/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
    at Request.emitEvent (/Users/ShEsKo/Desktop/S3/node_modules/aws-sdk/lib/request.js:408:10)
    at IncomingMessage.onEnd (/Users/ShEsKo/Desktop/S3/node_modules/aws-sdk/lib/event_listeners.js:184:26)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
```

This is the code I am using:

```
var aws = require('aws-sdk'),
  http = require('http'),
  fs = require('fs'),
  path = require('path'),
  express = require('express');

var app = new express();

app.set('views', __dirname + '/views');
app.set('view engine', 'jade');
app.use(express.bodyParser());
app.use(express.static(path.join(__dirname, 'public')));

var config_path = path.join(__dirname, '../auth.json');

aws.config.loadFromPath(config_path);
var s3 = new aws.S3();

app.get('/buckets', function (req, res) {
  s3.listBuckets(function (err, data) {
    res.json(data);
  });
});


module.exports = app;
```

These are my dependencies:

```
"dependencies": {
    "aws-sdk": "~1.3.0",
    "express": "~3.2.6",
    "jade": "~0.31.2"
  }
```

And my node version is v4.4.3

I can see that people have had this issue in the past years but all the solutions don't seem to work for me. Any idea on what I could do? 

I realised by messing around with the auth.json file that even when I put the wrong credentials it gives the same error. Could it be that I am doing something wrong with my credentials data?

**Comment by chrisradek** [comment]
@shesko 
It looks like you are using version 1.3 of the SDK. It's currently at version 2.4.1. Can you try updating the SDK and seeing if the problem still exists?

**Comment by shesko** [comment]
Yep, that was it. Next time I follow a tutorial I'll double check that the versions are up to date.

Thanks!
