### ISSUE TITLE
error after manually closing getObject read stream

### ISSUE THREAD

**Issue by Jarvie8176** [aws/aws-sdk-js#1087]
## versions

node: `6.2.2`
aws-sdk: `^2.4.12`

## goal

to close read stream upon error when writing streamed data to file to prevent bandwitch waste.

sample code:

``` javascript
var readStream = s3.getObject({...}).createReadStream();
var writeStream = getWriteStreamSomehow();

writeStream.on('error', function() {
    readStream.end();
})

readStream.on('error', function() {
    console.log(error);
})
```

then upon writeStream emitting error i got an error in readStream:

```
Error: write after end
    at writeAfterEnd (_stream_writable.js:166:12)
    at PassThrough.Writable.write (_stream_writable.js:217:5)
    at PassThrough.ondata (_stream_readable.js:561:20)
    at emitOne (events.js:96:13)
    at PassThrough.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at PassThrough.Readable.push (_stream_readable.js:130:10)
    at PassThrough.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:77:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at PassThrough._transform (_stream_passthrough.js:21:3)
    at PassThrough.Transform._read (_stream_transform.js:167:10)
    at PassThrough.Transform._write (_stream_transform.js:155:12)
    at PassThrough.lengthAccumulator._write (./node_modules/aws-sdk/lib/request.js:612:59)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
```

I probably didn't close / unpipe the readStream properly, since AWS request is still attempting to write to a closed readStream.

**Comment by LiuJoyceC** [comment]
Hi @Jarvie8176 

Thanks for opening an issue. I will investigate this error.

**Comment by mcprostar205** [comment]
I open [#1601](https://github.com/aws/aws-sdk-js/issues/1601) on a similar behavior was there a resolution to this issue?
