### ISSUE TITLE
I cannot create credentials by using loadFromPath or hard code

### ISSUE THREAD

**Issue by chinclubi** [aws/aws-sdk-js#1190]
Here is my first version which used loadFromPath function

```javascript
const AWS = require("aws-sdk")
const config = AWS.config.loadFromPath("...../s3.config.json")

function Upload() {
  var s3 = new AWS.S3(config)
  var params = {
      Bucket: "my-image"
      Key: "test.txt",
      Body: "HelloWorld"
  }
  s3.putObject(params, function (err, res) {
      if (err) {
          console.log("Error uploading data: ", err)
      } else {
          console.log("Success")
      }
  })
}
```

s3.config.json
```json
{
  "accessKeyId": "someKey", 
  "secretAccessKey": "secret", 
  "region": "ap-southeast-1"
}
```

Then, I try to use hard-code style which is not recommended in [docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html)

```javascript
const AWS = require("aws-sdk")
const config = AWS.config.update({
  accessKeyId: 'someKey', 
  secretAccessKey: 'secret', 
  region: 'ap-southeast-1'
})

function Upload() {
  var s3 = new AWS.S3(config)
  var params = {
      Bucket: "my-image"
      Key: "test.txt",
      Body: "HelloWorld"
  }
  s3.putObject(params, function (err, res) {
      if (err) {
          console.log("Error uploading data: ", err)
      } else {
          console.log("Success")
      }
  })
}
```

Both of them doesn't work for me. Check an error below.

````
Error uploading data:  { Error: connect ENETUNREACH 169.254.169.254:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  errno: 'ENETUNREACH',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2016-10-15T17:41:14.091Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     errno: 'ENETUNREACH',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2016-10-15T17:41:14.091Z,
     originalError:
      { code: 'ENETUNREACH',
        errno: 'ENETUNREACH',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,
        message: 'connect ENETUNREACH 169.254.169.254:80' } } }
````
I try to use the shared credentials file. It's work, but I don't want to use the shared credentials file or environment variables because it's not suitable for my case. Anyone know how to fix this? 

Thank you.

**Comment by shruthibhaskar** [comment]
Hi,
Did you find the solution for this problem?
i am facing the same problem. Kindly let me know your solution.
