### ISSUE TITLE
Big file upload: TypeError: Cannot read property 'Object.<anonymous>' of null.  

### ISSUE THREAD

**Issue by 1msoft** [aws/aws-sdk-js#1255]
upload small file ok. when big file upload 

{ TypeError: Cannot read property 'Object.<anonymous>' of null
        at Runtime._runScript (/node_modules/jest-runtime/build/index.js:458:49)
        at Runtime._execModule (/node_modules/jest-runtime/build/index.js:440:26)
        at Runtime.requireModule (/node_modules/jest-runtime/build/index.js:297:14)
        at Runtime.requireModuleOrMock (/node_modules/jest-runtime/build/index.js:366:19)
        at XMLElement.XMLNode (/node_modules/xmlbuilder/lib/XMLNode.js:39:18)
        at new XMLElement (/node_modules/xmlbuilder/lib/XMLElement.js:27:40)
        at new XMLBuilder (/node_modules/xmlbuilder/lib/XMLBuilder.js:24:14)
        at Object.<anonymous>.module.exports.create (/node_modules/xmlbuilder/lib/index.js:11:12)
        at XmlBuilder.Object.<anonymous>.XmlBuilder.toXML (/node_modules/aws-sdk/lib/xml/builder.js:7:21)
        at populateBody (/node_modules/aws-sdk/lib/protocol/rest_xml.js:23:36)
      message: 'Cannot read property \'Object.<anonymous>\' of null',
      code: 'TypeError',
      time: 2016-12-06T15:53:07.179Z }

**Comment by 1msoft** [comment]
```       
            let Body = file.contents
            let queueSize = options.queueSize
            let partSize = options.partSize
            self.emit('upload_begin', file)
            s3.upload({Bucket, Key, Body}, {queueSize, partSize}, done)
```

**Comment by 1msoft** [comment]
macOS 10.12
nodejs 6.9.1

**Comment by 1msoft** [comment]
when file.size > 5*1024*1024, raise TypeError.

**Comment by chrisradek** [comment]
@1msoft 
What did you set as the queueSize and partSize?
Are you seeing this consistently for files larger than 5 MB?
Can you instantiate your S3 client to add some additional logging?
```javascript
var s3 = new AWS.S3({
  logger: console
});
```
This might give us some clues additional clues.

**Comment by 1msoft** [comment]
Thank you.
{queueSize: 1, partSize: 5*1024*1024}

console.log __test__/aws-lib.test.js:106
    upload begin: /Users/william/projects/Accuragen/CloudAG/__test__/aws_uploads/guaranty.sql

  console.log node_modules/aws-sdk/lib/event_listeners.js:450
    [AWS s3 200 0.212s 0 retries] createMultipartUpload({ Bucket: 'ag-cloud', Key: 'Big_file_test/guaranty.sql' })

  console.log node_modules/aws-sdk/lib/event_listeners.js:450
    [AWS s3 200 6.328s 0 retries] uploadPart({ Body: <Buffer 2f 2a 0d 0a 4e 61 76 69 63 61 74 20 4d 79 53 51 4c 20 44 61 74 61 20 54 72 61 6e 73 66 65 72 0d 0a 0d 0a 53 6f 75 72 63 65 20 53 65 72 76 65 72 20 20 ... >,
      ContentLength: 5242880,
      PartNumber: 1,
      Bucket: 'ag-cloud',
      Key: 'Big_file_test/guaranty.sql',
      UploadId: 'kRmm92OHoiAGdqii6CXzKb4mzWUtYVPbWllQ8UWW4Q7elTcHj_x3cVmhxFROt3IKU8G64CgoTRIwAZ_7CHCb9uvEUdd45kLmXcim2gKnDAqPsFog.yYPjdQ7xKYlOseq' })

  console.log node_modules/aws-sdk/lib/event_listeners.js:450
    [AWS s3 200 6.302s 0 retries] uploadPart({ Body: <Buffer 6c 2c 20 6e 75 6c 6c 2c 20 6e 75 6c 6c 2c 20 27 32 30 31 35 2d 31 34 2d 38 2d 4a 27 2c 20 6e 75 6c 6c 2c 20 27 31 32 32 30 27 2c 20 27 31 27 2c 20 27 ... >,
      ContentLength: 5242880,
      PartNumber: 2,
      Bucket: 'ag-cloud',
      Key: 'Big_file_test/guaranty.sql',
      UploadId: 'kRmm92OHoiAGdqii6CXzKb4mzWUtYVPbWllQ8UWW4Q7elTcHj_x3cVmhxFROt3IKU8G64CgoTRIwAZ_7CHCb9uvEUdd45kLmXcim2gKnDAqPsFog.yYPjdQ7xKYlOseq' })

  console.log node_modules/aws-sdk/lib/event_listeners.js:450
    [AWS s3 200 2.464s 0 retries] uploadPart({ Body: <Buffer 27 35 31 39 32 27 29 3b 0d 0a 49 4e 53 45 52 54 20 49 4e 54 4f 20 60 72 65 74 75 72 6e 5f 63 6f 6e 66 69 72 6d 73 60 20 56 41 4c 55 45 53 20 28 27 32 ... >,
      ContentLength: 1867386,
      PartNumber: 3,
      Bucket: 'ag-cloud',
      Key: 'Big_file_test/guaranty.sql',
      UploadId: 'kRmm92OHoiAGdqii6CXzKb4mzWUtYVPbWllQ8UWW4Q7elTcHj_x3cVmhxFROt3IKU8G64CgoTRIwAZ_7CHCb9uvEUdd45kLmXcim2gKnDAqPsFog.yYPjdQ7xKYlOseq' })

  console.log node_modules/aws-sdk/lib/event_listeners.js:450
    [AWS s3 undefined 0.002s 0 retries] completeMultipartUpload({ MultipartUpload:
       { Parts:
          [ { ETag: '"64f398cda677c3f77055061988da2d6d"', PartNumber: 1 },
            { ETag: '"4cbf2107e4dcfcb00145aa6b43858e01"', PartNumber: 2 },
            { ETag: '"62d6f40e43970882f74ddeb4b54e2e3f"', PartNumber: 3 },
            [length]: 3 ] },
      Bucket: 'ag-cloud',
      Key: 'Big_file_test/guaranty.sql',
      UploadId: 'kRmm92OHoiAGdqii6CXzKb4mzWUtYVPbWllQ8UWW4Q7elTcHj_x3cVmhxFROt3IKU8G64CgoTRIwAZ_7CHCb9uvEUdd45kLmXcim2gKnDAqPsFog.yYPjdQ7xKYlOseq' })

  console.log __test__/aws-lib.test.js:99
    { TypeError: XMLText is not a constructor
        at XMLElement.Object.<anonymous>.module.exports.XMLNode.text (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/node_modules/xmlbuilder/lib/XMLNode.js:168:15)
        at XMLElement.Object.<anonymous>.module.exports.XMLNode.txt (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/node_modules/xmlbuilder/lib/XMLNode.js:279:19)
        at serializeScalar (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/xml/builder.js:71:7)
        at serialize (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/xml/builder.js:18:21)
        at Object.<anonymous> (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/xml/builder.js:37:9)
        at Object.arrayEach (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/util.js:477:32)
        at serializeStructure (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/xml/builder.js:23:8)
        at serialize (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/xml/builder.js:15:30)
        at Object.<anonymous> (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/xml/builder.js:59:7)
        at Object.arrayEach (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/util.js:477:32)
      message: 'XMLText is not a constructor',
      code: 'TypeError',
      time: 2016-12-07T01:06:32.322Z }

  console.log __test__/aws-lib.test.js:113
    upload 0 files, and skip 3 files and 1dirs

**Comment by 1msoft** [comment]
set partSize = 20*1024*1024, the file that size < 20M, upload is ok.

**Comment by 1msoft** [comment]
version :2.7.10

**Comment by 1msoft** [comment]
I switch aws-sdk 2.5, 2.6, same problem.

and i wirte a simple test code 
```
        AWS.config.update(awsconfig)
        let s3 = new AWS.S3({logger:console})
        let Body = fs.createReadStream('./__test__/aws_uploads/Dash.zip')
        s3.upload(
            {Bucket: 'ag-cloud', Key: 'sdk_test/Dash.zip', Body}, 
            {queueSize: 4, partSize: 10*1024*1024}, 
            (err,data) => {
               if (err) console.log(err)
               else console.log(data)
            })
```
console.log __test__/aws-lib.test.js:127
    { TypeError: Cannot read property 'Object.<anonymous>' of null
        at Runtime._runScript (/Users/william/projects/Accuragen/CloudAG/node_modules/jest-runtime/build/index.js:458:49)
        at Runtime._execModule (/Users/william/projects/Accuragen/CloudAG/node_modules/jest-runtime/build/index.js:440:26)
        at Runtime.requireModule (/Users/william/projects/Accuragen/CloudAG/node_modules/jest-runtime/build/index.js:297:14)
        at Runtime.requireModuleOrMock (/Users/william/projects/Accuragen/CloudAG/node_modules/jest-runtime/build/index.js:366:19)
        at XMLElement.XMLNode (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/node_modules/xmlbuilder/lib/XMLNode.js:39:18)
        at new XMLElement (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/node_modules/xmlbuilder/lib/XMLElement.js:27:40)
        at new XMLBuilder (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/node_modules/xmlbuilder/lib/XMLBuilder.js:24:14)
        at Object.<anonymous>.module.exports.create (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/node_modules/xmlbuilder/lib/index.js:11:12)
        at XmlBuilder.Object.<anonymous>.XmlBuilder.toXML (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/xml/builder.js:7:21)
        at populateBody (/Users/william/projects/Accuragen/CloudAG/node_modules/aws-sdk/lib/protocol/rest_xml.js:23:36)
      message: 'Cannot read property \'Object.<anonymous>\' of null',
      code: 'TypeError',
      time: 2016-12-07T02:59:37.875Z }

  console.log node_modules/aws-sdk/lib/event_listeners.js:450
    [AWS s3 undefined 0.013s 0 retries] createMultipartUpload({ Bucket: 'ag-cloud', Key: 'sdk_test/Dash.zip' })

**Comment by chrisradek** [comment]
@1msoft 
I'm unable to reproduce your problem using the same version of the SDK and node.js on mac osx.

It looks like the issue is coming from a dependency of `aws-sdk`, `xmlbuilder`. Can you try clearing your node_modules directory and re-running `npm install`? Can you also verify the version of `xmlbuilder` that's being consumed by the SDK?

**Comment by 1msoft** [comment]
xmlbuilder version is 2.6.2, 
I have removed node_modules, and yarn install.

**Comment by 1msoft** [comment]
when i run test in node test.js, that is ok.

so maybe jest

**Comment by wordyallen** [comment]
same issue.. It seems like the Jest Environment makes aws loose access to its C++ Classes
http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_external_1_1tinyxml2_1_1_x_m_l_text.html
