### ISSUE TITLE
Signature mismatch

### ISSUE THREAD

**Issue by OussamaRomdhane** [aws/aws-sdk-js#1256]
```
{ SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Request.extractError (XXXXX/node_modules/aws-sdk/lib/services/s3.js:538:35)
    at Request.callListeners (XXXXX/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (XXXXX/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (XXXXX/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (XXXXX/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (XXXXX/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at XXXXX/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (XXXXX/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (XXXXX/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (XXXXX/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  region: null,
  time: 2016-12-06T16:59:11.528Z,
  requestId: 'D28E9A2844589E83',
  extendedRequestId: 'uDB9DgDICktlz8Zr6gtGW+e1Pvf3q4mFp6GiToo3ePWpwEvTY65RqpIgGG2HtYKbhGMRKlOIx5w=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 152.94541625980597 }
```

This happens frequently for the first request after an "idle time" every request after that passes successfully.
Do you have any idea why is that? 
Thanks

**Comment by OussamaRomdhane** [comment]
@chrisradek can you please help?
I saw a lot of this in the closed issues but none match my case
Thanks

**Comment by chrisradek** [comment]
@OussamaRomdhane 
Is this within Lambda, or a different environment? Where are your credentials being sourced, and what operation are you calling when you see this error?

**Comment by OussamaRomdhane** [comment]
Thanks for the reply I don't know what Heroku uses, but we're running a node 6.x, and we are using this sdk to put objects into an S3 bucket. The aws-sdk version we use is the latest. 

This is mostly it (the part that causes the problem)

```
var s3obj = new AWS.S3({
            signatureVersion: 'v4',
            accessKeyId: bucket.accessKey,
            secretAccessKey: bucket.secret
        });
        s3obj.putObject({
            Bucket: bucket.name,
            Key,
            Body: file
        }).send(function(err, success) {
            if (err) { reject(err); } else { resolve(success); }
        });

```

**Comment by OussamaRomdhane** [comment]
@chrisradek Update: this seems to be caused by not having specified the region parameter in the AWS.S3 initialization 

```
new AWS.S3({
            signatureVersion: 'v4',
            accessKeyId: bucket.accessKey,
            secretAccessKey: bucket.secret,
            region: bucket.region
        });
```

Seems to solve the problem.

**Comment by chrisradek** [comment]
@OussamaRomdhane 
Great! Yes, when using `signatureVersion: 'v4'`, the region is used when signing requests, so the correct region that matches your bucket's location needs to be provided. The SDK has some tricks to try and figure out the correct region, but they aren't fool-proof.

I'm closing this issue since you've solved the problem.

**Comment by OussamaRomdhane** [comment]
@chrisradek thanks for the help mate 😄
