### ISSUE TITLE
S3 life cycle problem

### ISSUE THREAD

**Issue by georgesben** [aws/aws-sdk-js#1261]
Hi everybody !

I have a little problem with my code. I'm trying to put a life cycle to my bucket. To do so, I use this method: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketLifecycleConfiguration-property

And this is my code:
```javascript
exports.createBucket = function (name, acl, region, expirationDays){
    return new Promise(function(resolve, reject){
        let params = {
            Bucket : name,
            ACL: acl,
            CreateBucketConfiguration : {
                LocationConstraint : region
            }
        };
        s3.createBucket(params, function(err, data){
            if (err){
                console.log(err);
                reject(err);
            }
            else{
                if(expirationDays){
                    let params = {
                        Bucket: name, /* required */
                        LifecycleConfiguration: {
                            Rules: [ /* required */
                                {
                                    Status: 'Enabled', /* required */
                                    Expiration: {
                                        Days: expirationDays
                                    },
                                },
                            ]
                        }
                    };
                    console.log("params used is " + JSON.stringify(params));
                    s3.putBucketLifecycleConfiguration(params, function(err, data){
                       if (err){
                           console.log("life cycle problem for bucket");
                           console.log(err);
                           reject(err);
                       }
                       resolve(data);
                    });
                }
                resolve(data);
            }
        })
    });
};
```
I create a bucket and if I specified an expiration date for my files, I add a life cycle rule to my bucket. The params variable printed is the following:
`{"Bucket":"Mybucket","LifecycleConfiguration":{"Rules":[{"Status":"Enabled","Expiration":{"Days":3}}]}}`
Normally, it should be correct. But I have this error:

```
{ MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
    at Request.extractError (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\services\s3.js:538:35)
    at Request.callListeners (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:668:14)
    at Request.transition (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\request.js:670:12)
    at Request.callListeners (E:\GitHub\cloud2\cli\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
  message: 'The XML you provided was not well-formed or did not validate against our published schema',
  code: 'MalformedXML',
  region: null,
  time: 2016-12-12T16:09:42.756Z,
  requestId: '48F88EB389108616',
  extendedRequestId: 'CnUEp2C9lyd4+8NH60bxdalXvwJzyZgkZMm/Vtsk2cpBU3WPohQPPHkYsf7wCiYZdYZW9Ya2E40=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 99.62213168981509 }
```

Does someone understand why I have this error ?

Thank you very much for your help :)

**Comment by georgesben** [comment]
I have found the problem. I have forgotten the `Prefix` field.
