### ISSUE TITLE
headObject throws uncaught error - crashes app

### ISSUE THREAD

**Issue by thanpolas** [aws/aws-sdk-js#1282]
Hello,

Whenever I perform an `s3.headObject` operation on a forbidden or not found asset instead of catching the error in the node callback, AWS sdk throws an error and exits the app.

### Error when forbidden:

```
  orbidden: null
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

The `f` from `forbidden` is actually missing.

### Error when not found:

```
  otFound: null
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

The `N` from `NotFound` is actually missing here too.

I'm using AWS SDK 2.7.18 on node 6.9.1, I've been reproducing this even with custom values, when I can access the file and it is there, the SDK responds properly. Here's my very basic routine:

```js
ProcessDownload.prototype._s3Head = Promise.method(function () {
  return new Promise((resolve, reject) => {
    var params = {
      Bucket: 'www.waldo.photos', // this will work, any change and I get the results i explained
      Key: 'images/pic01.jpg',
    };

    const s3 = new AWS.S3();

    s3.headObject(params, (err, res) => {
      if (err) {
        reject(err);
        return;
      }
      resolve(res);
    });
  });
});
```

**Comment by thanpolas** [comment]
false alarm, the problem was higher up with my Promise error handling.
