### ISSUE TITLE
Timeout Error after 2 min of start of upload

### ISSUE THREAD

**Issue by MandeepKalkhanda** [aws/aws-sdk-js#1294]
Hi,

I am getting exception from SDK after 2 minute of start of upload. Uploading 1K+ files to S3.
Using version 2.6.15 of SDK. This is occurring every time if the upload process take more then 2 minutes.

Below is the traces of the exception.
...\node_modules\aws-sdk\lib\req
uest.js:31
            throw err;
            ^

Error: S3 headObject Error: Error: write EPROTO
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)
    at Request.callListeners (...\node_modules\aws-sdk\lib\sequential_executor.js:108:43)
    at Request.emit (...\node_mo
dules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (...\node_mo
dules\aws-sdk\lib\request.js:668:14)
    at Request.transition (...\n
ode_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (...\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at ...\node_modules\aws-sdk\
lib\state_machine.js:26:10
    at Request.<anonymous> (...\
node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (...\
node_modules\aws-sdk\lib\request.js:670:12)
    at Request.callListeners (...\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (...\node_mo
dules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (...\node_mo
dules\aws-sdk\lib\request.js:668:14)
    at Request.transition (...\n
ode_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (..\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at ...\node_modules\aws-sdk\
lib\state_machine.js:26:10
    at Request.<anonymous> (...\
node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (...\
node_modules\aws-sdk\lib\request.js:670:12)

**Comment by chrisradek** [comment]
@MandeepKalkhanda 
Can you share a code sample that shows how you're uploading your files to S3?

My first thought is that you're hitting the 2 minute timeout for an individual upload:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#httpOptions-property

Are you making `putObject`, or `upload` calls? `upload` will perform a multi-part upload for files larger than 5 MB, and each 'part' then has its own 2 minute timeout. This might be helpful unless you're already using `upload`.

Also, are you uploading files in batches, or all at once? Another potential issue could be that you've created thousands of upload requests, but only have X amount of connections open to S3 at a time. In that case, some of your requests could be waiting over 2 minutes before receiving a socket.

**Comment by MandeepKalkhanda** [comment]
@chrisradek 

I am using gulp-s3-upload package. Which is using putObject and I have set httpOption timeout to 0.

**Comment by chrisradek** [comment]
@MandeepKalkhanda 
The [`gulp-s3-upload`](https://github.com/clineamb/gulp-s3-upload) package is likely a better place to post this issue then. What I stated in the last 2 paragraphs could help with/explain the issue, but since you're using a tool that consumes this SDK, you would need to find a work-around specific to that tool.
