### ISSUE TITLE
nodejs application exception getting caught in aws-sdk

### ISSUE THREAD

**Issue by jeevankk** [aws/aws-sdk-js#131]
I am doing a dynamoDB `query` , if an exception is thrown in the callback passed to the `query` function, the callback gets called again. 

Why does this happen? 

If there is any exception/error in my code then I would like to handle it. But this doesn't happen in this particular case. 

I am attaching the sample test program for above problem. 

The error is caught here 
https://github.com/aws/aws-sdk-js/blob/master/lib/sequential_executor.js#L135 

``` javascript
var AWS = require('aws-sdk');

AWS.config.update("<<AWS_SECRET_KEY>>");
AWS.config.update({region: "<<REGION>>"});

var testclass = function() {}

testclass.prototype.add = function() {
    throw new Error();
};

testclass.prototype.second = function() {
    var thisC=this;
    console.log("Before Error thrown");
    thisC.add();

}

testclass.prototype.perform = function() {
    var thisC = this;

    var queryData = {
        "TableName":"class",
        "Limit":10,
        "KeyConditions":{
            "roll_no":{
                "ComparisonOperator":"EQ",
                "AttributeValueList":[{"N":"38"}]
            },
            "marks":{
                "ComparisonOperator":"GE",
                "AttributeValueList":[{"N":"0"}]
            }
        },
        "AttributesToGet":["name"]
    };

    var dynamodb = new AWS.DynamoDB();

    dynamodb.query(queryData, function (err, data) {
        console.log("query callback")
        thisC.second();
    });

};

var obj = new testclass();
obj.perform();
```

Output

```
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown
query callback
Before Error thrown

/home/john/tmp/node_modules/aws-sdk/lib/sequential_executor.js:261
        throw err;
              ^
Error
    at testclass.add (/home/john/tmp/program.js:16:8)
    at testclass.second (/home/john/tmp/program.js:22:8)
    at Response.<anonymous> (/home/john/tmp/program.js:49:9)
    at Request.<anonymous> (/home/john/tmp/node_modules/aws-sdk/lib/service.js:123:18)
    at Request.callListeners (/home/john/tmp/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
    at Request.emit (/home/john/tmp/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
    at Request.emitEvent (/home/john/tmp/node_modules/aws-sdk/lib/request.js:392:10)
    at Request.failRequest (/home/john/tmp/node_modules/aws-sdk/lib/request.js:353:12)
    at Request.<anonymous> (/home/john/tmp/node_modules/aws-sdk/lib/request.js:339:32)
    at Request.<anonymous> (/home/john/tmp/node_modules/aws-sdk/lib/request.js:396:20)

```

**Comment by Marak** [comment]
You should not be using domains like this.

Your API design for error reporting is flawed, and now causing me some real problems.

I don't really know what else to say. If you understood JavaScript best-practice this entire thread would have read much differently.
