### ISSUE TITLE
Ecs.runTask throws TimestampParserError

### ISSUE THREAD

**Issue by aviaoh** [aws/aws-sdk-js#1320]
Running new task using ecs.runTask throws the following error:
```
{ [TimestampParserError: unhandled timestamp format: 1.485179373361E9]
  message: 'unhandled timestamp format: 1.485179373361E9',
  code: 'TimestampParserError',
  time: Mon Jan 23 2017 15:49:33 GMT+0200 (IST),
  statusCode: 200,
  retryable: false,
  retryDelay: 85.99779012147337 }
Trace: 
TimestampParserError: unhandled timestamp format: 1.485179373361E9
    at Object.parseTimestamp (project/node_modules/aws-sdk/lib/util.js:312:11)
    at TimestampShape.toType (project/node_modules/aws-sdk/lib/model/shape.js:274:22)
    at translateScalar (project/node_modules/aws-sdk/lib/json/parser.js:61:16)
    at translate (project/node_modules/aws-sdk/lib/json/parser.js:16:21)
    at Object.<anonymous> (project/node_modules/aws-sdk/lib/json/parser.js:29:20)
    at Object.each (project/node_modules/aws-sdk/lib/util.js:478:32)
    at translateStructure (project/node_modules/aws-sdk/lib/json/parser.js:25:8)
    at translate (project/node_modules/aws-sdk/lib/json/parser.js:13:30)
    at Object.<anonymous> (project/node_modules/aws-sdk/lib/json/parser.js:41:18)
    at Object.arrayEach (project/node_modules/aws-sdk/lib/util.js:487:32)
    at translateList (project/node_modules/aws-sdk/lib/json/parser.js:40:8)
    at translate (project/node_modules/aws-sdk/lib/json/parser.js:15:25)
    at Object.<anonymous> (project/node_modules/aws-sdk/lib/json/parser.js:29:20)
    at Object.each (project/node_modules/aws-sdk/lib/util.js:478:32)
    at translateStructure (project/node_modules/aws-sdk/lib/json/parser.js:25:8)
    at translate (project/node_modules/aws-sdk/lib/json/parser.js:13:30)
    at JsonParser.parse (project/node_modules/aws-sdk/lib/json/parser.js:6:10)
    at Request.extractData (project/node_modules/aws-sdk/lib/protocol/json.js:54:24)
    at Request.callListeners (project/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (project/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (project/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (project/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (project/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (project/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (project/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (project/node_modules/aws-sdk/lib/request.js:670:12)
```

There are no timestamps in params to runTask:
```
{
  "taskDefinition": "worker:1",
  "cluster": "workers",
  "overrides": {
    "containerOverrides":
    [{
        "command": [ "worker" ],
        "environment": [{
            "name": "JOB_ID",
            "value": "175"
          }],
        "name": "worker"
      }]
  }
}
```

**Comment by aviaoh** [comment]
Digging in parser itself, response from ecs is actually 200 and sdk just fails to parse response. Printing `resp.httpResponse.body.toString()` in node_modules/aws-sdk/lib/protocol/json.js:46 shows:
```
{
  "failures": [],
  "tasks": [
    {
      "clusterArn": ...,
      "containerInstanceArn": ...,
      "containers": [...],
      "createdAt": 1.485189343605E9,
      ...
   ]
}
```

**Comment by chrisradek** [comment]
@aviaoh 
Can you check if the `createdAt` timestamp came back as a number or a string? Can you log
```javascript
typeof JSON.parse(resp.httpResponse.body.toString()).tasks[0].createdAt
```
The code is failing here:
https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L301

AWS.util.date.parseTimestamp with the value as a number works, but as a string doesn't, so I just want to verify which type you're receiving it as.

**Comment by chrisradek** [comment]
@aviaoh 
Can you also share what version of node.js and platform you're running on? I just tested `ecs.runTask` on node.js version `6.9.1` on mac os x and didn't get any errors like what you're seeing.

**Comment by aviaoh** [comment]
@chrisradek thanks for your quick response :)

We found the issue. We are using json-bigint so the type is string rather than number. In this case it is indeed unhandled format.

Closing this issue as it's not sdk issue. thanks :)

**Comment by thirteen-eleven** [comment]
@aviaoh I'm experiencing the same issue using the sdk with json-bigint.  Were you able to find a workaround?

Thanks!
