### ISSUE TITLE
shape.api is unexpectedly undefined

### ISSUE THREAD

**Issue by dpjanes** [aws/aws-sdk-js#1328]
I'm attempting to delete an S3 object (after doing a number of other S3 operations) and get the following error:

```# error executing: process
# Cannot read property 'xmlNamespaceUri' of undefined
# TypeError: Cannot read property 'xmlNamespaceUri' of undefined
    at applyNamespaces (/Users/davidjanes/node_modules/aws-sdk/lib/xml/builder.js:79:37)
    at XmlBuilder.toXML (/Users/davidjanes/node_modules/aws-sdk/lib/xml/builder.js:8:3)
    at populateBody (/Users/davidjanes/node_modules/aws-sdk/lib/protocol/rest_xml.js:23:36)
    at Request.buildRequest (/Users/davidjanes/node_modules/aws-sdk/lib/protocol/rest_xml.js:33:5)
    at Request.callListeners (/Users/davidjanes/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/davidjanes/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/davidjanes/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/davidjanes/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/davidjanes/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/davidjanes/node_modules/aws-sdk/lib/state_machine.js:26:10
```

I can't find a root cause for this happening and due to this being inside a lot of code, I can't isolate a nice test case, but making the following change to `lib/xml/builder.js` seems to do the trick

```  } else if (xml.isRoot && shape.api && shape.api.xmlNamespaceUri) {```

Where the change is `&& shape.api`.

**Comment by chrisradek** [comment]
@dpjanes 
Which version of the SDK are you using? Can you share what your parameters looked like when deleting an S3 object?

**Comment by dpjanes** [comment]
Standby. I'm going to see if I can isolate a test case for you make everyone happy.

**Comment by dpjanes** [comment]
I'm closing this one - there's some really subtle issue related to cloning objects around that shouldn't have been cloned around in the first place, such that everything worked except the delete object function!

**Comment by piercus** [comment]
This occured also to me.

In case it is useful for anyone else in the future

I was passing the s3 object (from `new AWS.S3({})` as a grunt option to a task. 

I think the s3 object has been processed/cloned by grunt `this.options()` (see https://gruntjs.com/api/inside-tasks#this.options) and this clone was corrupting the s3 instance, creating the same issue on `s3.copyObject`
