### ISSUE TITLE
Error: Incorrect arguments at Request.callListeners

### ISSUE THREAD

**Issue by torbenbru** [aws/aws-sdk-js#1454]
Hey guys, as i haven't seen this error anywhere else on stackoverflow I decided to ask for a fix here. This is the full error:
```
/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Incorrect arguments
    at Request.callListeners (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/torben/Dokumente/kommunikation-projekt/nodeExpressPassport/passport-dynamodb/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```

This happens in a Node Script using Express and Passportjs. As this happens after a tried login I'll just copy most of the login code here. I believe the query is the reason for this Error. I don't know why a Request Object is created as i enter an anonymous callback function as a second parameter to handle the query response.

  ```
  function(req,username,password,done) {
      var queryParams = {
	TableName: "users",
	KeyConditionExpression: "username = :user",
	ExpressionAttributeValues: {
	  //username entered in jade form
	  ":user":{"S":username}
	       }
      };
      //querying dynamodb for username
      dynamodb.query(queryParams,
	function(err,user) {
	  if(err) {
        console.error(username);
        console.error(queryParams);
	    console.error(err);
	    return done(err);
      }
	  //if no users with said username in db
	  if(user.Count < 1) {
        console.error("user: " + username + " not found in db");
	    return done(null, false, req.flash("message" , "user not found"));
	  }
	  //too many entries
	  if(user.Count > 1){
	    console.error("error, more than one user with " + username + " in db");
	    return done(null,false,req.flash("message", "more than version of the username in the db"));
	  } else {
	    //only one user exists in db, query for username was successful
	    user.Items.forEach(function(item){
        
	    //checking if entered password is wrong
	    if(!isValidPassword(item.username, item.password)) {
	    console.error("invalid username - password combination");
	    return done(null,false,req.flash("message","invalid user-password combination")); 
	       }
                    
	  //successful login - user and password match
	  console.log("login successful");
      console.log(user.username); //undefined
      console.log(user.password); //undefined
      console.log(user);
      //return user object for serialization
	  return done(null,user);
```

**Comment by jeskew** [comment]
Hi @torbenbru,

The SDK invokes callbacks from `Request.callListeners`, which means that errors thrown in a callback can surface with a stack trace that includes the SDK. I wasn't able to find any errors thrown with the message "Incorrect arguments" by the SDK, but it looks like [something similar is thrown by `bcrypt-nodejs`](http://stackoverflow.com/questions/35666594/passport-bcrypt-throw-incorrect-arguments). It's possible the error is first being thrown by the call to `isValidPassword`.

**Comment by torbenbru** [comment]
Hey @jeskew that totally fixed the Error. I still wonder why the compiler pointed to the aws-sdk lib though. Problem is that i'm running into another error now. When i query my local dynamodb the Keyschema is like this which should be fine. `KeySchema: [ [Object], [Object] ]` If i want to access e.g. the username of the object of the returned Items `Items: [ { username: [Object], password: [Object] }` the items are of  type `undefined` and I `cannot read property "username" of  type undefined ` Any help there? Thank you so much!

**Comment by MatthewGleeson** [comment]
I haven't been able to find any concise guide to setting up AWS sdk with DynamoDB and Passportjs. I have a sdk working with DynamoDB, but I'm having trouble figuring how to connect it to Passportjs(passport-local)
