### ISSUE TITLE
ECS Stop Task Returns 400 on Valid Params

### ISSUE THREAD

**Issue by tayhalla** [aws/aws-sdk-js#1466]
I'm seeing the ECS `stopTask` return a 400 despite giving it the correct parameters per its docs and type definition. The response is continually:
```
{ InvalidParameterException: Task Identifier is invalid
    at Request.extractError (/Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/taylor/Code/Mesh/CommitHub/node_modules/aws-sdk/lib/request.js:38:9)
.
.
.
  message: 'Task Identifier is invalid',
  code: 'InvalidParameterException',
  time: 2017-04-14T23:29:43.087Z,
  requestId: '3cec799a-216a-11e7-a6b7-d7d9caa833a1',
  statusCode: 400,
  retryable: false,
  retryDelay: 2.1553045985633013 }
```

This operation is using a Task ARN that I've tried with many other functions in the AWS ECS lib that all work OK w/ it. An example of the parameters I'm submitting:

```
{ task: 'arn:aws:ecs:us-west-2:266182953919:task-definition/StandupAPIProd:36',
  cluster: 'StandupAPI' }
```

Thanks!

**Comment by jeskew** [comment]
The ARN being sent looks like a task definition ARN instead of a task ARN. Task ARNS would look like `arn:aws:ecs:<region>:<aws_account_id>:task/<UUID>`; it should be returned in the response returned when `StartTask` or `RunTask` is called.

You should be able to identify the tasks started from a given task definition family by calling [`ListTasks`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#listTasks-property) and specifying the task definition family (`StandupAPIProd` in the case of the ARN provided above).
