### ISSUE TITLE
ecs.waitFor('servicesStable') issue

### ISSUE THREAD

**Issue by harishnagaraj** [aws/aws-sdk-js#1493]
Getting this Error:
2017-05-02T15:09:50.336Z	62afdd78-2f49-11e7-b9eb-7dc84b461e02	{ [Error: TypeError: length() expected argument 1 to be type 2,3,4 but received type 7 instead.]
  message: 'TypeError: length() expected argument 1 to be type 2,3,4 but received type 7 instead.',
  code: 'Error',
  time: Tue May 02 2017 15:09:50 GMT+0000 (UTC),
  statusCode: 400,
  retryable: false,
  retryDelay: 8.30292806494981 } 'Error: TypeError: length() expected argument 1 to be type 2,3,4 but received type 7 instead.
    at Object.Runtime._validateArgs (/var/task/node_modules/jmespath/jmespath.js:1252:23)
    at Object.Runtime.callFunction (/var/task/node_modules/jmespath/jmespath.js:1214:12)
    at Object.TreeInterpreter.visit (/var/task/node_modules/jmespath/jmespath.js:1068:35)
    at Object.TreeInterpreter.visit (/var/task/node_modules/jmespath/jmespath.js:978:28)
    at Object.TreeInterpreter.search (/var/task/node_modules/jmespath/jmespath.js:862:23)
    at Object.search (/var/task/node_modules/jmespath/jmespath.js:1660:26)
    at AWS.ResourceWaiter.inherit.matchers.path (/var/task/node_modules/aws-sdk/lib/resource_waiter.js:75:29)
    at /var/task/node_modules/aws-sdk/lib/resource_waiter.js:32:22
    at Array.forEach (native)
    at Request.CHECK_ACCEPTORS (/var/task/node_modules/aws-sdk/lib/resource_waiter.js:29:13)'

_# Lambda node js code is below:

var aws = require('aws-sdk');
var ecs = new aws.ECS();
var params = {
  cluster:'someclustername',
  services: ['someservicename']
};
ecs.waitFor('servicesStable', params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
};_

**Comment by jeskew** [comment]
The SDK isn't catching errors thrown by a dependency, which is causing the error you've encountered. I opened a PR to fix catch those errors and an issue on the dependency to improve their error messages.
