### ISSUE TITLE
MD5DigestCalculatingInputStream fails with CloneNotSupportedException

### ISSUE THREAD

**Issue by Gilis95** [aws/aws-sdk-js#1560]
I've got a problem with usage of AWS in java. Here are scenarios:

**First attempt:**
   

    private void multipartUpload(String bucket, String fileName, File tempFile, ObjectMetadata metadata)
            throws AmazonClientException, InterruptedException, IOException {
        // Create request to upload a part.
        List<PartETag> partETags = new ArrayList<>();
    
        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new
                InitiateMultipartUploadRequest(bucket, fileName);
        InitiateMultipartUploadResult initResponse =
                mS3Client.initiateMultipartUpload(initRequest);
    
        long currentFilePosition = 0;
        long contentLength = tempFile.length();
        long partSize = UploadConfigHelper.CHUNK_SIZE_FOR_MULTIPART_UPLOADS;
    
        for (int i = 0; currentFilePosition < contentLength; i++) {
    
            ResettableInputStream inputStream = newResettableInputStream(tempFile);
            inputStream.skip(currentFilePosition);
    
            // Last part can be less than 5 MB. Adjust part size.
            partSize = Math.min(partSize, (contentLength - currentFilePosition));
    
    
            // Create request to upload a part.
            UploadPartRequest uploadRequest = new UploadPartRequest()
                    .withBucketName(bucket).withKey(fileName)
                    .withUploadId(initResponse.getUploadId())
                    .withPartNumber(i)
                    .withFileOffset(currentFilePosition)
                    .withInputStream(inputStream)
                    .withPartSize(partSize);
    
            // Upload part and add response to our list.
            partETags.add(mS3Client.uploadPart(uploadRequest).getPartETag());
    
            inputStream.close();
            currentFilePosition += partSize;
    
        }
    
        CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(bucket, fileName,
                initResponse.getUploadId(), partETags);
    
        mS3Client.completeMultipartUpload(compRequest);
    }

**Which fails with next:**

  

      Caused by: java.lang.IllegalStateException: unexpected
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.cloneFrom(MD5DigestCalculatingInputStream.java:54)
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.mark(MD5DigestCalculatingInputStream.java:66)
    at com.amazonaws.internal.SdkFilterInputStream.mark(SdkFilterInputStream.java:96)
    at com.amazonaws.internal.SdkFilterInputStream.mark(SdkFilterInputStream.java:96)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:681)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:466)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
    at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3043)
    at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3028)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.multipartUpload(AmazonS3ConnectorImpl.java:414)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.upload(AmazonS3ConnectorImpl.java:322)
    ... 88 more
    
    
    Caused by: java.lang.CloneNotSupportedException
    at java.security.MessageDigest$Delegate.clone(MessageDigest.java:571)
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.cloneFrom(MD5DigestCalculatingInputStream.java:52)
    ... 100 more

Second attempt:

    private void multipartUpload(String bucket, String fileName, File tempFile, ObjectMetadata metadata)
            throws AmazonClientException, InterruptedException, IOException {
        // Create request to upload a part.
        List<PartETag> partETags = new ArrayList<>();

        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new
                InitiateMultipartUploadRequest(bucket, fileName);
        InitiateMultipartUploadResult initResponse =
                mS3Client.initiateMultipartUpload(initRequest);

        long currentFilePosition = 0;
        long contentLength = tempFile.length();
        long partSize = UploadConfigHelper.CHUNK_SIZE_FOR_MULTIPART_UPLOADS;
        /** File content represent as byte array */
        byte[] content = Files.readAllBytes(tempFile.toPath());

        for (int i = 0; currentFilePosition < contentLength; i++) {

            ResettableInputStream inputStream = newResettableInputStream(tempFile);
            inputStream.skip(currentFilePosition);

            // Last part can be less than 5 MB. Adjust part size.
            partSize = Math.min(partSize, (contentLength - currentFilePosition));

            String md5 = new String(content)
                    .substring((int) currentFilePosition, (int) (currentFilePosition + partSize));

            // Create request to upload a part.
            UploadPartRequest uploadRequest = new UploadPartRequest()
                    .withBucketName(bucket).withKey(fileName)
                    .withUploadId(initResponse.getUploadId())
                    .withPartNumber(i)
                    .withFileOffset(currentFilePosition)
                    .withInputStream(inputStream)
                    .withMD5Digest(Md5Utils.md5AsBase64(md5.getBytes()))
                    .withPartSize(partSize);

            // Upload part and add response to our list.
            partETags.add(mS3Client.uploadPart(uploadRequest).getPartETag());

            inputStream.close();
            currentFilePosition += partSize;

        }

        CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(bucket, fileName,
                initResponse.getUploadId(), partETags);

        mS3Client.completeMultipartUpload(compRequest);
    }

**Which fails with next**

    Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: The target server failed to respond
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:724)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:466)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
    at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3043)
    at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3028)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.multipartUpload(AmazonS3ConnectorImpl.java:420)
    at com.axway.st.plugins.amazon.site.AmazonS3ConnectorImpl.upload(AmazonS3ConnectorImpl.java:322)
    ... 88 more
    Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
    at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:875)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:715)
    ... 96 more

**P.S:**
Reason why I'm trying to sum MD5 is that otherwise aws wrap my input stream or file ,which transform, into MD5DigestCalculatingInputStream and tries to clone it which leads to error, I've already hit that problem into single upload and worked it around by passing md5 to upload method which leads to skip srtream wrapping. I am looking for way to pass again the md5 or to find why streams tries to clone or why exception is not handled.
I am testing against both Ceph and Official Amazon S3.

**Java Version** : 1.8.0_121-b13
**AWS Version** : 1.11.30

Thanks in advance.

**Comment by jeskew** [comment]
Hi @Gilis95,

Thanks for the detailed report, but I believe you're looking for [the AWS SDK for Java](https://github.com/aws/aws-sdk-java). If you copy and paste the above description into a new issue on that repository, the Java SDK team should be able to help you out.

**Comment by Gilis95** [comment]
Yes I've post to the wrong place sorry
