### ISSUE TITLE
SQS sendmessage returns InvalidChecksum with continuous hit on SQS

### ISSUE THREAD

**Issue by sam-qburst** [aws/aws-sdk-js#1567]
I got an error as `InvalidChecksum: sendMessage returned an invalid MD5 response. Got "*", expecting "*"` when I continuously hit the SQS. Is there any solution?

**Comment by chrisradek** [comment]
@sam-qburst 
When this error occurs, does it happen sporadically, or consistently? The SDK does perform an MD5 check of SQS messages, so this error indicates that the message received from the service doesn't match what they thought they sent you. Did both `*` look like MD5 hashes, and were different?

**Comment by amangpt777** [comment]
This is happening consistently. I am sending messages to FIFO queue in a loop of three to test. The first message is successfully sent without error, the second and third message gives error as mentioned by sam-qburst. Interestingly though I have the three messages in my queue irrespective of this error!

**Comment by zebralight** [comment]
I am also getting this error message when sending messages using the standard, non-FIFO method with a few messages being transmitted to the queue successfully in an unpredictable manner, in the same way that @amangpt777 describes.  Resolving this quickly would be much appreciated as I'd like to transition over to sqs as my sole method of communication between my modules.

**Comment by haraldkubota** [comment]
If anyone interested: happens to me too. aws-sdk 2.162 (current as of now). NodeJS 8.9.0 as well as 8.9.1 (current as of now).

Here my example error message:

`
{ InvalidChecksum: sendMessage returned an invalid MD5 response. Got "0d9f2fb6a7a6151e95e0b22ad6bccf44", expecting "d7a57fde014ff23e7d8d41b0c9b39a43".
    at features.constructor.throwInvalidChecksumError (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/services/sqs.js:94:37)
    at Request.verifySendMessageChecksum (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/services/sqs.js:33:20)
    at Request.callListeners (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/harald/src/aws/sqs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/harald/src/aws/sqs/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'sendMessage returned an invalid MD5 response. Got "0d9f2fb6a7a6151e95e0b22ad6bccf44", expecting "d7a57fde014ff23e7d8d41b0c9b39a43".',
  retryable: true,
  code: 'InvalidChecksum',
  messageIds: [ '3e96fb76-e15c-4ee3-9b2f-518ca1adc5e2' ],
  time: 2017-12-02T12:09:00.267Z,
  statusCode: 200 }
`

**Comment by iassal** [comment]
I was facing a similar issue and solved it as mentioned here https://github.com/aws/aws-sdk-js/issues/745#issuecomment-372317868

**Comment by srchase** [comment]
@sam-qburst,

Is this working for you?

@iassal has posted a comment on another issue that may be helpful.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
