### ISSUE TITLE
callback called twice using s3

### ISSUE THREAD

**Issue by acidjazz** [aws/aws-sdk-js#1579]
/Users/k/waa/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: callback called twice
    at onCb (/Users/k/waa/node_modules/pend/index.js:36:23)
    at Response.<anonymous> (/Users/k/waa/node_modules/s3/lib/index.js:401:9)
    at Request.<anonymous> (/Users/k/waa/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/k/waa/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/k/waa/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/k/waa/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/k/waa/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/k/waa/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/k/waa/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/k/waa/node_modules/aws-sdk/lib/request.js:38:9)

**Comment by jeskew** [comment]
What version of the SDK are you using? I don't see an error with the message "callback called twice" being thrown anywhere in the SDK, so could you include a snippet of code that's encountering this issue?

**Comment by acidjazz** [comment]
Closing this due to not being able to duplicate it anymore,
