### ISSUE TITLE
putObject Error on every upload...

### ISSUE THREAD

**Issue by PsyTae** [aws/aws-sdk-js#1597]
node -v 6.11.0
aws-sdk 2.77.0

I have an upload queue to limit how many uploads can be initiated at any one point in time from my server.  See Code Below..

```
var   async = require('async')
        , aws = require('aws-sdk')
	, s3 = new aws.S3()
	;
var uploads = fs.createWriteStream('d:/temp/uploads.log', {flags: 'a'});

var s3uploadQ = async.queue(function(task, callback){
	//task.Bucket, task.Key, task.FilePath
	console.log('\x1b[35m Upload Initiated', task.FilePath, '\x1b[0m');
	console.log(`${s3uploadQ.length()} uploads left in queue`);
	uploads.write(`[${moment().format('YYYY-MM-DD HH:mm:ss.SSS')}] Upload Initiated ${task.FilePath} ${s3uploadQ.length()} uploads left in queue${os.EOL}`);
	var begin = moment();
	fs.access(task.FilePath, function(accessErr){
		if(!accessErr){
			// mp4 accessable
			var fileStream = fs.createReadStream(task.FilePath);
			var putParams = {
				Bucket: task.Bucket,
				Key: task.Key,
				Body: fileStream
			};
			s3.putObject(putParams, function(upLoadErr, etag){
				var end = moment();
				var timeSpent = end.diff(begin);
				if(upLoadErr){
					console.error('\x1b[31m', `Upload Error '${upLoadErr.code}' for ${task.FilePath} after ${timeSpent} ms:\n`, upLoadErr, '\x1b[0m');
					uploads.write(`[${moment().format('YYYY-MM-DD HH:mm:ss.SSS')}] Upload Error '${upLoadErr.code}' for ${task.FilePath} after ${timeSpent} ms${os.EOL}`);
					callback(upLoadErr);
				} else {
					console.log(`[S3:Upload] ${path2.basename(task.FilePath)} took: ${timeSpent} ms to upload.`);
					console.log('\x1b[32m', `Upload Completed: ${task.FilePath}`, '\x1b[0m');
					uploads.write(`[${moment().format('YYYY-MM-DD HH:mm:ss.SSS')}] Upload Completed: ${task.FilePath} took: ${timeSpent} ms to upload${os.EOL}`);
					callback();
				}
			});
		} else {
			// error accesssing mp4 to upload
			callback(accessErr);
		}
	});
}, 100);
```

Recently Every upload attempt that is created has errored out with the exact same error.
I am using the sdk to initiate the upload so I don't know what is going on or why.

```
 [2017/06/24 21:54:06.037] [ERROR]
  Upload Error 'NetworkingError' for c:/Folder/Folder/Folder/Folder/Folder/Event1.mp4 after 207646 ms:
  { Error: write EPROTO 101057795:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:openssl\ssl\s23_lib.c:177:
     at exports._errnoException (util.js:1018:11)
     at WriteWrap.afterWrite (net.js:800:14)
   message: 'write EPROTO 101057795:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:openssl\\ssl\\s23_lib.c:177:\n',
   code: 'NetworkingError',
   errno: 'EPROTO',
   syscall: 'write',
   region: 'us-west-2',
   hostname: 'fleetvump4.s3-us-west-2.amazonaws.com',
   retryable: true,
   time: 2017-06-24T21:54:06.037Z }
 ```

**Comment by chrisradek** [comment]
@PsyTae 
The error you're getting is coming form OpenSSL, and indicates that your node.js application isn't able to create a connection over https to S3.

Is your environment configured to use a proxy? Can you also try setting [`s3ForcePathStyle`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#s3ForcePathStyle-property) to true and see if that helps at all?

**Comment by PsyTae** [comment]
After restarting the Node Script the Errors Disappeared.  Not sure why or what changed in my environment.  Same Code. Same AWS EC2. Same Security Groups/Firewalls.

**Comment by jeskew** [comment]
Based on the last comment, this sounds like an odd error somewhere farther down the stack than the SDK touches. Please feel free to reopen if the error resurfaces.
