### ISSUE TITLE
Url signing breaks if metadata field has null

### ISSUE THREAD

**Issue by Agrumas** [aws/aws-sdk-js#1598]
I tried to create signed url with `null` in one of metafield and it breaks in an unexpected way:
```
TypeError: Cannot read property 'split' of undefined
    at Request.signedUrlSigner (app\node_modules\aws-sdk\lib\signers\presign.js:62:42)
    at Request.callListeners (app\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at callNextListener (app\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
    at app\node_modules\aws-sdk\lib\event_listeners.js:207:9
    at finish (app\node_modules\aws-sdk\lib\config.js:315:7)
    at getStaticCredentials (app\node_modules\aws-sdk\lib\config.js:342:7)
    at Config.getCredentials (app\node_modules\aws-sdk\lib\config.js:349:9)
    at Request.SIGN (app\node_modules\aws-sdk\lib\event_listeners.js:179:22)
    at Request.callListeners (app\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (app\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
  message: 'Cannot read property \'split\' of undefined',
  code: 'TypeError',
  time: 2017-06-26T13:17:28.344Z,
  retryDelay: 33.933526783304345
```
Example:
```js
const S3 = require('aws-sdk/clients/s3');
const s3 = new S3({
  region: 'eu-central-1',
  signatureVersion: 'v4',
  credentials: {accessKeyId: 'accessKeyId', secretAccessKey: 'secretAccessKey'}
});

s3.getSignedUrl('putObject', {
  Metadata: {userId: null},
  Bucket: 'test',
  Key: 'test-key',
  ACL: 'authenticated-read',
  Expires: 3600,
}, (error, data) => {
  console.log(error, data);
});

```
Most likely this situation is the same as reported in #834

**Comment by chrisradek** [comment]
@Agrumas 
The error is occurring because we're attempting to call `toString` on null when collecting the canonical headers to sign:
https://github.com/aws/aws-sdk-js/blob/v2.77.0/lib/signers/v4.js#L142

We should be throwing a more helpful error in this case.

That said, what are you expecting to happen by specifying null metadata in the presigned url? If you leave it out of your options, then your object should not include the metadata. If you want `userId` to appear, but me empty, you could also set it to an empty string.

**Comment by Agrumas** [comment]
@chrisradek error handling would be appreciated in that place because I spent a few hours trying to figure out what is wrong with Authentication part... The null isn't necessary in my case, just it was passed from other layer and I even wasn't aware of it. I would expect empty string, missing field, but not an error :)
