### ISSUE TITLE
Unhandled Throttling error from CloudSearchDomain.uploadDocuments

### ISSUE THREAD

**Issue by justinmchase** [aws/aws-sdk-js#1605]
I am getting this error from the `CloudSearchDomain` api:

```
Error: Rate exceeded
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

The calling code:
```js
import { CloudSearch, CloudSearchDomain } from 'aws-sdk'
// get domain and items then...
function send (domain, items) {
  let params = {
    contentType: 'application/json',
    documents: JSON.stringify(items)
  }
  domain.uploadDocuments(params, callback) // unhandled exception is thrown
}
```

**Comment by chrisradek** [comment]
@justinmchase 
Is your callback to `domain.uploadDocuments` getting the error you posted?

The error's callstack looks like it's being thrown from `lib/protocol/query`, which makes sense for `CloudSearch`, but `CloudSearchDomain` is a rest-json based service so I'd expect the stack trace to look different.

**Comment by justinmchase** [comment]
Actually that's interesting because I am also calling the `CloudSearch` api in order find the `CloudSearchDomain` first. It's possible that that is what is throttled, I hadn't considered that because it is called much less frequently than the other. Thanks for the clue!

**Comment by justinmchase** [comment]
I'm pretty sure the other API is what is throwing the throttled error. Thanks for this clue.
