### ISSUE TITLE
Callback called twice on completion of upload using s3.upload

### ISSUE THREAD

**Issue by vimal** [aws/aws-sdk-js#1617]
I am using async queues to queue uploads and once the upload is complete, the callback to the particular task is issued.
I am using aws-sdk@2.80.0
In my logs I see multiple messages of the same completed upload file

```
Error: Callback was already called.
    at /Users/vimaldas/node-dev/aws-uploader/node_modules/async/dist/async.js:903:32
    at /Users/vimaldas/node-dev/aws-uploader/libs/lib_aws.js:39:9
    at ManagedUpload.callback (/Users/vimaldas/node-dev/aws-uploader/libs/lib_aws.js:292:21)
    at Response.finishSinglePart (/Users/vimaldas/node-dev/aws-uploader/node_modules/aws-sdk/lib/s3/managed_upload.js:667:12)
    at Request.<anonymous> (/Users/vimaldas/node-dev/aws-uploader/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/vimaldas/node-dev/aws-uploader/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/vimaldas/node-dev/aws-uploader/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/vimaldas/node-dev/aws-uploader/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/vimaldas/node-dev/aws-uploader/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/vimaldas/node-dev/aws-uploader/node_modules/aws-sdk/lib/state_machine.js:14:12)
```

**Comment by jeskew** [comment]
Can you post a bit of information about your runtime environment (e.g., the version of Node and the SDK in use) as well as about the async queue implementation you're using? Is this issue only encountered when aborting requests (per the discussion in #1616), or are you seeing this happen with requests that are not cancelled?

**Comment by vimal** [comment]
I am on a Mac
Node Version - 6.10.2
aws-sdk - 2.80.0

The queue
```
var uq = async.queue(function(upload_conf, callback) {
    _prepare_upload(upload_conf, function(err, data){
        if (err){
            console.log(err);
        }
        callback();
    })
}, 10)
```

Sample upload Conf
```
var upload_conf = {
    "bucket": "memories"
    "file_path": "/home/vimal/friends.txt",
    "s3_path": "/2017/friends.txt",
    "file_size": 8388608
}
```

Pushing the upload details to the async queue
```
for var(i=0;i<upload_confs.length;i++){
    dq.push(upload_confs[i]);
}
```

The upload logic
```
function _prepare_upload(upload_conf, callback){
    var file_data = fs.createReadStream(upload_conf.file_path);
    var upload_params = {
        Body: file_data,
        Bucket: upload_conf.bucket,
        Key: upload_conf.s3_path,
        contentLength: upload_conf.file_size,
        ContentType: 'application/octet-stream'
    };
    var upload_opts = {
        partSize: 1024 * 1024 * 5;,
        queueSize: 500
    };

    var multi_upload = s3.upload(part_params, part_opts);
    multi_upload.send(function(err, udata){
        if (err){
            console.log("Error uploading file :", upload_conf.file_path, " - ", err);
            callback(err);
        }else{
            console.log("Completed uploading file :", upload_conf.file_path);
            callback(null)
        }
    });
    upload_conf.request = multi_upload; //Updating the request in upload conf for reference
}
```

Aborting the upload
```
function cancel_uploads(){
    dq.pause(); // Pause the queue

    // Abort the requests picked up by the queue
    var workers = dq.workersList();
    for (var i=0;i<workers.length;i++){
        var worker_conf = workers[i].data;
        worker_conf.request.abort();
    }

    dq.remove();  // Flushes all the upload confs
    dq.resume();  // Get ready for the next set of uploads
}
```

**Comment by vimal** [comment]
When calling cancel uploads for the list of worker requests, it falls into the multi_upload.send's error callback and the queue call its own callback to pull the next upload. Then again it sometimes doesn't stop showing progress and eventually after 100% of upload completed, it falls into multi_upload.send's non-error callback and returns the queue's callback to trigger once again.

In summary, after abort it calls the callback in multi_upload.send() function twice, once on abort and once on completion

**Comment by davidjwalter** [comment]
What is the status of this issue? We are seeing very similar behavior where sometimes the async callback is called twice. We are using aws-sdk@2.139.0, async@2.1.5 and Node.js 6.10. The application is uploading a stream to S3 within an async.parallel. It does this successfully thousands of times per day, but once or twice a day async throws an error like below:

```
Error: Callback was already called.
 at /app/node_modules/async/dist/async.js:840:32
 at ManagedUpload.<anonymous> (/app/node_modules/async/dist/async.js:3691:13)
 at apply (/app/node_modules/async/dist/async.js:21:25)
 at ManagedUpload.callback (/app/node_modules/async/dist/async.js:56:12)
 at Response.finishSinglePart (/app/node_modules/aws-sdk/lib/s3/managed_upload.js:667:12)
 at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:364:18)
 at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
 at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
 at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
 at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
```
Here is a simplified view of the code:

```javascript
let activityStream = makeReadableJSON(activity);

async.parallel([
    (apc) => {
      	var params = {
      	    Bucket: bucketName,
      	    Key: s3_path,
      	    Body: activityStream
      	};
        s3.upload(params, apc);
    },
    other-work-here...
], callback);
```

**Comment by rayjennings3rd** [comment]
Same problem: thousands of times a day okay, every so often:

/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

```
Error: Callback was already called.
    at /root/jam-utils/node_modules/async/dist/async.js:903:32
    at Response.<anonymous> (/root/jam-utils/node_modules/streaming-s3/index.js:266:16)
    at Request.<anonymous> (/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/root/jam-utils/node_modules/streaming-s3/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by oshoemaker** [comment]
Same problem here:

let promises = [];
promises.push(s3.upload(params).promise());

Throws an error: Error: Callback was already called.

**Comment by freethejazz** [comment]
I am also experiencing this error. Not sure if historical context is important, but here's a much earlier version of this issue that was fixed in the past: https://github.com/aws/aws-sdk-js/issues/290

**Comment by 0190** [comment]
Same here, but for `s3.getObject`:

```
  const func = async () => {
  ...
  await s3.getObject(params, (err, data) => {
    if (err) {
      console.log(err);
    } else {
      console.log("got result");
    }
  }).promise();
  ...
}
await func();
```
`got result` is printed out twice.

**Comment by chrisradek** [comment]
@0190 
In your case, you're seeing `got result` printed twice because you're mixing calling operations by passing a callback and using promises. You should only use one method of getting the result.

**Comment by srchase** [comment]
Closing for inactivity.

**Comment by colbygk** [comment]
I also ran into this behavior when attempting to abort/destroy a streaming upload (using pipe() and a passthrough stream handed to the `Body:` of the upload).  After issuing the destroy, I see the callback passed to `upload` called twice.
