### ISSUE TITLE
Problems with SDK behind corporate proxy

### ISSUE THREAD

**Issue by jrbenito** [aws/aws-sdk-js#1619]
Hi,

My workstation is behind a corporate proxy, I have set environment variables and I am able to use everything but aws-sdk. Here a dump of the TCP connectio:

```
No.     Time           Source                Destination           Protocol Length Info
      2 1.834143       105.103.15.106        105.103.82.47         TCP      74     54952 → 8080 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=497254718 TSecr=0 WS=128
      3 1.836141       105.103.82.47         105.103.15.106        TCP      74     8080 → 54952 [SYN, ACK] Seq=0 Ack=1 Win=14480 Len=0 MSS=1460 SACK_PERM=1 TSval=3399116010 TSecr=497254718 WS=128
      4 1.836165       105.103.15.106        105.103.82.47         TCP      66     54952 → 8080 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=497254719 TSecr=3399116010
      5 1.836779       105.103.15.106        105.103.82.47         TCP      310    54952 → 8080 [PSH, ACK] Seq=1 Ack=1 Win=29312 Len=244 TSval=497254719 TSecr=3399116010
      6 1.838250       105.103.82.47         105.103.15.106        TCP      66     8080 → 54952 [ACK] Seq=1 Ack=245 Win=15616 Len=0 TSval=3399116012 TSecr=497254719
     20 123.670911     105.103.82.47         105.103.15.106        TCP      66     8080 → 54952 [FIN, ACK] Seq=1 Ack=245 Win=15616 Len=0 TSval=3399237839 TSecr=497254719
     21 123.674168     105.103.15.106        105.103.82.47         TCP      66     54952 → 8080 [FIN, ACK] Seq=245 Ack=2 Win=29312 Len=0 TSval=497285178 TSecr=3399237839
     22 123.676592     105.103.82.47         105.103.15.106        TCP      66     8080 → 54952 [ACK] Seq=2 Ack=246 Win=15616 Len=0 TSval=3399237843 TSecr=497285178
```

Notice that three-way handshake goes ok, than client (ip ending on 106) sends some data (psh, ack) on package number 5 and immediately, receiveis proxy´s ACK (packet number 6).  Then no communication for a long period (packages between 7 and 19 are not from this tcp conversation), packet 20 is a FIN (proxy timeout due no packages sent?). This conversation was generated by [example provided by Amazon](https://aws.amazon.com/blogs/developer/using-the-aws-sdk-for-javascript-from-behind-a-proxy/).

Node versions: tested on 6.10.0, 6.11.0 and 8.1.3
SDK installed today (2.82.0)

As a comparison, I run an `aws cloudformatin describe-stack-resources --stack-name my-stack` on the same Ubuntu machine. As known, `aws` CLI is python, the command runs ok, and conversation goes like:

```
No.     Time           Source                Destination           Protocol Length Info
      1 0.000000       105.103.15.106        105.103.82.47         TCP      74     54940 → 8080 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=496906305 TSecr=0 WS=128
      2 0.001987       105.103.82.47         105.103.15.106        TCP      74     8080 → 54940 [SYN, ACK] Seq=0 Ack=1 Win=14480 Len=0 MSS=1460 SACK_PERM=1 TSval=3397722434 TSecr=496906305 WS=128
      3 0.002008       105.103.15.106        105.103.82.47         TCP      66     54940 → 8080 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=496906305 TSecr=3397722434
      4 0.002100       105.103.15.106        105.103.82.47         TCP      127    [TCP segment of a reassembled PDU]
      5 0.003967       105.103.82.47         105.103.15.106        TCP      66     8080 → 54940 [ACK] Seq=1 Ack=62 Win=14592 Len=0 TSval=3397722436 TSecr=496906306
      6 0.003974       105.103.15.106        105.103.82.47         HTTP     68     CONNECT cloudformation.us-east-1.amazonaws.com:443 HTTP/1.0 
      7 0.006035       105.103.82.47         105.103.15.106        TCP      66     8080 → 54940 [ACK] Seq=1 Ack=64 Win=14592 Len=0 TSval=3397722438 TSecr=496906306
      8 0.247802       105.103.82.47         105.103.15.106        HTTP     185    HTTP/1.0 200 Connection established 
      9 0.247810       105.103.15.106        105.103.82.47         TCP      66     54940 → 8080 [ACK] Seq=64 Ack=120 Win=29312 Len=0 TSval=496906367 TSecr=3397722681
     10 0.248938       105.103.15.106        105.103.82.47         TLSv1.2  583    Client Hello
     11 0.250985       105.103.82.47         105.103.15.106        TCP      66     8080 → 54940 [ACK] Seq=120 Ack=581 Win=15616 Len=0 TSval=3397722683 TSecr=496906367
     12 0.684003       105.103.82.47         105.103.15.106        TLSv1.2  1995   Server Hello
     13 0.684011       105.103.15.106        105.103.82.47         TCP      66     54940 → 8080 [ACK] Seq=581 Ack=2049 Win=33152 Len=0 TSval=496906476 TSecr=3397723117
     14 0.690001       105.103.82.47         105.103.15.106        TLSv1.2  1488   CertificateServer Key Exchange, Server Hello Done
     15 0.690866       105.103.15.106        105.103.82.47         TLSv1.2  216    Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
     16 0.692974       105.103.82.47         105.103.15.106        TCP      66     8080 → 54940 [ACK] Seq=3471 Ack=731 Win=16640 Len=0 TSval=3397723125 TSecr=496906478
     17 0.968807       105.103.82.47         105.103.15.106        TLSv1.2  141    Change Cipher Spec, Encrypted Handshake Message
     18 0.969476       105.103.15.106        105.103.82.47         TLSv1.2  679    Application Data
     19 0.970992       105.103.82.47         105.103.15.106        TCP      66     8080 → 54940 [ACK] Seq=3546 Ack=1344 Win=17920 Len=0 TSval=3397723403 TSecr=496906547
     20 1.319977       105.103.82.47         105.103.15.106        TLSv1.2  617    Application Data
     21 1.324998       105.103.82.47         105.103.15.106        TCP      2114   [TCP segment of a reassembled PDU]
     22 1.325003       105.103.15.106        105.103.82.47         TCP      66     54940 → 8080 [ACK] Seq=1344 Ack=6145 Win=43008 Len=0 TSval=496906636 TSecr=3397723753
     23 1.329979       105.103.82.47         105.103.15.106        TLSv1.2  133    Application Data
     24 1.332987       105.103.15.106        105.103.82.47         TCP      66     54940 → 8080 [FIN, ACK] Seq=1344 Ack=6212 Win=43008 Len=0 TSval=496906638 TSecr=3397723763
     25 1.373825       105.103.82.47         105.103.15.106        TCP      66     8080 → 54940 [ACK] Seq=6212 Ack=1345 Win=17920 Len=0 TSval=3397723807 TSecr=496906638
     26 1.606041       105.103.82.47         105.103.15.106        TLSv1.2  119    Encrypted Alert
     27 1.606063       105.103.15.106        105.103.82.47         TCP      54     54940 → 8080 [RST] Seq=1345 Win=0 Len=0
```
Notice that packets from 1 to 3 are threeway handshake and exact same as with JS SDK, packet 4 is similar to packet 5 of JS SDK, it is not shown on summary but it also has PSH flag and ACK, differences are the content (expected) and packet 5 is the proxy ACK to that data. From this point on things are different, `aws` CLI sends next pack as soon as the ACK arrives on packet 6. After data received, `aws` CLI sends FIN, receives ACK, Encrypt Alert and sends a RST (this is due Encrypt Alert not expected).

I can´t find why JS SDK stop to send data after last server ACK. But since proxy times out and send FIN ACK after sometime, my node script seems to hang for long until abort with error below:

```
{ NetworkingError: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  message: 'socket hang up',
  code: 'NetworkingError',
  region: 'us-west-2',
  hostname: 'bucket.s3-us-west-2.amazonaws.com',
  retryable: true,
  time: 2017-07-07T19:31:29.494Z } null
```

Any clue?

**Comment by jeskew** [comment]
One thing that jumps out at me from the packet dumps posted is that Node does not seem to establish a TLS connection, whereas the trace for Python is able to communicate over HTTP and TLS. 

Are you able to use Node's `https` module to connect with any host via the corporate proxy (e.g., does `require('https').get('https://www.google.com')` work as expected)? If so, are you seeing this issue with multiple AWS services, or just with Cloudformation?

**Comment by jrbenito** [comment]
Hi @jeskew ,

> One thing that jumps out at me from the packet dumps posted is that Node does not seem to establish a TLS connection, whereas the trace for Python is able to communicate over HTTP and TLS.

It should be done after the last PSH,ACK but instead, a period without message and consequent proxy server timeout (FIN, ACK) happens.

Any AWS service is affected and I am able to use `request` with proxy:

```
No.     Time           Source                Destination           Protocol Length Info
      2 0.433423       105.103.15.106        105.103.82.47         TCP      74     56000 → 8080 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=561373560 TSecr=0 WS=128
      3 0.434944       105.103.82.47         105.103.15.106        TCP      74     8080 → 56000 [SYN, ACK] Seq=0 Ack=1 Win=14480 Len=0 MSS=1460 SACK_PERM=1 TSval=3655577491 TSecr=561373560 WS=128
      4 0.434960       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=561373560 TSecr=3655577491
      5 0.437067       105.103.15.106        105.103.82.47         HTTP     150    CONNECT www.google.com:443 HTTP/1.1 
      6 0.438963       105.103.82.47         105.103.15.106        TCP      66     8080 → 56000 [ACK] Seq=1 Ack=85 Win=14592 Len=0 TSval=3655577495 TSecr=561373561
      7 0.442943       105.103.82.47         105.103.15.106        HTTP     185    HTTP/1.1 200 Connection established 
      8 0.442948       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [ACK] Seq=85 Ack=120 Win=29312 Len=0 TSval=561373562 TSecr=3655577500
      9 0.463281       105.103.15.106        105.103.82.47         TLSv1.2  333    Client Hello
     10 0.503938       105.103.82.47         105.103.15.106        TCP      66     8080 → 56000 [ACK] Seq=120 Ack=352 Win=15616 Len=0 TSval=3655577561 TSecr=561373567
     11 1.378050       105.103.82.47         105.103.15.106        TLSv1.2  1995   Server Hello
     12 1.378061       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [ACK] Seq=352 Ack=2049 Win=33152 Len=0 TSval=561373796 TSecr=3655578435
     13 1.383965       105.103.82.47         105.103.15.106        TLSv1.2  1715   CertificateServer Key Exchange, Server Hello Done
     14 1.383970       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [ACK] Seq=352 Ack=3698 Win=36480 Len=0 TSval=561373797 TSecr=3655578440
     15 1.387097       105.103.15.106        105.103.82.47         TLSv1.2  257    Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message, Encrypted Handshake Message
     16 1.388978       105.103.82.47         105.103.15.106        TCP      66     8080 → 56000 [ACK] Seq=3698 Ack=543 Win=16640 Len=0 TSval=3655578445 TSecr=561373798
     17 1.879802       105.103.82.47         105.103.15.106        TLSv1.2  363    New Session Ticket, Change Cipher Spec, Hello Request, Hello Request
     18 1.883315       105.103.15.106        105.103.82.47         TLSv1.2  154    Application Data
     19 1.884966       105.103.82.47         105.103.15.106        TCP      66     8080 → 56000 [ACK] Seq=3995 Ack=631 Win=16640 Len=0 TSval=3655578941 TSecr=561373922
     20 2.346386       105.103.82.47         105.103.15.106        TCP      168    [TCP segment of a reassembled PDU]
     21 2.384899       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [ACK] Seq=631 Ack=4097 Win=39296 Len=0 TSval=561374048 TSecr=3655579403
     22 2.392992       105.103.82.47         105.103.15.106        TLSv1.2  965    Application Data
     23 2.392997       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [ACK] Seq=631 Ack=4996 Win=42240 Len=0 TSval=561374050 TSecr=3655579450
     24 2.398057       105.103.15.106        105.103.82.47         TLSv1.2  97     Encrypted Alert
     25 2.398878       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [FIN, ACK] Seq=662 Ack=4996 Win=42240 Len=0 TSval=561374051 TSecr=3655579450
     26 2.399996       105.103.82.47         105.103.15.106        TCP      66     8080 → 56000 [ACK] Seq=4996 Ack=662 Win=16640 Len=0 TSval=3655579456 TSecr=561374051
     32 2.404979       105.103.82.47         105.103.15.106        TCP      66     8080 → 56000 [FIN, ACK] Seq=4996 Ack=663 Win=16640 Len=0 TSval=3655579461 TSecr=561374051
     33 2.404986       105.103.15.106        105.103.82.47         TCP      66     56000 → 8080 [ACK] Seq=663 Ack=4997 Win=42240 Len=0 TSval=561374053 TSecr=3655579461
```

Based on [this old discussion](https://github.com/nodejs/node-v0.x-archive/issues/2474#issuecomment-3484290), node has issues with CONNECT method that python CLI seems to be using. I got an [answer at stackoverflow.com](https://stackoverflow.com/a/44980740/2726840) that point to [feature request](https://github.com/aws/aws-sdk-js/issues/108). 

Node´s `https` with tunnel-agent set, goes like:

```
No.     Time           Source                Destination           Protocol Length Info
      2 1.808497       105.103.15.106        105.103.82.47         TCP      74     56110 → 8080 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=562171144 TSecr=0 WS=128
      3 1.810142       105.103.82.47         105.103.15.106        TCP      74     8080 → 56110 [SYN, ACK] Seq=0 Ack=1 Win=14480 Len=0 MSS=1460 SACK_PERM=1 TSval=3658767683 TSecr=562171144 WS=128
      4 1.810156       105.103.15.106        105.103.82.47         TCP      66     56110 → 8080 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=562171145 TSecr=3658767683
      5 1.811591       105.103.15.106        105.103.82.47         TCP      332    56110 → 8080 [PSH, ACK] Seq=1 Ack=1 Win=29312 Len=266 TSval=562171145 TSecr=3658767683
      6 1.813140       105.103.82.47         105.103.15.106        TCP      66     8080 → 56110 [ACK] Seq=1 Ack=267 Win=15616 Len=0 TSval=3658767686 TSecr=562171145
      7 1.827001       105.103.82.47         105.103.15.106        TCP      124    8080 → 56110 [PSH, ACK] Seq=1 Ack=267 Win=15616 Len=58 TSval=3658767700 TSecr=562171145
      8 1.827004       105.103.15.106        105.103.82.47         TCP      66     56110 → 8080 [ACK] Seq=267 Ack=59 Win=29312 Len=0 TSval=562171149 TSecr=3658767700
[... conversation continues ...]
     22 1.850856       105.103.15.106        105.103.82.47         TCP      371    56110 → 8080 [PSH, ACK] Seq=632 Ack=1585 Win=34816 Len=305 TSval=562171155 TSecr=3658767717
     23 1.892164       105.103.82.47         105.103.15.106        TCP      66     8080 → 56110 [ACK] Seq=1585 Ack=937 Win=18816 Len=0 TSval=3658767765 TSecr=562171155
     36 122.059081     105.103.82.47         105.103.15.106        TCP      66     8080 → 56110 [FIN, ACK] Seq=1585 Ack=937 Win=18816 Len=0 TSval=3658887925 TSecr=562171155
     37 122.061821     105.103.15.106        105.103.82.47         TCP      66     56110 → 8080 [FIN, ACK] Seq=937 Ack=1586 Win=34816 Len=0 TSval=562201207 TSecr=3658887925
     38 122.063802     105.103.82.47         105.103.15.106        TCP      66     8080 → 56110 [ACK] Seq=1586 Ack=938 Win=18816 Len=0 TSval=3658887930 TSecr=562201207
```

As you can see, it fails more or less as before by timeout on message 36 (messages 24 to 35 are not from this conversation). SDK set with tunnel-agent do more or less the same throwing error like:

```
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1124:19)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  message: 'socket hang up',
  code: 'NetworkingError',
  region: 'us-west-2',
  hostname: 'bucket.s3-us-west-2.amazonaws.com',
  retryable: true,
  time: 2017-07-10T19:40:55.168Z } null
```

However, if I set tunnel-agent as `httpsOverHttp` I can use AWS-sdk from behind proxy:

```
No.     Time           Source                Destination           Protocol Length Info
      1 0.000000       105.103.15.106        105.103.82.47         TCP      74     56158 → 8080 [SYN] Seq=0 Win=29200 Len=0 MSS=1460 SACK_PERM=1 TSval=562390733 TSecr=0 WS=128
      2 0.001956       105.103.82.47         105.103.15.106        TCP      74     8080 → 56158 [SYN, ACK] Seq=0 Ack=1 Win=14480 Len=0 MSS=1460 SACK_PERM=1 TSval=3659645993 TSecr=562390733 WS=128
      3 0.001982       105.103.15.106        105.103.82.47         TCP      66     56158 → 8080 [ACK] Seq=1 Ack=1 Win=29312 Len=0 TSval=562390734 TSecr=3659645993
      4 0.003726       105.103.15.106        105.103.82.47         HTTP     215    CONNECT s3-us-west-2.amazonaws.com:443 HTTP/1.1 
      5 0.005580       105.103.82.47         105.103.15.106        TCP      66     8080 → 56158 [ACK] Seq=1 Ack=150 Win=15616 Len=0 TSval=3659645997 TSecr=562390734
      6 1.067785       105.103.82.47         105.103.15.106        HTTP     185    HTTP/1.1 200 Connection established 
      7 1.067796       105.103.15.106        105.103.82.47         TCP      66     56158 → 8080 [ACK] Seq=150 Ack=120 Win=29312 Len=0 TSval=562391000 TSecr=3659647059
      8 1.089246       105.103.15.106        105.103.82.47         TLSv1.2  345    Client Hello
      9 1.090774       105.103.82.47         105.103.15.106        TCP      66     8080 → 56158 [ACK] Seq=120 Ack=429 Win=16640 Len=0 TSval=3659647082 TSecr=562391006
     10 1.652870       105.103.82.47         105.103.15.106        TLSv1.2  1995   Server Hello
     11 1.652881       105.103.15.106        105.103.82.47         TCP      66     56158 → 8080 [ACK] Seq=429 Ack=2049 Win=33152 Len=0 TSval=562391147 TSecr=3659647644
     12 1.658780       105.103.82.47         105.103.15.106        TLSv1.2  1284   CertificateServer Key Exchange, Server Hello Done
     13 1.661066       105.103.15.106        105.103.82.47         TLSv1.2  192    Client Key Exchange, Change Cipher Spec, Encrypted Handshake Message
     14 1.662810       105.103.82.47         105.103.15.106        TCP      66     8080 → 56158 [ACK] Seq=3267 Ack=555 Win=16640 Len=0 TSval=3659647654 TSecr=562391149
     15 2.049608       105.103.82.47         105.103.15.106        TLSv1.2  117    Change Cipher Spec, Hello Request, Hello Request
     16 2.052918       105.103.15.106        105.103.82.47         TLSv1.2  565    Application Data
     17 2.054778       105.103.82.47         105.103.15.106        TCP      66     8080 → 56158 [ACK] Seq=3318 Ack=1054 Win=17792 Len=0 TSval=3659648046 TSecr=562391247
     18 2.959859       105.103.82.47         105.103.15.106        TLSv1.2  845    Application Data
     19 2.965808       105.103.82.47         105.103.15.106        TLSv1.2  152    Application DataEncrypted Alert
     20 2.965829       105.103.15.106        105.103.82.47         TCP      66     56158 → 8080 [ACK] Seq=1054 Ack=4183 Win=38912 Len=0 TSval=562391475 TSecr=3659648951
     21 2.967948       105.103.15.106        105.103.82.47         TLSv1.2  97     Encrypted Alert
     22 2.968818       105.103.15.106        105.103.82.47         TCP      66     56158 → 8080 [FIN, ACK] Seq=1085 Ack=4183 Win=38912 Len=0 TSval=562391476 TSecr=3659648951
     23 2.969797       105.103.82.47         105.103.15.106        TCP      66     8080 → 56158 [ACK] Seq=4183 Ack=1085 Win=17792 Len=0 TSval=3659648960 TSecr=562391475
     24 3.009816       105.103.82.47         105.103.15.106        TCP      66     8080 → 56158 [ACK] Seq=4183 Ack=1086 Win=17792 Len=0 TSval=3659649001 TSecr=562391476
     30 3.258792       105.103.82.47         105.103.15.106        TCP      66     8080 → 56158 [FIN, ACK] Seq=4183 Ack=1086 Win=17792 Len=0 TSval=3659649250 TSecr=562391476
     31 3.258803       105.103.15.106        105.103.82.47         TCP      66     56158 → 8080 [ACK] Seq=1086 Ack=4184 Win=38912 Len=0 TSval=562391548 TSecr=3659649250
```

So, this is not AWS-sdk fault but node´s limitation that can be workaround by using tunnel-agent properly configured.

Thanks for support.

**Comment by schof** [comment]
@jrbenito Thanks for posting this solution. I can confirm that use of the `tunnel` library worked for me.
