### ISSUE TITLE
Missing libraries for node_loader

### ISSUE THREAD

**Issue by rcfrias** [aws/aws-sdk-js#1634]
the file node_loader.js needs:

```
// node.js specific modules
	util.crypto.lib = require('crypto');
	util.Buffer = require('buffer').Buffer;
	util.domain = require('domain');
	util.stream = require('stream');
	util.url = require('url');
	util.querystring = require('querystring');
	util.environment = 'nodejs';
	var AWS;
	module.exports = AWS = require('./core');
```

from which non of them are included or defined as dependencies in the package.json.

It feels wrong to additionally have to add those dependencies by hand (Using System.js)

```
'aws-sdk/global': 'npm:aws-sdk/global',
      'crypto': 'npm:crypto' ...
```

**Comment by jeskew** [comment]
The `node_loader.js` file is only used in a Node.JS environment, and all of the modules mentioned are core modules provided by the Node.JS runtime. Can System.JS not automatically handle modules from node's standard library?

**Comment by rcfrias** [comment]
Not sure, I came to this hypothesis while trying to adapt the Cognito-Auth to Angular(4) Web app.  
So yeah, it makes sense that this wont be a problem in a Node.js app.  Now I just need a way of telling CognitoAuth that we are in a browser.  More to follow.

**Comment by jeskew** [comment]
When running in a browser, you will need to tell SystemJS to load the browser distributable instead of the package's main file. Please see https://github.com/aws/aws-sdk-js/issues/1337#issuecomment-276866816 for discussion and an example.

**Comment by rcfrias** [comment]
Yeah, so, it requires "/aws-sdk/global.js" and "/aws-sdk/clients/cognitoidentityserviceprovider.js
", and that is doing something wrong...

**Comment by jeskew** [comment]
If you add the following to your SystemJS declaration, do you still see any errors?

```
  System.config({
    paths: {
      // ...
    },
    map: {
      // ...
    },
    packages: {
      // ...
      'aws-sdk': {
        main: 'dist/aws-sdk.min.js',
        defaultExtension: 'js',
        format: 'global'
      }
    }
  });
```

**Comment by rcfrias** [comment]
After that update in SystemJS
im dealing with this:

```
(index):21 Error: (SystemJS) require is not a function
	TypeError: require is not a function
	    at eval (http://localhost:3000/node_modules/aws-sdk/global.js:1:1)
```

**Comment by rcfrias** [comment]
I think the amazon-cognito-auth.js script is the problem, because it has at the beginning this:

```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("aws-sdk/global"), require("aws-sdk/clients/cognitoidentityserviceprovider"));
	else if(typeof define === 'function' && define.amd)
		define(["aws-sdk/global", "aws-sdk/clients/cognitoidentityserviceprovider"], factory);
	else if(typeof exports === 'object')
		exports["AmazonCognitoIdentity"] = factory(require("aws-sdk/global"), require("aws-sdk/clients/cognitoidentityserviceprovider"));
	else
		root["AmazonCognitoIdentity"] = factory(root["AWSCognito"], root["AWSCognito"]["CognitoIdentityServiceProvider"]);
})(this, function(__WEBPACK_EXTERNAL_MODULE_7__, __WEBPACK_EXTERNAL_MODULE_11__) {
return /******/ (function(modules) { // webpackBootstrap
```
And the console is showing this message:

```
(SystemJS) Cannot set property '__esModule' of undefined
	TypeError: Cannot set property '__esModule' of undefined
	    at eval (http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js:102:50)
	    at Array.forEach (<anonymous>)
	    at Object.exports.__esModule (http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js:101:28)
	    at __webpack_require__ (http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js:48:30)
	    at exports.__esModule (http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js:68:18)
	    at eval (http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js:71:10)
	    at webpackUniversalModuleDefinition (http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js:27:35)
	    at eval (http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js:28:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:3000/node_modules/aws-sdk/dist/amazon-cognito-auth.js
```

Now I guess, I will try again with the sources, maybe I can get a way around.

**Comment by bravokeyl** [comment]
Since `Buffer` is a global in nodejs, may I know what's the use of doing this ` require('buffer').Buffer`? Same goes to others.

**Comment by srchase** [comment]
@rcfrias 

Is this still an open issue for you?
