### ISSUE TITLE
SDK throws error on remote servers, works well in local

### ISSUE THREAD

**Issue by DavidGereb** [aws/aws-sdk-js#1645]
We are using nodejs `aws-sdk@2.2.45` for a while, handling thousands of messages daily with SQS. But for a several hours now, we've just started receiveving the following error on a **production** environment:
```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided.
Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
The Canonical String for this request should have been
'...'
The String-to-Sign should have been 
'...'
at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/query.js:47:29)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at callNextListener (/app/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
at IncomingMessage.onEnd (/app/node_modules/aws-sdk/lib/event_listeners.js:269:13)
at emitNone (events.js:110:20)
at IncomingMessage.emit (events.js:207:7)
```
There has been no modification on the infrastruture, and IAMs are configured well. AWS creds have been tested and working on local, we've been able to send messages to our queues with the same `aws-sdk` package version with the same configuration.
IAM ARN sample: `arn:aws:iam::<uid>:user/iam-user-name`

**Comment by chrisradek** [comment]
@gerebdavid 
Can you share where your credentials are sourced from (shared credentials, env variables, etc) and if you're running on EC2 or ECS? Also, is every request failing, or is it intermittent?

It might also be helpful to see what the expected canonical string is (sans credentials) if you can remove identifying info.

**Comment by gerebdavid** [comment]
@chrisradek Credentials are provided via environment variables. We are running on kubernetes. Failing seems to be intermittent, but it's very frequent.

The expected canonical string is:
```
'POST / host:sqs.us-east-1.amazonaws.com request-id:a7d12be2-6a3a-484d-ad13-de2de00718c4 x-amz-content-sha256:2d2ffadd83b2f654cb7bdfd4bdd79ff720c9e9ff16d33052241b88fd76e38511 x-amz-date:20170726T110800Z x-client-send:1501067280687031 x-parent:0 x-span-id:13512653-1997-46e5-8d32-5daddca93374 host;request-id;x-amz-content-sha256;x-amz-date;x-client-send;x-parent;x-span-id 2d2ffadd83b2f654cb7bdfd4bdd79ff720c9e9ff16d33052241b88fd76e38511'
```

**Comment by jeskew** [comment]
What do the `x-parent` and `x-span-id` headers mean? Would those have been present on requests sent from your local environment, and would you expect a proxy in your production environment to alter those headers in any way?

**Comment by gerebdavid** [comment]
@jeskew We are not modifying the headers AFAIK. It's generated by the aws-sdk I think so.

**Comment by jeskew** [comment]
Those headers wouldn't be generated by the SDK. Just based on the names, they look like headers added by an instrumentation library. As such, I suspect they are "hop-by-hop" rather than "end-to-end" headers, i.e., headers that can reasonably be changed by a proxy or server in between your application and the AWS service receiving the message.

Are you using any kind of HTTP instrumentation in production that is not present in your local environment?

**Comment by DavidGereb** [comment]
If I remember right, it was some http queuing issue with expired timestamps and signatures.
