### ISSUE TITLE
© as a part of Content-Disposition header leads to SignatureDoesNotMatch

### ISSUE THREAD

**Issue by oaleynik** [aws/aws-sdk-js#1648]
Hi all!

ContentDisposition which is set to `attachment; filename="1 ©.jpg"` leads to:
```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Without ContentDisposition, or with ContentDisposition for file without © as a part of the name works fine. 

Per https://tools.ietf.org/html/rfc6266 and https://cs.stanford.edu/people/miles/iso8859.html © symbol should be allowed to be part of Content-Disposition header.

Can somebody give me a hint - what is wrong?

### Sample

```javascript
const fs = require('fs');
const path = require('path');
const util = require('util');

const AWS = require('aws-sdk');

const s3config = {
  bucket: '',
  accessKeyId: '',
  secretAccessKey: '',
  region: ''
};

AWS.config.update(s3config);

const S3 = new AWS.S3();

(async function() {
  const filepath = path.resolve('1 ©.jpg');
  const filename = path.basename(filepath);
  const rs = fs.createReadStream(filepath);

  const params = {
    Bucket: s3config.bucket,
    Key: 'images/gavinwadephoto/this-is-the-test-file.jpg',
    ContentDisposition: 'attachment; filename="1 ©.jpg"',
    Body: rs,
  };

  let upload = new AWS.S3.ManagedUpload({
    partSize: 10 * 1024 * 1024,
    queueSize: 5,
    params,
  });

  const result = await upload.promise();

  console.dir(result);
}()).catch(err => console.dir(err));
```

P.S. If add `Content-Disposition` to the list of ignored headers, request will go through:
https://github.com/aws/aws-sdk-js/blob/5d868465426a66c9bdae1f3f0bb67aeca5a5825f/lib/signers/v4.js#L190

**Comment by jeskew** [comment]
Hi @oaleynik,

I was able to reproduce the issue as described, but I believe this is a result of how strings are represented in JavaScript vs how they are interpreted over HTTP. It's true that the `©` character exists both in the ISO-8859-1 and UTF-8 character sets, but it is encoded differently in them, with the former representing it as `0xa9` and the latter as `[0xc2, 0xa9]`. When the SDK is signing a request, it uses Node.JS's default string encoding (UTF-8) to determine the byte buffer to sign. Node does not support ISO-8859-1 encoding:

```
> Buffer.from('©')
<Buffer c2 a9>
> Buffer.from('©', 'iso-8859-1')
TypeError: "encoding" must be a valid string encoding
    at fromString (buffer.js:264:13)
    at Function.Buffer.from (buffer.js:150:12)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
```

If the headers being sent include any characters outside of the US-ASCII character set, I would recommend using the [extended encoding scheme discussed in RFC-6266](https://tools.ietf.org/html/rfc6266#section-5). This allows for the encoding of arbitrary UTF-8 sequences and allows both the SDK and S3 to correctly determine the byte sequence to sign.

For the particular filename provided in the example, this would look like `"attachment; filename*=UTF-8''1%20%C2%A9.jpg"`. Generically, this could be determined from any filename `X` with the following function:
```
function getContentDisposition(filename) {
    return `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`;
}
```

**Comment by oaleynik** [comment]
Hi @jeskew! Thank you for response. Node actually has ISO-8859-1 encoding - it is aliased to 'latin1'.

```
> Buffer.from('©')
<Buffer c2 a9>
> Buffer.from('©', 'latin1')
<Buffer a9>
```

**Comment by jeskew** [comment]
You're right -- decoding the header string as 'latin1' isn't much help, as the signature will still need to match the one calculated by S3. I believe the safest way to guarantee signatures will match is to only use US-ASCII in header values and to use extended `filename*=UTF-8''` encoding for any string that could contain characters outside of the US-ASCII set.
