### ISSUE TITLE
new issue - InvalidSignatureException ? 

### ISSUE THREAD

**Issue by fprivitera** [aws/aws-sdk-js#168]
in the last few days I am having this error. Can it be related to the new version of the module? 

"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details." - code:InvalidSignatureException

**Comment by sabrinaluo** [comment]
same issue, nodejs@5.0.2 aws-sdk@2.2.21

```
InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/2015-03-31/functions/usercity_getRegionalTableByLocale/invocations
Qualifier=PROD
host:lambda.ap-northeast-1.amazonaws.com
x-amz-content-sha256:dcf4f50cca02685575a3c860c453eb09c66000b481359c9870e737cce54ad222
x-amz-date:20151204T084257Z

host;x-amz-content-sha256;x-amz-date
dcf4f50cca02685575a3c860c453eb09c66000b481359c9870e737cce54ad222'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20151204T084257Z
20151204/ap-northeast-1/lambda/aws4_request
8fa220f683adb6517b2df8f5558075060e023aabc1bb0308963977e75f161dda'

```

**Comment by compwright** [comment]
Same here with version 2.102.0:

```
{ InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:logs.us-east-1.amazonaws.com
x-amz-content-sha256:bc57f9a1b9550796843253f0df0271345bffa818f3b067bbed3402377acb0fd3
x-amz-date:20170827T072221Z
x-amz-target:Logs_20140328.DescribeLogStreams

host;x-amz-content-sha256;x-amz-date;x-amz-target
bc57f9a1b9550796843253f0df0271345bffa818f3b067bbed3402377acb0fd3'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20170827T072221Z
20170827/us-east-1/logs/aws4_request
422964b9aec83cb77088a89f80dea065183aae2ecddbe79c194748cd5db7ab48'

    at Request.extractError (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/nodejs/node-v6.11.2-linux-x64/lib/node_modules/bbva_email/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by TylerSustare** [comment]
I'm getting the same issue using version 2.5.2

**Comment by gigaga** [comment]
Same issue with 2.220.1.
Someone can propose a workaround?

**Comment by TylerSustare** [comment]
I need to update my comment, I had a typo in my keys when I got this error. I am not getting this error after using the correct keys. 👈 shame :(
