### ISSUE TITLE
Error: Invalid location provided. It has to consist of at least two elements separated by /

### ISSUE THREAD

**Issue by ArnoTF** [aws/aws-sdk-js#1689]
Hi,

I get an error in a Lambda function. The stacktrace indicates it is coming from the AWS-SDK:

8/16/2017, 6:57:11 PM 2017-08-16T16:57:11.196Z	eddea1d3-82a3-11e7-9d41-4fd55f6a2a02	Error: Invalid location provided. It has to consist of at least two elements separated by /
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

8/16/2017, 6:57:11 PM RequestId: eddea1d3-82a3-11e7-9d41-4fd55f6a2a02 Process exited before completing request

Can you look into this please?

**Comment by ArnoTF** [comment]
I think I know where it is coming from. I will reopen this when needed.
