### ISSUE TITLE
Bad marshalling in DynamoDBTypeConverterEnum.

### ISSUE THREAD

**Issue by adrianboimvaser** [aws/aws-sdk-js#1708]
DynamoDBTypeConverterEnum should use ``.name()`` instead of ``.toString()`` to marshall enums.

```
public enum VSROption {
    ALL("All"),
    EVENT_INVENTORY("TicketsNow Only"),
    OTHER("Other Sites Only"),
    NONE("None");

    private final String displayName;

    VSROption(String displayName) {
        this.displayName = displayName;
    }

    @Override
    public String toString() {
        return displayName;
    }
}
```

```
com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: InventoryTest[vsrOption]; could not unconvert attribute
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperTableModel.unconvert(DynamoDBMapperTableModel.java:271)
...
Caused by: java.lang.IllegalArgumentException: No enum constant com.vividseats.skybox.models.domain.enumerations.VSROption.TicketsNow Only
    at java.lang.Enum.valueOf(Enum.java:238)
    at com.amazonaws.services.dynamodbv2.datamodeling.StandardTypeConverters$ToEnum$FromString.convert(StandardTypeConverters.java:735)
```

**Comment by AllanFly120** [comment]
Hi, this is an issue concerning other SDK. You may open an issue [there](https://github.com/aws/aws-sdk-java/issues). This one will be closed.
