### ISSUE TITLE
XMLParserError: Unexpected close tag

### ISSUE THREAD

**Issue by rahulitzme94** [aws/aws-sdk-js#1721]
I'm facing an error while trying to create a bucket using fakes3 
  
`const createParams = {
      Bucket: 'trialBucket',
    }
    s3Client.createBucket(createParams, (err, data) => {
      if (err) console.log('errrorrr', err);
      else console.log('Bucket created', data);
    });
`

I receive an error

` { XMLParserError: Unexpected close tag
[1] Line: 11
[1] Column: 9
[1] Char: >
[1]     at error (path/node_modules/sax/lib/sax.js:667:10)
[1]     at strictFail (path/node_modules/sax/lib/sax.js:693:7)
[1]     at closeTag (path/node_modules/sax/lib/sax.js:887:9)
[1]     at SAXParser.write (path/node_modules/sax/lib/sax.js:1449:13)
[1]     at Parser.exports.Parser.Parser.parseString (path/node_modules/xml2js/lib/xml2js.js:508:31)
[1]     at Parser.parseString (path/node_modules/xml2js/lib/xml2js.js:7:59)
[1]     at NodeXmlParser.parse (path/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
[1]     at Request.extractError (path/node_modules/aws-sdk/lib/services/s3.js:563:39)
[1]     at Request.callListeners (path/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
[1]     at Request.emit (path/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
[1]     at Request.emit (path/node_modules/aws-sdk/lib/request.js:683:14)
[1]     at Request.transition (path/node_modules/aws-sdk/lib/request.js:22:10)
[1]     at AcceptorStateMachine.runTo (path/node_modules/aws-sdk/lib/state_machine.js:14:12)
[1]     at path/node_modules/aws-sdk/lib/state_machine.js:26:10
[1]     at Request.<anonymous> (path/node_modules/aws-sdk/lib/request.js:38:9)
[1]     at Request.<anonymous> (path/node_modules/aws-sdk/lib/request.js:685:12)
[1]   message: 'Unexpected close tag\nLine: 11\nColumn: 9\nChar: >',
[1]   code: 'XMLParserError',
[1]   retryable: true,
[1]   time: 2017-09-15T13:40:15.877Z,
[1]   statusCode: 500 }`

**Comment by rahulitzme94** [comment]
The issue was with the fake s3 location the access to that location was denied

**Comment by manticarodrigo** [comment]
@rahulitzme94 I thought fake s3 didn't care about permissions. I'm getting this error now and it was working fine yesterday. What should I do?

**Comment by rahulitzme94** [comment]
@manticarodrigo  the location provided in the command ie, `fakes3 -r /mnt/fakes3_root -p 4567` fakeS3 does need permission for accessing the location /mnt/fakes3_root. so could you try the same command with sudo access?
