### ISSUE TITLE
CodeCommit module return empty list of repositories

### ISSUE THREAD

**Issue by mgeissen** [aws/aws-sdk-js#1727]
I use SDK version 2.119.0 with node.js.

When I use the js sdk to list all repos of CodeCommit, I receive always an empty array. The following code snippet show how I implement it:

JS Code:
```
const AWS = require('aws-sdk');
AWS.config.loadFromPath('./credentials.json');

const codecommit = new AWS.CodeCommit();

codecommit.listRepositories({}, (err, data) => {
    if(err){
        console.log(err, err.stack);
    } else{
        console.log(data);
    }
});
```
Console output:
`{ repositories: [] }`

I have check the same function in the aws cli and with the java sdk. Following works for me:

CLI Command:
`aws codecommit list-repositories --profile sameProfil `
Output:
```
{
    "repositories": [
        {
            "repositoryName": "repoX", 
            "repositoryId": "someId"
        }, 
        {
            "repositoryName": "repoY", 
            "repositoryId": "otherId"
        }, 
        [..]
    ]
}
```

Java code:
```
BasicAWSCredentials credentials = new BasicAWSCredentials("AWSAccessKeyId", "AWSSecretKey");
        STSSessionCredentialsProvider provider = new STSSessionCredentialsProvider(credentials);

        AWSCodeCommit awsCodeCommit = AWSCodeCommitClientBuilder.standard()
                .withCredentials(provider)
                .build();

        ListRepositoriesResult result = awsCodeCommit.listRepositories(new ListRepositoriesRequest());
        List<RepositoryNameIdPair> repositories = result.getRepositories();
        repositories.forEach(pair -> System.out.println(pair.getRepositoryName()));
```
Output:
```
repoX
repoY
[..]
```

I am certain, that I use the same credentials in all options.

**Comment by Ishank-dubey** [comment]
I think u r missing the _params_ something like([here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeCommit.html#listRepositories-property)) -

 ```
var params = {
  nextToken: 'STRING_VALUE',
  order: ascending | descending,
  sortBy: repositoryName | lastModifiedDate
};
codecommit.listRepositories(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

**Comment by mgeissen** [comment]
On [this](http://docs.aws.amazon.com/codecommit/latest/APIReference/API_ListRepositories.html) site it stands that the params are not _Required_.

**Comment by jeskew** [comment]
Hi @mgeissen,

Are you sure all the tools are using the same region? The `ListRepositories` operation will only return repositories located in the region to which the API call was sent, and the code samples above appear to be deducing the AWS region from the environment. Can you check to see what values are used for the `AWS_REGION` and `AWS_DEFAULT_REGION` environment variables, as well as if a region is specified in the `~/.aws/config` file?

For example, this is the output I received when trying to reproduce this issue:
```
$ node .sandbox/issues/1727.js 
{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/path/to/aws-sdk-js/lib/event_listeners.js:91:45)
    at Request.callListeners (/path/to/aws-sdk-js/lib/sequential_executor.js:105:20)
    at callNextListener (/path/to/aws-sdk-js/lib/sequential_executor.js:95:12)
    at /path/to/aws-sdk-js/lib/event_listeners.js:85:9
    at finish (/path/to/aws-sdk-js/lib/config.js:315:7)
    at /path/to/aws-sdk-js/lib/config.js:333:9
    at SharedIniFileCredentials.get (/path/to/aws-sdk-js/lib/credentials.js:126:7)
    at getAsyncCredentials (/path/to/aws-sdk-js/lib/config.js:327:24)
    at Config.getCredentials (/path/to/aws-sdk-js/lib/config.js:347:9)
    at Request.VALIDATE_CREDENTIALS (/path/to/aws-sdk-js/lib/event_listeners.js:80:26)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2017-09-20T16:42:01.362Z }
$ AWS_REGION=us-west-2 node .sandbox/issues/1727.js 
{ repositories: 
   [ { repositoryName: 'myRepo',
       repositoryId: 'a_UUID' } ] }
$ AWS_REGION=us-west-1 node .sandbox/issues/1727.js 
{ repositories: [] }
```

The `.sandbox/issues/1727.js` is:
```javascript
const AWS = require('aws-sdk');

const cc = new AWS.CodeCommit();

cc.listRepositories((err, data) => {
  if (err) {
    console.error(err);
  } else {
    console.log(data);
  }
});
```

**Comment by mgeissen** [comment]
Hi @jeskew,

I'm a noob! I checked my region settings and in the credentials.json I'm using some other region.

Sorry for the unnecessary  request and thanks for your support!

Sorry for my
