### ISSUE TITLE
waitFor error: StateNotFoundError: State targetInService not found

### ISSUE THREAD

**Issue by ffoysal** [aws/aws-sdk-js#1732]
```
var AWS = require('aws-sdk');
AWS.config.update({region: 'us-west-2'});

var elbv2 = new AWS.ELBv2();

var params = {
  TargetGroupArn: 'my_target_arn_here'
};
elbv2.waitFor('targetInService', params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```
when I execute the above code, got the following error
```
$ node test.js
/home/foysal/node_modules/aws-sdk/lib/resource_waiter.js:196
      throw new AWS.util.error(new Error(), {
      ^

StateNotFoundError: State targetInService not found.
    at constructor.loadWaiterConfig (/home/foysal/node_modules/aws-sdk/lib/resource_waiter.js:196:32)
    at new constructor (/home/foysal/node_modules/aws-sdk/lib/resource_waiter.js:64:10)
    at waitFor (/home/foysal/node_modules/aws-sdk/lib/service.js:240:18)
    at Object.<anonymous> (/home/foysal/espial_works/tf-msp-aws/test.js:13:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by chrisradek** [comment]
@ffoysal 
Are you by chance using a version of the SDK older than 2.94.0? That's the version where `targetInService` appears.

Running the above in the latest version of the SDK, I don't get a `StateNotFoundError`.

**Comment by ffoysal** [comment]
THanks @chrisradek . It was wrong sdk version. now working.

**Comment by shubhamkes** [comment]
I am using the latest version 2.465.0 and noticing weird behaviour
I have more than 10 targets but **targetInService** can not fetch details for two targets out of those list and these targets having instances attached to it.

**Comment by trivikr** [comment]
Locking this thread as the issue is old, and resolved.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
