### ISSUE TITLE
Glacier ThrottlingException: Rate exceeded not handled in SDK

### ISSUE THREAD

**Issue by vardhanv** [aws/aws-sdk-js#1749]
Hi, 

Seems like the AWS SDK is not handling Rate Throttling exceptions for glacier. Please advice.

```
ThrottlingException: Rate exceeded 
    at Object.extractError (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/protocol/rest_json.js:45:8)
    at Request.callListeners (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/vardhan/play/nodejs-eclipse/glacier-delete/node_modules/aws-sdk/lib/request.js:685:12)
```

**Comment by jeskew** [comment]
The SDK will retry `ThrottlingException` errors, but there is a maximum number of times that will be retried before the error is surfaced. By default, if a Glacier client encounters a throttling error on its 3rd retry, then the request will fail. You can adjust the number of retries that will be attempted by setting the `maxRetries` configuration parameter: 

```javascript
const glacier = new AWS.Glacier({
    region: 'us-west-2',
    maxRetries: 5
});
```

**Comment by vardhanv** [comment]
Thank you. Is the error not reported in the call back, so I can slow down my request rate? 


Sent from Yahoo Mail for iPhone


On Monday, October 9, 2017, 12:57 AM, Jonathan Eskew <notifications@github.com> wrote:


The SDK will retry ThrottlingException errors, but there is a maximum number of times that will be retried before the error is surfaced. By default, if a Glacier client encounters a throttling error on its 3rd retry, then the request will fail. You can adjust the number of retries that will be attempted by setting the maxRetries configuration parameter:
const glacier = new AWS.Glacier({
    region: 'us-west-2',
    maxRetries: 5
});

**Comment by jeskew** [comment]
Callbacks are only invoked when an operation succeeds, fails with a terminal error, or when all retries have been exhausted. If you do receive a `ThrottlingException` error in a callback, it likely means that the operation was throttled several times and indicates that your application is exceeding the Glacier API limits.
