### ISSUE TITLE
TypeError while using lex service to update abortStatement

### ISSUE THREAD

**Issue by liesislukas** [aws/aws-sdk-js#1791]
"aws-sdk": "^2.143.0",
node v8.9.0
OS X

updated aws-sdk to `^2.145.0`, same errors.

```
{ TypeError: Cannot read property 'messages' of undefined
  at ParamValidator.validateStructure (/...../node_modules/aws-sdk/lib/param_validator.js:59:25)
  at ParamValidator.validateMember (/...../node_modules/aws-sdk/lib/param_validator.js:88:21)
  at ParamValidator.validateStructure (/...../node_modules/aws-sdk/lib/param_validator.js:75:14)
  at ParamValidator.validateMember (/...../node_modules/aws-sdk/lib/param_validator.js:88:21)
  at ParamValidator.validate (/...../node_modules/aws-sdk/lib/param_validator.js:34:10)
  at Request.VALIDATE_PARAMETERS (/...../node_modules/aws-sdk/lib/event_listeners.js:125:42)
  at Request.callListeners (/...../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
  at callNextListener (/...../node_modules/aws-sdk/lib/sequential_executor.js:95:12)
  at /...../node_modules/aws-sdk/lib/event_listeners.js:85:9
  at finish (/...../node_modules/aws-sdk/lib/config.js:320:7)
  at /...../node_modules/aws-sdk/lib/config.js:338:9
  at Credentials.get (/...../node_modules/aws-sdk/lib/credentials.js:126:7)
  at getAsyncCredentials (/...../node_modules/aws-sdk/lib/config.js:332:24)
  at Config.getCredentials (/...../node_modules/aws-sdk/lib/config.js:352:9)
  at Request.VALIDATE_CREDENTIALS (/...../node_modules/aws-sdk/lib/event_listeners.js:80:26)
  at Request.callListeners (/...../node_modules/aws-sdk/lib/sequential_executor.js:101:18)
  at Request.emit (/...../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/...../node_modules/aws-sdk/lib/request.js:683:14)
  at Request.transition (/...../node_modules/aws-sdk/lib/request.js:22:10)
  at AcceptorStateMachine.runTo (/...../node_modules/aws-sdk/lib/state_machine.js:14:12)
  at Request.runTo (/...../node_modules/aws-sdk/lib/request.js:403:15)
  at Request.send (/...../node_modules/aws-sdk/lib/request.js:367:10)
  at features.constructor.makeRequest (/...../node_modules/aws-sdk/lib/service.js:193:27)
  at features.constructor.svc.(anonymous function) [as putBot] (/...../node_modules/aws-sdk/lib/service.js:499:23)
  at Object._callee$ (/...../src/api/helpers/aws/helpers/bot/updateAbortStatements.js:66:33)
  at tryCatch (/...../node_modules/regenerator-runtime/runtime.js:65:40)
  at Generator.invoke [as _invoke] (/...../node_modules/regenerator-runtime/runtime.js:299:22)
  at Generator.prototype.(anonymous function) [as next] (/...../node_modules/regenerator-runtime/runtime.js:117:21)
  at step (/...../src/api/helpers/aws/helpers/bot/updateAbortStatements.js:1:287)
  at /...../src/api/helpers/aws/helpers/bot/updateAbortStatements.js:1:447
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Cannot read property \'messages\' of undefined',
    code: 'TypeError',
  time: 2017-11-06T15:21:46.241Z } 
```
To reproduce:

1. create bot with minimum input
```
    Lex.modelBuilding.putBot({
      name,
      locale,
      childDirected,
    }, (error, data) => {
    });
```
2. update bot with 

abortStatement has only messages: 
```
  const messages = [{
    content: 'Some text of the message',
    contentType: 'PlainText',
  }];
```

name is same as used in step 1

```
const updatedBot = {
      name,
      abortStatement,
      checksum: currentBot.data.checksum,
      childDirected: currentBot.data.childDirected,
      clarificationPrompt: currentBot.data.clarificationPrompt,
      description: currentBot.data.description,
      idleSessionTTLInSeconds: currentBot.data.idleSessionTTLInSeconds,
      intents: currentBot.data.intents,
      locale: currentBot.data.locale,
      processBehavior: currentBot.data.processBehavior,
      voiceId: currentBot.data.voiceId,
    };

    Lex.modelBuilding.putBot(updatedBot, (error, data) => {
      console.log(error);
    });
```

**Comment by liesislukas** [comment]
Same thing while updating childDirected from false to true. I've used new bot just like described in initial post and called putBot with:

```

    const updatedBot = {
      name,
      abortStatement: currentBot.data.abortStatement,
      checksum: currentBot.data.checksum,
      childDirected,
      clarificationPrompt: currentBot.data.clarificationPrompt,
      description: currentBot.data.description,
      idleSessionTTLInSeconds: currentBot.data.idleSessionTTLInSeconds,
      intents: currentBot.data.intents,
      locale: currentBot.data.locale,
      processBehavior: currentBot.data.processBehavior,
      voiceId: currentBot.data.voiceId,
    };

    Lex.modelBuilding.putBot(updatedBot, (error, data) => {
      console.log(error, data);
    });
```

```

{ TypeError: Cannot read property 'messages' of undefined
  at ParamValidator.validateStructure (/....../node_modules/aws-sdk/lib/param_validator.js:59:25)
  at ParamValidator.validateMember (/....../node_modules/aws-sdk/lib/param_validator.js:88:21)
  at ParamValidator.validateStructure (/....../node_modules/aws-sdk/lib/param_validator.js:75:14)
  at ParamValidator.validateMember (/....../node_modules/aws-sdk/lib/param_validator.js:88:21)
  at ParamValidator.validate (/....../node_modules/aws-sdk/lib/param_validator.js:34:10)
  at Request.VALIDATE_PARAMETERS (/....../node_modules/aws-sdk/lib/event_listeners.js:125:42)
  at Request.callListeners (/....../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
  at callNextListener (/....../node_modules/aws-sdk/lib/sequential_executor.js:95:12)
  at /....../node_modules/aws-sdk/lib/event_listeners.js:85:9
  at finish (/....../node_modules/aws-sdk/lib/config.js:320:7)
  at /....../node_modules/aws-sdk/lib/config.js:338:9
  at Credentials.get (/....../node_modules/aws-sdk/lib/credentials.js:126:7)
  at getAsyncCredentials (/....../node_modules/aws-sdk/lib/config.js:332:24)
  at Config.getCredentials (/....../node_modules/aws-sdk/lib/config.js:352:9)
  at Request.VALIDATE_CREDENTIALS (/....../node_modules/aws-sdk/lib/event_listeners.js:80:26)
  at Request.callListeners (/....../node_modules/aws-sdk/lib/sequential_executor.js:101:18)
  at Request.emit (/....../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
  at Request.emit (/....../node_modules/aws-sdk/lib/request.js:683:14)
  at Request.transition (/....../node_modules/aws-sdk/lib/request.js:22:10)
  at AcceptorStateMachine.runTo (/....../node_modules/aws-sdk/lib/state_machine.js:14:12)
  at Request.runTo (/....../node_modules/aws-sdk/lib/request.js:403:15)
  at Request.send (/....../node_modules/aws-sdk/lib/request.js:367:10)
  at features.constructor.makeRequest (/....../node_modules/aws-sdk/lib/service.js:193:27)
  at features.constructor.svc.(anonymous function) [as putBot] (/....../node_modules/aws-sdk/lib/service.js:499:23)
  at Object._callee$ (/....../src/api/helpers/aws/helpers/bot/updateChildDirected.js:48:33)
  at tryCatch (/....../node_modules/regenerator-runtime/runtime.js:65:40)
  at Generator.invoke [as _invoke] (/....../node_modules/regenerator-runtime/runtime.js:299:22)
  at Generator.prototype.(anonymous function) [as next] (/....../node_modules/regenerator-runtime/runtime.js:117:21)
  at step (/....../src/api/helpers/aws/helpers/bot/updateChildDirected.js:1:287)
  at /....../src/api/helpers/aws/helpers/bot/updateChildDirected.js:1:447
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Cannot read property \'messages\' of undefined',
    code: 'TypeError',
  time: 2017-11-06T15:41:42.610Z }
```

**Comment by AllanFly120** [comment]
Hi @liesislukas,
According type definition of SDK, the `messages` property in `abortStatement` and `clarificationPrompt` is required. One thing you can do is to check whether you have set these properties.

**Comment by liesislukas** [comment]
Thank you for quick respond. While your statement is true, data was missing but the error did not say anything about it + i was able to create bot **without all** data provided but when i call to update it throws TypeError. I think this issue is still valid telling about poor developer experience while using sdk because of not informative messages. And **TypeError** is not something i would expect from aws. Seems like a bug.
