### ISSUE TITLE
Cloudwatch putMetricAlarm Rate exceeded error

### ISSUE THREAD

**Issue by patrick-motard** [aws/aws-sdk-js#1822]
I'm getting this same error for Cloudwatch putMetricAlarm.

```
{ Throttling: Rate exceeded
    at Request.extractError (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'Rate exceeded',
  code: 'Throttling',
  time: 2017-05-24T00:11:10.473Z,
  requestId: '7da27912-4015-11e7-a4b7-19825624989e',
  statusCode: 400,
  retryable: true }

```
I also have the following as recommended in [#412](https://github.com/aws/aws-sdk-js/issues/412)  :

```
AWS.events.on('retry', function(resp) {
    if (resp.error && resp.error.code === 'Throttling') {
        resp.error.retryable = true;
    }
});

```

**Comment by chrisradek** [comment]
@patrick-motard 
The SDK should already be retrying on Throttling errors, and it looks like it will based on the `retryable: true` entry in your error.

You can tweak the retry behavior by modifying either the global config or the config passed into a client on instantiation:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#retryDelayOptions-property

By default, the SDK will attempt to retry 3 times, with exponential back-off/jitter that uses a base delay of 100 ms. 

It looks like putMetricAlarm has a limit of [3 transactions per second](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) so you may want to add logic to stay within those constraints if you're going vastly over this and retrying isn't enough, or request a limit increase.

**Comment by srchase** [comment]
@patrick-motard 

Do you have any further questions? If not, I'd like to close this issue.

**Comment by srchase** [comment]
Closing out this issue.  Let us know if you have anything additional to add.
