### ISSUE TITLE
Error Code: SignatureDoesNotMatch when trying to write ByteArrayInputStream to S3

### ISSUE THREAD

**Issue by vivekkr12** [aws/aws-sdk-js#1954]
I'm trying to read a Zip file from an S3 bucket and write the extracted file to another S3 bucket. 

```
static AmazonS3 amazonS3 = AmazonS3ClientBuilder.standard().withRegion("us-east-1")
            .build();

static AmazonS3 uploadClient = AmazonS3ClientBuilder.standard().withRegion("ap-south-1")
            .build();

void readAndWrite(String bucket, String key) {
    S3Object s3Object = amazonS3.getObject(bucket, key);
    S3ObjectInputStream objectContent = s3Object.getObjectContent();
    ZipInputStream sourceZipInputStream = new ZipInputStream(objectContent);
    
    ZipEntry zipEntry;
    
    while((zipEntry = sourceZipInputStream.getNextEntry()) != null) {
        String entryName = zipEntry.getName();
        String fileName = entryName.substring(entryName.lastIndexOf("/") + 1);
    
    
        ObjectMetadata s3objectMetadata = new ObjectMetadata();
        String contentType = fileName.endsWith(".kmz") ? "application/vnd.google-earth.kmz" : "image/png";
        s3objectMetadata.setContentType(contentType);
        s3objectMetadata.setContentLength(zipEntry.getSize());
    
        ByteArrayOutputStream artifactBytes = new ByteArrayOutputStream();
        byte[] buffer = new byte[10240];
        int len;
        while((len = sourceZipInputStream.read(buffer)) > -1) {
            artifactBytes.write(buffer, 0, len);
        }
        ByteArrayInputStream artifactBytesInputStream = new ByteArrayInputStream(artifactBytes.toByteArray());
    
        sourceZipInputStream.closeEntry();
    
        System.out.println(fileName + " | " + zipEntry.getSize() + " | " + artifactBytes.toByteArray().length);
    
        uploadClient.putObject( "dest-bucekt", fileName, artifactBytesInputStream, s3objectMetadata);
    
        System.out.println(threadName +": Copied " + fileName);
    
    
    }
    
    while(objectContent.read(new byte[1024]) != -1) {
        // do nothing
    }
    
    objectContent.close();
```

This code gives me the following output: 
```
xxxxxxxxxxxxxx.kmz | 4746776 | 4746776
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 879B93C38BEF5C2C), S3 Extended Request ID: tFPkVXjcmSZu0vUnppDVKz6zf1ZPnK0nJy8k8/MIH8S7oXuznZgNUrnZj56AWrOXDpVOKy6Xgm4=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4227)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4174)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1722)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1584)
```

For the record, both the access keys and the secret keys are correct, otherwise the source zip would not be read as well. If I write the `ByteArrayInputStream` to a file and then upload that file to S3, it works.

**Comment by vivekkr12** [comment]
Closing this as it needs to be posted in `aws-java-sdk`
