### ISSUE TITLE
Encountering error after running node setup.js and entering required parameters.

### ISSUE THREAD

**Issue by tnyanhongo** [aws/aws-sdk-js#1974]
Guys Im a newbie here and following the AZero-Administration Amazon Redshift Database Loader tutorial im running into an error below after inputting all parameters under section 
Getting Started: Entering the Configuration, node setup.js .Can anyone debug this for me .

Creating S3 Event Source for s3://pcg-ppl-wa-stats-data/
C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

TypeError: Cannot read property 'AWS:SourceAccount' of undefined
    at C:\Users\tnyanhongo\aws-lambda-redshift-loader\common.js:441:81
    at Array.map (<anonymous>)
    at Response.<anonymous> (C:\Users\tnyanhongo\aws-lambda-redshift-loader\common.js:440:24)
    at Request.<anonymous> (C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:360:18)
    at Request.callListeners (C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:673:14)
    at Request.transition (C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\tnyanhongo\aws-lambda-redshift-loader\node_modules\aws-sdk\lib\state_machine.js:26:10

Thanks 
tnyanhongo

**Comment by AllanFly120** [comment]
Hey @tnyanhongo 
Can you show me the link to the tutorial you are working on? and it would be helpful if you show me your code snippet especially on common.js line 440, 441 where the code is broken.

**Comment by tnyanhongo** [comment]
@AllanFly120 Here is the link to the tut Im following 
https://aws.amazon.com/blogs/big-data/a-zero-administration-amazon-redshift-database-loader/

As far as the code I believe here are lines you need.
First two are 440&441
![code](https://user-images.githubusercontent.com/37414235/37503814-90fb064e-28a8-11e8-955e-23ca8c978007.PNG)


statements.map(function (item) { 
if (item.Resource ===   functionArn && item.Condition.StringEquals['AWS:SourceAccount'] ===   sourceAccount) {
foundMatch = true;  
} 

Note In the documentation this is the Getting Started: Entering the Configuration--.run the setup.js script by entering node setup.js in Git Bash 

The code isnt mine and I have the common.js file installed locally when I installed AWS SDK for JavaScript .

Let me know if u need more information and thanks for looking at this!

**Comment by AllanFly120** [comment]
I think this issue happens because 'StringEquals' field is missing in the response of [`lambda.getPolicy()`](https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/common.js#L425). It may have something to do with the response parsing or your lambda IAM policy setting, rather than issues with aws-sdk. I believe you will get more accurate response directly from the library author if you raise the issue on the [lambda-redshift-loader repo](https://github.com/awslabs/aws-lambda-redshift-loader/issues).
