### ISSUE TITLE
Error yarn add aws-sdk

### ISSUE THREAD

**Issue by rafaelgfirmino** [aws/aws-sdk-js#1996]
Error using command 
```shell
yarn add aws-sdk
```

```shell
error Couldn't find package "aws.js-sign2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "aws.js-sign2" on the "npm" registry.
    at /usr/share/yarn/lib/cli.js:49061:15
    at Generator.next (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:92:30)
    at /usr/share/yarn/lib/cli.js:103:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by chrisradek** [comment]
@rafaelgfirmino 
Can you try adding the SDK in a new package? I'm not sure where `aws.js-sign2` is coming from, that is not related to our SDK.

I just created a new project running the following and didn't encounter any errors:
```bash
yarn init
yarn add aws-sdk
```

Tested using yarn 1.5.1 and node 8.4.0

**Comment by srchase** [comment]
Closing for inactivity.
