### ISSUE TITLE
s3.waitFor throws ResourceNotReady error

### ISSUE THREAD

**Issue by yohei1126** [aws/aws-sdk-js#2020]
When I try to call `waitFor`, it always throws ResourceNotReady error.
Would you help me fix this?
I am using  JavaScript SDK 2.225.1 and node v8.9.1

1. upload file to s3

```
$ aws s3 cp index.js s3://rfid-test/index.js
```

2. check if the key exists
```
$ aws s3api head-object --bucket rfid-test --key index.js
{
    "AcceptRanges": "bytes",
    "Expiration": "expiry-date=\"Tue, 24 Apr 2018 00:00:00 GMT\", rule-id=\"delete-expired-objects\"",
    "LastModified": "Fri, 20 Apr 2018 06:53:16 GMT",
    "ContentLength": 354,
    "ETag": "\"8ba84cb100e428b4532f6a298bd4d0ed\"",
    "ContentType": "application/javascript",
    "ServerSideEncryption": "AES256",
    "Metadata": {}
}
```

3. run code

```
$ cat index.js 
var AWS = require('aws-sdk');
var s3 = new AWS.S3({apiVersion: '2006-03-01'});
var params = {
  Bucket: 'rfid-test', /* required */
  Key: "index.js", /* required */
};
s3.waitFor('objectExists', params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
$ node index.js 
{ BadRequest: Resource is not in the state objectExists
    at Request.extractError (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/services/s3.js:557:35)
    at Request.callListeners (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/01087872/Documents/sample/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Resource is not in the state objectExists',
  code: 'ResourceNotReady',
  region: 'ap-northeast-1',
  time: 2018-04-20T06:57:24.180Z,
  requestId: 'DF9858D3CF21B178',
  extendedRequestId: 'AixdzDi/yHT8QpS5GclgwzyqJEJ2gnxjQPLTMboJGrNNYEd2YPsbaXAT34AL6Mq5ramVqi4Xt6E=',
  cfId: undefined,
  retryable: false,
  statusCode: 400,
  retryDelay: 5000 } 'BadRequest: Resource is not in the state objectExists\n    at Request.extractError (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/services/s3.js:557:35)\n    at Request.callListeners (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /Users/01087872/Documents/sample/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/Users/01087872/Documents/sample/node_modules/aws-sdk/lib/sequential_executor.js:115:18)'
```

my package.json is as follows.

```
$ cat package-lock.json 
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "aws-sdk": {
      "version": "2.225.1",
      "resolved": "https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.225.1.tgz",
      "integrity": "sha1-bsaZSmM38rVTsW9ldt806hrDFNg=",
      "requires": {
        "buffer": "4.9.1",
        "events": "1.1.1",
        "ieee754": "1.1.8",
        "jmespath": "0.15.0",
        "querystring": "0.2.0",
        "sax": "1.2.1",
        "url": "0.10.3",
        "uuid": "3.1.0",
        "xml2js": "0.4.17",
        "xmlbuilder": "4.2.1"
      }
    },
    "base64-js": {
      "version": "1.3.0",
      "resolved": "https://registry.npmjs.org/base64-js/-/base64-js-1.3.0.tgz",
      "integrity": "sha512-ccav/yGvoa80BQDljCxsmmQ3Xvx60/UpBIij5QN21W3wBi/hhIC9OoO+KLpu9IJTS9j4DRVJ3aDDF9cMSoa2lw=="
    },
    "buffer": {
      "version": "4.9.1",
      "resolved": "https://registry.npmjs.org/buffer/-/buffer-4.9.1.tgz",
      "integrity": "sha1-bRu2AbB6TvztlwlBMgkwJ8lbwpg=",
      "requires": {
        "base64-js": "1.3.0",
        "ieee754": "1.1.8",
        "isarray": "1.0.0"
      }
    },
    "events": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/events/-/events-1.1.1.tgz",
      "integrity": "sha1-nr23Y1rQmccNzEwqH1AEKI6L2SQ="
    },
    "ieee754": {
      "version": "1.1.8",
      "resolved": "https://registry.npmjs.org/ieee754/-/ieee754-1.1.8.tgz",
      "integrity": "sha1-vjPUCsEO8ZJnAfbwii2G+/0a0+Q="
    },
    "isarray": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz",
      "integrity": "sha1-u5NdSFgsuhaMBoNJV6VKPgcSTxE="
    },
    "jmespath": {
      "version": "0.15.0",
      "resolved": "https://registry.npmjs.org/jmespath/-/jmespath-0.15.0.tgz",
      "integrity": "sha1-o/Iiqarp+Wb10nx5ZRDigJF2Qhc="
    },
    "lodash": {
      "version": "4.17.5",
      "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.5.tgz",
      "integrity": "sha512-svL3uiZf1RwhH+cWrfZn3A4+U58wbP0tGVTLQPbjplZxZ8ROD9VLuNgsRniTlLe7OlSqR79RUehXgpBW/s0IQw=="
    },
    "punycode": {
      "version": "1.3.2",
      "resolved": "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz",
      "integrity": "sha1-llOgNvt8HuQjQvIyXM7v6jkmxI0="
    },
    "querystring": {
      "version": "0.2.0",
      "resolved": "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz",
      "integrity": "sha1-sgmEkgO7Jd+CDadW50cAWHhSFiA="
    },
    "sax": {
      "version": "1.2.1",
      "resolved": "https://registry.npmjs.org/sax/-/sax-1.2.1.tgz",
      "integrity": "sha1-e45lYZCyKOgaZq6nSEgNgozS03o="
    },
    "url": {
      "version": "0.10.3",
      "resolved": "https://registry.npmjs.org/url/-/url-0.10.3.tgz",
      "integrity": "sha1-Ah5NnHcF8hu/N9A861h2dAJ3TGQ=",
      "requires": {
        "punycode": "1.3.2",
        "querystring": "0.2.0"
      }
    },
    "uuid": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz",
      "integrity": "sha512-DIWtzUkw04M4k3bf1IcpS2tngXEL26YUD2M0tMDUpnUrz2hgzUBlD55a4FjdLGPvfHxS6uluGWvaVEqgBcVa+g=="
    },
    "xml2js": {
      "version": "0.4.17",
      "resolved": "https://registry.npmjs.org/xml2js/-/xml2js-0.4.17.tgz",
      "integrity": "sha1-F76T6q4/O3eTWceVtBlwWogX6Gg=",
      "requires": {
        "sax": "1.2.1",
        "xmlbuilder": "4.2.1"
      }
    },
    "xmlbuilder": {
      "version": "4.2.1",
      "resolved": "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-4.2.1.tgz",
      "integrity": "sha1-qlijBBoGb5DqoWwvU4n/GfP0YaU=",
      "requires": {
        "lodash": "4.17.5"
      }
    }
  }
}
```

**Comment by yohei1126** [comment]
Java SDK seems to be OK

```
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.GetObjectMetadataRequest;
import com.amazonaws.waiters.Waiter;
import com.amazonaws.waiters.WaiterParameters;

public class Main {
    public static void main(String[] args) {
        Waiter<GetObjectMetadataRequest> waiter = AmazonS3ClientBuilder.defaultClient().waiters().objectExists();
        GetObjectMetadataRequest request = new GetObjectMetadataRequest("rfid-test", "index.js");
        waiter.run(new WaiterParameters<>(request));
    }
}
```

**Comment by yohei1126** [comment]
This issue can be fixed by specifying region.
```
    const s3 = new S3({apiVersion: "2006-03-01", region: "ap-northeast-1"});
```

**Comment by vorticalbox** [comment]
> This issue can be fixed by specifying region.
> 
> ```
>     const s3 = new S3({apiVersion: "2006-03-01", region: "ap-northeast-1"});
> ```

```
const AWS = require('aws-sdk');
const s3 = new AWS.S3({
    region: 'eu-west-1',
});
 s3.waitFor('objectExists', params, (err, data) => err ? console.error(err) : console.info(data));
```

gives error 

```"Forbidden: Resource is not in the state objectExists"```

so adding the region does not fix this issue

**Comment by jorgeavaldez** [comment]
I'm experiencing the same issue.

Adding the region and version don't fix it.
