### ISSUE TITLE
Error: connect EHOSTDOWN 

### ISSUE THREAD

**Issue by nachbarshund** [aws/aws-sdk-js#2038]
Try to use a serverless s3 sync plugin (https://github.com/k1LoW/serverless-s3-sync) which use the aws-sdk.
Since today there is a connection problem:

```
/Users/nachbarshund/Projects/xxx/node_modules/@monolambda/s3/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: connect EHOSTDOWN 169.254.169.254:80 - Local (192.168.2.116:53971)
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at internalConnect (net.js:976:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:283:19)
    at net.js:1074:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Any ideas or solutions?

**Comment by AllanFly120** [comment]
Seems like this is a low-level connecting issue. In what circumstance does the issue happen? Can you provide any code or description to help us reproduce this issue?
