### ISSUE TITLE
Rekognition invalid parameter

### ISSUE THREAD

**Issue by keithdarragh** [aws/aws-sdk-js#2059]
Currently getting invalid parameter failure on requests to compareFaces of rekognition using this js SDK. I can make the same request using the python sdk and can successfully receive a comparison result. 

Each of the images contain a face and are not corrupt. 

`{ InvalidParameterException: Request has Invalid Parameters
    at Request.extractError (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/protocol/json.js:49:27)
    at Request.callListeners (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/keithdarragh/code/prototype/rekognition-test/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Request has Invalid Parameters',
  code: 'InvalidParameterException',
  time: 2018-05-22T13:14:48.014Z,
  requestId: '192c9243-5dc2-11e8-a49d-877a080f8540',
  statusCode: 400,
  retryable: false,
  retryDelay: 59.74350851590253 }`

Is there a reason we can get a comparison result for the python version and not JS?

**Comment by chrisradek** [comment]
@keithdarragh 
Can you share an example of how you're calling the operation?

**Comment by keithdarragh** [comment]
@chrisradek 

This is how we call the compareFaces operation: 
```    
const request = {
      SimilarityThreshold: 50,
      SourceImage: {
        Bytes: getBinary(body.sourceImage),
      },
      TargetImage: {
        Bytes: getBinary(body.targetImage),
      },
};
const response = await rekognition.compareFaces(request).promise();
```

Where body.sourceImage is a base64 encoded string. It is sent as base64-encoded image bytes.

Any ideas?

**Comment by chrisradek** [comment]
What does your `getBinary` function look like? Is it simply something like:
```javascript
return Buffer.from(image, 'base64');
```

Can you confirm that the `Bytes` fields are byte arrays?

I wasn't able to reproduce your issue using the following where both images are less than 5 MB:
```javascript
async function run() {
    const result = await rekognition.compareFaces({
        SimilarityThreshold: 50,
        SourceImage: {
            Bytes: fs.readFileSync(path.join(__dirname, 'face1.jpg'))
        },
        TargetImage: {
            Bytes: fs.readFileSync(path.join(__dirname, 'face2.jpg'))
        }
    }).promise();

    console.log(result);
}
```

**Comment by keithdarragh** [comment]
We solved the issue. Our image was getting captured with incorrect orientation values. Stripping the image exif data solved the problem.

**Comment by trevorrowe** [comment]
Glad to hear you resolved your issue.
