### ISSUE TITLE
Configure requests to http://*.amazonaws.com:443

### ISSUE THREAD

**Issue by filipre** [aws/aws-sdk-js#2076]
Hi!

In our server setup we are using "Istio Side Car Injections" which take care of TLS throughout all our deployed applications. As a consequence, all our requests have to be made using HTTP and not HTTPS.
I am wondering, if there is a way to configure the aws-sdk to make request not to `https://*.amazonaws.com` but `http://*.amazonaws.com:443`. Notice that the protocol is `http` but the port is still `443`. 

I tried to use `sslEnabled: false` for each Amazon request as well as globally in the AWS object (using AWS.config.update [1]), but this seems not to solve my problem. I also noticed that you can specify a proxy server but I don't want to proxy my requests through a different server but simply change the protocol and port (and nothing else). I also experimented a bit with an http agent but could not come up with a solution. 

This is my current error when I try to use `sslEnabled: false` only. The `unknown protocol` indicates that there are still requests using `https`.

```
{ Error: write EPROTO 140423368517440:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14)
  message: 'write EPROTO 140423368517440:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n',
  errno: 'EPROTO',
  code: 'NetworkingError',
  syscall: 'write',
  region: 'us-east-1',
  hostname: 'sts.amazonaws.com',
  retryable: true,
  time: 2018-06-06T11:42:24.536Z } 'Error: write EPROTO 140423368517440:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n\n    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14)'
```

I hope my question makes sense for you. Is there a simple way to solve this?

Greetings
René

## Related Issues

https://github.com/aws/aws-sdk-js/issues/1640, https://github.com/aws/aws-sdk-js/issues/862, 

## Node and SDK Version

- aws-sdk: `2.215.1`
- Node Version: `9.11.1`

## References

[1] AWS.config.update
```javascript
AWS.config.update({
   sslEnabled: false,
});
```

**Comment by filipre** [comment]
For anyone having the same issue: It seems like Istio 0.8 introduced a new resource type `ServiceEntry` that can enable https for defined hostnames.
