### ISSUE TITLE
s3.upload fails on streams: The "list[0]" argument must be one of type Array, Buffer, or Uint8Array. Received type string

### ISSUE THREAD

**Issue by jjosef** [aws/aws-sdk-js#2081]
Been trying to debug this, and the only solution I've been able to use is to stream to a buffer and then upload the buffer. This is not ideal. If anyone has a workaround it would be appreciated but this is the error I'm getting:

env: Node 10.2.0

```
TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be one of type Array, Buffer, or Uint8Array. Received type string
    at Function.concat (buffer.js:479:13)
    at ManagedUpload.fillStream (node_modules/aws-sdk/lib/s3/managed_upload.js:443:40)
    at ReadStream.<anonymous> (node_modules/aws-sdk/lib/s3/managed_upload.js:190:28)
    at ReadStream.emit (events.js:187:15)
    at ReadStream.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This is the code:
```js
const Client = require('ssh2-sftp-client')
let sftp = new Client()
let stream = await sftp.get(`${config.sftp.environment}/${file.name}`)

let params = {
  Bucket: config.s3.bucket,
  Key: file.name,
  Body: stream,
  ServerSideEncryption: 'AES256'
}

uploadResult = await s3.upload(params).promise()
```

Back tracing through this I'm unsure what the error is in managed_upload. It seems like its trying to Buffer.concat something that isn't a buffer or array. Could be an issue with stfp module, but that's just using node streams.

**Comment by jjosef** [comment]
Wow, thank you @chrisradek that fixed it. I thought I had tried this, but apparently I had configured it wrong.

```js
stream = await sftp.get(`${config.sftp.environment}/${file.name}`, false, null)
```
