### ISSUE TITLE
Cannot use profile with role

### ISSUE THREAD

**Issue by leonardoesx** [aws/aws-sdk-js#2115]
My ~/.aws/config is like this:
```
[profile dev]
output = json
region = us-east-1
role_arn = arn:aws:iam::<account_number>:role/<role_name>
source_profile = default
[default]
output = json
region = us-east-1
```

I'm using a small script to test listing all DynamDB tables:

```javascript
const AWS = require('aws-sdk');

var dynamodb = new AWS.DynamoDB();
var params = {
};
console.log('listTables');
dynamodb.listTables(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
  /*
  data = {
   clusterArns: [
      "arn:aws:ecs:us-east-1:<aws_account_id>:cluster/test", 
      "arn:aws:ecs:us-east-1:<aws_account_id>:cluster/default"
   ]
  }
  */
});
```

To assume my profile I'm using env variable AWS_PROFILE

```bash
export AWS_PROFILE=dev
node test.js
```

Running the script using my "dev" profile Is giving the following error:

```bash
HTTP 22057: createConnection 169.254.169.254:80: { servername: '169.254.169.254',
  path: null,
  headers: { 'User-Agent': 'aws-sdk-nodejs/2.265.1 linux/v10.5.0' },
  method: 'GET',
  port: 80,
  host: '169.254.169.254',
  _agentKey: '169.254.169.254:80:' }
NET 22057: createConnection [ { servername: '169.254.169.254',
    path: null,
    headers: { 'User-Agent': 'aws-sdk-nodejs/2.265.1 linux/v10.5.0' },
    method: 'GET',
    port: 80,
    host: '169.254.169.254',
    _agentKey: '169.254.169.254:80:',
    encoding: null },
  [Function: oncreate],
  [Symbol(normalizedArgs)]: true ]
NET 22057: pipe false null
HTTP 22057: sockets 169.254.169.254:80: 1
HTTP 22057: outgoing message end.
NET 22057: _read
NET 22057: _read wait for connection
NET 22057: afterConnect
NET 22057: destroy
NET 22057: close
NET 22057: close handle
HTTP 22057: SOCKET ERROR: connect ETIMEDOUT 169.254.169.254:80 Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:14)
{ Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:14)
  message: 'Missing credentials in config',
  errno: 'ETIMEDOUT',
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2018-06-28T17:15:43.246Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     errno: 'ETIMEDOUT',
     code: 'CredentialsError',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2018-06-28T17:15:43.246Z,
     originalError:
      { errno: 'ETIMEDOUT',
        code: 'ETIMEDOUT',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,
        message: 'connect ETIMEDOUT 169.254.169.254:80' } } } 'Error: connect ETIMEDOUT 169.254.169.254:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:14)'
NET 22057: emit close
HTTP 22057: CLIENT socket onClose
HTTP 22057: removeSocket 169.254.169.254:80: writable: false
HTTP 22057: HTTP socket close
```

**Comment by AllanFly120** [comment]
Hey @leonardoesx 

Our SDK does use the profile with role but it doesn't read the `~/.aws/config` by default. To enable reading the config file you can set environment variable: `export AWS_SDK_LOAD_CONFIG=1`. In addition, if you want to load config file from else where, you can use another env variable. For example: `export AWS_CONFIG_FILE=~/.aws/another_config`.
