### ISSUE TITLE
SQS failed to receiveMessage/read from the queue with JSON message body

### ISSUE THREAD

**Issue by warnerpinz** [aws/aws-sdk-js#2118]
During the sqs receiveMessage() call, below exception is thrown.
Here's the sample SQS message body:
{
  "Type" : "Notification",
  "MessageId" : "9bac8241-669d-55b0-b4ce-xxxxx",
  "TopicArn" : "arn:aws:sns:ap-southeast-1:xxxxxx:dev-xxxxx",
  "Message" : "{\"id\":5302589645580055883}",
  "Timestamp" : "2018-06-29T14:06:18.624Z",
  "SignatureVersion" : "1",
  "Signature" : "xxxx",
  "SigningCertURL" : "https://sns.ap-southeast-1.amazonaws.com/xxxx",
  "UnsubscribeURL" : "https://sns.ap-southeast-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=xxxx"
}

Exception thrown during the SQS receiveMessage() call:
{
    "code": "MalformedInput",
    "time": "2018-06-30T03:45:28.570Z",
    "requestId": "afadc835-7158-57cd-a286-9b858e401897",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 79.54107968865323
}
MalformedInput
at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:47:29)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)

**Comment by chrisradek** [comment]
@warnerpinz 
What are the parameters you're passing in your `receiveMessage` call?

Was this a one-time issue, or do you see this every time with the same parameters? When you encounter the error, it may be helpful if you also provide the body sent to the service. Here's an example of how to get that:

```javascript
sqs.receiveMessage({/** params **/}, function(err, data) {
  console.log(this.request.httpRequest.body.toString());
});
```
If you're using `AttributeNames` or `MessageAttributeNames`, we want to make sure that the parameters in the body start at index `1`.

If you can also share which version of the SDK you're using, as well as the runtime environment, that may help.
