### ISSUE TITLE
Getting 'Missing credentials in config' when using assume role

### ISSUE THREAD

**Issue by bahtou** [aws/aws-sdk-js#2139]
getting a similar error to this closed issue:
https://github.com/aws/aws-sdk-js/issues/1955

version: `aws-sdk@2..263.1`
OS: `macOS Sierra 10.13.4`

Issue:
Keep receving these errors

```
{ Error: connect EHOSTUNREACH
    at internalConnect (net.js:928:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at defaultTriggerAsyncIdScope (net.js:1020:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
  message: 'Missing credentials in config',
  errno: 'EHOSTUNREACH',
  code: 'CredentialsError',
  syscall: 'connect',
  address: <my_ip>
  port: <my_port>,
  time: 2018-07-13T19:26:53.413Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     errno: 'EHOSTUNREACH',
     code: 'CredentialsError',
     syscall: 'connect',
     address: <my_ip>
     port: <my_port>,
     time: 2018-07-13T19:26:53.413Z,
     originalError:
      { errno: 'EHOSTUNREACH',
        code: 'EHOSTUNREACH',
        syscall: 'connect',
        address: <my_ip>
        port: <my_port>,
        message:
         'connect EHOSTUNREACH <my_ip> - Local (<my_ip>)' } } } 'Error: connect EHOSTUNREACH <my_ip> - Local (<my_ip>)\n    
         at internalConnect (net.js:928:16)\n    
         at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)\n    
         at defaultTriggerAsyncIdScope (net.js:1020:9)\n    
         at process._tickCallback (internal/process/next_tick.js:61:11)\n    
         at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)\n    
         at startup (internal/bootstrap/node.js:240:19)\n    
         at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)'
```

```
{ Error: connect ETIMEDOUT <my_ip>
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:14)
  message: 'Missing credentials in config',
  errno: 'ETIMEDOUT',
  code: 'CredentialsError',
  syscall: 'connect',
  address: <my_ip>,
  port: <my_port>,
  time: 2018-07-13T19:17:29.317Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     errno: 'ETIMEDOUT',
     code: 'CredentialsError',
     syscall: 'connect',
     address: <my_ip>,
     port: <my_port>,
     time: 2018-07-13T19:17:29.317Z,
     originalError:
      { errno: 'ETIMEDOUT',
        code: 'ETIMEDOUT',
        syscall: 'connect',
        address: <my_ip>,
        port: <my_port>,
        message: 'connect ETIMEDOUT <my_ip>' } } } 'Error: connect ETIMEDOUT <my_ip>\n    
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:14)'
```

My set up:
`~/.aws/config`

```
[default]
region=us-east-1
role_arn=<arn-role>
source_profile=default
aws_access_key_id=<access-key>
aws_secret_access_key=<access-secret>
```

`~/.aws/credentials`

```
[default]
aws_access_key_id = <my_access_key>
aws_secret_access_key = <my_secret>
```

`~/.bash_profile`

```
export AWS_SDK_LOAD_CONFIG=1
export AWS_SHARED_CREDENTIALS_FILE=$HOME/.aws/credentials
export AWS_CONFIG_FILE=$HOME/.aws/config
```

Logging the `SharedIniFileCredentials` in `sts.config.credentialProvider`
```
SharedIniFileCredentials {
  expired: false,
  expireTime: null,
  accessKeyId: undefined,
  sessionToken: undefined,
  filename: undefined,
  profile: 'default',
  disableAssumeRole: false,
  preferStaticCredentials: false,
  roleArn: <arn-role> }
```

Test code is the following:

```
var AWS = require('aws-sdk');
AWS.config.region = 'us-east-1';

var sts = new AWS.STS();

sts.assumeRole({
  RoleArn: <arn-role>
  RoleSessionName: 'awssdk'
}, function(err, data) {
  if (err) { // an error occurred
    console.log('Cannot assume role');
    console.log(err, err.stack);
  } else { // successful response
    AWS.config.update({
      accessKeyId: data.Credentials.AccessKeyId,
      secretAccessKey: data.Credentials.SecretAccessKey,
      sessionToken: data.Credentials.SessionToken
    });
  }
});
```

Thank you in advance!

**Comment by bahtou** [comment]
I changed my test code to 
```
async function connAWS() {
  var sts = new AWS.STS({ region: 'us-east-1' });

  const params = {
    RoleArn: '<arn-role>',
    RoleSessionName: 'awssdk'
  };
  let assumeRole;

  try {
    assumeRole1 = await sts.assumeRole(params).promise();
  } catch (err) {
    console.log('Cannot assume role');
    console.log(err, err.stack);
    return;
  }

  const accessparams = {
    accessKeyId: assumeRoleStep1.Credentials.AccessKeyId,
    secretAccessKey: assumeRoleStep1.Credentials.SecretAccessKey,
    sessionToken: assumeRoleStep1.Credentials.SessionToken,
  };

  const s3 = await new AWS.S3(accessparams);
  console.log('s3', s3);
}

connAWS();
```

Devops had the assumeRole misconfigured. The above works.
closing

**Comment by shivarajbakale** [comment]
The error persists @bahtou

**Comment by bahtou** [comment]
@shivarajbakale whats your setup look like?

**Comment by bahtou** [comment]
@rhaegar453 I am currently using the above configuration on my machine without issues. I would suggest you make sure your `~/.aws/config` & `~/.aws/credentials` have the necessary creds. Also, double check the configuration in the AWS console to make sure `assumeRole` is configured correctly (as that was the ONLY issue preventing the above to work. Once the `assumeRole` was configured correctly the issue went away.
