### ISSUE TITLE
S3 method "getBucketNotificationConfiguration" not working properly

### ISSUE THREAD

**Issue by RLThomaz** [aws/aws-sdk-js#2154]
Hello all, I am opening this ticket to report an issue I am having with the S3 method "getBucketNotificationConfiguration" on my Lambda function triggered by an S3 event. The main issue, that might be holding me from solving the real problem - the error that happens inside the method, is that the function is not logging properly.

Important information about the logs:

- The Lambda function usually fails twice before working on the third try.
- The CloudWatch logs seem to be missing the logs from "getBucketNotificationConfiguration" either if there is an error or not.

Before I proceed with the code, here is a brief explanation of what my Lambda node.js function is supposed to do. Notice that this code actually *WORKS* - just not always, and the problem is that I cannot find out why.

> The Lambda function is called when a Put Object event happens on my S3 bucket. Therefore, the Lambda function first logs the event and retrieve the bucket name and the key that triggered the event. By using the bucket name, the Lambda then calls the getBucketNotificationConfiguration method. This is done for retrieving the "Lambda" object (itself) in order to read two predefined tags - an "application-name" and "deploymentgroup-name" - by calling the Lambda method "listTags". After that, the tags, bucket name, and key are used to deploy a new revision to our Deployment Group using CodeDeploy.

Everything up to the Lambda call seems to be working properly. After the function is called, however, it exits returning a generic error.

```json
2018-07-20T09:18:17.929Z	b35db697-8bfd-11e8-981a-b9029c24ccb9
{
    "errorMessage": "Error"
}
```

By logging every step we can notice that this error is returned when Creating Deployment due to the "application-name" being undefined.

```json
START RequestId: b35db697-8bfd-11e8-981a-b9029c24ccb9 Version: $LATEST
2018-07-20T09:17:19.549Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Received event:
2018-07-20T09:17:19.551Z	b35db697-8bfd-11e8-981a-b9029c24ccb9
{
    "Records": [
        {
            "eventVersion": "2.0",
            "eventSource": "aws:s3",
            "awsRegion": "ap-southeast-1",
            "eventTime": "2018-07-20T09:17:18.664Z",
            "eventName": "ObjectCreated:Put",
            "userIdentity": {
                "principalId": "AWS:AROAJKQ62M6QT3AOWW73I:devcloud-PutObjectLambda-1HJ6UES4MY2ZO"
            },
            "requestParameters": {
                "sourceIPAddress": "52.221.199.35"
            },
            "responseElements": {
                "x-amz-request-id": "9519173A6AABDC2C",
                "x-amz-id-2": "6Eo3FpvOXAcUtNKm7S4pMcVkdnDZWScAb0OrVZ2FlrT4F4fP5xi8ZQicsOqQc5JrxDCN6xw1Nbw="
            },
            "s3": {
                "s3SchemaVersion": "1.0",
                "configurationId": "b23cc5b3-1d0a-4ee8-8a3e-0439d80eaf0d",
                "bucket": {
                    "name": "devcloud-s3codedeploybucket-1pxm8khf3hbpz",
                    "ownerIdentity": {
                        "principalId": "AG2HVTS90ENAS"
                    },
                    "arn": "arn:aws:s3:::devcloud-s3codedeploybucket-1pxm8khf3hbpz"
                },
                "object": {
                    "key": "CloudFormationApp.zip",
                    "size": 2662,
                    "eTag": "457a1238081945d20e73f11dfe13b8fe",
                    "sequencer": "005B51A89E9ED11ABB"
                }
            }
        }
    ]
}

2018-07-20T09:17:20.709Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Creating deployment
2018-07-20T09:17:20.770Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	undefined
2018-07-20T09:17:20.771Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	{ MissingRequiredParameter: Missing required key 'applicationName' in params
at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:61:14)
at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:125:42)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:85:9
at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:320:7)
at /var/runtime/node_modules/aws-sdk/lib/config.js:338:9
message: 'Missing required key \'applicationName\' in params',
code: 'MissingRequiredParameter',
time: 2018-07-20T09:17:20.769Z } 'MissingRequiredParameter: Missing required key \'applicationName\' in params\n at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)\n at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:61:14)\n at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)\n at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)\n at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:125:42)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)\n at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:85:9\n at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:320:7)\n at /var/runtime/node_modules/aws-sdk/lib/config.js:338:9'
2018-07-20T09:17:20.828Z	b35db697-8bfd-11e8-981a-b9029c24ccb9
{
    "errorMessage": "Error"
}

END RequestId: b35db697-8bfd-11e8-981a-b9029c24ccb9
REPORT RequestId: b35db697-8bfd-11e8-981a-b9029c24ccb9	Duration: 1290.50 ms	Billed Duration: 1300 ms Memory Size: 128 MB	Max Memory Used: 36 MB	
```

If the "application-name" is undefined it means that the code did not reach the "lambda.listTags" method or this method returned an error. I assume that it is not reaching "lambda.listTags" since I cannot log the "getBucketNotificationConfiguration" method. Even when everything works - wich includes getting the tags from the lambda function and Creating Deployment, there is no log on CloudWatch for "getBucketNotificationConfiguration".

Here is the full log of when the Lambda finishes the job:

```json
START RequestId: b35db697-8bfd-11e8-981a-b9029c24ccb9 Version: $LATEST
2018-07-20T09:20:23.190Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Received event:
2018-07-20T09:20:23.191Z	b35db697-8bfd-11e8-981a-b9029c24ccb9
{
    "Records": [
        {
            "eventVersion": "2.0",
            "eventSource": "aws:s3",
            "awsRegion": "ap-southeast-1",
            "eventTime": "2018-07-20T09:17:18.664Z",
            "eventName": "ObjectCreated:Put",
            "userIdentity": {
                "principalId": "AWS:AROAJKQ62M6QT3AOWW73I:devcloud-PutObjectLambda-1HJ6UES4MY2ZO"
            },
            "requestParameters": {
                "sourceIPAddress": "52.221.199.35"
            },
            "responseElements": {
                "x-amz-request-id": "9519173A6AABDC2C",
                "x-amz-id-2": "6Eo3FpvOXAcUtNKm7S4pMcVkdnDZWScAb0OrVZ2FlrT4F4fP5xi8ZQicsOqQc5JrxDCN6xw1Nbw="
            },
            "s3": {
                "s3SchemaVersion": "1.0",
                "configurationId": "b23cc5b3-1d0a-4ee8-8a3e-0439d80eaf0d",
                "bucket": {
                    "name": "devcloud-s3codedeploybucket-1pxm8khf3hbpz",
                    "ownerIdentity": {
                        "principalId": "AG2HVTS90ENAS"
                    },
                    "arn": "arn:aws:s3:::devcloud-s3codedeploybucket-1pxm8khf3hbpz"
                },
                "object": {
                    "key": "CloudFormationApp.zip",
                    "size": 2662,
                    "eTag": "457a1238081945d20e73f11dfe13b8fe",
                    "sequencer": "005B51A89E9ED11ABB"
                }
            }
        }
    ]
}

2018-07-20T09:20:23.869Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	{ Tags: 
{ 'application-name': 'CloudFormationApp',
'deploymentgroup-name': 'devcloud-DeploymentGroup-1N91XZFV1S1HC' } }
2018-07-20T09:20:23.870Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Logging Application Name
2018-07-20T09:20:23.870Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	CloudFormationApp
2018-07-20T09:20:23.870Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	{ Tags: 
{ 'application-name': 'CloudFormationApp',
'deploymentgroup-name': 'devcloud-DeploymentGroup-1N91XZFV1S1HC' } }
2018-07-20T09:20:23.871Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Logging Application Name
2018-07-20T09:20:23.871Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	CloudFormationApp
2018-07-20T09:20:23.908Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Creating deployment
2018-07-20T09:20:23.970Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	{ TopicConfigurations: [],
QueueConfigurations: [],
LambdaFunctionConfigurations: 
[ { Id: 'b23cc5b3-1d0a-4ee8-8a3e-0439d80eaf0d',
LambdaFunctionArn: 'arn:aws:lambda:ap-southeast-1:449288401443:function:devcloud-DeployRevision-F2GY7GSV2A8P',
Events: [Object] } ] }
2018-07-20T09:20:24.124Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	{ Tags: 
{ 'application-name': 'CloudFormationApp',
'deploymentgroup-name': 'devcloud-DeploymentGroup-1N91XZFV1S1HC' } }
2018-07-20T09:20:24.124Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Logging Application Name
2018-07-20T09:20:24.124Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	CloudFormationApp
2018-07-20T09:20:24.722Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	{ deploymentId: 'd-6SQPTADQT' }
2018-07-20T09:20:24.722Z	b35db697-8bfd-11e8-981a-b9029c24ccb9	Finished executing lambda function
END RequestId: b35db697-8bfd-11e8-981a-b9029c24ccb9
REPORT RequestId: b35db697-8bfd-11e8-981a-b9029c24ccb9	Duration: 1627.27 ms	Billed Duration: 1700 ms Memory Size: 128 MB	Max Memory Used: 38 MB
```

Finally, here is the node.js Lambda function:

```node.js
var aws = require("aws-sdk");
var s3 = new aws.S3({ apiVersion: "2006-03-01" });
var lambda = new aws.Lambda({apiVersion: '2015-03-31'});
var codedeploy = new aws.CodeDeploy();

exports.handler = function(event, context) {
  var artifact_type;
  var bucket;
  var key;
  var applicationName;
  var deploymentGroupName;

  /* runtime functions */
  function getS3ObjectAndCreateDeployment() {
    // Get the s3 object to fetch application-name and deploymentgroup-name metadata.
    s3.headObject({ Bucket: bucket, Key: key }, function(err, data) {
      if (err) {
        console.log(err, err.stack);
        context.done("Error", "Error getting s3 object: " + err);
      } else {
        console.log("Creating deployment");
        createDeployment(data);
      }
    });
  }
  function createDeployment(data) {
    var params = {
      applicationName: applicationName,//data.Metadata["application-name"],
      deploymentGroupName: deploymentGroupName,//data.Metadata["deploymentgroup-name"],
      description: "Lambda invoked codedeploy deployment",
      ignoreApplicationStopFailures: false,
      revision: {
        revisionType: "S3",
        s3Location: { bucket: bucket, bundleType: artifact_type, key: key }
      }
    };
    codedeploy.createDeployment(params, function(err, data) {
      if (err) {
        console.log(err, err.stack);
        context.done("Error", "Error creating deployment: " + err);
      } else {
        console.log(data); // successful response
        console.log("Finished executing lambda function");
        context.done();
      }
    });
  }
  console.log("Received event:");
  console.log(JSON.stringify(event, null, "  "));
  // Get the object from the event
  bucket = event.Records[0].s3.bucket.name;
  key = event.Records[0].s3.object.key;
  var params = {
    Bucket: bucket
  };
  s3.getBucketNotificationConfiguration(params, function(err,data)
  {
    if (err) console.log(err, err.stack);
    else
    {
      console.log(data);
      lambda.listTags({Resource: data.LambdaFunctionConfigurations[0].LambdaFunctionArn}, function(err, data)
      {
        if(err) console.log(err, err.stack);
        else
        {
          console.log(data);
          applicationName = data.Tags["application-name"];
          deploymentGroupName = data.Tags["deploymentgroup-name"];
        }
      });
    }
  });
  var tokens = key.split(".");
  artifact_type = tokens[tokens.length - 1];
  if (artifact_type == "gz") {
    artifact_type = "tgz";
  } else if (["zip", "tar", "tgz"].indexOf(artifact_type) < 0) {
    artifact_type = "tar";
  }
  getS3ObjectAndCreateDeployment();
};
```

Thank you in advance.

**Comment by RLThomaz** [comment]
I'm closing this ticket. The method is asynchronous, so the last bit of code should be inside of the inner callback.
