### ISSUE TITLE
SNS returning Error with Statuscode 404

### ISSUE THREAD

**Issue by kishoredonepudi** [aws/aws-sdk-js#2159]
We are getting statusCode:404 error with SNS getSubscriptionAttributes ,unsubscribe  , getEndpointAttributes ,deleteEndpoint operations . This is happening even when the subscription's and endpoint exists.  Please let us know if you have any insight with this problem.

getSubscriptionAttributes Error: { 404: null
at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:52:29)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
message: null,
code: 404,
time: 2018-07-25T14:17:11.502Z,
requestId: 'IECINV6O85ELBSCGEVCQV0GLSNVV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 404,
retryable: false,
retryDelay: 68.41146370928142 }

getEndpointAttributes Error : { 404: null
at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:52:29)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
message: null,
code: 404,
time: 2018-07-25T14:17:11.522Z,
requestId: '1O0PKU17QO172O9GMQLK9BNL9RVV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 404,
retryable: false,
retryDelay: 3.5327793025121013 }

**Comment by chrisradek** [comment]
@kishoredonepudi 
It looks like you are reaching the services since you're getting a response. Can you share how you're making your SNS calls, and how you've configured your SNS client?

**Comment by kishoredonepudi** [comment]
@chrisradek 
I am using the following way to call unsubscribe a subscription.
const aws = require('aws-sdk');
aws.config.apiVersions = {
        sns: '2010-03-31'
    };
const sns =new aws.SNS();
var unsubscribe = async (subscriptionArn) => {
        if (typeof subscriptionArn !== 'undefined' && subscriptionArn) {
            var params = {
                SubscriptionArn: subscriptionArn  /* required */
            };
            return await sns.unsubscribe(params).promise().then((res) => {
                console.log("response for unsubscribe:", res);
                return res;
            }).catch((error) => {
                console.log("Error unsubscribing subscription:", error, params);
                return Promise.reject({
                    errorType: "ERROR_UNSUBSCRIBING_SUBSCRIPTION",
                    error: error,
                    input: subscriptionArn,
                    params: params
                });
            });
        } else {
            return Promise.reject({ error: "Require subscriptionArn" });
        }
    };

**Comment by chrisradek** [comment]
@kishoredonepudi 
Do you see your subscriptionArn when you call `sns.listSubscriptions`, or do you also get an error via that request?

The 404 errors indicate that the resources you're trying to act on don't exist. How are you validating that the resources exist?

**Comment by kishoredonepudi** [comment]
@chrisradek 
I didn't used listSubscriptions since there are more than 1000 subscriptions. After looking at the error I logged into console and verified it is there and also verified with aws cli command.

**Comment by chrisradek** [comment]
@kishoredonepudi 
Are you able to unsubscribe to the same arn that fails with the JS SDK from by using the CLI? If so, then we can take a look at the raw http request/response from both tools to see where the issue is. Otherwise you may need to reach out on the [AWS SNS forums](https://forums.aws.amazon.com/forum.jspa?forumID=72)

**Comment by kishoredonepudi** [comment]
@chrisradek 
Yes I was able to unsubscribe with same code by requesting again . The problem I have is why it is not unsubscribing on first request every time. This is not happening for all requests.

**Comment by srchase** [comment]
@kishoredonepudi 

Were you able to get this issue resolved?  Or are you still seeing the same behavior?

Did you engage the SNS Service Team on their [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=72)?
