### ISSUE TITLE
Trigger `adminresetuserpassword` in aws-sdk 

### ISSUE THREAD

**Issue by YaswanthC** [aws/aws-sdk-js#2185]
Hi,

I am triggering 'adminResetuserpassword` API in aws-sdk . The below is my code

    var AWS = require('aws-sdk');
    var cognito = new AWS.CognitoIdentityServiceProvider({apiVersion: '2016-04-18'});
    var myCredentials = new AWS.CognitoIdentityCredentials({IdentityPoolId:config.cognito.IDENTITY_POOL_ID});
          var myConfig = new AWS.Config({
            credentials: myCredentials, region: 'ap-south-1'
          });
      
          var params = {
            UserPoolId: config.cognito.USER_POOL_ID, /* required */
            Username: this.state.email /* required */
          };
          cognito.adminResetUserPassword(params, function(err, data) {
            if (err) console.log(err, err.stack); // an error occurred
            else     console.log(data)         // successful response
          });

Eventhough i am passing `region` i am still getting error like this 

    Error: Missing region in config
        at Request.VALIDATE_REGION (event_listeners.js:91)
        at Request.callListeners (sequential_executor.js:105)
        at callNextListener (sequential_executor.js:95)
        at event_listeners.js:85
        at finish (config.js:320)
        at Config.getCredentials (config.js:365)
        at Request.VALIDATE_CREDENTIALS (event_listeners.js:80)
        at Request.callListeners (sequential_executor.js:101)
        at Request.emit (sequential_executor.js:77)
        at Request.emit (request.js:683)
        at Request.transition (request.js:22)
        at AcceptorStateMachine.runTo (state_machine.js:14)
        at Request.runTo (request.js:403)
        at Request.send (request.js:367)
        at features.constructor.makeRequest (service.js:193)
        at features.constructor.svc.(:3000/anonymous function) [as adminResetUserPassword] (http://localhost:3000/static/js/bundle.js:45704:23)
        at Login._callee$ (Login.js:63)
        at tryCatch (runtime.js:62)
        at Generator.invoke [as _invoke] (runtime.js:296)
        at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:135430:21)
        at step (Login.css?5833:26)
        at Login.css?5833:26 "ConfigError: Missing region in config
        at Request.VALIDATE_REGION (http://localhost:3000/static/js/bundle.js:39823:45)
        at Request.callListeners (http://localhost:3000/static/js/bundle.js:45064:20)
        at callNextListener (http://localhost:3000/static/js/bundle.js:45054:12)
        at http://localhost:3000/static/js/bundle.js:39817:9
        at finish (http://localhost:3000/static/js/bundle.js:36589:7)
        at Config.getCredentials (http://localhost:3000/static/js/bundle.js:36634:7)
        at Request.VALIDATE_CREDENTIALS (http://localhost:3000/static/js/bundle.js:39812:26)
        at Request.callListeners (http://localhost:3000/static/js/bundle.js:45060:18)
        at Request.emit (http://localhost:3000/static/js/bundle.js:45036:10)
        at Request.emit (http://localhost:3000/static/js/bundle.js:43670:14)
        at Request.transition (http://localhost:3000/static/js/bundle.js:43009:10)
        at AcceptorStateMachine.runTo (http://localhost:3000/static/js/bundle.js:48555:12)
        at Request.runTo (http://localhost:3000/static/js/bundle.js:43390:15)
        at Request.send (http://localhost:3000/static/js/bundle.js:43354:10)
        at features.constructor.makeRequest (http://localhost:3000/static/js/bundle.js:45398:27)
        at features.constructor.svc.(anonymous function) [as adminResetUserPassword] (http://localhost:3000/static/js/bundle.js:45704:23)
        at Login._callee$ (http://localhost:3000/static/js/bundle.js:145573:27)
        at tryCatch (http://localhost:3000/static/js/bundle.js:135378:40)
        at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:135612:22)
        at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:135430:21)
        at step (http://localhost:3000/static/js/bundle.js:145496:191)
        at http://localhost:3000/static/js/bundle.js:145496:361"

I can't figure it out why i am getting this error. [Reference][1]
Does this API exists in `amplify` ?

Any help is appreciated 

  [1]: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminResetUserPassword-property

**Comment by srchase** [comment]
@YaswanthC,

In your code, there are two configs being referenced.  You're setting the region on the AWS.config below, but the config used to initialize the CognitoIdentityCredentials is the one missing the region.

If you have questions on authentication with Amplify, you can start with the [Authentication Guide](https://aws-amplify.github.io/amplify-js/media/authentication_guide)
