### ISSUE TITLE
Local dynamodb throws InvalidHeader: Header host contains invalid value

### ISSUE THREAD

**Issue by bodyslam** [aws/aws-sdk-js#2186]
Hey all,

I've installed Dynamodb locally as per instructions [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html#DynamoDBLocal.DownloadingAndRunning)

I'm trying to query dynamodb locally using the following typescript
```
export async function getCarts(): Promise<AWS.DynamoDB.GetItemOutput> {
  return new Promise((resolve, reject) => {
    AWS.config.update( {
      Host: 'localhost',
      accessKey: 'AKID',
      endpoint: 'http: //localhost:8000',
      host: 'localhost',
      region: 'REGION',
      secretAccessKey: 'SECRET'
    });
    const db = new AWS.DynamoDB.DocumentClient();
    const scanQuery: any = {
      Limit: 10,
      TableName: TABLE_NAME
    };

    db.scan(scanQuery, (
      err: AWS.AWSError,
      data: AWS.DynamoDB.GetItemOutput
    ) => {
      if (err) return reject(err);
      return resolve(data);
    });
  });
}
```

But I'm getting the following:
```
{ InvalidHeader: Header host contains invalid value
    at V4.<anonymous> (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/signers/v4.js:144:32)
    at V4.arrayEach (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/util.js:494:32)
    at V4.canonicalHeaders (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/signers/v4.js:139:24)
    at V4.canonicalString (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/signers/v4.js:123:21)
    at V4.stringToSign (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/signers/v4.js:112:41)
    at V4.signature (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/signers/v4.js:104:50)
    at V4.authorization (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/signers/v4.js:92:36)
    at V4.addAuthorization (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/signers/v4.js:34:12)
    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/event_listeners.js:223:18
    at finish (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/aws-sdk/lib/config.js:320:7)
  message: 'Header host contains invalid value',
  code: 'InvalidHeader',
  time: 2018-08-09T15:16:32.505Z,
  retryDelay: 8.409149195123334 }
```

I was also able to dump the headers
```
 [ [ 'Content-Length', 40 ],
  [ 'Content-Type', 'application/x-amz-json-1.0' ],
  [ 'Host', null ],
  [ 'User-Agent',
    'aws-sdk-nodejs/2.289.0 darwin/v9.11.2 callback' ],
  [ 'X-Amz-Content-Sha256',
    'bea7aecd65f4badeb304bc2a1886a7553bee74b9171d352ba01243a4f310a61d' ],
  [ 'X-Amz-Date', '20180809T151632Z' ],
  [ 'X-Amz-Target', 'DynamoDB_20120810.Scan' ] ]
```

I've added 'host' and 'Host' entries into the config but it doesn't appear to get picked up.  
Help?

**Comment by bodyslam** [comment]
Additional information:
```
  "name": "aws-sdk",
  "description": "AWS SDK for JavaScript",
  "version": "2.289.0",
```

My local
```
/node_modules/aws-sdk$ npm version
{ 'aws-sdk': '2.289.0',
  npm: '5.6.0',
  ares: '1.13.0',
  cldr: '33.0',
  http_parser: '2.8.0',
  icu: '61.1',
  modules: '59',
  napi: '3',
  nghttp2: '1.32.0',
  node: '9.11.2',
  openssl: '1.0.2o',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.19.2',
  v8: '6.2.414.46-node.23',
  zlib: '1.2.11' }
```

**Comment by srchase** [comment]
Hello @bodyslam,

The endpoint has to be set when initializing the DocumentClient, not on the global config:

```
const db = new AWS.DynamoDB.DocumentClient({
  accessKeyId: 'AKID',
  endpoint: 'http: //localhost:8000',
  region: 'REGION',
  secretAccessKey: 'SECRET'
});
```

This will set the Host header appropriately in the request.

See this [comment](https://github.com/aws/aws-sdk-js/issues/1635#issuecomment-316472907) for an explanation.

If you're not using the global config elsewhere, you can set the credentials on the client. Note, it's accessKeyId instead of accessKey.
