### ISSUE TITLE
Receive 403 Access Denied

### ISSUE THREAD

**Issue by Ferrari** [aws/aws-sdk-js#2213]
Start to receive 403 error after upgrade to v2.291.0 (also tried the latest version v2.297.0, same error message as following). Downgrade to v2.276.1 (Just pick the version before the previous S3 changed) and everything works well.

```
{ AccessDenied: Access Denied
    at Request.extractError (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/sylee/api-server/pg-api-staging/node_modules/aws-sdk/lib/event_listeners.js:294:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2018-08-21T15:59:56.075Z,
  requestId: 'FFA6265F07A7EA8C',
  extendedRequestId: 'xf1u48bYo7bLSvxYHLGEYUaRNjFE2YM+IUINXngCMvAmLsoTS9V1a1x7g6krQP0wcQTcIjNV4yE=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 42.32940462418664 }
```

**Comment by AllanFly120** [comment]
Hey @Ferrari,
Can you share whats your S3 key and bucket like? Also, are you calling a cross-region S3 bucket? The most recent S3 servcie api change is 2.273.1 but we fixed an S3 retry bug in 2.297.0, otherwise there was no S3-specific code change within the version range. Can you specify how you are using the SDK, more detailed information will help us locate the potential issue.

**Comment by Ferrari** [comment]
Sorry, there has some private information some I could not list the setting at here, but our key & bucket just a simple string and did not include any special characters inside. And all we use is just a simple upload like following. (Credential assign from env)

The issue happened because we use `^` on package.json so `aws-sdk` upgrade automatically. We test our credential with AWS cli and it work fine. So we guess might be package issue so we downgrade the package version and problem solved.

```
const s3 = new AWS.S3()

s3
  .upload({
    Body: FILE_BUFFER,
    Bucket: BUCKET_NAME,
    Key: KEY,
    ACL: 'public-read'
  })
  .send(callback)
```

**Comment by srchase** [comment]
@Ferrari 

Does the latest version of the SDK give you the same error now?

**Comment by belmer** [comment]
Hi @srchase,

I'm having the same exact issue as the above mentioned. The version I've used is "2.233.1". Downgrading to "v2.276.1" does not help. Im still trying to figure out why.

**Comment by AmrAlmagic** [comment]
Are you solve this issue?
