### ISSUE TITLE
Could not find API configuration s3-2006-03-01   

### ISSUE THREAD

**Issue by mvidalis** [aws/aws-sdk-js#2227]
Tried to run my node server and got the following error:

Error: Could not find API configuration s3-2006-03-01
    at Collection.memoize (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\model\collection.js:4:26)
    at new Collection (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\model\collection.js:15:15)
    at new Api (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\model\api.js:45:28)
    at setApi (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\service.js:566:29)
    at Function.defineServiceApi (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\service.js:575:11)
    at features.constructor.getLatestServiceClass (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\service.js:91:19)
    at features.constructor.loadServiceClass (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\service.js:81:19)
    at features.constructor.Service [as constructor] (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\service.js:27:29)
    at new features.constructor (C:\tecbotDev\sitecircles\node_modules\aws-sdk\lib\util.js:602:24)
    at Object.<anonymous> (C:\tecbotDev\sitecircles\routes\projects.js:10:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

Please could we fix this ASAP or point to a fix on my end? i don't think it's an issue on my side however. 
Thanks!

**Comment by chrisradek** [comment]
@mvidalis 
Can you share how you're instantiating your S3 client?

**Comment by mvidalis** [comment]
@chrisradek 

in one of my routes files, I instantiate the s3 object as follows:

var s3 = new aws.S3();

**Comment by mvidalis** [comment]
I've been using the sdk for just over a month now. I just ran an npm install to install all my node packages and now I'm seeing this error.

**Comment by chrisradek** [comment]
@mvidalis 
Just starting a new project with the following code and the latest version of the SDK, I'm not seeing that issue:
```javascript
const AWS = require('aws-sdk');

var s3 = new AWS.S3();

s3.listBuckets(console.log);
```

Can you share which version of the SDK you're using now, and which version you were using before?
Just to confirm, are you running this in node.js?

**Comment by mvidalis** [comment]
If i run npm -v aws-sdk, it shows I'm running v5.6.0. It is a node project.
I'm not entirely sure of which version I was running previously, however I installed it around the beginning of July this year.
Do you think it could be an error on my side?

**Comment by mvidalis** [comment]
Sorry, my mistake!

It shows I am running v2.304.0

**Comment by chrisradek** [comment]
@mvidalis 
Does your package.json show the previous version? You'd probably see something like `"aws-sdk": "^2.#.#"`, and you were likely using whatever version that field shows.

Can you try just running my above example and see if you get the same error?

**Comment by mvidalis** [comment]
@chrisradek 

My package.json shows v2.304.0

I ran that code in a new project and it prints out the buckets in my s3 repository.

**Comment by mvidalis** [comment]
Should I uninstall the package and reinstall it?

**Comment by srchase** [comment]
@mvidalis 

Go ahead and try uninstalling and reinstalling the package.  Let us know if that makes a difference.
