### ISSUE TITLE
Issue with uploading png's larger than 1.1mb

### ISSUE THREAD

**Issue by empty-Seth** [aws/aws-sdk-js#2237]
Hello.
I faced up with problem while trying to upload images to s3. Storage throws error 500 'UnknownError' on png's larger than 1.1mb or jpg's larger than 1.7mb.
Tried to call method 'upload' with async/await and with callback style, tried call 'putObject' but always the same error.
Here is code example:
```javascript
const S3 = require('aws-sdk/clients/s3');

const s3 = new S3({
    accessKeyId: <access key>,
    secretAccessKey: <secret key>,
    endpoint: <endpoint>,
    s3ForcePathStyle: true,
    signatureVersion: 'v4'
});
const uploadToBucket = ({ Key, Body, ContentType }) => {
    const params = {
        Key,
        Body,
        Bucket: <bucket>,
        ACL: 'public-read',
        ContentType
    };

    const manager = s3.upload(params);
    return manager.promise();
};

// calling inside some async func
const params = {
       Key: <some name>,
       Body: <buffer or stream>,
       ContentType: 'image/png'
};
const s3Response = await uploadToBucket(params);
```
Here is response:
```
{ UnknownError: null
image_uploader_1   |     at Request.extractError (/srv/http/node_modules/aws-sdk/lib/services/s3.js:582:35)
image_uploader_1   |     at Request.callListeners (/srv/http/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
image_uploader_1   |     at Request.emit (/srv/http/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
image_uploader_1   |     at Request.emit (/srv/http/node_modules/aws-sdk/lib/request.js:683:14)
image_uploader_1   |     at Request.transition (/srv/http/node_modules/aws-sdk/lib/request.js:22:10)
image_uploader_1   |     at AcceptorStateMachine.runTo (/srv/http/node_modules/aws-sdk/lib/state_machine.js:14:12)
image_uploader_1   |     at /srv/http/node_modules/aws-sdk/lib/state_machine.js:26:10
image_uploader_1   |     at Request.<anonymous> (/srv/http/node_modules/aws-sdk/lib/request.js:38:9)
image_uploader_1   |     at Request.<anonymous> (/srv/http/node_modules/aws-sdk/lib/request.js:685:12)
image_uploader_1   |     at Request.callListeners (/srv/http/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
image_uploader_1   |     at Request.emit (/srv/http/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
image_uploader_1   |     at Request.emit (/srv/http/node_modules/aws-sdk/lib/request.js:683:14)
image_uploader_1   |     at Request.transition (/srv/http/node_modules/aws-sdk/lib/request.js:22:10)
image_uploader_1   |     at AcceptorStateMachine.runTo (/srv/http/node_modules/aws-sdk/lib/state_machine.js:14:12)
image_uploader_1   |     at /srv/http/node_modules/aws-sdk/lib/state_machine.js:26:10
image_uploader_1   |     at Request.<anonymous> (/srv/http/node_modules/aws-sdk/lib/request.js:38:9)
image_uploader_1   |     at Request.<anonymous> (/srv/http/node_modules/aws-sdk/lib/request.js:685:12)
image_uploader_1   |     at Request.callListeners (/srv/http/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
image_uploader_1   |     at callNextListener (/srv/http/node_modules/aws-sdk/lib/sequential_executor.js:99:12)
image_uploader_1   |     at IncomingMessage.onEnd (/srv/http/node_modules/aws-sdk/lib/event_listeners.js:294:13)
image_uploader_1   |     at IncomingMessage.emit (events.js:187:15)
image_uploader_1   |     at IncomingMessage.EventEmitter.emit (domain.js:442:20)
image_uploader_1   |   message: null,
image_uploader_1   |   code: 'UnknownError',
image_uploader_1   |   region: null,
image_uploader_1   |   time: 2018-09-06T07:36:13.207Z,
image_uploader_1   |   requestId: 'tx00000000000000002d639-005b90d8e3-cbaae46-default',
image_uploader_1   |   extendedRequestId: undefined,
image_uploader_1   |   cfId: undefined,
image_uploader_1   |   statusCode: 500,
image_uploader_1   |   retryable: true }
```
Everything works fine with images of smaller size.

**Comment by srchase** [comment]
@empty-Seth 

I'm not getting this error when executing this code with node using the latest version of the SDK.

Which version of the SDK are you using?

Are you able to successfully upload those same larger png's and jpg's using the AWS CLI?

**Comment by empty-Seth** [comment]
@srchase 
aws-sdk: 2.309.0
node: 10.9.0

I can successfully upload any file with s3cmd.

**Comment by srchase** [comment]
@empty-Seth 

How about with the AWS CLI?

[https://aws.amazon.com/cli/](https://aws.amazon.com/cli/)

**Comment by empty-Seth** [comment]
@srchase 
Everything works with AWS CLI. So Im also trying to find error in other parts of application.

**Comment by srchase** [comment]
@empty-Seth 

Let us know if you're able uncover any additional details that would help to get a reliable reproduction of the issue.
