### ISSUE TITLE
Sagemaker - Invalid image format exception

### ISSUE THREAD

**Issue by pabloDon** [aws/aws-sdk-js#2248]
Hi! I've created through Amazon Sagemaker a image classification engine with endpoint following [this](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/imageclassification_caltech/Image-classification-fulltraining.ipynb) example. I've tested it through the same notebook and it works perfect.

Now I want to create an API server with Express + AWS-SDK to make requests publicly. My code is as follows:

```
export function sendRequestToSageMaker(base64image) {
  const params = {
    Body: new Buffer(base64image, 'base64') , /* Strings will be Base-64 encoded on your behalf */ /* required */
    EndpointName: 'DEMO-imageclassification-ep--XXXX', /* required */
    Accept: 'application/json',
    ContentType: 'application/x-image'
  };
  sagemakerruntime.invokeEndpoint(params, function(err, data) {
    if (err) 
      console.error(err, err.stack); // an error occurred
    else     
      console.log(data);           // successful response
   });
   return null;
}
```
where `base64image` will be a base64 image sent into the body request.

I execute my  express server and everything goes fine. After that, with Postman, I send such request and code crash with the following trace:

```
Error during recognition: { InvalidImageFormatException: Request has Invalid image format
  at Request.extractError (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/protocol/json.js:48:27)
  at Request.callListeners (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
  at Request.emit (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
  at Request.emit (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/request.js:683:14)
  at Request.transition (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/request.js:22:10)
  at AcceptorStateMachine.runTo (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/request.js:38:9)
  at Request.<anonymous> (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/request.js:685:12)
  at Request.callListeners (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
  at Request.emit (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
  at Request.emit (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/request.js:683:14)
  at Request.transition (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/request.js:22:10)
  at AcceptorStateMachine.runTo (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/state_machine.js:14:12)
  at /Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/state_machine.js:26:10
  at Request.<anonymous> (/Users/pdonaire/Documents/workspaceNode/trsps-controller/node_modules/aws-sdk/lib/request.js:38:9)

message: 'Request has Invalid image format',
code: 'InvalidImageFormatException',
time: 2018-09-10T04:42:07.530Z,
requestId: 'de3a04ff-b4b3-11e8-9bd8-8b88f803570c',
statusCode: 400,
retryable: false,
retryDelay: 55.860720412209794 }
```

To test it, I've used a jpeg image encoded with [this](https://www.base64-image.de/) website.

My dependencies:

```
"dependencies": {
    "aws-sdk": "^2.311.0",
    "babel-core": "^6.25.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "body-parser": "^1.16.1",
    "cookie-parser": "^1.4.3",
    "debug": "^3.0.0",
    "express": "^4.15.4",
    "mongoose": "^5.2.13",
    "morgan": "^1.8.2",
    "serve-favicon": "^2.4.3",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "chai": "^4.1.1",
    "chai-http": "^3.0.0",
    "eslint": "^4.5.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-mocha": "^4.11.0",
    "eslint-plugin-react": "^7.2.1",
    "express-swagger-generator": "^1.1.9"
  }
```

**Comment by srchase** [comment]
@pabloDon 

Are you able to get this working with a local file, rather than one that's getting handled through Express?

You could also try testing with Rekognition, as that also requires a base64 image.

```const aws = require('aws-sdk');
const rekognition = new aws.Rekognition({region: 'us-west-2'});
const fs = require('fs');

const bitmap = fs.readFileSync('localFile.jpg');
const buffer = new Buffer.from(bitmap, 'base64')

const params = {
  Image: {
    Bytes: buffer
  }
}

rekognition.detectText(params, function(err, data) {
  console.log(err,data)
})
```

If the image is not encoded correctly, Rekognition will raise the same InvalidImageFormatException.

**Comment by pabloDon** [comment]
It works... looks like base64 is encoded wrongly, who knows. Thanks!
