### ISSUE TITLE
aws sdk not working with Node10

### ISSUE THREAD

**Issue by sriramHaven** [aws/aws-sdk-js#2252]
While running unit test with sinon framework, in node 10 ( precisely node v10.10.0), there is a 
maximum call stack exceeded error. logs below. While commenting the part of 

> `require('domain')` in node_loader.js

 , this goes away. Could be related to domain getting deprecated in Node 10, this needs a fix asap.  ( mentioned here: https://nodejs.org/api/domain.html )

```
/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:239
                this._zoneDelegate.handleError(this, err);
                                   ^
RangeError: Maximum call stack size exceeded
    at Zone.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:239:36)
    at Zone.scheduleEventTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:258:25)
    at process.prependListener (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1744:33)
    at process.on (domain.js:152:13)
    at ZoneDelegate.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:496:34)
    at process.ZoneTask.invoke (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:485:48)
    at process.emit (events.js:187:15)
    at processEmit (/builds/hit/haven/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process.emit (/builds/hit/haven/node_modules/source-map-support/source-map-support.js:453:21)
    at process.emit (/builds/hit/haven/node_modules/ts-mocha/node_modules/source-map-support/source-map-support.js:439:21)
    at _addListener (events.js:211:14)
    at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
    at ZoneTask.customSchedulePrepend [as scheduleFn] (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1622:47)
    at ZoneDelegate.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:407:26)
    at Zone.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:232:43)
    at Zone.scheduleEventTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:258:25)
    at process.prependListener (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1744:33)
    at process.on (domain.js:152:13)
    at ZoneDelegate.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:496:34)
    at process.ZoneTask.invoke (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:485:48)
    at process.emit (events.js:187:15)
    at processEmit (/builds/hit/haven/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process.emit (/builds/hit/haven/node_modules/source-map-support/source-map-support.js:453:21)
    at process.emit (/builds/hit/haven/node_modules/ts-mocha/node_modules/source-map-support/source-map-support.js:439:21)
    at _addListener (events.js:211:14)
    at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
    at ZoneTask.customSchedulePrepend [as scheduleFn] (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1622:47)
    at ZoneDelegate.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:407:26)
    at Zone.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:232:43)
    at Zone.scheduleEventTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:258:25)
    at process.prependListener (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1744:33)
    at process.on (domain.js:152:13)
    at ZoneDelegate.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:496:34)
    at process.ZoneTask.invoke (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:485:48)
    at process.emit (events.js:187:15)
    at processEmit (/builds/hit/haven/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process.emit (/builds/hit/haven/node_modules/source-map-support/source-map-support.js:453:21)
    at process.emit (/builds/hit/haven/node_modules/ts-mocha/node_modules/source-map-support/source-map-support.js:439:21)
    at _addListener (events.js:211:14)
    at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
    at ZoneTask.customSchedulePrepend [as scheduleFn] (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1622:47)
    at ZoneDelegate.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:407:26)
    at Zone.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:232:43)
    at Zone.scheduleEventTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:258:25)
    at process.prependListener (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1744:33)
    at process.on (domain.js:152:13)
    at ZoneDelegate.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:496:34)
    at process.ZoneTask.invoke (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:485:48)
    at process.emit (events.js:187:15)
    at processEmit (/builds/hit/haven/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process.emit (/builds/hit/haven/node_modules/source-map-support/source-map-support.js:453:21)
    at process.emit (/builds/hit/haven/node_modules/ts-mocha/node_modules/source-map-support/source-map-support.js:439:21)
    at _addListener (events.js:211:14)
    at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
    at ZoneTask.customSchedulePrepend [as scheduleFn] (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1622:47)
    at ZoneDelegate.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:407:26)
    at Zone.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:232:43)
    at Zone.scheduleEventTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:258:25)
    at process.prependListener (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1744:33)
    at process.on (domain.js:152:13)
    at ZoneDelegate.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:496:34)
    at process.ZoneTask.invoke (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:485:48)
    at process.emit (events.js:187:15)
    at processEmit (/builds/hit/haven/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process.emit (/builds/hit/haven/node_modules/source-map-support/source-map-support.js:453:21)
    at process.emit (/builds/hit/haven/node_modules/ts-mocha/node_modules/source-map-support/source-map-support.js:439:21)
    at _addListener (events.js:211:14)
    at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
    at ZoneTask.customSchedulePrepend [as scheduleFn] (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1622:47)
    at ZoneDelegate.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:407:26)
    at Zone.scheduleTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:232:43)
    at Zone.scheduleEventTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:258:25)
    at process.prependListener (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:1744:33)
    at process.on (domain.js:152:13)
    at ZoneDelegate.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:496:34)
    at process.ZoneTask.invoke (/builds/hit/haven/node_modules/zone.js/dist/zone-node.js:485:48)
    at process.emit (events.js:187:15)
    at processEmit (/builds/hit/haven/node_modules/nyc/node_modules/signal-exit/index.js:155:32)
    at process.emit (/builds/hit/haven/node_modules/source-map-support/source-map-support.js:453:21)
    at process.emit (/builds/hit/haven/node_modules/ts-mocha/node_modules/source-map-support/source-map-support.js:439:21)
    at _addListener (events.js:211:14) 
```

**Comment by srchase** [comment]
@sriramHaven 

Can you provide us with a code snippet to reproduce this issue?  Your package.json file would also be helpful.

**Comment by sriramHaven** [comment]
@srchase  the command that I have run is for mocha unit test. It will be `npm run coverage:ci`

```
"coverage:ci": "nyc --nycrc-path ./.nycrc-ci npm run test",
    "test": "mocha --require source-map-support/register ./dist-server/test/unit/**/*.js --recursive",
```
is there a particular section of package.json , you would like to see ?

**Comment by sriramHaven** [comment]
@srchase this error comes out when we include `aws-sdk` in our .ts files, which is imported when the unit test runs.

**Comment by sriramHaven** [comment]
@srchase its also worth to note that , this works totally fine with Node 8.11.4

**Comment by chrisradek** [comment]
@sriramHaven 
Can you provide a code sample that reproduces this issue as well?

We currently include testing domains in node 10 in our travis builds and haven't seen this issue. While domains is deprecated, it has not yet been replaced. We can't remove the use of domains since some users use them today and that would require a breaking change.

The stack trace you provided points at zone.js as possibly being a culprit, but an code sample would go a long way in helping us dig into what the root cause is.

**Comment by sriramHaven** [comment]
@chrisradek These are the following steps i did

Add the following in one of the controllers that will be imported **while running the mocha tests.** 

These are from .ts format which gets transpiled to .js before running tests.. i believe it should happen if you do it in .js

```
import * as AWS from "aws-sdk";
```

**in the constructor or a init() of controller.ts** 
```
let a = new AWS.S3();
        console.log(a); 
```

the command I have run is

```
npm run tsc && npm run test
```

**Definition from package.json for them**
```
"tsc" : tsc
"test": "mocha --require source-map-support/register ./dist-server/test/unit/**/*.js --recursive",
```
Versions of mocha and source-map-support

 ```
   "mocha": "5.2.0",
   "source-map-support": "0.5.3",
```

**Comment by srchase** [comment]
@sriramHaven 

I put together a quick test using the same versions of node, mocha and source-map-support and didn't encounter any errors when importing the latest aws-sdk.  I ran mocha against transpiled JS as well as against typescript directly (using ts-node).

Did you try removing zone.js from the equation to see if that changes anything?

**Comment by srchase** [comment]
Closing for inactivity.
