### ISSUE TITLE
Cannot find module 'jmespath' when starting Express server

### ISSUE THREAD

**Issue by armorgreg** [aws/aws-sdk-js#2255]
I am using Express, Node 8.1.1 and `aws-sdk` and after running an `npm install` I'm getting this error `Cannot find module 'jmespath'` along with:

```
Error: Cannot find module 'jmespath'
[0]     at Function.Module._resolveFilename (module.js:485:15)
[0]     at Function.Module._load (module.js:437:25)
[0]     at Module.require (module.js:513:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (/Users/armorgreg/gs/tests/myApp/v1/myApp/node_modules/aws-sdk/lib/request.js:5:16)
[0]     at Module._compile (module.js:569:30)
[0]     at Object.Module._extensions..js (module.js:580:10)
[0]     at Module.load (module.js:503:32)
[0]     at tryModuleLoad (module.js:466:12)
[0]     at Function.Module._load (module.js:458:3)
[0]     at Module.require (module.js:513:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (/Users/armorgreg/gs/tests/myApp/v1/myApp/node_modules/aws-sdk/lib/core.js:78:1)
[0]     at Module._compile (module.js:569:30)
[0]     at Object.Module._extensions..js (module.js:580:10)
[0]     at Module.load (module.js:503:32)
```

I added `aws-sdk` via `npm install --save aws-sdk` as well as ran `npm install` to try to resolve it. Could this be a node issue?

**Comment by srchase** [comment]
@armorgreg 

Which version of the aws-sdk are you using?

Can you provide your package.json file?

**Comment by armorgreg** [comment]
@srchase I did another git clone of my repo and it seems to be working now. Not sure what happened there. Thanks for the response.

**Comment by srchase** [comment]
Glad to hear it's working!

**Comment by rajeshbala01** [comment]
Error: Cannot find module 'jmespath'

Error: Cannot find module 'jmespath'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Program Files\Git\aws-sdk-js-master\lib\request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

I am still not able to run the command which build aws-sdk.js file
