### ISSUE TITLE
CloudWatch.putMetricData gives error "Unexpected key 'Values' found in params..."

### ISSUE THREAD

**Issue by jhohlfeld-otto** [aws/aws-sdk-js#2273]
Hi everyone,

I've got an error when using cloudwatch to put some metric data. I am trying to put this data bundle:

```javascript
const params = {
    "MetricData": [
        {
            "MetricName": "metric-name",
            "Dimensions": [
                {
                    "Name": "FunctionName",
                    "Value": "lambda-function-name"
                }
            ],
            "Timestamp": "2018-09-24T08:31:16.883Z",
            "Unit": "Microseconds",
            "Values": [
                1037.889061
            ],
            "Counts": [
                1
            ]
        }
    ],
    "Namespace": "AWS/Lambda"
};

cloudwatch.putMetricData(params, (err, data) => {
/** ... **/
});
```

As I understand the docs (https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-data.html resp. https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatch.html#putMetricData-property), there should be no problem in publishing multiple (up tp 150) data points at once.

However, the SDK raises this error:

```
MultipleValidationErrors: There were 2 validation errors:
* UnexpectedParameter: Unexpected key 'Values' found in params.MetricData[0]
* UnexpectedParameter: Unexpected key 'Counts' found in params.MetricData[0]
at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:40:28)
at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:125:42)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
at callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:99:12)
at /var/task/node_modules/aws-sdk/lib/event_listeners.js:85:9
at finish (/var/task/node_modules/aws-sdk/lib/config.js:322:7)
at /var/task/node_modules/aws-sdk/lib/config.js:340:9
at EnvironmentCredentials.get (/var/task/node_modules/aws-sdk/lib/credentials.js:126:7)
at getAsyncCredentials (/var/task/node_modules/aws-sdk/lib/config.js:334:24)
at Config.getCredentials (/var/task/node_modules/aws-sdk/lib/config.js:354:9)
```

Am I missing something?

**Comment by srchase** [comment]
@jhohlfeld-otto 

I was able to execute your code using the latest version of the SDK and did not encounter that error.

What version of the SDK are you using?

**Comment by jhohlfeld-otto** [comment]
```bash
% grep version node_modules/aws-sdk/package.json 
  "version": "2.307.0"
```

I was using 2.307.0. I'll try aws-sdk@2.321.0. Sorry, I thought I was using the most recent version.

**Comment by jhohlfeld-otto** [comment]
Thanks a lot, bumping the version solved it 🙄🤦‍♂️😅

**Comment by tqhoughton** [comment]
I'm getting this error with AWS SDK version of 2.435
