### ISSUE TITLE
createWorkerBlock erroneously requires reason as parameter

### ISSUE THREAD

**Issue by mike-feldmeier** [aws/aws-sdk-js#2345]
For the current version of the npm-sourced library: "aws-sdk": "^2.349.0" on Node 8.11.3 / Windows...

The API documentation for createWorkerBlock at https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateWorkerBlockOperation.html specifies that the "Reason" parameter is not required, however the library clearly requires and validates that parameter.  

This is low-priority for me, since my use case would allow me to simply hard-code a default value, but I am interested in what the correct behavior is since the documentation and implementation are at odds with one another.

When making the call as such:

`mturk.createWorkerBlock({ WorkerId: id }).promise()`

the following error occurs:

`{ MissingRequiredParameter: Missing required key 'Reason' in params
    at ParamValidator.fail (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\param_validator.js:61:14)
    at ParamValidator.validateMember (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\param_validator.js:88:21)
    at ParamValidator.validate (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\event_listeners.js:125:42)
    at Request.callListeners (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at callNextListener (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\event_listeners.js:85:9
    at finish (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\config.js:322:7)
    at C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\config.js:340:9
  message: 'Missing required key \'Reason\' in params',
  code: 'MissingRequiredParameter',
  time: 2018-11-08T20:40:42.772Z }`

As an attempted workaround, supplying a blank "Reason" as such:

`mturk.createWorkerBlock({ WorkerId: id, Reason: '' }).promise()`

results in the following error:

`{ ParameterValidationError: Your request parameter Reason  has a minimum length of 1. (1541709713092)
    at Request.extractError (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.callListeners (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\code\tic\mTurkWeb\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
  message: 'Your request parameter Reason  has a minimum length of 1. (1541709713092)',
  code: 'ParameterValidationError',
  time: 2018-11-08T20:41:52.980Z,
  requestId: '6fef2092-6532-46ee-b184-6c30b29f8947',
  statusCode: 400,
  retryable: false,
  retryDelay: 72.25239917225875 }`

**Comment by srchase** [comment]
Thanks for opening this issue.

We've opened a request with the Mechanical Turk Service Team to resolve whether or not the Reason field is required on this operation.  We will let you know when we get an update and can get this issue resolved (either by updating the documentation, or changing the API model in the SDK).

**Comment by srchase** [comment]
@mike-feldmeier 

The Mechanical Turk Service Team confirmed that the reason parameter is required.  They are in the process of updating the documentation.
