### ISSUE TITLE
Expected params.Key to be a string

### ISSUE THREAD

**Issue by Benjamin-Gardien** [aws/aws-sdk-js#2355]
When I try to send file to S3, I have this error :
`(node:9656) UnhandledPromiseRejectionWarning: InvalidParameterType: Expected params.Key to be a string
    at ParamValidator.fail (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:232:10)
    at ParamValidator.validateString (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:154:32)
    at ParamValidator.validateScalar (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:130:21)
    at ParamValidator.validateMember (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:94:21)
    at ParamValidator.validateStructure (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/config.js:341:7)
    at /Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/config.js:359:9
    at Credentials.get (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/config.js:353:24)
    at Config.getCredentials (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/config.js:373:9)
    at Request.VALIDATE_CREDENTIALS (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/event_listeners.js:81:26)
    at Request.callListeners (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/benjamin/Documents/api-clementine/node_modules/aws-sdk/lib/request.js:22:10)
(node:9656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without)
(node:9656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will term.`
Unfortunately, I try to force Key to be a string:
`const uploadParams = {
      Body: file,
      Key: tmpKey.toString(),
      MetaData: {
        folder,
      },
      ContentType: mimetype,
      StorageClass: 'STANDARD_IA',
    };
return new Promise((resolve, reject) => s3.upload(uploadParams, (err, data) => {
      if (err) return reject(err);
      return resolve(data);
    }));
`
But I've the same issue.

**Comment by srchase** [comment]
@Goal54 

Can you share how you're setting tmpKey?

**Comment by Goal54** [comment]
@srchase Yes it's : 
`const getFinalFolderForS3 = async (idSociety, folder, filename) => {
  const keyFile = uuid(filename, uuidv4());
  let tmpKey;
  if (idSociety) {
    tmpKey = `${idSociety}/${folder}/${keyFile}`;
  } else {
    tmpKey = `${folder}/${keyFile}`;
  }
  return tmpKey.toString();
};
`

**Comment by srchase** [comment]
@Goal54 

If you replace tmpKey with a string for testing, does it work as expected?

What does ```typeof(tmpKey)``` return?

**Comment by Goal54** [comment]
@srchase if I replace with a string it doesn't work as expected too. Type of (tmpKey) return me "string" as expected. This issue is very strange because I can upload with success my file

**Comment by srchase** [comment]
How are you handling the credentials to make this call?  The trace you've provided includes ```Request.VALIDATE_CREDENTIALS```.

Are those credentials being set in ```params``` somewhere?

**Comment by Goal54** [comment]
I create something like that:
`AWS.config = new AWS.Config();
AWS.config.accessKeyId = awsClementine.accessKeyId;
AWS.config.secretAccessKey = awsClementine.secretAccessKey;

// is refacto
const s3 = new AWS.S3({
  apiVersion: awsClementine.apiVersion,
  params: {
    Bucket: clementineBucketName,
  },
});`
I put all in my config.json

**Comment by srchase** [comment]
@Goal54 

Your function to get tmpKey is async, so it has not been resolved and is being evaluated as a Promise instead a string.

Can you try removing async on that function?
