### ISSUE TITLE
SQS consumer performance concern

### ISSUE THREAD

**Issue by oliviertassinari** [aws/aws-sdk-js#2371]
We are looking at the CPU usage of our workers, we have noticed that they use 100% of the available CPU. We have started running a profiler.

![capture d ecran 2018-11-22 a 16 52 36](https://user-images.githubusercontent.com/3165635/48912860-0cea4a00-ee77-11e8-890b-801a08baa031.png)

![capture d ecran 2018-11-22 a 16 49 01](https://user-images.githubusercontent.com/3165635/48912867-11166780-ee77-11e8-9da4-194b4d4663dc.png)

It feels like we are spending most of the time performing DNS lookups, TCP connections, TLS handshakes and AWS ACL verifications.

Is there a way to use the same agent, credentials between the repeative calls of 
`sqs.receiveMessage().promise()` and `sqs.deleteMessage().promise()`?

**Comment by srchase** [comment]
@oliviertassinari 

How are you setting up sqs?

Is that the same client?  Or are you re-instantiating that between calls?

**Comment by oliviertassinari** [comment]
We use the same client.

**Comment by oliviertassinari** [comment]
**SqsConsumer.js**
```js
import AWS from 'aws-sdk'
import config from 'config'
import log from 'modules/scripts/log'
import crashReporter from 'modules/crashReporter/common'
import { addTeardown, removeTeardown, isShuttingDown } from 'modules/process/handleKillSignals'
import Queue from 'modules/async/Queue'

export default class SqsConsumer {
  constructor(options) {
    const QueueUrl = options.queueUrl || config.get(`sqs.${options.topic}`)
    if (!QueueUrl) {
      throw new Error(`The following config is missing: sqs.${options.topic}`)
    }

    this.name = `sqsConsumer[${options.topic}]`
    this.sqs = new AWS.SQS({
      apiVersion: '2012-11-05',
      params: {
        MaxNumberOfMessages: 10,
        QueueUrl,
        WaitTimeSeconds: 5, // Long polling
      },
      region: config.get('aws.region'),
    })
    this.queue = new Queue(
      async ({ message, options: { handler } }) => {
        try {
          await handler(JSON.parse(message.Body))
          await this.sqs.deleteMessage({ ReceiptHandle: message.ReceiptHandle }).promise()
        } catch (err) {
          if (isShuttingDown() && err.signal === 'SIGINT') {
            return
          }

          crashReporter.captureException(err, {
            extra: {
              message,
            },
            tags: {
              scope: this.name,
            },
          })
        }
      },
      { concurrency: options.concurrency }
    )
    addTeardown((this.tearDown = { callback: this.destroy, nice: 3 }))
  }

  destroy = async () => {
    log.info({ name: this.name, msg: 'closing' })
    removeTeardown(this.tearDown)
    await this.queue.destroy()
    log.info({ name: this.name, msg: 'closed' })
  }

  consume = async options => {
    const { Messages: messages = [] } = await this.sqs.receiveMessage().promise()

    if (isShuttingDown()) {
      return
    }

    this.queue.push(messages.map(message => ({ message, options })))

    await this.queue.waitUntil({ predicate: 'almost-empty' })
  }

  consumeAll = async options => {
    log.info({ name: this.name, msg: 'consumeAll' })
    await new Promise(async (resolve, reject) => {
      try {
        while (!isShuttingDown()) {
          // eslint-disable-next-line no-await-in-loop
          await this.consume(options)
        }
        resolve()
      } catch (err) {
        reject(err)
      }
    })
  }
}
```

**Comment by srchase** [comment]
@oliviertassinari 

Thanks for following up with this detail.

Does enabling keepAlive improve the performance?

```
this.sqs = new AWS.SQS({
  apiVersion: '2012-11-05',
  httpOptions: {
    agent: new http.Agent({
      keepAlive: true
    })
  },
  params: {
    MaxNumberOfMessages: 10,
    QueueUrl,
    WaitTimeSeconds: 5, // Long polling
  },
  region: config.get('aws.region'),
})
```

**Comment by oliviertassinari** [comment]
@srchase We will try that out next Monday :).

**Comment by oliviertassinari** [comment]
No luck:
> NetworkingError: Protocol "https:" not supported. Expected "http:"
  at new ClientRequest (_http_client.js:118:11)
  at Object.request (https.js:280:10)
  at features.constructor.handleRequest (/onepixel/app/node_modules/aws-sdk/lib/http/node.js:42:23)
  at executeSend (/onepixel/app/node_modules/aws-sdk/lib/event_listeners.js:333:29)
  at Request.SEND (/onepixel/app/node_modules/aws-sdk/lib/event_listeners.js:347:9)
  at Request.callListeners (/onepixel/app/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
  at Request.emit (/onepixel/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
  at Request.emit (/onepixel/app/node_modules/aws-sdk/lib/request.js:683:14)
  at Request.transition (/onepixel/app/node_modules/aws-sdk/lib/request.js:22:10)
  at AcceptorStateMachine.runTo (/onepixel/app/node_modules/aws-sdk/lib/state_machine.js:14:12)

Using an https agent doesn't help either.

**Comment by srchase** [comment]
@oliviertassinari 

Yes, it should be https.

Here's a simplified example:

```
const AWS = require('aws-sdk');
const https = require('https');

const sqs = new AWS.SQS({
  region: 'us-west-2',
  httpOptions: {
    agent: new https.Agent({
      keepAlive: true
    })
  }
})

sqs.listQueues({}, (err,data) => {
  console.log(data)
})
```

**Comment by oliviertassinari** [comment]
@srchase Yes, thanks. I have tried after an https client after seeing the http network error of node. However, the flame graph is the same.

**Comment by srchase** [comment]
@oliviertassinari 

I should've asked earlier, but are you using Node?  Or by 'worker' did you mean web worker?

What version of Node?  What version of the SDK?  Any other environmental details that would help for digging into profiling this?

**Comment by oliviertassinari** [comment]
@srchase We are using:
- Node v10.12.0
- aws-sdk v2.335.0
- The node process is hosted by a Fargate on a Docker.

**Comment by oliviertassinari** [comment]
@srchase Yes, I can test it again Tuesday :).

**Comment by thales-gaddini** [comment]
@oliviertassinari , did it work? How did you solve this?

**Comment by oliviertassinari** [comment]
@thales-gaddini Stopped using SQS

**Comment by thales-gaddini** [comment]
If anyone else stumbles here as I did, the keepAlive fix worked for me.
