### ISSUE TITLE
Require more detail message for KMS permission denied error while doing s3:putObject from Lamba (NodeJS)

### ISSUE THREAD

**Issue by uptownaravi** [aws/aws-sdk-js#2404]
Had written a Lambda (nodeJS) function to putObjects in a KMS encrypted s3 bucket.

But got an error 
{ AccessDenied: Access Denied
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:577:35)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'Access Denied',
code: 'AccessDenied',

Found out that the KMS key created in IAM console was not associated with the role that Lambda is using.
So added that role under Key Users in IAM then the function was able to putObjects in the encrypted bucket.

But this was not indicated in the error message clearly.
is it possible to add a error message which says role does not have permission to the KMS key ?

**Comment by uptownaravi** [comment]
okay will post it there, thanks.
