### ISSUE TITLE
can't upload file to s3bucket using root access and secret key with nodejs

### ISSUE THREAD

**Issue by mfaizan1** [aws/aws-sdk-js#2413]
I am trying to upload images using aws-sdk with nodejs 

here is nodejs code 

```
const aws = require("aws-sdk");
const fs = require("fs");

const uploadFile = async ({ filePath, fileType,key }) => {
  return new Promise((resolve, reject) => {
    aws.config.update({
      region: "ap-south-1",
      // You'll need your service's access keys here
      accessKeyId: "ACCESS KEY HERE",
      secretAccessKey: "SECRET KEY HERE",
    });

    const stream = fs.createReadStream(filePath);
    stream.on("error", function(err) {
      reject(err);
    });

    const s3 = new aws.S3({
      });

    s3.upload(
      {
        ACL: "public-read",
        // You'll input your bucket name here
        Bucket: "BUCKET NAME HERE",
        Body: stream,
        Key: key,
        ContentType: fileType,
      },
      function(err, data) {
        if (err) {
          reject({key:0,url:0});
          console.log(err);
         
        } else if (data) {
          resolve({ key: data.Key, url: data.Location });
        }
      }
    );
  });
};

module.exports = { uploadFile };
```

when this code is executed i get following errors on console.

nodejs error

```
{ AccessDenied: Access Denied
    at Request.extractError (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/services/s3.js:582:35)
    at Request.callListeners (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/user/node-practice/cyres/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/user/node-practice/cyres/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/user/node-practice/cyres/node_modules/aws-sdk/lib/event_listeners.js:294:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
```

message from promise 

```
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2018-12-08T23:50:19.245Z,
  requestId: '3347E41D9D4019D1',
  extendedRequestId: 'bl6YzedJGoqyw6R5t7CcaBi/xcnLZtNQKjpVikbE3s2HNy3qaC12h43UZRDTB7+JiM1pjGsvjQY=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 124.14287007056402 }
```
with root key and secret is it supposed to generate any kind of error?

bucket was created using default settings and permissions i changed nothing.

**Comment by mfaizan1** [comment]
Silly mistake i had set wrong region

**Comment by rsshilli** [comment]
I have the same problem.  @mfaizan1 Can you give a little more insight into what you did wrong?  How did you set the region correctly?

**Comment by rsshilli** [comment]
I figured out my problem. For the next poor soul, I was updating a file where the encryption was set and I didn't specify the same encryption when updating it. So previously had:
```
  let s3Params = {
    Bucket: someBucket,
    Key: someKey,
    Body: contents
  };

  console.log("Uploading file with parameters: " + JSON.stringify(s3Params));
  return await s3.putObject(s3Params).promise();
```

And I had to change it to:
```
  let s3Params = {
    Bucket: someBucket,
    Key: someKey,
    ServerSideEncryption: "AES256",
    Body: contents
  };

  console.log("Uploading file with parameters: " + JSON.stringify(s3Params));
  return await s3.putObject(s3Params).promise();
```
