### ISSUE TITLE
Throttling exection while fetching for emr cluster details

### ISSUE THREAD

**Issue by LamaBimal** [aws/aws-sdk-js#2432]
I have written a lambda function which fetches the cluster details of an received notification. while fetching the cluster details. I got an error like this:

2018-12-14T02:00:17.989Z	ffdf5c83-ff43-11e8-8067-fb1206afb610	{ ThrottlingException: Rate exceeded
at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'Rate exceeded',
code: 'ThrottlingException',
time: 2018-12-14T02:00:17.988Z,

Please suggest how could i resolve it?

**Comment by AllanFly120** [comment]
Hi @LamaBimal 

Are you seeing this error when evoking Lambda or lambda trying to fetch the resource? The exception shows your request is throttled, you can either limit how many calls you make every minute or contact the service to increase your limit.
