### ISSUE TITLE
putObject hangs on file streams

### ISSUE THREAD

**Issue by batrudinych** [aws/aws-sdk-js#2434]
Node: 8.5.0
aws-sdk: 2.360.0 / 2.376.0 / 2.377.0
ubuntu 16.06

The following code hangs forever (or nearly). Copy-paste the code to `script.js` and run `node script.js`
Returns nothing, no messages printed:
```
const fs = require('fs');
const aws = require('aws-sdk');
const s3 = new aws.S3();

s3.putObject({
  Bucket: 'bucket-name',
  ACL: 'public-read',
  Key: 'LICENSE',
  Body: fs.createReadStream('LICENSE'),
})
  .promise()
  .then(res => {
    console.log(res);
  })
  .catch(e => {
    console.log(e);
  });
```
Meanwhile:
* non-stream `putObject` works fine
```
const fs = require('fs');
const aws = require('aws-sdk');
const s3 = new aws.S3();

s3.upload({
  Bucket: 'bucket-name',
  ACL: 'public-read',
  Key: 'LICENSE',
  Body: Buffer.from('test', 'utf8'),
})
  .promise()
  .then(res => {
    console.log(res);
  })
  .catch(e => {
    console.log(e);
  });
```
* `upload` works just fine
```
const fs = require('fs');
const aws = require('aws-sdk');
const s3 = new aws.S3();

s3.upload({
  Bucket: 'bucket-name',
  ACL: 'public-read',
  Key: 'LICENSE',
  Body: fs.createReadStream('LICENSE'),
})
  .promise()
  .then(res => {
    console.log(res);
  })
  .catch(e => {
    console.log(e);
  });
```

**Comment by batrudinych** [comment]
Waited enough to get a response:
```
{ TimeoutError: Connection timed out after 120000ms
    at ClientRequest.<anonymous> (/...../node_modules/aws-sdk/lib/http/node.js:83:34)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:661:40)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at TLSSocket.Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:425:11)
  message: 'Connection timed out after 120000ms',
  code: 'TimeoutError',
  time: 2018-12-17T17:39:30.921Z,
  region: 'eu-west-1',
  hostname: 'bucket-name.s3.eu-west-1.amazonaws.com',
  retryable: true,
  statusCode: 301 }
```

I have AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID variables set in the env

**Comment by srchase** [comment]
@batrudinych 

Thanks for opening this issue.

I'm seeing the same behavior.  The following will (eventually) fail, but only when the file being read is less than 1mb.

```
const fs = require('fs');
const aws = require('aws-sdk');
const s3 = new aws.S3();

s3.putObject({
  Bucket: 'bucket-name',
  ACL: 'public-read',
  Key: 'LICENSE',
  Body: fs.createReadStream('LICENSE'),
})
  .promise()
  .then(res => {
    console.log(res);
  })
  .catch(e => {
    console.log(e);
  });
```

Does a stream with putObject work for you if the file is larger that 1mb?

**Comment by batrudinych** [comment]
@srchase 

Yes, uploading file > 1MB works for me

**Comment by srchase** [comment]
Closing out this issue.  The fix will go out with the next release.
