### ISSUE TITLE
Code deploy not working and getting aws-sdk error

### ISSUE THREAD

**Issue by rameshmote** [aws/aws-sdk-js#2437]
When we are trying to update the new code using code deploy, the build was successful at bit bucket and codeship but its not getting updated to EC2 instances. And we are running the AWS-SDK version is 2.22.0
Giving below error.

LifecycleEvent - ApplicationStop
Script - deploy-scripts/deregisterWithAS
[stderr]/opt/codedeploy-agent/node_modules/aws-sdk/lib/request.js:31
[stderr] throw err;
[stderr] ^
[stderr]
[stderr]TypeError: Cannot read property 'Reservations' of null
[stderr] at Response.ec2.describeInstances (/opt/codedeploy-agent/deployment-root/87114924-3f0a-467f-80b5-1b5001952be8/d-30R3Y3U0X/deployment-archive/deploy-scripts/deregisterWithAS:29:8)
[stderr] at Request.<anonymous> (/opt/codedeploy-agent/node_modules/aws-sdk/lib/request.js:364:18)
[stderr] at Request.callListeners (/opt/codedeploy-agent/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[stderr] at Request.emit (/opt/codedeploy-agent/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[stderr] at Request.emit (/opt/codedeploy-agent/node_modules/aws-sdk/lib/request.js:683:14)
[stderr] at Request.transition (/opt/codedeploy-agent/node_modules/aws-sdk/lib/request.js:22:10)
[stderr] at AcceptorStateMachine.runTo (/opt/codedeploy-agent/node_modules/aws-sdk/lib/state_machine.js:14:12)
[stderr] at /opt/codedeploy-agent/node_modules/aws-sdk/lib/state_machine.js:26:10
[stderr] at Request.<anonymous> (/opt/codedeploy-agent/node_modules/aws-sdk/lib/request.js:38:9)
[stderr] at Request.<anonymous> (/opt/codedeploy-agent/node_modules/aws-sdk/lib/request.js:685:12)

**Comment by srchase** [comment]
@rameshmote

Can you provide an example of the code you are using?
