### ISSUE TITLE
Error: Cannot find module 'jmespath'

### ISSUE THREAD

**Issue by rajeshbala01** [aws/aws-sdk-js#2460]
C:\Program Files\Git\aws-sdk-js-master>node dist-tools/browser-builder.js > aws-sdk.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'jmespath'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Program Files\Git\aws-sdk-js-master\lib\request.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

I am still not able to run the command to build the aws-sdk.js file

Version of aws-sdk-js i am using is 2.10.0

[package.zip](https://github.com/aws/aws-sdk-js/files/2711011/package.zip)

**Comment by srchase** [comment]
@rajeshbala01 

Did you run ```npm install``` first?
