### ISSUE TITLE
Authenticating elastic search client from lambda broken in 2.382.0

### ISSUE THREAD

**Issue by wheresrhys** [aws/aws-sdk-js#2469]
Since upgrading to 2.382.0 calls to ES from my lambda have stopped working, throwing the following error. 

```
message:	 AWS credentials not provided	
    	 stack:	 Error: AWS credentials not provided
    at getEsClient (/var/task/dist/lib/es-client.js:26:11)
    at Object.search (/var/task/dist/lib/es-client.js:44:10)
    at searchPage (/var/task/dist/searchHandler.js:104:36)
    at Promise.resolve.then.then.isSignedIn (/var/task/dist/lib/lambda.js:125:12)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)	
    	 type:	 Error	
```

Downgrading to 2.381.0 fixes the issue

Here is my es client code (all dependencies on latest versions):

```js

const httpAwsEs = require('http-aws-es');
const AWS = require('aws-sdk');
const elasticsearch = require('elasticsearch');
const config = require('./config');

let esClient;

// this is a getter of a singleton so we can manually assume the application role
// in integration tests before creating the client with AWS credentials
const getEsClient = () => {
	if (esClient) {
		return esClient;
	}

	if (!config.get('ES_HOST')) {
		throw new Error('ElasticSearch Index not defined');
	}

	if (!AWS.config.credentials) {
		throw new Error('AWS credentials not provided');
	}

	console.info(
		{ host: config.get('ES_HOST') },
		'Connecting to ElasticSearch host',
	);

	return new elasticsearch.Client({
		connectionClass: httpAwsEs,
		awsConfig: AWS.config,
		host: config.get('ES_HOST'),
		apiVersion: '6.3',
	});
};

function search(query) {
	console.info({ query }, 'Starting Elasticsearch');

	return getEsClient()
		.search({
			index: 'biz-ops-search',
			body: query,
		})
		.then(results => {
			console.info(
				{ hitCount: results.hits.total },
				'Elasticsearch complete with hits',
			);
			console.debug({ results }, 'Elasticsearch results');

			return {
				total: results.hits.total,
				results: results.hits ? results.hits.hits.map(hit => hit._source) : [],
			};
		})
		.catch(error => {
			if (error.response) {
				error.response = JSON.parse(error.response);
			}

			console.error(
				{ event: 'ELASTICSEARCH_ERROR', error, query },
				'Elasticsearch query failed',
			);

			throw error;
		});
}

module.exports = {
	search,
};

```

I wonder if it's related to this (or something like it) https://github.com/aws/aws-sdk-js/issues/2455

**Comment by srchase** [comment]
@wheresrhys 

Have you tried rolling back to 2.381.0?

**Comment by srchase** [comment]
@wheresrhys 

2.383.0 has been released.  Closing out this issue.
