### ISSUE TITLE
Model validation can conflict with additional Object prototype methods

### ISSUE THREAD

**Issue by CaptainCharlieGreen** [aws/aws-sdk-js#2475]
I've recently fixed a bug in my system that caused this error on many different sdk calls:

{ Error: Unrecognized shape type: map
    at Function.create (/home/faux/lit/lsl/node_modules/aws-sdk/lib/model/shape.js:143:13)
    at /home/faux/lit/lsl/node_modules/aws-sdk/lib/model/api.js:54:18
    at /home/faux/lit/lsl/node_modules/aws-sdk/lib/model/collection.js:5:12
    at Collection.S11 (/home/faux/lit/lsl/node_modules/aws-sdk/lib/util.js:668:23)
    at Function.resolve (/home/faux/lit/lsl/node_modules/aws-sdk/lib/model/shape.js:95:38)
    at Function.create (/home/faux/lit/lsl/node_modules/aws-sdk/lib/model/shape.js:109:24)
    at /home/faux/lit/lsl/node_modules/aws-sdk/lib/model/shape.js:173:20
    at /home/faux/lit/lsl/node_modules/aws-sdk/lib/model/collection.js:5:12
    at Collection.Metadata (/home/faux/lit/lsl/node_modules/aws-sdk/lib/util.js:668:23)
    at /home/faux/lit/lsl/node_modules/aws-sdk/lib/model/operation.js:73:18
  message: 'Unrecognized shape type: map',
  code: 'Error',
  time: 2019-01-08T18:46:35.492Z }

The root cause was I had added a "map" method to the Object prototype:

Object.prototype.map = function (fn) {
  if (fn === undefined) return this;
  return Object.keys(this)
    .reduce((newMap, key) => {
      newMap[key] = fn(this[key]);
      return newMap;
    }, {});
};

This blew up in your model validation here (lib/model/shape.js:143) when shape.type was "map":
    if (Shape.normalizedTypes[shape.type]) {
      shape.type = Shape.normalizedTypes[shape.type];
    } 

I can fix this issue by either removing/renaming the new Object.map, or changing your test above to be .hasOwnProperty(shape.type).  I fully accept this is a silly situation, but "map" is a very common word to be looking for on objects willy-nilly.  If you deem this fix-worthy I'd be happy to submit a PR to change the [] test to .hasOwnProperty.

**Comment by srchase** [comment]
@CaptainCharlieGreen 

Thanks for opening this issue.

You're welcome to submit a PR on the test for us to review.  I understand some packages alter Object.prototype, but so far this has been a bit of an edge case.
