### ISSUE TITLE
missing credentials in config when assuming the role

### ISSUE THREAD

**Issue by shivarajbakale** [aws/aws-sdk-js#2488]

**Comment by shivarajbakale** [comment]
var AWS=require('aws-sdk');

async function connAWS() {
    var sts = new AWS.STS({ region: 'ap-south-1' });
  
    const params = {
      RoleArn: 'my role',
      RoleSessionName: 'awssdk'
    };
    let assumeRole;
  
    try {
      assumeRole1 = await sts.assumeRole(params).promise();
    } catch (err) {
      console.log('Cannot assume role');
      console.log(err, err.stack);
      return;
    }
  
    const accessparams = {
      accessKeyId: assumeRoleStep1.Credentials.AccessKeyId,
      secretAccessKey: assumeRoleStep1.Credentials.SecretAccessKey,
      sessionToken: assumeRoleStep1.Credentials.SessionToken,
    };
  
    const s3 = await new AWS.S3(accessparams);
    console.log('s3', s3);
  }
  
  connAWS();

**Comment by srchase** [comment]
@shivarajbakale 

Can you provide the error you receive?  Using this code, I would expect some issues due to using 
```assumeRole```, ```assumeRole1``` and ```assumeRoleStep1```.

**Comment by shivarajbakale** [comment]
Cannot assume role
{ Error: connect EHOSTUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  message: 'Missing credentials in config',
  errno: 'EHOSTUNREACH',
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2019-01-19T19:03:21.661Z,
  originalError:
   { message: 'Could not load credentials from any providers',
     errno: 'EHOSTUNREACH',
     code: 'CredentialsError',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2019-01-19T19:03:21.661Z,
     originalError:
      { errno: 'EHOSTUNREACH',
        code: 'EHOSTUNREACH',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,
        message: 'connect EHOSTUNREACH 169.254.169.254:80' } } } 'Error: connect EHOSTUNREACH 169.254.169.254:80\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)'

**Comment by shivarajbakale** [comment]
Cannot assume role
{ AccessDenied: Access denied
    at Request.extractError (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Access denied',
  code: 'AccessDenied',
  time: 2019-01-19T19:06:57.121Z,
  requestId: '6406fec1-1c1d-11e9-b9d0-79ec2d277109',
  statusCode: 403,
  retryable: false,
  retryDelay: 7.110264642110686 } 'AccessDenied: Access denied\n    at Request.extractError (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/protocol/query.js:50:29)\n    at Request.callListeners (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\nat Request.emit (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/home/shivarajapple/projects/competition/projectS/node_modules/aws-sdk/lib/sequential_executor.js:116:18)'

**Comment by srchase** [comment]
@rhaegar453 

Did you make changes to the ```assumeRole``` variables?

**Comment by rhaegar453** [comment]
@srchase  No , I didnt make any changes to assumeRole variables. Just installed the AWS-sdk for node and use the above code

**Comment by srchase** [comment]
@rhaegar453 

Can you consolidate these variables and see if you can get your code working that way?

```assumeRole```, ```assumeRole1``` and ```assumeRoleStep1```
