### ISSUE TITLE
s3.getSignedUrl can't generate postObject

### ISSUE THREAD

**Issue by 1mike12** [aws/aws-sdk-js#2491]
using `^2.388.0`
I have a client library that seems to only allow POST requests. I tried simply redirecting a post into a put request serverside but the library is finicky. 

I can generate successful PUT links with `s3.getSignedUrl("putObject", params)` but trying it with `s3.getSignedUrl("postObject", params)` gives me: 

``` 
(node:744) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'input' of undefined
    at Request.VALIDATE_PARAMETERS (C:\[project]\node_modules\aws-sdk\lib\event_listeners.js:124:61)
    at Request.callListeners (C:\[project]\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at callNextListener (C:\[project]\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at C:\[project]\node_modules\aws-sdk\lib\event_listeners.js:86:9
    at finish (C:\[project]\node_modules\aws-sdk\lib\config.js:350:7)
    at C:\[project]\node_modules\aws-sdk\lib\config.js:368:9
    at Credentials.get (C:\[project]\node_modules\aws-sdk\lib\credentials.js:127:7)
    at getAsyncCredentials (C:\[project]\node_modules\aws-sdk\lib\config.js:362:24)
    at Config.getCredentials (C:\[project]\node_modules\aws-sdk\lib\config.js:382:9)
    at Request.VALIDATE_CREDENTIALS (C:\[project]\node_modules\aws-sdk\lib\event_listeners.js:81:26)
    at Request.callListeners (C:\[project]\node_modules\aws-sdk\lib\sequential_executor.js:102:18)
    at Request.emit (C:\[project]\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\[project]\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\[project]\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\[project]\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at Request.runTo (C:\[project]\node_modules\aws-sdk\lib\request.js:403:15)
```

It looks like the operation is not defined in `aws-sdk\apis\s3-2006-03-01.min.json`

**Comment by srchase** [comment]
@1mike12 

There is a separate operation for Posts: [createPresignedPost](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property).

Does that work for your client library?
