### ISSUE TITLE
Randomly fails to refresh access key: TypeError: Cannot read property 'accessKeyId' of null

### ISSUE THREAD

**Issue by VTLee** [aws/aws-sdk-js#2493]
We use aws-sdk in our application, and this normally runs fine (for weeks or months) non-stop.

However, this morning, a container that was running for a week randomly decided to throw the following stack trace, which crashed NPM:

```
/app/node_modules/aws-sdk/lib/service.js:338
request.service.config.credentials.accessKeyId
^
TypeError: Cannot read property 'accessKeyId' of null
at features.constructor.apiAttemptEvent (/app/node_modules/aws-sdk/lib/service.js:338:42)
at Request.API_CALL_ATTEMPT (/app/node_modules/aws-sdk/lib/service.js:392:34)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
```
From this trace, you can see this never touches my organization's code.

This appears to be an issue with getting/refreshing credentials... which is especially weird because it was able to read messages from SQS, then failed 3 seconds later trying to act on messages -- so the access key just _poofed_, to be technical.

The credentials are 100% AWS-managed. The container and task definition have no knowledge or support for access key, it inherits the values from the Role attached to the service. The service appears to work, then for an unknown reason fail with this error.

I can't easily correlate this to any processes we run, since we have 10 simultaneous threads being worked on once it reads from the queue. Generally speaking, we jitter and exponentially back off when we catch throttling or other errors, but we crash in TypeErrors like above (since they appear to be completely outside any try/catch blocks)

If it matters, we generally run 3 M4.large instances, and each instance has about 12 containers on it at any given point. These containers are microservices, with ~3 duplicates of each service. When this error happened, only 1 service was impacted, and it was impacted regardless of which instance it was created on. It continued to fail when we moved it to a brand new server.

We have an open case with AWS support, but they suggested making this bug report since it appears there might be a problem in the SDK (as this *probably* should be returning a proper exception, not a TypeError)

AWS-SDK version 2.332.0

I have no knowledge of how to reproduce this, as I don't know what really caused it in the first place. It seems to happen semi-randomly every 2-3 months, We thought container/server age might be a factor, but this server was only up for a month, and this container only for a week.

**Comment by AllanFly120** [comment]
Hi, @VTLee 

Looks like a dup of #2433. We have deployed a fix on [that](https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L342~L343), you can try out the newest version of SDK.

**Comment by VTLee** [comment]
I was incorrect on my SDK version, but looks like it still falls under #2433 -- We were running 2.377 on the container. Will try latest.
