### ISSUE TITLE
"Missing credentials in config" using shared credentials file

### ISSUE THREAD

**Issue by Bunnoo** [aws/aws-sdk-js#2503]
Hello,

I have read lots of topics about this error but still can't seem to figure out a solution to my issue.. I am using AWS SDK JS as part of a Nuxt project, and whenever I try to instantiate AWS, I get the following error:

```
Error: Missing credentials in config
    at credError (C:\wamp64\www\project\node_modules\aws-sdk\lib\config.js:354)
    at Config.getCredentials (C:\wamp64\www\project\node_modules\aws-sdk\lib\config.js:395)
    at Request.VALIDATE_CREDENTIALS (C:\wamp64\www\project\node_modules\aws-sdk\lib\event_listeners.js:81)
    at Request.callListeners (C:\wamp64\www\project\node_modules\aws-sdk\lib\sequential_executor.js:102)
    at Request.emit (C:\wamp64\www\project\node_modules\aws-sdk\lib\sequential_executor.js:78)
    at Request.emit (C:\wamp64\www\project\node_modules\aws-sdk\lib\request.js:683)
    at Request.transition (C:\wamp64\www\project\node_modules\aws-sdk\lib\request.js:22)
    at AcceptorStateMachine.runTo (C:\wamp64\www\project\node_modules\aws-sdk\lib\state_machine.js:14)
    at Request.runTo (C:\wamp64\www\project\node_modules\aws-sdk\lib\request.js:403)
    at C:\wamp64\www\project\node_modules\aws-sdk\lib\request.js:792 "CredentialsError: Missing credentials in config
    at credError (http://localhost:3000/_nuxt/pages_contact.js:4900:40)
    at Config.getCredentials (http://localhost:3000/_nuxt/pages_contact.js:4941:14)
    at Request.VALIDATE_CREDENTIALS (http://localhost:3000/_nuxt/pages_contact.js:8724:26)
    at Request.callListeners (http://localhost:3000/_nuxt/pages_contact.js:14013:18)
    at Request.emit (http://localhost:3000/_nuxt/pages_contact.js:13989:10)
    at Request.emit (http://localhost:3000/_nuxt/pages_contact.js:12637:14)
    at Request.transition (http://localhost:3000/_nuxt/pages_contact.js:11976:10)
    at AcceptorStateMachine.runTo (http://localhost:3000/_nuxt/pages_contact.js:17613:12)
    at Request.runTo (http://localhost:3000/_nuxt/pages_contact.js:12357:15)
    at http://localhost:3000/_nuxt/pages_contact.js:12746:12"
```
I have setup my credentials and config files as follows in C:\Users\Bruno\.aws

credentials
```
[default]
aws_access_key_id=A***********
aws_secret_access_key=**********
```

config
```
[default]
region=eu-west-3
output=json
aws_access_key_id=A***********
aws_secret_access_key=**********
```

I have tried installing the dotenv package to override environment variable, and 
`console.log(process.env.AWS_SHARED_CREDENTIALS_FILE);`
displays
`C:\Users\Bruno\.aws\credentials`

So.. I really don't understand why AWS seems unable to retrieve credentials from anywhere. I also installed aws-cli, and when running `aws configure` it picks up correctly the default credentials I've input.

**Comment by srchase** [comment]
@Bunnoo 

Which version SDK are you using?  Which version of Node?

Can you show a code sample of how you are using the SDK?

**Comment by srchase** [comment]
@Bunnoo,

The code you've provided runs in the browser, is that correct?

You'll need to refer to this documentation: [Setting Credentials in a Web Browser](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-browser.html)
