### ISSUE TITLE
AWS.Transfer is not a constructor

### ISSUE THREAD

**Issue by viper25** [aws/aws-sdk-js#2514]
On using the AWS JavaScript SDK 

```js
var transfer = new AWS.Transfer();
```

I get the error. Just plain followed the [API docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Transfer.html)

```
TypeError: AWS.Transfer is not a constructor
    at removekeysFromAWSTransfer (C:\DATA\git\project\AWS_nodeJs\index.js:56:17)
    at C:\DATA\git\project\AWS_nodeJs\index.js:46:5
    at Array.forEach (<anonymous>)
    at Response.<anonymous> (C:\DATA\git\project\AWS_nodeJs\index.js:33:16)
    at Request.<anonymous> (C:\DATA\git\project\AWS_nodeJs\node_modules\aws-sdk\lib\request.js:364:18)
    at Request.callListeners (C:\DATA\git\project\AWS_nodeJs\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\DATA\git\project\AWS_nodeJs\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\DATA\git\project\AWS_nodeJs\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\DATA\git\project\AWS_nodeJs\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\DATA\git\project\AWS_nodeJs\node_modules\aws-sdk\lib\state_machine.js:14:12)
```

I can do 

```js
ddb = new AWS.DynamoDB();
```

in the same nodejs app without any error.

**Comment by viper25** [comment]
> 
> 
> Hi @viper25, I was not able to reproduce this. Transfer is a fairly new addition, so it is likely that your AWS package might be out of date. Can you please check and let me know what version you are using?

I created a brand new nodeJS app at the time of writing this post. And I got the latest node packages via
```js
npm install aws-sdk
```
so I assume it's pulling the latest. Or no?

**Comment by drexler** [comment]
@viper25 the constructor takes an argument. https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Transfer.html#constructor-property

Test file:
```
const AWS = require('aws-sdk')


const transfer = new AWS.Transfer({
    apiVersion: '2018-11-05',
    region: `us-east-1`
});

const params = {
    ServerId: 'hlaoslloesses' /* required */
};

transfer.describeServer(params, (err, data) => {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```

**Comment by viper25** [comment]
I'm sure it's the aws-sdk version I'm using. It's shown as 

```dos
C:\AWS_nodeJs> npm list aws-sdk
C:\AWS_nodeJs
`-- aws-sdk@2.361.0
```

I got the above by running `npm install aws-sdk` and that's what I got. Noob Q: How do I _force_ npm to get the latest `aws-sdk`?

**Comment by klaytaybai** [comment]
That is interesting.  It’s good to be aware of that.  Thanks for sharing!

I’ll close this out now.
