### ISSUE TITLE
Is there any way to get more information on which rate limit I've exceeded?

### ISSUE THREAD

**Issue by mreinstein** [aws/aws-sdk-js#2557]
in invoking AWS transcribe, I'm getting a very vague throttling error, like so:

```
2019-02-27T18:23:57.372Z	63044701-6b0c-43f6-84b3-0fc6008f85a5	ThrottlingException: Rate exceeded
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

Is there any way to get more detailed information on which rate I'm running into? i.e., which of these did I overflow?
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits-amazon-transcribe

**Comment by srchase** [comment]
@mreinstein 

Thanks for opening this issue.

The SDK Team is able to provide any information regarding the ThrottlingException returned by the service.

You can engage the Transcribe Team via their AWS Developer Forum: [AWS Transcribe](https://forums.aws.amazon.com/forum.jspa?forumID=278)

If there's any followup questions regarding the behavior of the SDK, let us know and we can re-open this issue if needed.
