### ISSUE TITLE
XMLParserError: Non-whitespace before first tag

### ISSUE THREAD

**Issue by ElijahPrince73** [aws/aws-sdk-js#2623]
Hello, I'm having an issue uploading images to Digital Ocean.

This piece of code was working for a while till I switched from Mlab to MongoDB Atlas not sure if that's related though.

I get an error back saying this

`{ XMLParserError: Non-whitespace before first tag.
Line: 0
Column: 1
Char: E
    at error (/Users/elijahprince/Dev/E-Commerce-API/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/Users/elijahprince/Dev/E-Commerce-API/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/Users/elijahprince/Dev/E-Commerce-API/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/Users/elijahprince/Dev/E-Commerce-API/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/Users/elijahprince/Dev/E-Commerce-API/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/Users/elijahprince/Dev/E-Commerce-API/node_modules/xml2js/lib/parser.js:5:59)
    at NodeXmlParser.parse (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
    at Request.extractError (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/services/s3.js:571:39)
    at Request.callListeners (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/elijahprince/Dev/E-Commerce-API/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: E',
  code: 'XMLParserError',
  retryable: true,
  time: 2019-04-15T02:11:11.759Z,
  statusCode: 400 }`

This is the code I'm using to upload images

[https://github.com/ElijahPrince73/E-Commerce-API/blob/master/utils/post-image-to-bucket.js](url)

**Comment by AllanFly120** [comment]
Hi @ElijahPrince73 

It seems like the response XML is corrupted. You need to check the response body to see if the xml is parsable. But I don't think there's any issue with SDK itself. 

I will close this issue, please comment here if you have further questions.

**Comment by peterpod-c1** [comment]
Hi I'm getting the same error. This was working for a long time when uploading via http, and now we are moving to sslEnabled upload.

```
Fatal error: Failed to upload versionedRelease/BUILD-12345/assets/icons/bill.svg with bucket bankoaoqaweb
XMLParserError: Non-whitespace before first tag.
Line: 0
Column: 1
Char:
```

```npm list 
├─┬ aws-sdk@2.0.31
│ │ ├─┬ xml2js@0.2.6
│ │ │ └── sax@0.4.2
│ │ └── xmlbuilder@0.4.2
```

**Comment by ElijahPrince73** [comment]
@peterpod-c1 My solution had something to do with the NPM package I was using to load in my env I had my values wrapped in quotes like this

DB_URL="some_url"

when I really needed it to look like DB_URL=some_url

**Comment by peterpod-c1** [comment]
I ended up spawning a child process with grunt and using the cli directly.
Something is acting up in either this sdk or the `xml2js` dependency it uses.
