### ISSUE TITLE
Sending Message from Lambda to SQS throws SSL Exceptions

### ISSUE THREAD

**Issue by devlin3004** [aws/aws-sdk-js#2646]
Application is written in Node.js 8.10 and relies on AWS SDK for interacting with other AWS resources, such as SQS. No additional options to SQS library are passed in:

const sqs = new AWS.SQS({ apiVersion: "2012-11-05" });

Stacktrace:

START RequestId: cbcf4aab-dc21-520b-82e0-1f9ff5fba11e Version: $LATEST
2019-04-19T19:55:26.563Z	28ea02cb-8fba-5fc8-8559-57ffa6244cdd	{ Error: write EPROTO 140515788527488:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:

at _errnoException (util.js:1022:11)
at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
message: 'write EPROTO 140515788527488:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:\n',
code: 'NetworkingError',
errno: 'EPROTO',
syscall: 'write',
region: 'us-east-1',
hostname: 'sqs.us-east-1.amazonaws.com',
retryable: true,
time: 2019-04-19T19:55:26.563Z } 'Error: write EPROTO 140515788527488:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:\n\n at _errnoException (util.js:1022:11)\n at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)'
2019-04-19T19:55:26.564Z	28ea02cb-8fba-5fc8-8559-57ffa6244cdd	(node:1) UnhandledPromiseRejectionWarning: Error: write EPROTO 140515788527488:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:

at _errnoException (util.js:1022:11)
at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
2019-04-19T19:55:26.564Z	28ea02cb-8fba-5fc8-8559-57ffa6244cdd	(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)

**Comment by srchase** [comment]
@devlin3004,

Which version of the SDK are you using?

**Comment by srchase** [comment]
@devlin3004,

Assuming you're using the Lambda provided version of the SDK, 2.290.0, I'm not getting this same error.

If you can provide any details on your function, permissions, SQS queue or anything else that might be relevant, that would be helpful in pointing to the underlying issue.
