### ISSUE TITLE
SignatureDoesNotMatch: Signature expired in SNS publish calls

### ISSUE THREAD

**Issue by doronin** [aws/aws-sdk-js#265]
Hello, I'm using aws-sdk and have a long-running instance of sns client running. From time to type I see `SignatureDoesNotMatch` errors triggered when making `sns.publish` call. Does SDK generate signature on each request or do I have to make a call to re-generate signature from time to time? What can I do to prevent this error from happening?

SignatureDoesNotMatch: Signature expired: 20140428T172145Z is now earlier than 20140428T172828Z (20140428T174328Z - 15 min.)
    at Request.extractError (aws-sdk/lib/service_interface/query.js:46:35)
    at Request.callListeners (aws-sdk/lib/sequential_executor.js:117:20)
    at Request.callListeners (aws-sdk/lib/sequential_executor.js:118:16)
    at Request.emit (aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (aws-sdk/lib/request.js:536:10)
    at Request.emitEvents (aws-sdk/lib/request.js:510:12)
    at Request.completeRequest (aws-sdk/lib/request.js:480:10)
    at Request.HTTP_DONE (aws-sdk/lib/event_listeners.js:239:12)
    at Request.callListeners (aws-sdk/lib/sequential_executor.js:117:20)
    at Request.emit (aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (aws-sdk/lib/request.js:536:10)
    at IncomingMessage.onEnd (aws-sdk/lib/event_listeners.js:177:24)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickDomainCallback (node.js:459:13) |JSON|{"message":"Signature expired: 20140428T172145Z is now earlier than 20140428T172828Z (20140428T174328Z - 15 min.)","code":"SignatureDoesNotMatch","time":"2014-04-28T17:43:28.876Z","statusCode":403,"retryable":false}

**Comment by felipesabino** [comment]
@lsegal I am having this issue using `2.0.0-rc.14` version :disappointed:

**Comment by lsegal** [comment]
@felipesabino 2.0.0-rc.14 is an extremely old version. Have you reproduced this on the latest version of the SDK?
