### ISSUE TITLE
AWS EC2 Unable to set region "eu-west-3"

### ISSUE THREAD

**Issue by mcourant** [aws/aws-sdk-js#2656]
Hello,

I am trying to get ec2 informations instance through the sdk.

Problem:
```
{ UnsupportedOperation: The functionality you requested is not available in this region.
    at Request.extractError (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'The functionality you requested is not available in this region.',
  code: 'UnsupportedOperation',
  time: 2019-05-07T14:34:37.397Z,
  requestId: '9ac65872-d45a-493b-88d5-6f96508f0157',
  statusCode: 400,
  retryable: false,
  retryDelay: 84.11396975328887 } 'UnsupportedOperation: The functionality you requested is not available in this region.\n    at Request.extractError (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/services/ec2.js:50:35)\n    at Request.callListeners (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/Users/maximecourant/GitLab/Utils/api-aws/node_modules/aws-sdk/lib/sequential_executor.js:116:18)'
```
Steps to reproduce the issue:
```
import AWS from "aws-sdk"

export const getEc2 = (req, res) => {
    var ec2 = new AWS.EC2({ apiVersion: '2016-11-15', region: 'eu-west-3'});
    ec2.describeClassicLinkInstances(params, function(err, data) {
        if (err) console.log(err, err.stack); // an error occurred
        else     console.log(data);           // successful response
    });
}
```

Thanks a lot.

EDIT: formatted code

**Comment by AllanFly120** [comment]
@mcourant 

From what I can see in the response, The operation is not yet supported in the region `eu-west-3`. This is not a client-side issue with SDK, so I will close this issue. You can reach out to the service team on the [EC2 forum](https://forums.aws.amazon.com/forum.jspa?forumID=30) for more help.

Feel free to comment here if you have more questions with the SDK.
