### ISSUE TITLE
S3 constructor ignore region 

### ISSUE THREAD

**Issue by mrcportillo** [aws/aws-sdk-js#2667]
I'm having an issue with the S3 object to fetch a single object from my bucket. This is my code:

```
  let s3 = new AWS.S3({ region: 'us-west-2' });
  console.log(s3.config);
  return s3.getObject({ Bucket: 'bucket', Key: 'key/fake.txt' }).promise();
 ``` 

getting this error:

```
{ ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/Users/project/path/node_modules/aws-sdk/lib/event_listeners.js:92:45)
    at Request.callListeners (/Users/project/path/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/project/path/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /Users/project/path/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/Users/project/path/node_modules/aws-sdk/lib/config.js:350:7)
    at /Users/project/path/node_modules/aws-sdk/lib/config.js:368:9
    at SharedIniFileCredentials.get (/Users/project/path/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/Users/project/path/node_modules/aws-sdk/lib/config.js:362:24)
    at Config.getCredentials (/Users/project/path/node_modules/aws-sdk/lib/config.js:382:9)
    at Request.VALIDATE_CREDENTIALS (/Users/project/path/node_modules/aws-sdk/lib/event_listeners.js:81:26)
    at Request.callListeners (/Users/project/path/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/Users/project/path/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/project/path/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/project/path/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/project/path/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/project/path/node_modules/aws-sdk/lib/request.js:403:15)
    at /Users/project/path/node_modules/aws-sdk/lib/request.js:792:12
    at new Promise (<anonymous>)
    at Request.promise (/Users/project/path/node_modules/aws-sdk/lib/request.js:778:12)
    at decrypt (/Users/project/path/src/common/aws-utils.js:1:2372)
    at getS3Object.then.data (/Users/project/path/src/authenticator/utils.js:1:6431)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2019-05-13T16:46:58.994Z }
```

the console.log output is: 
```
Config {
  credentials:
   SharedIniFileCredentials {
     expired: false,
     expireTime: null,
     refreshCallbacks: [],
     accessKeyId: 'MYACCESSKEYID',
     sessionToken: undefined,
     filename: undefined,
     profile: 'default',
     disableAssumeRole: true,
     preferStaticCredentials: false,
     tokenCodeFn: null,
     httpOptions: null },
  credentialProvider:
   CredentialProviderChain {
     providers:
      [ [Function],
        [Function],
        [Function],
        [Function],
        [Function],
        [Function] ],
     resolveCallbacks: [] },
  region: 'us-west-2',
  logger: null,
  apiVersions: {},
  apiVersion: null,
  endpoint: 's3.us-west-2.amazonaws.com',
  httpOptions: { timeout: 120000 },
  maxRetries: undefined,
  maxRedirects: 10,
  paramValidation: true,
  sslEnabled: true,
  s3ForcePathStyle: false,
  s3BucketEndpoint: false,
  s3DisableBodySigning: true,
  computeChecksums: true,
  convertResponseTypes: true,
  correctClockSkew: false,
  customUserAgent: null,
  dynamoDbCrc32: true,
  systemClockOffset: 0,
  signatureVersion: 's3',
  signatureCache: true,
  retryDelayOptions: {},
  useAccelerateEndpoint: false,
  clientSideMonitoring: false,
  endpointDiscoveryEnabled: false,
  endpointCacheSize: 1000,
  hostPrefixEnabled: true }
```

Looks like the region it's ok, but the error said that it's missing.
Besides this part, I've set the AWS.config params in another part of the code, and also I've my credentials and config set up in `./aws/` home folder, this should not affect the configuration that I passing to the S3 constructor according to the config priorities order found in the documentation: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html

could this error covering something else?

**Comment by AllanFly120** [comment]
Hi @mrcportillo,

It is abnormal. Can you try to log whether `config.region` still available after the request being made:

```javascript
s3.getObject({ Bucket: 'bucket', Key: 'key/fake.txt' }, function(err, data) {
    console.log(s3.config.region);
})
```

It will also be helpful if you can create a reproducible repo that we can look into.

**Comment by mrcportillo** [comment]
Hi @AllanFly120 thank you for your response, I did what you suggest (use the callback instead promise) and realize that getObject() was resolving well, the issue was with another AWS service call after this with a bad configuration. I'll close this issue, thanks again.
