### ISSUE TITLE
Cognito Trigger broken with sdk v2.466.0 nodejs10.x

### ISSUE THREAD

**Issue by vuongngo** [aws/aws-sdk-js#2692]
**Describe the bug**
I use lambda cognito trigger to do some identity check. Trigger work find with with node8.10 (sdk v2.457.0). However, after updating to sdk v2.466.0 and nodejs10.x, it is broken.
Here is the message from cognito: 
```
{__type: "InvalidLambdaResponseException", message: "Invalid lambda function output : Invalid JSON"}
```
I always return callback(null, event) without changing event in lambda function. It shouldn't affect json structure.

**Is the issue in the browser/Node.js?**
Lambda/Cognito

**Details of the browser/Node.js version**
nodejs10.x

**SDK version number**
v2.466.0

**To Reproduce (observed behavior)**
Use lambda on Post Authentication Trigger
```
callback(null, event);
```

**Expected behavior**
Should not broken json structure as nothing change.

**Further info**
It works with sdk v2.466.0 on nodejs8.10. Buffer constructor deprecation warning still received on nodejs10.x during function invocation.
I tried to both exclude and include aws-sdk from bundle with serverless webpack, but it still doesn't work with nodejs10.x. Probably something related to sdk in run-time environment.

**Comment by AllanFly120** [comment]
Hey @vuongngo 
I suspect the post authenticate function raises exceptions so the function doesn't return the expected JSON. Can you inspect the Cloudwatch log for the Lambda? Do you see increased error rate there? It will be helpful if you can share the log associated with the failed post auth trigger.

**Comment by vuongngo** [comment]
Yeah, possibly.

This is the log from the first call
```
 04:14:49
2019-06-03T04:14:49.105Z	undefined	INFO	initialising global knex in base model class
 04:14:49
START RequestId: 57fb45b0-d1f0-4d87-b654-7f7bf291c8e2 Version: $LATEST
 04:14:49
2019-06-03T04:14:49.122Z	57fb45b0-d1f0-4d87-b654-7f7bf291c8e2	INFO	function called postConfirmation @auth-trigger/controller/member
 04:14:49
2019-06-03T04:14:49.204Z	57fb45b0-d1f0-4d87-b654-7f7bf291c8e2	ERROR	(node:7) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
 04:14:49
END RequestId: 57fb45b0-d1f0-4d87-b654-7f7bf291c8e2
 04:14:49
REPORT RequestId: 57fb45b0-d1f0-4d87-b654-7f7bf291c8e2	Duration: 90.12 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 230 MB
```
Second call I caught error from try catch block, but there is no error output
```
 04:17:01
2019-06-03T04:17:01.987Z	ff00b2a3-ce59-4182-9345-07b9b4c57e22	INFO	function called postConfirmation @auth-trigger/controller/member
 04:17:01
2019-06-03T04:17:01.990Z	ff00b2a3-ce59-4182-9345-07b9b4c57e22	INFO	******* postConfirmation error ************
 04:17:01
END RequestId: ff00b2a3-ce59-4182-9345-07b9b4c57e22
 04:17:01
REPORT RequestId: ff00b2a3-ce59-4182-9345-07b9b4c57e22	Duration: 6.81 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 230 MB
```
This is an error from third call
```
 04:18:20
START RequestId: 7cfd9c14-b30e-4e3f-bc38-3cfd492698ba Version: $LATEST
 04:18:20
2019-06-03T04:18:20.065Z	8a089af5-59d9-4e02-99a2-8d313c529cfd	INFO	{ TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at _bluebird.default.try.tap.catch (/var/task/src/index.js:32049:13)
 04:18:20
at tryCatcher (/var/task/src/index.js:22823:23)
 04:18:20
at /var/task/src/index.js:59767:41
 04:18:20
at tryCatcher (/var/task/src/index.js:22823:23)
 04:18:20
at Promise._settlePromiseFromHandler (/var/task/src/index.js:114388:31)
 04:18:20
at Promise._settlePromise (/var/task/src/index.js:114445:18)
 04:18:20
at Promise._settlePromise0 (/var/task/src/index.js:114490:10)
 04:18:20
at Promise._settlePromises (/var/task/src/index.js:114566:18)
 04:18:20
at _drainQueueStep (/var/task/src/index.js:114797:12)
 04:18:20
at _drainQueue (/var/task/src/index.js:114790:9)
 04:18:20
at Async.module.exports.Async._drainQueues (/var/task/src/index.js:114806:5)
 04:18:20
at Immediate.Async.drainQueues [as _onImmediate] (/var/task/src/index.js:114676:14)
 04:18:20
at runCallback (timers.js:705:18)
 04:18:20
at tryOnImmediate (timers.js:676:5)
 04:18:20
at processImmediate (timers.js:658:5)
 04:18:20
at process.topLevelDomainCallback (domain.js:120:23) sql: undefined, bindings: undefined }
 04:18:20
2019-06-03T04:18:20.069Z	7cfd9c14-b30e-4e3f-bc38-3cfd492698ba	INFO	function called postConfirmation @auth-trigger/controller/member
 04:18:20
2019-06-03T04:18:20.069Z	7cfd9c14-b30e-4e3f-bc38-3cfd492698ba	INFO	******* postConfirmation error ************
 04:18:20
2019-06-03T04:18:20.069Z	7cfd9c14-b30e-4e3f-bc38-3cfd492698ba	INFO	TypeError: Cannot destructure property `userAttributes` of 'undefined' or 'null'. at postConfirmation (/var/task/src/index.js:160423:9)
 04:18:20
at Runtime.src_postConfirmation [as handler] (/var/task/src/index.js:160485:3)
 04:18:20
at Runtime.handleOnce (/var/runtime/Runtime.js:65:25)
 04:18:20
at process._tickCallback (internal/process/next_tick.js:68:7)
 04:18:20
2019-06-03T04:18:20.071Z	7cfd9c14-b30e-4e3f-bc38-3cfd492698ba	INFO	******* postConfirmation error ************
 04:18:20
2019-06-03T04:18:20.071Z	7cfd9c14-b30e-4e3f-bc38-3cfd492698ba	INFO	{ TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at _bluebird.default.try.tap.catch (/var/task/src/index.js:32049:13)
 04:18:20
at tryCatcher (/var/task/src/index.js:22823:23)
 04:18:20
at /var/task/src/index.js:59767:41
 04:18:20
at tryCatcher (/var/task/src/index.js:22823:23)
 04:18:20
at Promise._settlePromiseFromHandler (/var/task/src/index.js:114388:31)
 04:18:20
at Promise._settlePromise (/var/task/src/index.js:114445:18)
 04:18:20
at Promise._settlePromise0 (/var/task/src/index.js:114490:10)
 04:18:20
at Promise._settlePromises (/var/task/src/index.js:114566:18)
 04:18:20
at _drainQueueStep (/var/task/src/index.js:114797:12)
 04:18:20
at _drainQueue (/var/task/src/index.js:114790:9)
 04:18:20
at Async.module.exports.Async._drainQueues (/var/task/src/index.js:114806:5)
 04:18:20
at Immediate.Async.drainQueues [as _onImmediate] (/var/task/src/index.js:114676:14)
 04:18:20
at runCallback (timers.js:705:18)
 04:18:20
at tryOnImmediate (timers.js:676:5)
 04:18:20
at processImmediate (timers.js:658:5)
 04:18:20
at process.topLevelDomainCallback (domain.js:120:23) sql: undefined, bindings: undefined }
 04:18:20
END RequestId: 7cfd9c14-b30e-4e3f-bc38-3cfd492698ba
 04:18:20
REPORT RequestId: 7cfd9c14-b30e-4e3f-bc38-3cfd492698ba	Duration: 4.67 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 230 MB
```

I established database connection with knex outside function scope, which got auth info from secretsmanager.
```js
try {
  setup(config);
} catch (err) {
  console.log('********** knex initialization error *********');
  console.log(err);
}

export const postConfirmation = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;
  authCtr.postConfirmation(event)
    .then(() => callback(null, event))
    .catch(() => callback(null, event));
};
``` 

```js
// this function is used to get database auth values before setting connection
function createConnectionSettings (connectionSettings) {
  return new Promise(function (resolve, reject) {
    // Use settings if no secret
    if (!connectionSettings.secretName) {
      return resolve({
        ...connectionSettings
      });
    }

    let region = connectionSettings.region;
    let secretName = connectionSettings.secretName;
    let secret;
    let decodedBinarySecret;

    let client = new AWS.SecretsManager({
      region: region
    });

    client.getSecretValue({ SecretId: secretName }, function (err, data) {
      console.log('secret error', err);
      if (err) {
        console.log('secret error', err);
        return reject(err);
      } else {
        if ('SecretString' in data) {
          secret = data.SecretString;
        } else {
          let buff = Buffer.from(data.SecretBinary, 'base64');
          decodedBinarySecret = buff.toString('ascii');
        }
      }

      let connection = JSON.parse(secret || decodedBinarySecret);

      let settings = {
        ...connectionSettings,
        user: connection.username,
        password: connection.password
      };
      return resolve(settings);
    });
  });
}
```
Although I use sdk v2.466.0, it is excluded from bundle using serverless webpack. Let me know if you need more information.

**Comment by vuongngo** [comment]
Indeed, when I use dummy function without doing anything, I still receive invalid JSON from cognito. There is no error from cloudwatch.

**Comment by AllanFly120** [comment]
Hey @vuongngo,

Do you mean you encountered this issue even without using aws-sdk?

**Comment by vuongngo** [comment]
With dummy function, yes! Should I raise support rather than on this thread?

**Comment by AllanFly120** [comment]
@vuongngo I think you should. There's not much we can do from sdk side.

**Comment by vuongngo** [comment]
yeah, I close this issue for now.
