### ISSUE TITLE
Missing credentials in config error even though we have DynamoDB full permisssions role on EC2 this node js app running

### ISSUE THREAD

**Issue by bsdoma** [aws/aws-sdk-js#2695]
**Describe the bug**
Missing credentials in config
    at EnvironmentCredentials.refresh (/app/node_modules/aws-sdk/lib/credentials/environment_credentials.js:79:11)
    at EnvironmentCredentials.get (/app/node_modules/aws-sdk/lib/credentials.js:122:12)
    at getAsyncCredentials (/app/node_modules/aws-sdk/lib/config.js:362:24)
    at Config.getCredentials (/app/node_modules/aws-sdk/lib/config.js:382:9)
    at Request.VALIDATE_CREDENTIALS (/app/node_modules/aws-sdk/lib/event_listeners.js:81:26)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/app/node_modules/aws-sdk/lib/request.js:403:15)
    at Request.send (/app/node_modules/aws-sdk/lib/request.js:367:10)
    at DocumentClient.makeServiceRequest (/app/node_modules/aws-sdk/lib/dynamodb/document_client.js:101:15)
    at DocumentClient.put (/app/node_modules/aws-sdk/lib/dynamodb/document_client.js:297:17)
    at handleYesDecision (/app/services/alexa/request_handler/decision_handler_yes.js:768:30)
    at <anonymous>

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

al003110165:.aws bdoma001$ node -v
v12.1.0

**SDK version number**
v2.437.0

**Comment by ajredniwja** [comment]
Is this still a persisting issue @bsdoma?

Can you please update the SDK and share the minimal code to reproduce if this is still an issue?
