### ISSUE TITLE
AWS S3 selectObjectContent is not retrying after InternalError

### ISSUE THREAD

**Issue by JuanchiRios** [aws/aws-sdk-js#2720]
**Describe the bug**
`selectObjectContent` method from `S3` class is not using the retry mechanism provided by the SDK when S3 returns `InternalError`.

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Node.js 10.X (running in AWS Lambda)

**SDK version number**
v2.440.0

**To Reproduce (observed behavior)**
It's not that simple to reproduce it because it's non-deterministic. Sometimes it's returning the expected answer and other times throw an `internalError` without retrying.

**Expected behavior**
I coded a customBackoff function that it will log the retry's delay and returns the delay in ms. I'm not seeing this logs in Cloudwatch, So, it looks like S3 is not retrying when executing `selectObjectContent`. I've already used this mechanism for other methods (e.g. `getObject`)
Simplify example:
```
const customBackoff =  (retryCount) => {
    console.log(`retry count: ${retryCount}, waiting: 1000ms`);
    return 1000;
  };
const S3 = new AWS.S3({
		      maxRetries: 10,
		      retryDelayOptions: { customBackoff}
		    }));
```
So, before seeing any `internalError`, I was expecting to read this in cloudwatch:
```
retry count: 1, waiting: 1000ms
retry count: 2, waiting: 1000ms
...
retry count: 10, waiting: 1000ms
```
But here is what I'm reading when S3 is returning `internalError`:
```
{
    "errorType": "InternalError",
    "errorMessage": "We encountered an internal error. Please try again.",
    "code": "InternalError",
    "stack": [
        "InternalError: We encountered an internal error. Please try again.",
        "    at parseError (/var/runtime/node_modules/aws-sdk/lib/event-stream/parse-event.js:63:17)",
        "    at parseEvent (/var/runtime/node_modules/aws-sdk/lib/event-stream/parse-event.js:17:19)",
        "    at EventUnmarshallerStream._transform (/var/runtime/node_modules/aws-sdk/lib/event-stream/event-message-unmarshaller-stream.js:26:21)",
        "    at EventUnmarshallerStream.Transform._read (_stream_transform.js:190:10)",
        "    at EventUnmarshallerStream.Transform._write (_stream_transform.js:178:12)",
        "    at doWrite (_stream_writable.js:410:12)",
        "    at writeOrBuffer (_stream_writable.js:394:5)",
        "    at EventUnmarshallerStream.Writable.write (_stream_writable.js:294:11)",
        "    at EventMessageChunkerStream.ondata (_stream_readable.js:689:20)",
        "    at EventMessageChunkerStream.emit (events.js:189:13)"
    ],
    "name": "InternalError"
}
```

**Screenshots**
Using the `Show preview file` in the UI, it's returning the expected responses sometimes and returning `InternalError` other times.

![Screenshot from 2019-06-13 17-03-37](https://user-images.githubusercontent.com/11356439/59515997-c43bc200-8e96-11e9-96c1-e9c32d12c0c0.png)

![Screenshot from 2019-06-13 17-03-47](https://user-images.githubusercontent.com/11356439/59516016-caca3980-8e96-11e9-899d-d756cfaa2e13.png)

**Additional context**

Initialization
```
AWS.config.apiVersions = {
  s3: '2006-03-01'
}
AWS.config.region = process.env.REGION || 'us-east-2';// us-east-1 in this case

// Custom backoff function
const defaultDelays =  [[300, 500], [500, 1000], [1000, 2000],  [2000, 3000], [3000, 4000],
  [4000,5000], [5000, 6000], [6000, 7000] ,[7000, 8000], [8000,10000]];
function exponentialBackoffCreator(delays = defaultDelays) {
  /*
  * Implementation took from official Mozilla page
  * see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random
  */

  const randomInclusive = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
  const minDelay = (retryCount) => delays[retryCount][0];
  const maxDelay = (retryCount) => delays[retryCount][1];

  return (retryCount) => {
    const delay = randomInclusive(minDelay(retryCount), maxDelay(retryCount));
    console.log(`retry count: ${retryCount}, waiting: ${delay}`);
    return delay;
  };
}

//Instantiating S3 client
const S3 = new AWS.S3({
		      maxRetries: 10,
		      retryDelayOptions: { customBackoff: exponentialBackoffCreator()}
		    }));
```

Auxilary function to create selectObjectContent's params
```
const RECORD_DELIMITER = '\n';
/**
 * Parameter object used to initiate an S3 SQL query on a parquet file. Returns results as a
 * CSV with comma field separators and newline row separators.
 *
 * @param {string} Bucket
 * @param {string} Key - The S3 object key that references the target parquet file
 * @param {string} query - The SQL query to retrieve the data
 * @returns {*}
 */
function csvSelectParams(Bucket: string, Key: string, query: string) {
  return {
    Key,
    Bucket,
    Expression: query,
    ExpressionType: 'SQL',
    InputSerialization: {
      CompressionType: 'NONE',
      Parquet: {}
    },
    OutputSerialization: {
      CSV: {
        FieldDelimiter: ',',
        QuoteCharacter: '"',
        QuoteEscapeCharacter: '"',
        QuoteFields: 'ASNEEDED',
        RecordDelimiter: RECORD_DELIMITER
      }
    },
    RequestProgress: {
      Enabled: false
    }
  };
}
```

Invoking selectObjectContent
```
//Consuming parquet file in S3 using selectObjectContent

const results = [];
await S3.selectObjectContent(params)
    .promise()
    .then(data => {
      return new Promise((resolve, reject) => {
        const eventStream = data.Payload;

        eventStream.on('data', ({ Records, End }) => {
          if (Records) {
            results.push(Records.Payload)
          } else if (End) {
            debug(`Retrieved ${retrievalCount} records from S3://${bucket}/${s3Key}`);
            resolve(retrievalCount);
          }
        });
        eventStream.on('error', reject);
      });
    })
    .catch(err => {
      if (err.code === 'NoSuchKey') {
        console.info(`Ignoring an S3 query on an invalid or missing key: ${s3Key}`);
        return Promise.resolve(0);
      }
      console.error(`Error reading invalid parquet file: ${s3Key}: ${err}`);
      throw err;
    });
}

```

**Comment by JuanchiRios** [comment]
Since anyone seems to be responding this, I'm leaving the workaround in case that someone is facing the same issue.
Basically, it's just adding an if condition to the catch clause and an extra default parameter to the method.

This is what it was added:

```
if (retryCount > 0) {
	console.log(`Retrying... Number of retries remaining: ${retryCount - 1}`);
	return selectFromS3(bucket, s3Key, query, numColumns, recordStream, retryCount - 1);
```
This is a simpler example of my solution (removing unnecessary code):
```
const selectFromS3 = async ( params, retryCount = 3) => {
	const totalCsvRows =[];
	try {
		const result = await S3.selectObjectContent(params).promise();
		const events = result.Payload;
		for await (const event of events) {
	      if (event.Records) {
	        const csvRows = event.Records.Payload.split(RECORD_DELIMITER);
	        csvRows.forEach(row => if (row) totalCsvRows.push(row));
	      }
	    }
	    return totalCsvRows;
  } catch (err) {
    if (err.code === 'NoSuchKey') {
      console.info(`Ignoring an S3 query on an invalid or missing key: ${params.s3Key}`);
      return [];
    } else if (err.code === 'InternalError') {
    	if (retries > 0) {
			console.log(`Retring... Number of retries remaining: ${retryCount - 1}`);
        	return selectFromS3(params, retries - 1);
     	} else {
			throw new Error(`maximum number of attempts reached for: ${params.s3Key}`)
	  	}
	}
    console.error(`Error reading invalid parquet file: ${params.s3Key}: ${err}`);
    throw err;
  }
}

```


This is how my method is looking right now:
```
async function selectFromS3(
  bucket: string,
  s3Key: string,
  query: string,
  numColumns: number,
  recordStream: Function,
  retryCount: number = 3
) {
	const results = [];
	return await S3.selectObjectContent(params)
	    .promise()
	    .then(data => {
	      return new Promise((resolve, reject) => {
	        const eventStream = data.Payload;
	
	        eventStream.on('data', ({ Records, End }) => {
	          if (Records) {
	            results.push(Records.Payload)
	          } else if (End) {
	            debug(`Retrieved ${retrievalCount} records from S3://${bucket}/${s3Key}`);
	            resolve(retrievalCount);
	          }
	        });
	        eventStream.on('error', reject);
	      });
	    })
	    .catch(err => {
	      if (err.code === 'NoSuchKey') {
	        console.info(`Ignoring an S3 query on an invalid or missing key: ${s3Key}`);
	        return Promise.resolve(0);
	      }
	      if (err.code === 'InternalError') {
	        if (retryCount > 0) {
	          console.log(`Retrying... Number of retries remaining: ${retryCount - 1}`);
	          return selectFromS3(bucket, s3Key, query, numColumns, recordStream, retryCount - 1);
	        }
	      }
	      console.error(`Error reading invalid parquet file: ${s3Key}: ${err}`);
	      throw err;
	    });
```

**Comment by ajredniwja** [comment]
Hey @JuanchiRios,

Thank-you for reaching out. If you are not facing this problem anymore, I would like to close the issue. You can reach out if you still have any questions. Additionally any PRs will be welcomed as well.

**Comment by JuanchiRios** [comment]
@ajredniwja I'm using the workaround that I suggested but I guess that the issue is still happening. 
Pretty sad to get a response after 4 months :disappointed:

**Comment by ajredniwja** [comment]
@JuanchiRios, I will try to reproduce this, is it possible for you to share a repro repository for the issue so we can have our hands on it?

**Comment by JuanchiRios** [comment]
@ajkerr Nope, sorry. That's why I add the different pieces of code. I hope it helps.
