### ISSUE TITLE
DynamoDB.createTable params not accurate

### ISSUE THREAD

**Issue by pdot86** [aws/aws-sdk-js#2734]
**Describe the bug**
In both the [SDK documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#createTable-property) and the [API Reference](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#API_CreateTable_RequestSyntax) it appears as though the params for createTable will accept a key of BillingMode with a string value, and a key of Tags with an array value; however, when including either one of these keys an UnexpectedParameter error is thrown (Unexpected key 'Tags' found in params).

Additionally it will throw a MissingRequiredParameter error when you do not include the "ProvisionedThroughput" key (if you were to create a PAY_PER_REQUEST or on demand table), when the docs say: 
> "If you set BillingMode as PROVISIONED, you must specify this property. If you set BillingMode as PAY_PER_REQUEST, you cannot specify this property."

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
```
{ 
  UnexpectedParameter: Unexpected key 'Tags' found in params
    at ParamValidator.fail (/app/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/app/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/app/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/app/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/app/node_modules/aws-sdk/lib/event_listeners.js:114:42)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/app/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /app/node_modules/aws-sdk/lib/event_listeners.js:74:9
    at finish (/app/node_modules/aws-sdk/lib/config.js:315:7)
    at /app/node_modules/aws-sdk/lib/config.js:333:9
  message: "Unexpected key 'Tags' found in params",
  code: 'UnexpectedParameter',
  time: 2019-06-20T19:44:01.229Z
}
```

**SDK version number**
v2.63.0

**To Reproduce (observed behavior)**
```
// Scenario A
// ------------------
// Expectation: Create a PAY_PER_REQUEST table
//
// Results: 
//      MissingRequiredParameter: Missing required key 'ProvisionedThroughput' in params
//      UnexpectedParameter: Unexpected key 'BillingMode' found in params
//      UnexpectedParameter: Unexpected key 'Tags' found in params
// 
// NOTES: Docs say: "If you set BillingMode as PROVISIONED, you must specify 
//                   this property. If you set BillingMode as PAY_PER_REQUEST, 
//                   you cannot specify this property."

const dynamodb = new AWS.DynamoDB();

dynamodb.createTable({
  TableName: 'example',
  BillingMode: 'PAY_PER_REQUEST',
  AttributeDefinitions: [
    {
      AttributeName: "id",
      AttributeType: "S"
    }
  ],
  KeySchema: [
    {
      AttributeName: "id",
      KeyType: "HASH"
    }
  ],
  StreamSpecification: {
    StreamEnabled: false
  },
  Tags: [
    {
      'Key': 'MYTAG',
      'Value': 'myvalue'
    }
  ]
}, (err, data) => {
  if (err) {
    console.log(err);
  } else {
    console.log(data);
  }
});
```

```
// Scenario B
// ------------------
// Expectation: Create a PROVISIONED table with Tags
//
// Results: 
//       UnexpectedParameter: Unexpected key 'Tags' found in params

dynamodb.createTable({
  TableName: 'example',
  AttributeDefinitions: [
    {
      AttributeName: "id",
      AttributeType: "S"
    }
  ],
  KeySchema: [
    {
      AttributeName: "id",
      KeyType: "HASH"
    }
  ],
  StreamSpecification: {
    StreamEnabled: false
  },
  ProvisionedThroughput: {
    ReadCapacityUnits: 5,
    WriteCapacityUnits: 5
  },
  Tags: [
    {
      'Key': 'MYTAG',
      'Value': 'myvalue'
    }
  ]
}, (err, data) => {
  if (err) {
    console.log(err);
  } else {
    console.log(data);
  }
});
```

**Expected behavior**
It should create a table that is set to on demand, or create a table with the specified tags.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by AllanFly120** [comment]
Hey @pdot86,

You are using SDK at `2.63.0`. However, the `Tag` is available only since `2.443.0` and `BillingMode` is only available from `2.365.0`. You can have a try with the newest version SDK.
