### ISSUE TITLE
What does it mean: Error: write EPROTO

### ISSUE THREAD

**Issue by leonetosoft** [aws/aws-sdk-js#2766]
I have a client that is having difficulty sending data to S3 first I get the error:
```
[10/07/2019 - 10:33]: { Error: write EPROTO
    at WriteWrap.afterWrite [as oncomplete] (net.js:833:14)
  message: 'write EPROTO',
  errno: 'EPROTO',
  code: 'NetworkingError',
  syscall: 'write',
  region: 'us-east-1',
  hostname: 'upaqui.s3.amazonaws.com',
  retryable: true,
  time: 2019-07-10T14:33:32.282Z,
  statusCode: 400 }
```

Subsequently I receive:

```
[10/07/2019 - 10:45]: { RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
    at Request.extractError (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\services\s3.js:585:35)
    at Request.callListeners (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\USUARIO\AppData\Local\Programs\upaki-sync-ui\resources\app.asar\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
  message:
   'Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.',
  code: 'RequestTimeout',
  region: null,
  time: 2019-07-10T14:45:40.349Z,
  requestId: '58F44DDDB3BACD76',
  extendedRequestId:
   'gFR8eq5DeHu0pU4THaZQcGBFVPaLXBAhQcEHHi62Eq/kYUbSfc3jsLLHauYgxoKTKgiNzjf7VB0=',
  cfId: undefined,
  statusCode: 400,
  retryable: true }
```

**Is the issue in the browser/Node.js?**
NodeJS

**Details of the browser/Node.js version**
Node Version: 10.2.0
--
**SDK version number**
Version: 2.213.1

**Comment by trivikr** [comment]
@eonetosoft Can you share minimal code to reproduce this issue?

**Comment by leonetosoft** [comment]
@trivikr I can not reproduce the problem, it happens in occasional clients, the Upload never completes, I'm using MultiPartUpload.

**Comment by ajredniwja** [comment]
Hey @leonetosoft,

I believe this is a duplicate issue similar to #1597. Can you try following the [instructions](https://github.com/aws/aws-sdk-js/issues/1597#issuecomment-311163032-permalink) provided in the comments? Please reach out if you have further questions.
