### ISSUE TITLE
AWS Personalize PutEvents - Error parsing properties json

### ISSUE THREAD

**Issue by keroic** [aws/aws-sdk-js#2773]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I try to invoke AWS Personalize putEvents API call and it response me the error as follows. And, I have tried to set the IAM Policy to allow "*" on resources for the User to use PutEvents Action, sounds like not related to the IAM.

```console
Error parsing properties json, InvalidInputException: Error parsing properties json
    at Object.extractError (/usr/src/app/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/src/app/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/src/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/src/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/src/app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/request.js:685:12)
```

Here is the sample Params Object to pass to the API, (Remarks: Tracking ID was fake)
```json
{
  "eventList": [
    {
      "eventType": "view",
      "properties": "{\"itemId\": \"16\"}",
      "sentAt": 1563160514
    }
  ],
  "sessionId": "1563160514151",
  "trackingId": "12345678-1234-1234-1234-123456789012",
  "userId": "1"
}
```

EDIT:
* (keroic): eventList[].properties was JSON Stringify value, seems the backslash was removed when submit, please note
* (trivikr): Added console and json block, beautified json

**Comment by hideokamoto** [comment]
Hi. I've got a similar error by using the SDK.

## Environment

```
$ node -v
v10.16.0

$ npm -v 
6.9.0

$ cat package.json | jq .dependencies | grep aws-sdk
  "aws-sdk": "^2.517.0",
```

## DatasetSchema

```json
{
	"name": "Interactions",
	"namespace": "com.amazonaws.personalize.schema",
	"type": "record",
	"fields": [
		{
			"name": "USER_ID",
			"type": "string"
		},
		{
			"name": "ITEM_ID",
			"type": "string"
		},
		{
			"name": "EVENT_TYPE",
			"type": "string"
		},
		{
			"name": "EVENT_VALUE",
			"type": "float"
		},
		{
			"name": "TIMESTAMP",
			"type": "long"
		},
		{
			"name": "SESSION_ID",
			"type": "string"
		}
	],
	"version": "1.0"
}
```

## Codes

### 1st try -> ERROR
```typescript
import {
  PersonalizeEvents,
} from 'aws-sdk'
import { v4 } from 'uuid'
import moment from 'moment'

const trackEvent = async () => {
  const client = new PersonalizeEvents({
    region: 'ap-northeast-1'
  })
  const params: PersonalizeEvents.Types.PutEventsRequest = {
    trackingId: 'xxx-xxx-xxx-xxx',
    userId: '1',
    sessionId: v4(),
    eventList: [{
      eventId: v4(),
      sentAt: moment().toDate(),
      eventType: 'rating',
      properties: JSON.stringify({
        itemId: '1',
        eventValue: 1.0
      })
    }]
  }
  console.log(params)
  const result = await client.putEvents(params).promise()
  console.log(result)
  return
}
trackEvent()
```

#### Result

```bash
$  ./node_modules/.bin/ts-node libs/index.ts 
{ trackingId: '52c88f57-7d7f-4941-8396-4c6a7434ec0d',
  userId: '1',
  sessionId: '4d58f851-6c8e-4ae8-8038-56f86f5f40ee',
  eventList:
   [ { eventId: 'd6ed382a-999e-4728-9895-98612a959506',
       sentAt: 2019-08-25T14:57:30.307Z,
       eventType: 'rating',
       properties: '{"itemId":"1","eventValue":1}' } ] }

{ InvalidInputException: Error parsing properties json
    at Object.extractError (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/develop/sandbox/aws-playground/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Error parsing properties json',
  code: 'InvalidInputException',
  time: 2019-08-25T14:57:30.537Z,
  requestId: 'd6766b7e-69b0-4889-83cf-18171e509b4a',
  statusCode: 400,
  retryable: false,
  retryDelay: 65.34243647640349 }
```

### 2nd try -> ERROR
```typescript
import {
  PersonalizeEvents,
} from 'aws-sdk'
import { v4 } from 'uuid'
import moment from 'moment'

const trackEvent = async () => {
  const client = new PersonalizeEvents({
    region: 'ap-northeast-1'
  })
  const params: PersonalizeEvents.Types.PutEventsRequest = {
    trackingId: 'xxx-xxx-xxx-xxx',
    userId: '1',
    sessionId: v4(),
    eventList: [{
      eventId: v4(),
      sentAt: moment().toDate(),
      eventType: 'rating',
      properties: {
        itemId: '1',
        eventValue: 1.0
      }
    }]
  }
  console.log(params)
  const result = await client.putEvents(params).promise()
  console.log(result)
  return
}
trackEvent()
```

#### Result

```bash
$  ./node_modules/.bin/ts-node libs/index.ts 

/Users/develop/sandbox//node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
libs/index.ts:34:7 - error TS2322: Type '{ itemId: string; eventValue: number; }' is not assignable to type 'string'.

34       properties: {
         ~~~~~~~~~~

  node_modules/aws-sdk/clients/personalizeevents.d.ts:37:5
    37     properties: EventPropertiesJSON;
           ~~~~~~~~~~
    The expected type comes from property 'properties' which is declared here on type 'Event'
```

### Final Try -> Success

```typescript
import {
  PersonalizeEvents,
} from 'aws-sdk'
import { v4 } from 'uuid'
import moment from 'moment'

const trackEvent = async () => {
  const client = new PersonalizeEvents({
    region: 'ap-northeast-1'
  })
  const params: PersonalizeEvents.Types.PutEventsRequest = {
    trackingId: 'xxx-xxx-xxx-xxx',
    userId: '1',
    sessionId: v4(),
    eventList: [{
      eventId: v4(),
      sentAt: moment().toDate(),
      eventType: 'rating',
      properties: {
        itemId: '1',
        eventValue: 1.0
      } as any as PersonalizeEvents.Types.EventPropertiesJSON
    }]
  }
  console.log(params)
  const result = await client.putEvents(params).promise()
  console.log(result)
  return
}
trackEvent()
```


#### Result

```bash
$  ./node_modules/.bin/ts-node libs/index.ts 
{ trackingId: '52c88f57-7d7f-4941-8396-4c6a7434ec0d',
  userId: '1',
  sessionId: 'dcaf9abd-db3b-4793-a43e-6bb9ce6a1f9a',
  eventList:
   [ { eventId: 'b938051a-bf9c-4e3c-8c9a-b0453bee46e5',
       sentAt: 2019-08-25T14:59:26.639Z,
       eventType: 'rating',
       properties: [Object] } ] }
{}
```

## Problems
I think the `PersonalizeEvents.Event` should be the following.

### Wrong

```typescript
declare namespace PersonalizeEvents {
  export type _Date = Date;
  export interface Event {
    /**
     * An ID associated with the event. If an event ID is not provided, Amazon Personalize generates a unique ID for the event. An event ID is not used as an input to the model. Amazon Personalize uses the event ID to distinquish unique events. Any subsequent events after the first with the same event ID are not used in model training.
     */
    eventId?: StringType;
    /**
     * The type of event. This property corresponds to the EVENT_TYPE field of the Interactions schema.
     */
    eventType: StringType;
    /**
     * A string map of event-specific data that you might choose to record. For example, if a user rates a movie on your site, you might send the movie ID and rating, and the number of movie ratings made by the user. Each item in the map consists of a key-value pair. For example,  {"itemId": "movie1"}   {"itemId": "movie2", "eventValue": "4.5"}   {"itemId": "movie3", "eventValue": "3", "numberOfRatings": "12"}  The keys use camel case names that match the fields in the Interactions schema. The itemId and eventValue keys correspond to the ITEM_ID and EVENT_VALUE fields. In the above example, the eventType might be 'MovieRating' with eventValue being the rating. The numberOfRatings would match the 'NUMBER_OF_RATINGS' field defined in the Interactions schema.
     */
    properties: EventPropertiesJSON;
    /**
     * The timestamp on the client side when the event occurred.
     */
    sentAt: _Date;
  }
  export type EventList = Event[];
  export type EventPropertiesJSON = string;
...
```


### OK

```typescript
declare namespace PersonalizeEvents {
  export type _Date = Date;
  export interface Event {
    /**
     * An ID associated with the event. If an event ID is not provided, Amazon Personalize generates a unique ID for the event. An event ID is not used as an input to the model. Amazon Personalize uses the event ID to distinquish unique events. Any subsequent events after the first with the same event ID are not used in model training.
     */
    eventId?: StringType;
    /**
     * The type of event. This property corresponds to the EVENT_TYPE field of the Interactions schema.
     */
    eventType: StringType;
    /**
     * A string map of event-specific data that you might choose to record. For example, if a user rates a movie on your site, you might send the movie ID and rating, and the number of movie ratings made by the user. Each item in the map consists of a key-value pair. For example,  {"itemId": "movie1"}   {"itemId": "movie2", "eventValue": "4.5"}   {"itemId": "movie3", "eventValue": "3", "numberOfRatings": "12"}  The keys use camel case names that match the fields in the Interactions schema. The itemId and eventValue keys correspond to the ITEM_ID and EVENT_VALUE fields. In the above example, the eventType might be 'MovieRating' with eventValue being the rating. The numberOfRatings would match the 'NUMBER_OF_RATINGS' field defined in the Interactions schema.
     */
    properties: EventPropertiesJSON;
    /**
     * The timestamp on the client side when the event occurred.
     */
    sentAt: _Date;
  }
  export type EventList = Event[];
  export type EventPropertiesJSON = {[key: string]: any};
...
```

**Comment by naveensky** [comment]
@hideokamoto - I followed your guidelines to typecast eventList and it worked 👍. Though, I am getting an error which says `Invalid trackingId ccc57531-49c7-4574-95a6-XXXXXXX in account XXXX`. 

I am assuming that we generate the `trackingId` from AWS console and then use it, right?

**Comment by ajredniwja** [comment]
@keroic apologies for late reply, is this still a persisting issue?

Can you please use the [issue template](https://github.com/aws/aws-sdk-js/issues/new/choose) or answer the questions found in the template.

**Comment by AllanFly120** [comment]
@naveensky @naveensky Please refer to my comment: https://github.com/aws/aws-sdk-js/pull/2821#issuecomment-600859520 for the root cause. I will reopen this issue as it still persists

**Comment by AllanFly120** [comment]
After discussing with the team, we decide that we won't prioritize the support for this feature by SDK dev team. Because it touches relatively small subset of services and only affects TypeScript users. Currently the workaround proposed by @hideokamoto works fine.
However, this issue is already supported in [new V3 SDK](https://github.com/aws/aws-sdk-js-v3), which recently released beta version, and we have spent a lot of time optimizing it. It offers many advantages over current V2 SDK, you should try it if you can.
