### ISSUE TITLE
Missing region in config after request success

### ISSUE THREAD

**Issue by Awaydrasil** [aws/aws-sdk-js#2782]
Hi,
After a timeout which is about 20 secondes, no matter if I'm doing HTTP requests to DynamoDB or not, my app crashes and says.

```
C:\Users\john\Documents\projects\node_api-js\node_modules\q\q.js:155
                throw e;
                ^

Error [ConfigError]: Missing region in config
    at Request.VALIDATE_REGION (C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\event_listeners.js:92:45)
    at Request.callListeners (C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at callNextListener (C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\event_listeners.js:86:9
    at finish (C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\config.js:350:7)
    at C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\config.js:392:9
    at Object.<anonymous> (C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\credentials\credential_provider_chain.js:111:13)
    at Object.arrayEach (C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\util.js:493:32)
    at resolveNext (C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\credentials\credential_provider_chain.js:110:20)
    at C:\Users\john\Documents\projects\node_api-js\node_modules\dynamoose\node_modules\aws-sdk\lib\credentials\credential_provider_chain.js:126:13 {
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2019-07-24T07:39:59.698Z
}
```

If I'm doing HTTP requests, those are successful, and send me back fetched datas in Dynamo

This is my _server.js_ : 

```
    const express = require('express');
    const config = require('./config');
    const cors = require('cors');
    const createError = require('http-errors');
    const bodyParser = require('body-parser');
    const app = express();

    // parse requests
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({ extended: false }));
    
    //Enable CORS for all HTTP methods
    app.use(cors());
    
    // Routes
    require('./routes/survey.route.js')(app);
    require('./routes/user.route.js')(app);
    
    // Handle defaut request without any route or params
    app.get('/', (request, response) => {
         response.send("Welcome to my API !");
    });
    
    // Listen on port 8080 for connections
    app.listen(config.serverPort, (err) => {
        if (err) {
            return console.log('something bad happened', err);
        }

        console.log(`server is listening on ${config.serverPort}`);
    });
    
    // catch 404 and forward to error handler
    app.use(function(req, res, next) {
        console.log(req);
        next(createError(404));
    });
    module.exports = app;
```

Each of my routes' requests include the file _database.js_

Which has code :

```
    // Configuring the database
    const AWS = require('aws-sdk');
    const config = require('./config');
    
    AWS.config.update({
        accessKeyId: config.aws_accessKeyId,
        secretAccessKey: config.aws_secretAccessKey,
        region: config.aws_region
    });
```

And this is my _config.js_ :
```
    module.exports = {
        baseUrl: '/api',
        serverPort: 8080,
        aws_accessKeyId: 'XXXXX',
        aws_secretAccessKey: 'XXXXX',
        aws_region: "us-east-2"
    };

    module.exports = AWS;
```

I tried to add 
```
const AWS = require('aws-sdk');

AWS.config.update({
        accessKeyId: config.aws_accessKeyId,
        secretAccessKey: config.aws_secretAccessKey,
        region: config.aws_region
    });
```
at the very beginning of _server.js_, after **const app = express()** but I still have the same issue.

It isn't a local config issue because if the server is started on localhost or deployed on AWS elasticbean, both my servers keep crashing

**EDIT :** fixed by deleting dynamoose, it was causing the bug

**Comment by trivikr** [comment]
@Awaydrasil Please follow [bug report template](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug+report&template=---bug-report.md&title=) while creating issues.
