### ISSUE TITLE
crash when parsing `~/.aws/config` without profile prefix

### ISSUE THREAD

**Issue by cyrfer** [aws/aws-sdk-js#2796]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Applications like `amplify init` can crash when using the `ini-loader` if `~/.aws/config` contains profile names that are identical except for the prefix `profile `.

The `ini-loader` will crash if `~/.aws/config` contains the following:
```
[default]
output=json
region=us-west-2

[profile default]
output=json
region=us-west-2
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.3.1

**SDK version number**
`aws-sdk@2.474.0`

**To Reproduce (observed behavior)**
1. add the example above to `~/.aws/config`
2. make an application folder for `amplify` to, e.g. `npx create-react-app amplify-test`
3. `cd amplify-test`
4. `amplify init` and answer questions.
5. observe crash.

**Expected behavior**
I expect the code not to crash.

**Screenshots**
This is the CLI output from `amplify init`:
```
✖ Root stack creation failed
init failed
TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at /Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:11:14
    at Array.forEach (<anonymous>)
    at IniLoader.parseFile (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader
.js:8:26)
    at IniLoader.loadFrom (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at Config.region (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/node_loader.js:98:36)
    at Config.set (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:477:39)
    at Config.<anonymous> (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:312:12)
    at Config.each (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/util.js:507:32)
    at new Config (/Users/jkgrant/.nvm/versions/node/v12.3.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/config.js:311:19)
```

**Comment by cyrfer** [comment]
Please consider the pull request https://github.com/aws/aws-sdk-js/pull/2797/commits/b0fca6f0727733c7e36f7e3a3cab58f0af701830

**Comment by ajredniwja** [comment]
Hey @cyrfer,

Thank-you for reaching out, I was not able to reproduce it, I have the following in my config file and I get create complete after ```amplify init```

```[default]
region=us-west-2
output=json

[profile default]]
region=us-west-2
output=json
``` 

can you try updating the SDK  and see if its still an issue?

**Comment by cyrfer** [comment]
@ajredniwja  I'm not sure if you made a typo above, but your profile does not look like what I said was required to reproduce it. You are missing `[default]` at the top, which is added by some AWS CLI operations.

**Comment by ajredniwja** [comment]
@cyrfer,

I apologize for the typo, yes ```[default]``` is there in the config file, however ```[profile default]]``` is a typo in my config file, I will look into it and and the PR and get back to you.

**Comment by cyrfer** [comment]
I finally found which tool inserts the `profile` word into the `~/.aws/config` file. It's the AWS CLI, with this kind of usage:
```bash
aws configure --profile default
aws configure --profile dev
aws configure --profile etc
```

All the profiles in my `~/.aws/config` file look like `[profile name]` rather than only `[name]` EXCEPT `[default]`.
