### ISSUE TITLE
RDS Signer throws an uncatchable exception if passed invalid credentials and a callback

### ISSUE THREAD

**Issue by ixalon** [aws/aws-sdk-js#2829]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The RDS Signer throws an uncatchable exception if passed invalid credentials and a callback function rather than calling the callback with the underlying error.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Not lambda

**Details of the browser/Node.js version**
`v10.12.0`

**SDK version number**
`2.519.0`

**To Reproduce (observed behavior)**
```
const { CognitoIdentityCredentials } = require("aws-sdk");
const { RDS } = require("aws-sdk");

const credentials = new CognitoIdentityCredentials(
  {
    IdentityPoolId: 'eu-central-1:0',
    Logins: []
  },
  {
    region: "eu-central-1"
  }
);

const signer = new RDS.Signer({
  credentials,
  region: 'eu-central-1',
  hostname: 'rds.example.com',
  port: 3306,
  username: 'username'
});

signer.getAuthToken({}, function(err, data) {
  if (err) {
    console.log('Caught error:', err);
  } else {
    console.log('Token:', data);
  }
});
```

When run gives the output:
```
/Users/chris/tbone/beamly-flywheel/packages/beamly-flywheel-api/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'undefined' of undefined
    at Service.apiCallEvent (/Users/chris/.../node_modules/aws-sdk/lib/service.js:294:45)
    at Request.API_CALL (/Users/chris/tbone/beamly-flywheel/packages/beamly-flywheel-api/node_modules/aws-sdk/lib/service.js:429:31)
    at Request.callListeners (/Users/chris/.../node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/chris/.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/chris/.../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/chris/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/chris/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/chris/.../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/chris/.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/chris/.../node_modules/aws-sdk/lib/request.js:685:12)
```

**Expected behavior**
The callback function should be called with the underlying error, giving the expected output:

```
Caught error: { ResourceNotFoundException: IdentityPool 'eu-central-1:0' not found.
    at Request.extractError (/Users/chris/.../node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/chris/.../node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/chris/.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/chris/.../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/chris/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/chris/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/chris/.../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/chris/.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/chris/.../node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/chris/.../node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Additional context**

This is because https://github.com/aws/aws-sdk-js/blob/master/lib/rds/signer.js#L11-L14 does not specify a map of `operations`, yet https://github.com/aws/aws-sdk-js/blob/master/lib/service.js#L293 assumes it is present.

It can be fixed by changing:
```
var api = {
    signatureVersion: 'v4',
    signingName: 'rds-db'
};
```

To:
```
var api = {
    signatureVersion: 'v4',
    signingName: 'rds-db',
    operations: {}
};
```

**Comment by AllanFly120** [comment]
Hey @ixalon Thanks a lot for bringing this up. I can confirm this is a bug. I have approved your PR. Thanks a lot for investigating and fixing this!
