### ISSUE TITLE
CloudFront invalidation doesnt work for javaScript API

### ISSUE THREAD

**Issue by AdletAzhibek** [aws/aws-sdk-js#2841]
err while invalidation
```
{ TypeError: Cannot set property 'Timestamp' of undefined
    at addAuthorization (/opt/nodejs/backend/node_modules/aws-sdk/lib/signers/v2.js:14:24)
    at /opt/nodejs/backend/node_modules/aws-sdk/lib/event_listeners.js:236:18
    at finish (/opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:349:7)
    at /opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:367:9
    at Credentials.get (/opt/nodejs/backend/node_modules/aws-sdk/lib/credentials.js:127:7)
    at getAsyncCredentials (/opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:361:24)
    at Config.getCredentials (/opt/nodejs/backend/node_modules/aws-sdk/lib/config.js:381:9)
    at Request.SIGN (/opt/nodejs/backend/node_modules/aws-sdk/lib/event_listeners.js:212:22)
    at Request.callListeners (/opt/nodejs/backend/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at callNextListener (/opt/nodejs/backend/node_modules/aws-sdk/lib/sequential_executor.js:96:12) retryDelay: 67.35441836652538 } 

/aws-sdk/lib/signers/v2.js:14:24 is following
![v2js](https://user-images.githubusercontent.com/55197950/64706021-b10ab380-d4d2-11e9-9f9e-dafc3132a2c5.PNG)
```

my code snipped is:

![v2js](https://user-images.githubusercontent.com/55197950/64706746-d0eea700-d4d3-11e9-8fa1-23457653b49a.PNG)

**Comment by ajredniwja** [comment]
Hey @AdletAzhibek,

Thank-you reaching out, can you please follow the [issue tempelate](https://github.com/aws/aws-sdk-js/issues/new/choose).
