### ISSUE TITLE
S3 Upload Error (NetworkingError)

### ISSUE THREAD

**Issue by pikaphu** [aws/aws-sdk-js#2842]
AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible
----------------------------------------------------------------------------------------------------

✅ NOW, I fix this problem by remove `upload `from `XMLHttpRequest`  
modify this:  `m.upload.addEventListener` to `m.addEventListener`

  and for unpacked code (no need to change this if it already work) : `xhr.upload.addEventListener('progress'`  to `xhr.addEventListener('progress' `

And it now works. 😄 

----------------------------------------------------------------------------------------------------
  
- 🆘  **My problem** is when I try to use upload function of s3, it always error at 
`NetworkingError: m.upload.addEventListener is not a function` 
...
_(full error detail)_  
``` 
NetworkingError: m.upload.addEventListener is not a function
    at t.constructor.t.constructor.handleRequest (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:1:339199)
    at n (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:15:25878)
    at constructor.<anonymous> (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:15:26121)
    at constructor.callListeners (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:1:1103983)
    at constructor.emit (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:1:1103722)
    at constructor.emitEvent (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:8:27638)
    at constructor.e (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:8:23271)
    at r.runTo (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:15:762031)
    at http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:15:762236
    at constructor.<anonymous> (http://localhost:9526/static/js/chunk-5eb94f49.32ca7127.js:8:23481)
```
❗️  _update:_

--  at `aws-sdk.min.js` I found that it error on this line: (this error)

`m.upload.addEventListener("progress",function(e){u.emit("sendProgress",e)})`

--   Then I track it at` aws-sdk.js` I think this is unpacked code of above: (but this work just find)
```
xhr.upload.addEventListener('progress', function (evt) {
      emitter.emit('sendProgress', evt);
    });  
```

- ❓ But it error only when I deploy with **Production** built (vue-cli-service build) . 
If it run with development build it work fine 😕 . So I'm not sure this error occurred because of aws-sdk or my VueJS. Anyone have problem like this? Any solution? 

- 👨‍💻 I'm using VuejS + element.eleme.io (latest version) with AWS SDK for JavaScript v2.524.0 (and already try with latest verison but still not work)  
- my code:
```
const AWS = require('aws-sdk')
function uploadToS3(file) {
  const s3bucket = new AWS.S3({
    accessKeyId: IAM_USER_KEY,
    secretAccessKey: IAM_USER_SECRET,
    Bucket: BUCKET_NAME
  })
  s3bucket.createBucket(function() {
    var params = {
      Bucket: BUCKET_NAME,
      Key: file.name,
      Body: file.data
    }
    s3bucket.upload(params, function(err, data) { // <--- err occurred when build Production
      if (err) { 
        console.log('error in callback')
        console.log(err)
      }
      console.log('success')
      console.log(data)
    })
  })
}
```

*note: I'm just newbie in front-end. if I can't explain clearly, please forgive me.

**Comment by pikaphu** [comment]
Hi, I just want to update my solution. I found the REAL cause that is my Vue porject using "mockXHR" and it modify my XMLHttpRequest, So it make prototype upload not working too.

And I just fix mockXHR and it work now. 

Not relate with AWS-SDK-JS. Sorry for my noobs.
