### ISSUE TITLE
Budgets service paginated API calls do not support pagination

### ISSUE THREAD

**Issue by nhinds** [aws/aws-sdk-js#2862]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The `describeBudgets`, `describeBudgetPerformanceHistory`, `describeNotificationsForBudget`, and `describeSubscribersForNotification` methods in the AWS.Budgets service all return a `NextToken` in their reponse for pagination, but the SDK does not support using this token for pagination with `Request.eachItem`, `Request.eachPage`, `Request.isPageable`, `Response.hasNextPage`, or `Response.nextPage`.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.7.0

**SDK version number**
v2.535.0

**To Reproduce (observed behavior)**
Calling `.isPageable()`:
```
const AWS = require('aws-sdk');
console.log(new AWS.Budgets().describeBudgets().isPageable());
console.log(new AWS.Budgets().describeBudgetPerformanceHistory().isPageable());
console.log(new AWS.Budgets().describeNotificationsForBudget().isPageable());
console.log(new AWS.Budgets().describeSubscribersForNotification().isPageable());
```
Output:
```
false
false
false
false
```

Using `.hasNextPage()` and `.nextPage()`:
```
new AWS.Budgets().describeBudgets({ AccountId: process.env.ACCOUNT_ID, MaxResults: 1 }, function(err, data) {
  console.log('page 1');
  if (err) {
    console.error(err);
  } else {
    console.log(data.Budgets.length);
    console.log(this.hasNextPage());
    this.nextPage(function(err, data){
      console.log('page 2');
      if (err) {
        console.error(err);
      } else {
        console.log(data.Budgets.length);
        console.log(this.hasNextPage());
      }
    })
  }
})
```
Output:
```
page 1
1
undefined
page 2
Error: No pagination configuration for describeBudgets
    at features.constructor.paginationConfig (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/service.js:646:17)
    at Response.nextPage (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/response.js:137:24)
    at Response.<anonymous> (/tmp/sdk-budgets-bug/repro.js:14:10)
    at Request.<anonymous> (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/state_machine.js:26:10 {
  message: 'No pagination configuration for describeBudgets',
  time: 2019-09-24T21:49:40.800Z
}
```

Using `.eachPage()`:
```
new AWS.Budgets().describeBudgets({ AccountId: process.env.ACCOUNT_ID, MaxResults: 1 }).eachPage(function(err, data) {
  if (err) {
    console.error(err);
  } else if (data) {
    console.log(data.Budgets.length);
  } else {
    console.log('No more data');
  }
});
```
Output:
```
1
No more data
```

Using `.eachItem()`:
```
new AWS.Budgets().describeBudgets({ AccountId: process.env.ACCOUNT_ID, MaxResults: 1 }).eachItem(function(err, data) {
  if (err) {
    console.error(err);
  } else if (data) {
    console.log('Got budget');
  } else {
    console.log('No more data');
  }
});
```
Output:
```
Error [TypeError]: Cannot read property 'resultKey' of null
    at wrappedCallback (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:522:30)
    at Response.<anonymous> (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/util.js:253:25)
    at Request.wrappedCallback (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:494:16)
    at Request.callListeners (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/tmp/sdk-budgets-bug/node_modules/aws-sdk/lib/request.js:38:9)
```

**Expected behavior**
The 4 API calls should return `true` for `isPageable()`, because they accept a 'NextToken' for pagination.

`.hasNextPage()` should return `true` or `false`, not `undefined`.

`.nextPage()` should perform an API call to retrieve the next page, not throw an exception about pagination configuration.

`.eachPage()` should perform multiple API calls and call the callback for each page, not just return the first page and silently ignore the future pages.

`.eachItem()` should call the callback once for each item, not throw an exception about the 'resultKey' property.

**Screenshots**
N/A

**Additional context**
This might be related to the [`budgets-2016-10-20.paginators.json`](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/apis/budgets-2016-10-20.paginators.json) which has an empty object for its pagination.

**Comment by ajredniwja** [comment]
Hey @nhinds, 

I reached out to service team for the feature to be implemented. I will update you once I hear back from them.

**Comment by MynockSpit** [comment]
@ajredniwja -- Do you know why this doesn't work by default? Budgets seems to use the "standard" key for more (NextToken).

**Comment by ajredniwja** [comment]
@MynockSpit it is not implemented and kept empty to implement it later.

**Comment by ajredniwja** [comment]
Soft update: the service team has worked on the feature you may expect to see the change soon.

**Comment by ajredniwja** [comment]
https://github.com/aws/aws-sdk-js/blob/master/apis/budgets-2016-10-20.paginators.json

This was implemented, closing this issue now.
