### ISSUE TITLE
Built-in retry doesn't work (retryable: false for throttling)

### ISSUE THREAD

**Issue by AAlon** [aws/aws-sdk-js#2884]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
The docs imply that automatic retries are supported for all services and all that needs to be done is to specify the `maxRetries` configuration option.

When using the SDK for Lex I'm getting throttled (`LimitExceededException`) with status code 429, which should be retryable: https://github.com/aws/aws-sdk-js/blob/v2.543.0/lib/util.js#L896

However, the error object has `retryable: false`, and no retries are performed. I'd appreciate your help figuring out whether this is a feature miss or a bug and how would  you suggest we overcome it. Thanks!

**Comment by ajredniwja** [comment]
Hey @AAlon,

Can you please provide the minimal repro code and all log traces.
```JavaScript
const lex = new AWS.Lex({logger: console}); 
```
One case I can think about is maybe the maxRetries are already exhausted.

**Comment by AAlon** [comment]
@ajredniwja It doesn't seem like there were any retries at all; see the `retryable: false` property of the exception.

```js
var AWS = require('aws-sdk');

AWS.config.update({region: 'us-west-2'});
AWS.config.update({maxRetries: 10, retryDelayOptions: {base: 1000}});
AWS.config.lexmodelbuildingservice = { params: {maxRetries: 10, retryDelayOptions: {base: 1000}} };
var lmbs = new AWS.LexModelBuildingService({logger: console, params: {maxRetries: 10, retryDelayOptions: {base: 1000}}});

var putBotAliasParams = {
  locale: "en-US",
  childDirected: false,
  intents: [{"intentName": "hello", "intentVersion": "$LATEST"}], /* some dummy intent set up in advance */
};

/* Send multiple putBot requests. Bot names cannot contain numbers so each bot name is test<c> where c goes from chr(start) to chr(end - 1) */
async function hitLexThrottling() {
    var i;
    var end = 11;
    var start = 1;
    for (i = start; i < end; i++) {
      putBotAliasParams.name = "test" + String.fromCharCode(97 + ( i % 22 ));
      const res = await lmbs.putBot(putBotAliasParams).promise().catch(error => console.log(error));
    } 
}

hitLexThrottling();
```


Environment is Cloud9 IDE using latest SDK:
```js

Admin:~/environment $ node test.js

[AWS lexmodelbuildingservice 429 0.08s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testb' })
{ LimitExceededException: The rate of requests exceeds the throughput limit. Retry the request.
    at Object.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The rate of requests exceeds the throughput limit. Retry the request.',
  code: 'LimitExceededException',
  time: 2019-10-08T20:57:06.288Z,
  requestId: '92434c82-13e7-4b8a-98f6-c4a30b444bca',
  statusCode: 429,
  retryable: false,
  retryDelay: 40.884882156780876 }


[AWS lexmodelbuildingservice 429 0.017s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testc' })
{ LimitExceededException: The rate of requests exceeds the throughput limit. Retry the request.
    at Object.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The rate of requests exceeds the throughput limit. Retry the request.',
  code: 'LimitExceededException',
  time: 2019-10-08T20:57:06.311Z,
  requestId: '4b1743c4-9cb1-4139-a9a7-213815ed8236',
  statusCode: 429,
  retryable: false,
  retryDelay: 185.68718960270348 }


[AWS lexmodelbuildingservice 200 0.048s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testd' })
[AWS lexmodelbuildingservice 429 0.014s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'teste' })
{ LimitExceededException: The rate of requests exceeds the throughput limit. Retry the request.
    at Object.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The rate of requests exceeds the throughput limit. Retry the request.',
  code: 'LimitExceededException',
  time: 2019-10-08T20:57:06.376Z,
  requestId: 'f90dbfcf-4e96-43be-af5a-61c2206b0fd8',
  statusCode: 429,
  retryable: false,
  retryDelay: 653.2419302624335 }


[AWS lexmodelbuildingservice 200 0.042s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testf' })
[AWS lexmodelbuildingservice 429 0.015s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testg' })
{ LimitExceededException: The rate of requests exceeds the throughput limit. Retry the request.
    at Object.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The rate of requests exceeds the throughput limit. Retry the request.',
  code: 'LimitExceededException',
  time: 2019-10-08T20:57:06.436Z,
  requestId: '817d8df7-a977-4f5b-a6a8-baafb3469a47',
  statusCode: 429,
  retryable: false,
  retryDelay: 37.59164712872454 }


[AWS lexmodelbuildingservice 429 0.014s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testh' })
{ LimitExceededException: The rate of requests exceeds the throughput limit. Retry the request.
    at Object.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The rate of requests exceeds the throughput limit. Retry the request.',
  code: 'LimitExceededException',
  time: 2019-10-08T20:57:06.452Z,
  requestId: 'a594e8af-507c-415f-a21a-3c36c8425c3b',
  statusCode: 429,
  retryable: false,
  retryDelay: 968.7641040350235 }


[AWS lexmodelbuildingservice 429 0.009s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testi' })
{ LimitExceededException: The rate of requests exceeds the throughput limit. Retry the request.
    at Object.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The rate of requests exceeds the throughput limit. Retry the request.',
  code: 'LimitExceededException',
  time: 2019-10-08T20:57:06.463Z,
  requestId: '0086e22a-8dac-436f-9d18-ada7cc8ef01f',
  statusCode: 429,
  retryable: false,
  retryDelay: 725.7840878950904 }
[AWS lexmodelbuildingservice 200 0.041s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testj' })


[AWS lexmodelbuildingservice 429 0.017s 0 retries] putBot({ locale: 'en-US',
  childDirected: false,
  intents:
   [ { intentName: 'hello', intentVersion: '$LATEST' },
     [length]: 1 ],
  name: 'testk' })
{ LimitExceededException: The rate of requests exceeds the throughput limit. Retry the request.
    at Object.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/ubuntu/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/node_modules/aws-sdk/lib/request.js:685:12)
  message:
   'The rate of requests exceeds the throughput limit. Retry the request.',
  code: 'LimitExceededException',
  time: 2019-10-08T20:57:06.523Z,
  requestId: '5cfb644b-d18d-4441-8134-b6d905f18368',
  statusCode: 429,
  retryable: false,
  retryDelay: 315.6770994668725 }

Admin:~/environment $ 
```

**Comment by AllanFly120** [comment]
Hey @AAlon the code you linked handling 429 is not actually executed during making API request. It's only called in [handleRequestWithRetries()](https://github.com/aws/aws-sdk-js/blob/a203c0e23010e256c88092a0be1e66a7a392eedf/lib/util.js#L867), which only used in credential refreshing request. For actual API request, we don't retry 429 by default. I will add it to SDK soon
