### ISSUE TITLE
UnknownError: Bad Request  error while updateAlias for lambda

### ISSUE THREAD

**Issue by prudhvireddy123** [aws/aws-sdk-js#2917]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
UnknownError: Bad Request  error while updateAlias for lambda
**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v10.15.1
**SDK version number**
 2.554.0

**To Reproduce (observed behavior)**
const AWS = require('aws-sdk');
const options = {
  httpOptions: {
    timeout: 10000,
  }
};

AWS.config.update({ region: 'us-east-1' });

var lambda = new AWS.Lambda(options);

const updateParams = {
  Description: 'Version 1',
  FunctionName: 'SomeLambdaFunction',
  FunctionVersion: '2',
  Name: 'prod'
};

lambda.updateAlias(updateParams, function(err, data) {
  if (err) console.log(err);
  else console.log(data); // successful response
});

**Expected behavior**
It supposes to update the alias version of lambda 

**Additional context**
{ UnknownError: Bad Request
    at Object.extractError (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/pkumar8/lifion/sre/sample-play/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Bad Request',
  code: 'UnknownError',
  statusCode: 400,
  time: 2019-10-23T07:29:34.545Z,
  requestId: undefined,
  retryable: false,
  retryDelay: 3.6073671580947764 }

**Comment by ajredniwja** [comment]
Hi @prudhvireddy123,

Thank-you for reaching out. I wasn't able to reproduce it locally on my machine, I believe your code is good. Can you provide any additional context for your particular use case?
