### ISSUE TITLE
SQS message attribute BinaryValue

### ISSUE THREAD

**Issue by pyrasis** [aws/aws-sdk-js#292]
Hello.

I sent a message with a binary message attribute.
(encoded with base64)

``` javascript
var AWS = require('aws-sdk');
AWS.config.loadFromPath('./config.json');

var sqs = new AWS.SQS();

var params = {
  MessageBody: 'Hello SQS',
  QueueUrl: 'https://sqs.ap-northeast-1.amazonaws.com/123456789000/ExampleQueue',
  DelaySeconds: 0,
  MessageAttributes: {
    someKey: {
      DataType: 'Binary',
      BinaryValue: 'SGVsbG8gQmluYXJ5'
    }
  }
};

sqs.sendMessage(params, function (err, data) {
  if (err)
    console.log(err, err.stack);
  else
    console.log(data);
});
```

I received a message and message attribute.

``` javascript
var AWS = require('aws-sdk');
AWS.config.loadFromPath('./config.json');

var sqs = new AWS.SQS();

var params = {
  QueueUrl: 'https://sqs.ap-northeast-1.amazonaws.com/123456789000/ExampleQueue',
  AttributeNames: [
    'Policy | VisibilityTimeout | MaximumMessageSize | MessageRetentionPeriod | ApproximateNumberOfMessages | ApproximateNumberOfMessagesNotVisible | CreatedTimestamp | LastModifiedTimestamp | QueueArn | ApproximateNumberOfMessagesDelayed | DelaySeconds | ReceiveMessageWaitTimeSeconds | RedrivePolicy',
  ],
  MaxNumberOfMessages: 1,
  MessageAttributeNames: [
    'someKey'
  ],
  VisibilityTimeout: 0,
  WaitTimeSeconds: 0
};

sqs.receiveMessage(params, function (err, data) {
  if (err)
    console.log(err, err.stack);
  else
    console.log(data);
});
```

but, node.js occurred this error.

```
{ [XMLParserError: unhandled type: base64]
  message: 'unhandled type: base64',
  code: 'XMLParserError',
  time: Thu Jun 05 2014 14:26:08 GMT+0900 (KST),
  statusCode: 200,
  retryable: false,
  _willRetry: false } 'XMLParserError: unhandled type: base64\n    at XMLParser.parseMember (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:150:28)\n    at XMLParser.<anonymous> (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:67:43)\n    at XMLParser.each (/home/pyrasis/example/node_modules/aws-sdk/lib/util.js:441:32)\n    at XMLParser.parseStructure (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:56:19)\n    at XMLParser.parseMember (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:135:19)\n    at XMLParser.<anonymous> (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:84:24)\n    at XMLParser.arrayEach (/home/pyrasis/example/node_modules/aws-sdk/lib/util.js:450:32)\n    at XMLParser.parseMap (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:83:24)\n    at XMLParser.parseMember (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:139:19)\n    at XMLParser.<anonymous> (/home/pyrasis/example/node_modules/aws-sdk/lib/xml/node_parser.js:67:43)'
```

2.0.0-rc.19

**Comment by SirCameronMcAlpine** [comment]
I still get the error above, even after installing the latest sdk.

Error: Service must be constructed with `new' operator
    at Object.Service (/srv/microservices/adjust.worker/node_modules/aws-sdk/lib/service.js:23:28)
    at Object.features.constructor [as SNS] (/srv/microservices/adjust.worker/node_modules/aws-sdk/lib/util.js:654:24)
    at Object.<anonymous> (/srv/microservices/adjust.worker/index.js:12:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
