### ISSUE TITLE
 comprehendMedical.startEntitiesDetectionV2Job is not a function, error in serverless

### ISSUE THREAD

**Issue by ShawnLimit** [aws/aws-sdk-js#2948]
When I use `comprehendMedical.startEntitiesDetectionV2Job` in my js code for serverless I get 

```	ERROR	Invoke Error	{
    "errorType": "TypeError",
    "errorMessage": "comprehendMedical.startEntitiesDetectionV2Job is not a function",
    "stack": [
        "TypeError: comprehendMedical.startEntitiesDetectionV2Job is not a function",
        "    at records.map (/var/task/handler.js:21:30)",
        "    at Array.map (<anonymous>)",
        "    at module.exports.comprehend (/var/task/handler.js:10:35)",
        "    at Runtime.handler (/var/task/serverless_sdk/index.js:9:87626)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

my handler:

```
'use strict';

const awsSdk = require('aws-sdk');

const comprehendMedical = new awsSdk.ComprehendMedical();

module.exports.comprehend = (event, context, callback) => {
  const records = event.Records;

  const medicalPromises = records.map((record) => {
    const recordUrl = [
      'https://s3.amazonaws.com',
      process.env.S3_PARSED_BUCKET,
      record.s3.object.key,
    ].join('/');

    console.log(recordUrl);

    return comprehendMedical.startEntitiesDetectionV2Job({
      DataAccessRoleArn: role arn numbers,
      InputDataConfig: {
        S3Bucket: process.env.S3_PARSED_BUCKET,
      },
      LanguageCode: process.env.LANGUAGE_CODE,
      OutputDataConfig: {
        S3Bucket: process.env.S3_COMPREHENDED_BUCKET,
      }
    }).promise();
  });

  Promise.all(medicalPromises)
    .then(() => {
      callback(null, { message: 'Start Entities Detection V2 job successfully' });
    })
    .catch(err => callback(err, { message: 'Error Start Entities Detection V2 Job'}));
};
```

I tested Amazon Transcribe and Amazon Comprehend, they both work fine.
Its just comprehend medical that messes up with the function.

**Comment by monken** [comment]
You need to bundle the aws-sdk with your function. The version of aws-sdk on Lambda is not always the latest and doesn't include this service yet.

**Comment by ajredniwja** [comment]
Hey @ShawnLimit, I agree with @monken. You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies). 

Please reach out to us if you continue to see this problem.

**Comment by ShawnLimit** [comment]
Thank you for the help
