### ISSUE TITLE
Buffer deprecation warnings still exist in Lambda Node.js 12.x runtime

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#2979]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm still seeing this warning in Lambda. Full stack trace:

```
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:162:11)
    at new Buffer (buffer.js:245:3)
    at Object.send (/var/task/src/webpack:/node_modules/aws-xray-sdk-core/lib/segment_emitter.js:131:19)
    at c.flush (/var/task/src/webpack:/node_modules/aws-xray-sdk-core/lib/segments/attributes/subsegment.js:321:22)
    at c.streamSubsegments (/var/task/src/webpack:/node_modules/aws-xray-sdk-core/lib/segments/attributes/subsegment.js:336:10)
    at close (/var/task/src/webpack:/node_modules/aws-xray-sdk-core/lib/segments/attributes/subsegment.js:270:14)
    at constructor.apply (/var/task/src/webpack:/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:123:18)
    at constructor.callListeners (/var/task/src/webpack:/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at constructor.call (/var/task/src/webpack:/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at constructor.emitEvent (/var/task/src/webpack:/node_modules/aws-sdk/lib/request.js:683:14)
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Lambda

**Comment by ajredniwja** [comment]
Hey @ffxsam,

Thank-you for reaching out to us with your issue.

Can you please make sure that you are using the latest version of the SDK.

You can import the latest version of SDK by [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

**Comment by ffxsam** [comment]
@ajredniwja I'm not packaging `aws-sdk` with my Lambda func, since the Node.js 12.x runtime has it natively. So wouldn't it be up to AWS to keep it up-to-date?

**Comment by ajredniwja** [comment]
You're right @ffxsam, lambda team strives to incorporate the latest version of the SDK in their models thats why I provided you with guidelines on how you can import the latest SDK.

**Comment by ffxsam** [comment]
Gotcha. I see the Lambda Node.js 12.x runtime is currently using 2.536.0, and the latest SDK is at 2.580.0. I'll go ahead and just include that as a production-level dependency. Thanks!
