### ISSUE TITLE
Getting "Forbidden: null" in my Node.js application when trying to access files from my S3 bucket

### ISSUE THREAD

**Issue by jfsalaza** [aws/aws-sdk-js#3028]
This is an issue I've encountered in the last couple of days in my Node.js application. I am running aws-sdk version 2.272.1.

The error comes from the function s3.headObject. I am not sure if it relates to the access and secret keys not being configured properly or something else but I've unable to fix this issue.

```
let awsParams = { Bucket: generic-bucket-name, Key: req.params.profile_image_unique_id };
return s3.headObject(awsParams, function (err, data) {
            if (err) {
               return res.status(400).send({
                    error_title: 'File failed to download, unknown error',
                    error_message: 'File failed to download, unknown error'
                });
            }

            let stream = s3.getObject(awsParams).createReadStream();

            // forward errors
            stream.on('error', function error(err) {
                return res.status(400).send({
                    error_title: 'File failed to download, unknown error',
                    error_message: 'File failed to download, unknown error'
                });
            });

            res.set('Content-Type', mime.getType('.jpeg'));
            res.set('Content-Length', data.ContentLength);
            res.set('Last-Modified', data.LastModified);
            res.set('ETag', data.ETag);
            res.status(200);

            stream.pipe(res);
        });
```

This is the error I get when calling the s3.headObject function. The error message is not that helpful besides telling me that I have no access to the files stored in my s3 bucket.

```
{ 
    Forbidden: null
         at Request.extractError (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\services\s3.js:798:35)
         at Request.callListeners (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
         at Request.emit (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
         at Request.emit (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:683:14)
         at Request.transition (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:22:10)
         at AcceptorStateMachine.runTo (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\state_machine.js:14:12)
         at C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\state_machine.js:26:10
         at Request.<anonymous> (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:38:9)
         at Request.<anonymous> (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:685:12)
         at Request.callListeners (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
         at Request.emit (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
         at Request.emit (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:683:14)
         at Request.transition (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:22:10)
         at AcceptorStateMachine.runTo (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\state_machine.js:14:12)
         at C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\state_machine.js:26:10
         at Request.<anonymous> (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:38:9)
         at Request.<anonymous> (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\request.js:685:12)
         at Request.callListeners (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
         at callNextListener (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
         at IncomingMessage.onEnd (C:\Users\johnn\Documents\juristerra-v3\Express\node_modules\aws-sdk\lib\event_listeners.js:307:13)
         at IncomingMessage.emit (events.js:203:15)
         at IncomingMessage.EventEmitter.emit (domain.js:448:20)
       message: null,
       code: 'Forbidden',
       region: null,
       time: 2019-12-26T20:42:02.817Z,
       requestId: '15B13D1F7B4432A3',
       extendedRequestId:
        '+0xHIoU3OZ7RoLBJFKp0CO6VO9qNet0g1gyPBoBUfTuboTa9f6FIHXA0/A+5wjYpLnpTFH4J5/8=',
       cfId: undefined,
       statusCode: 403,
       retryable: false,
       retryDelay: 55.89876980791042 
}
```

Have any of you encountered an issue like this before?

**Comment by ajredniwja** [comment]
Hey @jfsalaza, thank-you for reaching out to us with your issue.

This error is related to permissions which indicates the user trying to access the bucket does't have the correct permissions. 

Can you please make sure for the user accessing the bucket has correct permissions. 

You can check for the ```CORS``` permissions, more information found [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html). 

Please reach out if that doesn't solve the problem.
