### ISSUE TITLE
update() is not a function error in nodejs

### ISSUE THREAD

**Issue by nsawit** [aws/aws-sdk-js#3057]
Code below generates the following error

> docClient.update(params, function(err, data) { ^ TypeError: docClient.update is not a function at Object. (C:\Projects\demo\db-demo\project-demo\src\js\update-item.js:21:11) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10) at Module.load (internal/modules/cjs/loader.js:914:32) at Function.Module._load (internal/modules/cjs/loader.js:822:14) at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12) at internal/main/run_main_module.js:16:11

```
const AWS = require("aws-sdk");
    AWS.config.update({
      region: region,
      accessKeyId: secret,
      secretAccessKey: secret
    });
    const docClient = new AWS.DynamoDB();

    var params = {
        TableName:"TestTable",
        Key:{
            "UID": "130",
        },
        UpdateExpression: "set Description = :descr",
        ExpressionAttributeValues:{
            ":descr":"This value has been modified",
        },
        ReturnValues:"UPDATED_NEW"
    };
    docClient.update(params, function(err, data) {
        if (err) {
            console.log(JSON.stringify(err, undefined, 2));
        } else {
            console.log(JSON.stringify(data, undefined, 2));
        }
    });
```

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

**Comment by nsawit** [comment]
When tried to use aws-sdk inside script tags in html, this works and successfully updated the item in db
```
<html>
 <head>
  <script src="https://sdk.amazonaws.com/js/aws-sdk-2.604.0.min.js"></script>
    AWS.config.update({
        region: region,
      accessKeyId: secret,
      secretAccessKey: secret
    });
    var docClient = new AWS.DynamoDB.DocumentClient();

    function updateItem() {
        var params = {
            TableName:"TestTable",
            Key:{
                "UID": "130",
            },
            UpdateExpression: "set Description = :descr",
            ExpressionAttributeValues:{
                ":descr":"This value has been modified",
            },
            ReturnValues:"UPDATED_NEW"
        };
        docClient.update(params, function(err, data) {
            if (err) {
                //my codes here
            } else {
                //my codes here
            }
        });
    }
    </script></head><body>
    <input type="button" value="Update Item" onclick="updateItem();" /></body>
    </html>
```
