### ISSUE TITLE
aws-sdk: Resource is not in the state channelStopped

### ISSUE THREAD

**Issue by geosav** [aws/aws-sdk-js#3062]
my code:

```
async stopUpstreamChannel(id: string): Promise<StopUpstreamChannelResult> {
     const params = { ChannelId: id };

     // Stop channel with ChannelId
     await this.mediaLive.stopChannel(params).promise();


     const result = await self.mediaLive.waitFor('channelStopped', params).promise();

     return result;
}
```
when run code: mediaLive.waitFor('channelStopped', params) get next error:
```
ResourceNotReady: Resource is not in the state channelStopped
[0]     at constructor.setError (.../node_modules/aws-sdk/lib/resource_waiter.js:182:47)
[0]     at Request.CHECK_ACCEPTORS (.../node_modules/aws-sdk/lib/resource_waiter.js:44:12)
[0]     at Request.callListeners (.../node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[0]     at Request.emit (.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[0]     at Request.emit (.../node_modules/aws-sdk/lib/request.js:683:14)
[0]     at Request.transition .../node_modules/aws-sdk/lib/request.js:22:10)
[0]     at AcceptorStateMachine.runTo (.../node_modules/aws-sdk/lib/state_machine.js:14:12)
[0]     at .../node_modules/aws-sdk/lib/state_machine.js:26:10
[0]     at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:38:9)
[0]     at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:685:12)
[0]     at Request.callListeners (.../node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[0]     at Request.emit (.../node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[0]     at Request.emit (.../node_modules/aws-sdk/lib/request.js:683:14)
[0]     at Request.transition (.../node_modules/aws-sdk/lib/request.js:22:10)
[0]     at AcceptorStateMachine.runTo (.../node_modules/aws-sdk/lib/state_machine.js:14:12)
[0]     at .../node_modules/aws-sdk/lib/state_machine.js:26:10 {
[0]   message: 'Resource is not in the state channelStopped',
[0]   code: 'ResourceNotReady',
[0]   retryable: true,
[0]   time: 2020-01-22T15:55:53.889Z,
[0]   statusCode: 200,
[0]   retryDelay: 5000
[0] }
```
and when run this function stopUpstreamChannel again everything ok. What I do wrong?

**Comment by ajredniwja** [comment]
Hey @geosav thank-you for reaching out to us with your issue. 

Can you please answer the questions found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug+report&template=---bug-report.md&title=).
