### ISSUE TITLE
Signing URL with custom policy without passing URL

### ISSUE THREAD

**Issue by s4kh** [aws/aws-sdk-js#3086]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Signing URL with custom policy throws `TypeError: Cannot read property 'split' of undefined`

`getSignedUrl(options: Signer.SignerOptionsWithPolicy | Signer.SignerOptionsWithoutPolicy): string;`

You can pass policy object, but in the code([signer.js](https://github.com/aws/aws-sdk-js/blob/3dd8ab44334c0b9598a96bf9975000219619fbe8/lib/cloudfront/signer.js#L196)), it is using `options.url` to determine whether it is `rmtp://`.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Nope.

**Details of the browser/Node.js version**
v10.16.3

**SDK version number**
2.587.0
**To Reproduce (observed behavior)**
sign a URL with a custom policy.

**Expected behavior**
should return signed URL

**Screenshots**
`TypeError: Cannot read property 'split' of undefined
    at determineScheme (/app/node_modules/aws-sdk/lib/cloudfront/signer.js:52:21)
    at getResource (/app/node_modules/aws-sdk/lib/cloudfront/signer.js:66:13)
    at Signer.getSignedUrl (/app/node_modules/aws-sdk/lib/cloudfront/signer.js:178:28)
    at getSignedUrl (/app/src/lib/videoProviderAWS.js:74:28)
    at signUrl (/app/src/lib/videoProviderAWS.js:156:24)
    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/app/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/app/src/lib/videoProviderAWS.js:28:103)
    at _next (/app/src/lib/videoProviderAWS.js:30:194)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

**Additional context**

**Comment by s4kh** [comment]
Here is my code
```
const signer = new aws.CloudFront.Signer(AWS_ACCESS_KEY, key);
  const folderURL = url.substring(0, url.lastIndexOf('/') + 1);
  const policy = JSON.stringify({
    Statement: [
      {
        Resource: `${folderURL}*`,
        Condition: {
          DateLessThan: {
            'AWS:EpochTime':
              Math.floor(new Date().getTime() / 1000) + 60 * 60 * 1, // Current Time in UTC + time in seconds, (60 * 60 * 1 = 1 hour)
          },
        },
      },
    ],
  });
  console.log(policy);
  const signedURL = signer.getSignedUrl({ policy });
