### ISSUE TITLE
I'm getting Error [UnknownError] code seems to be ok. 

### ISSUE THREAD

**Issue by JavierPons** [aws/aws-sdk-js#3115]
Confirm by changing [ ] to [x] below:
- [ X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
This is the error I get
```
Error [UnknownError]
    at Request.extractError (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/javierpons/apptest_api/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/javierpons//apptest_api/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/javierpons/apptest_api/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/Users/javierpons//apptest_api/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/Users/javierpons/apptest_api/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:208:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20) {
  message: '',
  code: 'UnknownError',
  statusCode: 400,
  time: 2020-02-25T08:11:28.547Z,
  requestId: 'c3e67bb8-279b-45ab-9b27-ff92d55f0f7a',
  retryable: false,
  retryDelay: 95.92017470657987
}
```

My code 
```
data.repositories = await Promise.all(
      data.repositories.map(async function(repo) {
        // console.log("This is repo22", repo);
        const datas = await codecommit.listBranches({ repositoryName: repo.repositoryName }).promise();
        // console.log("this is data from listBranches", datas.branches); // branches
        // console.log("this is repo ... ", repo); // repo Name and Id
        // console.log("this is repo.branches ... ", repo.branches); // empty

        repo.branches = datas.branches;

        const branchdates = await codecommit.batchGetRepositories({ repositoryNames: [repo.repositoryName] }).promise();
        console.log("branchdates", branchdates);
        // const infobranch = await codecommit.getBranch({ branchName: datas.branches, repositoryName: repo.repositoryName }).promise();

        // console.log("infobranch... ", infobranch);
        console.log("datas branches ", datas.branches);
         try {
        const datos = await Promise.all(
          datas.branches.map(async (item, i) => {
            console.log("my item branch ", item);
            // console.log("repoooo", repo.repositoryName);
            const infobranch = await codecommit.getBranch({ branchName: item, repositoryName: repo.repositoryName }).promise();
            console.log("infobranch... ", infobranch);

            // const branchData = await codecommit.getCommit({ commitId: item, repositoryName: repo.repositoryName }).promise();

            // console.log("branchData  ", branchData);
          })
        );
        console.log("All this ", datos);
        } catch (err) {
          console.log(err);
           console.log(err.requestId);
         }

        // console.log("datessss ", branchdates);

        repo.dates = branchdates;

        // console.log("this is repo.branches After ... ", repo.branches);
        // console.log("this is REPO ... ", repo.dates); // repo is all package Name, id and branch
        return repo;
      })
    );
```

**Comment by ajredniwja** [comment]
Hey @JavierPons thankyou for reaching out to us with your issue, can you please share the complete async function that you are using.

**Comment by JavierPons** [comment]
`router.get("/repo", async function(req, res) {
  AWS.config.update({
    region: "some",
    accessKeyId: process.env.ACCESS_KEY,
    secretAccessKey: process.env.SECRET_KEY
  });

  const codecommit = new AWS.CodeCommit();

  const data = await codecommit.listRepositories().promise();


data.repositories = await Promise.all(
      data.repositories.map(async function(repo) {
        // console.log("This is repo22", repo);
        const datas = await codecommit.listBranches({ repositoryName: repo.repositoryName }).promise();
        // console.log("this is data from listBranches", datas.branches); // branches
        // console.log("this is repo ... ", repo); // repo Name and Id
        // console.log("this is repo.branches ... ", repo.branches); // empty

        repo.branches = datas.branches;

        const branchdates = await codecommit.batchGetRepositories({ repositoryNames: [repo.repositoryName] }).promise();
        console.log("branchdates", branchdates);
        // const infobranch = await codecommit.getBranch({ branchName: datas.branches, repositoryName: repo.repositoryName }).promise();

        // console.log("infobranch... ", infobranch);
        console.log("datas branches ", datas.branches);
         try {
        const datos = await Promise.all(
          datas.branches.map(async (item, i) => {
            console.log("my item branch ", item);
            // console.log("repoooo", repo.repositoryName);
            const infobranch = await codecommit.getBranch({ branchName: item, repositoryName: repo.repositoryName }).promise();
            console.log("infobranch... ", infobranch);

            // const branchData = await codecommit.getCommit({ commitId: item, repositoryName: repo.repositoryName }).promise();

            // console.log("branchData  ", branchData);
          })
        );
        console.log("All this ", datos);
        } catch (err) {
          console.log(err);
           console.log(err.requestId);
         }

        // console.log("datessss ", branchdates);

        repo.dates = branchdates;

        // console.log("this is repo.branches After ... ", repo.branches);
        // console.log("this is REPO ... ", repo.dates); // repo is all package Name, id and branch
        return repo;
      })
    );

  res.send(data.repositories);

});`

**Comment by ajredniwja** [comment]
@JavierPons running the above code snippet, I am not able to reproduce the error. 

Can you try not doing `Promise.all` and do calls in batches of two? 

This was discussed in https://forums.aws.amazon.com/thread.jspa?threadID=306991 where a customer was seeing similar error.

**Comment by ajredniwja** [comment]
Closing this issue due to lack of response. Feel free to reach out if you have questions.
