### ISSUE TITLE
listObjectsV2 in async function exception

### ISSUE THREAD

**Issue by sytolk** [aws/aws-sdk-js#3197]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
```
TypeError: str.indexOf is not a function
    at Object.validateARN [as validate] (/var/runtime/node_modules/aws-sdk/lib/util.js:983:25)
    at Object.hasBucketInParams [as isAccessPointApplicable] (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:180:23)
    at Object.setupRequestListeners (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:126:14)
    at Object.addAllRequestListeners (/var/runtime/node_modules/aws-sdk/lib/service.js:276:10)
    at Object.makeRequest (/var/runtime/node_modules/aws-sdk/lib/service.js:203:10)
    at Object.listObjectsV2 (/var/runtime/node_modules/aws-sdk/lib/service.js:674:23)
    at listMetaDirectoryPromise (/var/task/src/indexer.js:693:34)
    at /var/task/src/indexer.js:380:31
    at new Promise (<anonymous>)
    at listDirectoryPromise (/var/task/src/indexer.js:376:6)
```

**If on Node.js, are you running this on AWS Lambda?**
Yes this is in Lambda:
```
const listDirectory = async (path, bucketName) => {
    const params = {
        Delimiter: '/',
        Prefix: 'path_not_exist/path/',
        Bucket: bucketName
    };
    try {
        const results = await s3.listObjectsV2(params).promise().then(data => {. //LINE 693
            return data;
        }).catch(function (err) {
            console.warn('Not exist folder exception is not catch here!' );
            return false;
        });
        return results;
    } catch (e) {
        console.warn('Error listing meta directory ' + path); //<-- I can catch here only
    }
```

**Expected behavior**
If path exist on S3 bucket this code works.
I think that the developers will expect not exsist path exception will be throw in internal listObjectV2 catch.

**Comment by sytolk** [comment]
my bad this Exception is trown if `bucketName = undefined`
