### ISSUE TITLE
Error: Could not find API configuration s3-2006-03-01; while runing unit test 

### ISSUE THREAD

**Issue by cruzortiz99** [aws/aws-sdk-js#3220]
Hi i´m  trying ti run this test:
```ts
import { expect } from 'chai'
import fs from 'fs'
import 'mocha'
import sinon from 'sinon'
import { saveIntoS3Factory } from '../../../../src/utils/s3'

describe.only('Save into S3 storage', () => {
  let S3StubUpload: sinon.SinonStub
  let saveIntoS3
  beforeEach(async () => {
    sinon.stub(fs, 'readFileSync').returns('test')
    S3StubUpload = sinon.stub(S3.prototype, 'upload')
    saveIntoS3 = saveIntoS3Factory(new S3())
    await saveIntoS3({ filename: 'test' }, { Bucket: 'test', Key: 'test' })
  })
  afterEach(() => {
    sinon.restore()
  })
  it('It upload files into S3', () => {
    expect(S3StubUpload.calledOnce).to.be.true
  })
})
```
But i get the follwing error:
```shell
 1) Save into S3 storage
       "before each" hook for "It upload files into S3":
     Error: Could not find API configuration s3-2006-03-01
      at JSON.parse (<anonymous>)
      at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Module.require (internal/modules/cjs/loader.js:690:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.get [as 2006-03-01] (node_modules\aws-sdk\clients\s3.js:11:17)
      at Object.apiLoader (node_modules\aws-sdk\lib\api_loader.js:5:33)
      at Function.defineServiceApi (node_modules\aws-sdk\lib\service.js:768:22)
      at features.constructor.getLatestServiceClass (node_modules\aws-sdk\lib\service.js:103:19)
      at features.constructor.loadServiceClass (node_modules\aws-sdk\lib\service.js:93:19)
      at features.constructor.Service [as constructor] (node_modules\aws-sdk\lib\service.js:28:29)
      at new features.constructor (node_modules\aws-sdk\lib\util.js:624:24)
      at Context.beforeEach (tests\unit\utils\s3\index.spec.ts:14:36)
      at process.topLevelDomainCallback (domain.js:126:23)
```

the code to test is:

````ts 
import { S3 } from 'aws-sdk'
import { FileInfo } from 'html-pdf'
import fs from 'fs'

export const saveIntoS3Factory = (storage: S3) => async (
  fileInfo: FileInfo,
  params: S3.PutObjectRequest,
  options?: S3.ManagedUpload.ManagedUploadOptions
): Promise<S3.ManagedUpload.SendData | null> => {
  try {
    return await storage
      .upload(
        {
          ...params,
          Body: fs.readFileSync(fileInfo.filename),
          ContentType: 'application/pdf'
        },
        options
      )
      .promise()
  } catch (error) {
    console.error(error)
    return null
  }
}
````

the npm dependencies are:
```json
{
  "aws-sdk": "^2.657.0",
  "chai": "^4.2.0",
  "mocha": "^7.1.0",
  "sinon": "^9.0.1",
}
```

I can't tell where is the error on the test.

**Comment by jlosardoLB** [comment]
+1

**Comment by cruzortiz99** [comment]
Actually that's it, there is no more configuration. Only the basics to run tests with mocha, chai and sinon.
