### ISSUE TITLE
The specified queue does not exist or you do not have access to it

### ISSUE THREAD

**Issue by MatteoGioioso** [aws/aws-sdk-js#3228]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The queue is deployed in the Singapore region, the EC2 has the right IAM permission to send message in batch (I have also tried with full access), basically everything is in place, however it does not work and I get this error:
```
    "message": "The specified queue does not exist or you do not have access to it.",

    "stack": "AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist or you do not have access to it.\n    at Request.extractError (/var/www/app/node_modules/aws-sdk/lib/protocol/query.js:50:29)\n    at Request.callListeners (/var/www/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/var/www/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/var/www/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/var/www/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/var/www/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /var/www/app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/var/www/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/var/www/app/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/var/www/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/var/www/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/var/www/app/node_modules/aws-sdk/lib/request.js:683:14)\n    at Request.transition (/var/www/app/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/var/www/app/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /var/www/app/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/var/www/app/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/var/www/app/node_modules/aws-sdk/lib/request.js:685:12)\n    at Request.callListeners (/var/www/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at callNextListener (/var/www/app/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n    at IncomingMessage.onEnd (/var/www/app/node_modules/aws-sdk/lib/event_listeners.js:307:13)\n    at IncomingMessage.emit (events.js:203:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:466:23)",

```
**Since the same operation works fine with the AWS CLI**, I thought this might be a problem with the sdk

```
const SQS = require("aws-sdk/clients/sqs");
const sqs = new SQS({
  region: "ap-southeast-1",
  apiVersion: "2012-11-05"
});

async sendMessageBatch(entries) {
      const params = {
        Entries: entries,
        QueueUrl: "https://sqs.<my_region>.amazonaws.com/<account_id>/<queue_name>"
      };

      await sqs.sendMessageBatch(params).promise();
    }
```
**This one fails**

Same operation with the aws-cli:
```
aws --region <my_region> sqs send-message-batch --queue-url https://sqs.<my_region>.amazonaws.com/<account_id>/<queue_name> --entries Id=string,MessageBody=string 
```
**This one is successful**

**Is the issue in the browser/Node.js?**
Nodejs on EC2

**Details of the browser/Node.js version**
`node 10`

**SDK version number**
`  "aws-sdk": "^2.638.0",`

**Expected behavior**
should find the queue

**Comment by MatteoGioioso** [comment]
My bad, it was a problem with AWS itself!
