### ISSUE TITLE
Service.prototype.customizeRequests is not a function

### ISSUE THREAD

**Issue by jcald1** [aws/aws-sdk-js#3256]
I'm using version 5.1.0 and aws-sdk version 2.678.0 and aws-xray-sdk version 3.0.1

When I run the following in my test:

```
const AWS = require('aws-sdk-mock');
AWS.mock('S3', 'upload', { msg : 'success' });

// Test function
const lambda = require('../../handler.js');

which imports:

AWS = AWSXRay.captureAWS(require('aws-sdk')), // Errors out
```

I get:

```
      TypeError: Service.prototype.customizeRequests is not a function
          at Object.captureAWS (/Users/name/projects/bw/app/lambdas/myapp/node_modules/aws-xray-sdk/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:37:25)
          at Object.<anonymous> (/Users/name/projects/bw/app/lambdas/myapp/services/staticFileStorage/strategies/s3/strategy.js:5:21)
          at Module._compile (internal/modules/cjs/loader.js:701:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
          at Module.load (internal/modules/cjs/loader.js:600:32)
          at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
          at Function.Module._load (internal/modules/cjs/loader.js:531:3)
          at Module.require (internal/modules/cjs/loader.js:637:17)
```

**Comment by ajredniwja** [comment]
Hey @jcald1 thankyou for reaching out to us with your issue, I believe this should be an issue for https://github.com/aws/aws-xray-sdk-node/issues

Can you re-open it there.

Few things I would check before that is:

Bundle the latest version of the SDK using [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies)

Also refer to https://forums.aws.amazon.com/thread.jspa?messageID=821510#821510

Please reach out if you have any questions.
