### ISSUE TITLE
'InternalException: Internal server error' calling GuardDuty's enableOrganizationAdminAccount method

### ISSUE THREAD

**Issue by satie** [aws/aws-sdk-js#3265]
Confirm by changing [ ] to [x] below:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution

**Describe the question**
I am trying to call GuardDuty's [enableOrganizationAdminAccount](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/GuardDuty.html#enableOrganizationAdminAccount-property) API method using the nodejs sdk via a Lambda function. I get the following exception when I call the method.

I should add that the Lambda function is deployed via a CloudFormation stack with an appropriate role policy defined for it. Also, I have bundled the `aws-sdk` (version `2.679.0`) via `node_modules` as the current Lamba runtime version (`2.631.0`) does not support the `enableOrganizationAdminAccount` method.

When I run the javascript code on my desktop it works without an error.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Lambda

**Details of the browser/Node.js version**
13.1.0

**SDK version number**
v2.679.0

**To Reproduce (observed behavior)**
  
```javascript
const AWS = require('aws-sdk');
const guardDuty = new AWS.GuardDuty();

const params = {
        AdminAccountId: process.env.guarddutyMaster /* required */
};
const data = await guardDuty.enableOrganizationAdminAccount(params).promise();
```
**Expected behavior**
API call succeeds without error

**Observed behavior**
```
2020-05-20T05:26:30.125Z	f5b212e0-a3a7-4f83-90db-162a9ef37289	ERROR	Invoke Error 	
{
    "errorType": "InternalException",
    "errorMessage": "Internal server error.",
    "code": "InternalException",
    "message": "Internal server error.",
    "time": "2020-05-20T05:26:30.100Z",
    "requestId": "3fb27f14-8fc3-448a-917b-c821525df20c",
    "statusCode": 500,
    "retryable": true,
    "stack": [
        "InternalException: Internal server error.",
        "    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
        "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"
    ]
}
```
Looking for guidance to resolve this issue. I have posted on the [forum](https://forums.aws.amazon.com/thread.jspa?threadID=322250) as well.

**Comment by philipwigg** [comment]
It seems like the 500 error is coming from the GuardDuty API itself.

Is there anything in the CloudTrail logs for GuardDuty that might explain the 500 error? All the API calls should be logged in there and it should hopefully supply some clues as to why it's rejecting your request.

https://docs.aws.amazon.com/guardduty/latest/ug/logging-using-cloudtrail.html

**Comment by ajredniwja** [comment]
Hey @satie not able to reproduce it locally, is it possible to try it with the latest version of the SDK?

**Comment by ajredniwja** [comment]
Apologies for late reply.

**Comment by ipsensejuan** [comment]
I have the same problem.
In this case it was possible to collect on Cloudtrail

```
{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "xxxxxxx",
        "arn": "xxxxxxxxx",
        "accountId": "000000000000",
        "accessKeyId": "xxxxxxx",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "xxxxxxx",
                "arn": "xxxxxxxxx",
                "accountId": "000000000000",
                "userName": "xxxxxxxxx"
            },
            "webIdFederationData": {},
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2020-07-09T13:25:49Z"
            }
        }
    },
    "eventTime": "2020-07-09T13:27:53Z",
    "eventSource": "guardduty.amazonaws.com",
    "eventName": "EnableOrganizationAdminAccount",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "x.x.x.x",
    "userAgent": "Boto3/1.12.49 Python/3.7.7 Linux/4.14.165-102.205.amzn2.x86_64 exec-env/AWS_Lambda_python3.7 Botocore/1.15.49",
    "errorCode": "InternalServerErrorException",
    "requestParameters": {
        "adminAccountId": "810585855845"
    },
    "responseElements": {
        "message": "Endpoint request timed out"
    },
    "requestID": "bfe1973e-7480-438d-a938-c1394be7167d",
    "eventID": "7a0f5491-e8e4-4ce8-9fbc-e17e51a9b2da",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "recipientAccountId": "000000000000"
}
```

**Comment by ipsensejuan** [comment]
I have the same problem.
In this case it was possible to collect on Cloudtrail

```
{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "xxxxxxx",
        "arn": "xxxxxxxxx",
        "accountId": "000000000000",
        "accessKeyId": "xxxxxxx",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "xxxxxxx",
                "arn": "xxxxxxxxx",
                "accountId": "000000000000",
                "userName": "xxxxxxxxx"
            },
            "webIdFederationData": {},
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2020-07-09T13:25:49Z"
            }
        }
    },
    "eventTime": "2020-07-09T13:27:53Z",
    "eventSource": "guardduty.amazonaws.com",
    "eventName": "EnableOrganizationAdminAccount",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "x.x.x.x",
    "userAgent": "Boto3/1.12.49 Python/3.7.7 Linux/4.14.165-102.205.amzn2.x86_64 exec-env/AWS_Lambda_python3.7 Botocore/1.15.49",
    "errorCode": "InternalServerErrorException",
    "requestParameters": {
        "adminAccountId": "000000000000"
    },
    "responseElements": {
        "message": "Endpoint request timed out"
    },
    "requestID": "bfe1973e-7480-438d-a938-c1394be7167d",
    "eventID": "7a0f5491-e8e4-4ce8-9fbc-e17e51a9b2da",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "recipientAccountId": "000000000000"
}
```

**Comment by abdullah432** [comment]
**Similar issue. Help needed**
```
{
    "errorType": "InternalServerErrorException",
    "errorMessage": "internal server error",
    "code": "InternalServerErrorException",
    "message": "internal server error",
    "time": "2020-08-02T14:44:03.180Z",
    "requestId": "c72b58cd-131c-4bd1-bdde-35078b4b57ca",
    "statusCode": 500,
    "retryable": true,
    "stack": [
        "InternalServerErrorException: internal server error",
        "    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
        "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)"
    ]
}
```

**Comment by ajredniwja** [comment]
Does changing region resolves the problem? Can @satie and @ipsensejuan try it?

**Comment by debragail** [comment]
What was the resolution on this?  I'm getting a similar error on one of my node lambdas
