### ISSUE TITLE
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details

### ISSUE THREAD

**Issue by tesujimath** [aws/aws-sdk-js#3322]
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

This is a followup to the (locked) issue #86

My problem was that my hex encoding of the signature was in upper case.  It gets rejected with the SignatureDoesNotMatch error, which covers a multitude of sins.

The solution was to make the signature in lower case hex.

Perhaps a comment to that effect could be added to these pages?

- https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html#signing-request-intro
- https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html
- https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html#signature-v4-troubleshooting-key-signing

**Comment by ajredniwja** [comment]
Hey @tesujimath thank-you for reaching out and addressing that, having a note about that should be really helpful, I can reach out to the documentation team on how they might some common user errors in the documentation.

**Comment by yciurlik-sage** [comment]
Hi,

Same issue for me with a newly created SMTP credentials and using this code : 
```
let nodemailer = require("nodemailer");
let AWS = require("aws-sdk");

// configure AWS SDK
AWS.config.update({
  accessKeyId: "AKIAXXX",
  secretAccessKey: "ITS/A/KEY+YESSSS",
  region: "eu-west-1",
});

// create Nodemailer SES transporter
let transporter = nodemailer.createTransport({
SES: new AWS.SES({
  apiVersion: '2010-12-01',
})
});

// send some mail
transporter.sendMail({
    from: "xxx@domain.com",
    to: "xxx@domain.com",
  subject: 'Message',
  text: 'I hope this message gets sent!'
}, (err, info) => {
  if(err) console.log(err);
  else {
    console.log(info.envelope);
    console.log(info.messageId);  
  }
  
});

```

I am encoutering this error message : 
```
 ➜ node sender.js
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:email.eu-west-1.amazonaws.com
x-amz-content-sha256:4c4c45c30a15830ddd0f7c5562009d6f70fffff0dcb89bfed8c276d5abdbf2
x-amz-date:20210609T152614Z

host;x-amz-content-sha256;x-amz-date
4c4c45c30a15830920f7c55fff9d6f70cb3eeb0f0dcb89bffff276d5abdbf2'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20210609T152614Z
20210609/eu-west-1/ses/aws4_request
d046cd86253a63ffa6a89f66c7265b72fff9efaf451b78bc5777'

    at Request.extractError (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/yciurlik/xxx/smtp/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'SignatureDoesNotMatch',
  time: 2021-06-09T15:26:15.041Z,
  requestId: '52fda40b-b93d-4874-b3f2-f418db3d2a64',
  statusCode: 403,
  retryable: false,
  retryDelay: 49.12993168059248
}
```

**Comment by dimacros** [comment]
I have the same error as @yciurlik-sage. Any news about it?
