### ISSUE TITLE
Trying to invoke lambda errors with: 'Error [UnknownError]: Bad Request'

### ISSUE THREAD

**Issue by rbingham** [aws/aws-sdk-js#3383]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I am getting a the following error when attempting to invoke a lambda through the SDK.
```
Error [UnknownError]: Bad Request
    at Object.extractError (/home/jenkins/test/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/home/jenkins/test/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/home/jenkins/test/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/jenkins/test/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/jenkins/test/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/jenkins/test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/jenkins/test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/jenkins/test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/jenkins/test/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/jenkins/test/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'UnknownError',
  statusCode: 400,
  time: 2020-08-05T21:00:55.537Z,
  requestId: undefined,
  retryable: false,
  retryDelay: 6.420482634168545
}
```

The code I am executing:
```javascript
const AWS = require("aws-sdk");
AWS.config.update({
  httpOptions: {
    proxy: "http://proxy.com:8000",
  },
});
const LambdaFunctionName = 'lambda-function';
const params = {
  Payload: JSON.stringify({
    body: {
      action: "anAction",
      data: {
        dataKey: "dataValue",
      },
    },
  }),
  FunctionName: `${LambdaFunctionName}`,
  InvocationType: "RequestResponse",
};

new AWS.Lambda({ apiVersion: "2015-03-31" })
.invoke(params, (err, data) => {
    console.log(err, data);
});

```
**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
not running on lambda

**Details of the browser/Node.js version**
v12.18.2

**SDK version number**
I have tried this in v2.500.0, v2.603.0, v2.712.0, v2.727.0

**To Reproduce (observed behavior)**
code provided above

**Expected behavior**
I expect a 200 response with the data from the lambda

**Additional context**
Authentication credentials are pulled from the ~/.aws/credentials file using the `AWS_SDK_LOAD_CONFIG=1 and AWS_PROFILE=${profileName}` environment variables.
Both CLI and Python sdks are able to make the request successfully on my machine.

**Comment by ajredniwja** [comment]
@rbingham thank-you for reaching out to us with your issue, do you get the same results when not using Proxy? 

Also can you provide me with the CLI command that you are using?

**Comment by rbingham** [comment]
@ajredniwja I am not able to test without the proxy (this testing is from a corporate environment). The code that I submitted has been anonymized, so that hostname isn't actually the proxy that I am using.

The cli command that I am running is `aws dynamodb scan --table-name ${table-name}`. Both the cli and node versions are using the same proxy settings.

**Comment by lstatro** [comment]
We run up against our proxies all the time where I work and get a similar error.  

Looking at your code maybe the agent needs a bit more config then just the proxy string.  We use proxy-agent to build our agent and it works w/o much issue.  

AWS was kind enough to even provide a [formal example](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html).


```javascript
/** from your original post */
AWS.config.update({
  httpOptions: {
    proxy: "http://proxy.com:8000",
  },
});
```

```javascript
/** you'll need to npm install this first */ 
const proxy = require('proxy-agent')

/** potential change */
AWS.config.update({
  httpOptions: {

    /** proxy-agent will return an agent configured with the supplied proxy for the sdk to use*/
    agent: proxy('http://proxy.com:8000)
  }
})
```
Hopefully this helps!
