### ISSUE TITLE
XMLParserError: Non-whitespace before first tag

### ISSUE THREAD

**Issue by Infotaku** [aws/aws-sdk-js#340]
Hello everyone,

I am getting an exception after publishing to SNS, the request is successfully sent towards SNS but the callback is always returning an XMLParserError. The weird thing is that I only get the exception on my Ubuntu server, everything is working fine on my local computer.

Here is the code I use for testing : 

```
var AWS = require('aws-sdk');

var SNS = new AWS.SNS(
    {
        accessKeyId: '########',
        secretAccessKey: '##############',
        region: 'eu-west-1',
        apiVersion: '2010-03-31',
        sslEnabled: false,
        convertResponseTypes: false
    }
);

var params = {
    Message: 'Message', /* required */
    TargetArn: 'arn:aws:sns:eu-west-1:############:endpoint/GCM/mobile-push-test/ee232220-8889-3c33-8a94-306e1d8522f9'
};

SNS.publish(params, function(err, data) { });
```

Nothing fancy about it but I've tried everything and nothing is working, not even the workaround given in this similar issue : https://github.com/aws/aws-sdk-js/issues/49

I should mention that I never had this issue with the version 1.4.x I was using until now.

**Comment by capaj** [comment]
@lsegal I did run into the issue just now-I am on ubuntu 17.04 and node 8.1.0 when using S3
```
S3 Upload: begin upload file /home/capaj/git_projects/looop/project-alpha/back-end/src/tmp/U1-HIIeET67vMpKDcHX4Vw1d.png
S3 Upload: error while uploading file /home/capaj/git_projects/looop/project-alpha/back-end/src/tmp/U1-HIIeET67vMpKDcHX4Vw1d.png { XMLParserError: Non-whitespace before first tag.
Line: 0
Column: 1
Char: {
    at error (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/sax/lib/sax.js:693:7)
    at beginWhiteSpace (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/sax/lib/sax.js:967:7)
    at SAXParser.write (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/sax/lib/sax.js:1019:11)
    at Parser.exports.Parser.Parser.parseString (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/xml2js/lib/xml2js.js:7:59)
    at NodeXmlParser.parse (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/xml/node_parser.js:30:10)
    at Request.extractError (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/services/s3.js:525:39)
    at Request.callListeners (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/capaj/git_projects/looop/project-alpha/back-end/node_modules/aws-sdk/lib/request.js:684:12)
  message: 'Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: {',
  code: 'XMLParserError',
  retryable: true,
  time: 2017-06-15T08:10:09.028Z,
  statusCode: 500 }

```

**Comment by shouze** [comment]
We encounter the same **S3** one than @capaj after the upgrade to node 8.7.0 today:
```
   Message:
     XMLParserError: Non-whitespace before first tag.
     Line: 0
     Column: 1
     Char: 4
         at error (/home/node/node_modules/sax/lib/sax.js:667:10)
         at strictFail (/home/node/node_modules/sax/lib/sax.js:693:7)
         at beginWhiteSpace (/home/node/node_modules/sax/lib/sax.js:967:7)
         at SAXParser.write (/home/node/node_modules/sax/lib/sax.js:1019:11)
         at Parser.exports.Parser.Parser.parseString (/home/node/node_modules/xml2js/lib/xml2js.js:508:31)
         at Parser.parseString (/home/node/node_modules/xml2js/lib/xml2js.js:7:59)
         at NodeXmlParser.parse (/home/node/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
         at Request.extractError (/home/node/node_modules/aws-sdk/lib/services/s3.js:563:39)
         at Request.callListeners (/home/node/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
         at Request.emit (/home/node/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
         at Request.emit (/home/node/node_modules/aws-sdk/lib/request.js:683:14)
         at Request.transition (/home/node/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/home/node/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /home/node/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/home/node/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/home/node/node_modules/aws-sdk/lib/request.js:685:12)
```
We were running aws sdk `2.117.0` and it still occurs after upgrading to `2.133.0`.

Ping @capaj have you fixed this one? If yes, how?

**Comment by capaj** [comment]
@shouze nope, I still get this error. Good thing we're running on node 6 in production.

**Comment by shouze** [comment]
Ok. Are you experiencing this issue with the real S3 platform? I didn't mentioned that but this error occurs on our `CI` ATM, which uses [minio](https://www.minio.io/) to simulate a S3 infra. So maybe I need to ensure it's not a related minio issue too.
