### ISSUE TITLE
SharedIniFileCredentials/AWS_STS_REGIONAL_ENDPOINTS=regional fails if there's no '[default]' profile

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-sdk-js#3418]
**Describe the bug**

When using `SharedIniFileCredentials` with:

* A profile name supplied as argument (*not* via `AWS_PROFILE`).
* A profile that uses assumerole credentials
* AWS_STS_REGIONAL_ENDPOINTS=regional

Then the credential retrieval fails if there's not a `[default]` profile with a region (even if both profiles involved in the AssumeRole operation *do have* a `region` in them). I'm assuming if there *is* a `[default]` profile then the provider will use the wrong region--I did not try to confirm that.

The problem does not appear when I configure `AWS_PROFILE` which makes me think there's some code that's forgetting to pass on the `profile` constructor argument to the right object.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v12.12.0

**SDK version number**
2.713.0

**To Reproduce (observed behavior)**

The following code:

```js
process.env.AWS_SDK_LOAD_CONFIG = '1';
process.env.AWS_STS_REGIONAL_ENDPOINTS = 'regional';

const AWS = require('aws-sdk');

const creds = new AWS.SharedIniFileCredentials({ profile: 'huijbers-admin-role' });

const chain = new AWS.CredentialProviderChain([creds]);
chain.resolvePromise().then(console.log);
```

Fails when given the following config:

```
============ ~/.aws/credentials =======================
[huijbers-admin-user]
aws_access_key_id = AKIA****************
aws_secret_access_key = YASbc2*****************

[huijbers-admin-role]
role_arn = arn:aws:iam::993655754359:role/Assumable
source_profile = huijbers-admin-user

============ ~/.aws/config =======================
[profile huijbers-admin-role]
region = eu-west-1

[profile huijbers-admin-user]
region = eu-west-1
```

The error is the following:

```
(node:66546) UnhandledPromiseRejectionWarning: ConfigError: Missing region in config
    at Request.optInRegionalEndpoint (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/services/sts.js:75:30)
    at Request.callListeners (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/request.js:408:15)
    at Request.send (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/request.js:372:10)
    at features.constructor.makeRequest (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/service.js:205:27)
    at features.constructor.svc.<computed> [as assumeRole] (/Users/huijbers/Temp/repro/node_modules/aws-sdk/lib/service.js:677:23)
```

And succeeds when the following is added to `~/.aws/config`:

```
[default]
region = eu-west-1
```

**Expected behavior**
I would have expected the region from the `huijbers-admin-role` profile to be used.

**Additional context**

Originally reported in https://github.com/aws/aws-cdk/issues/9937

**Comment by rix0rrr** [comment]
Isn't the solution to add this:

https://github.com/aws/aws-sdk-js/blob/f1c689ffbca0d21d7bd359d5d4a5f1bd2b498a8b/lib/credentials/shared_ini_file_credentials.js#L219-L222

```js
    var sts = new STS({
      region: roleProfile['region'],
      credentials: sourceCredentials,
      httpOptions: this.httpOptions
    });
```

**Comment by rix0rrr** [comment]
Aha well the fix is more complicated than that because `roleProfile` doesn't actually contain the `~/.aws/profile` data, it contains the `~/.aws/credentials` data. Ha ha.

**Comment by rix0rrr** [comment]
Oh, what I proposed won't actually work  because of this piece of code:

https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L969-L974

Given:

```
========== config ===============
[profile foo]
region = us-east-1

========= credentials ==============
[foo]
aws_access_key_id = 123
```

The "config" profile will be *completely overwritten* (not merged) by the credentials profile and the end result will be:

```
{
  "foo": {
    "aws_access_key_id": "123"
  }
}
```

Is this on purpose?
