### ISSUE TITLE
Is it possible that aws-sdk causes an SQLite syntax error on DynamoDB local?

### ISSUE THREAD

**Issue by edg956** [aws/aws-sdk-js#3435]
Confirm by changing [ ] to [x] below:
- [X ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**
**Context**: 
- Problem found while upgrading from Nodejs 6 to 12 and with that the project's dependencies.
- Using dynamoose 2.3
- Containerized application using docker-compose: backend and dynamodb instance only 
Docker file for dynamodb:
```
FROM openjdk:latest

\# Bundle dynamodb
COPY . .

EXPOSE 8000
CMD [ "java", "-jar", "DynamoDBLocal.jar" ]
```

**Problem:** when lifting up the containers, after the backend initializes the dynamodb instance throws the errors below, causing any subsequent query or call to stall and return on timeout on the backend's side.

Error:
```
dynamodb_1  | Sep 03, 2020 8:14:36 AM com.almworks.sqlite4java.Internal log
dynamodb_1  | WARNING: [sqlite] SQLiteDBAccess$10@b6f156c: job exception
dynamodb_1  | com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() DROP INDEX Foobar*HVI; [near "*": syntax error]
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:580)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:635)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:622)
dynamodb_1  |   at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.getPreparedStatement(AmazonDynamoDBOfflineSQLiteJob.java:138)
dynamodb_1  |   at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$10.dropGSISQLiteIndex(SQLiteDBAccess.java:1221)
dynamodb_1  |   at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$10.dropIndices(SQLiteDBAccess.java:1169)
dynamodb_1  |   at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$10.doWork(SQLiteDBAccess.java:1155)
dynamodb_1  |   at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.SQLiteDBAccess$10.doWork(SQLiteDBAccess.java:1152)
dynamodb_1  |   at com.amazonaws.services.dynamodbv2.local.shared.access.sqlite.AmazonDynamoDBOfflineSQLiteJob.job(AmazonDynamoDBOfflineSQLiteJob.java:97)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteJob.execute(SQLiteJob.java:372)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteQueue.executeJob(SQLiteQueue.java:534)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:667)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
dynamodb_1  |   at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
dynamodb_1  |   at java.base/java.lang.Thread.run(Thread.java:832)
```

I suspect this is happening when creating the tables through Dynamoose's model() which under the hood calls aws' DynamoDB createTable method.

I'm currently just analysing the upgrade to nodejs 12 and dynamoose 2.3. In local I would prefer to have it run to test other parts of the project, so I don't mind updating indexes and recreating tables, but wish to know where this syntax error is coming from to fix it and carry on.

**Question**: Is it possible that the aws-sdk causes a DynamoDB local instance to attempt to drop an index with an SQLite syntax error?

**Comment by philipwigg** [comment]
Anything's possible but I think the [issue](https://github.com/dynamoose/dynamoose/issues/1001) you've raised in the Dynamoose project is probably the best place to start troubleshooting this and raise an issue here if you have a reproducible test case we can look at with some code from the aws-sdk.

**Comment by edg956** [comment]
@philipwigg I agree, but nevertheless people here probably know more about the internals of the interface with DynamoDB, time is running and I need to start discarding possibilities, hence my shot at it.

Apologies if the question is completely out of place.

**Comment by ajredniwja** [comment]
Hey @edg956, thanks for raising this, I believe this might not be related to the SDK at all but how Dynamoose calls DynamoDb. Node 6 to 12 is also a huge bump which may have changed a lot of things. Since this a syntax issue, I can not possibly tell you whats wrong without looking at any code. In general the syntax error has to come from clients side, not with certainty but I guess this might be just be related to how a query is made, a syntax error related to the query for which I think you may wanna locate the query which uses `*` and try to change that.

**Comment by fishcharlie** [comment]
Posting for visibility.

https://github.com/dynamoose/dynamoose/issues/1001#issuecomment-687349638

---

Additionally, I'd be happy to help debug this as much as I can from the Dynamoose side. However, all of our calls are made through the `aws-sdk`, so I'm not quite sure where to even start. It'd make sense if we were doing non-standard actions or calls, but everything occurs through the official library.

So it's likely I'd need a lot more information in order to help debug this.

**Comment by edg956** [comment]
I'll dig deeper into this and get back to this with a conclusion or minimal reproducible example in case this continues.

**Comment by ajredniwja** [comment]
@edg956 I would need to look at some code to help you with this because I suspect it on the code usage, as you mentioned earlier, minimal reproducible example would be great.

**Comment by edg956** [comment]
@ajredniwja I found what the issue was. As expected, on the client side. I want to have a deeper look since both the project I'm working on and Dynamodb are new to me, but the error came from declaring a key as a hashkey and making it have index as global. Currently I haven't been able to work on it anymore to provide a proper conclusion, but plan to do so. In any case, that's the cause of the problem.

**Comment by ajredniwja** [comment]
@edg956 Thanks for updating me, I would like to close the issue now, please reach out if you have any other questions.
