### ISSUE TITLE
headBucket method fails inconsistently when the length of Bucket varies

### ISSUE THREAD

**Issue by RonWang** [aws/aws-sdk-js#3456]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
For a simple headBucket call, the failure messages are very inconsistent based on the `Bucket` value:
```
client = new aws.S3()
client.headBucket({ Bucket: 'k' }, (err) => {
  // Here is the error object:
  Error
    at Request.extractError (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/services/s3.js:811:35)
    at Request.callListeners (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListen
});
```

While when the Bucket string is longer then 2, the error becomes
```
client = new aws.S3()
client.headBucket({ Bucket: 'kkkk' }, (err) => {
Error
    at Request.extractError (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/services/s3.js:811:35)
    at Request.callListeners (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/nongwang/Github/ask-cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {message: null, code: 'Forbidden', region: 'us-east-2', time: Mon Sep 21 2020 10:28:11 GMT-0700 (Pacific Daylight Time), requestId: '64E1D3CC431DFE6F'}
});

```

When the Bucket string is longer then 6, the stack trace does not show, which is the normal error our downstream can deal with consistently.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No, local code

**Details of the browser/Node.js version**
v10.8.0

**SDK version number**
2.716.0

**To Reproduce (observed behavior)**
Shown as the code snippet above.

**Comment by ajredniwja** [comment]
Hey @RonWang, thanks for opening this issue with us, I am little confused about your request, the bucket name has to be between 3 and 63 characters long, from what I understand you are expecting a better error message or a consistent message for both 1 and 2 letters word, I believe that will be an unlikely scenario with `headBucket` operation since there can not be any buckets that can be created with that type of names. 

Feel free to comment if I am not getting what you are trying to point out.
