### ISSUE TITLE
SSM waiter does not wait for the command to be created resulting in it being unusable

### ISSUE THREAD

**Issue by jmp-aws** [aws/aws-sdk-js#3457]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
https://stackoverflow.com/search?q=%5Baws-sdk-js%5D+ssm+waiter
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
 When using SSM and a waiter, the waiter does not wait for the command to be created. This results in the waiter failing a majority of the time with the error: 

```
{
    "errorType": "InvocationDoesNotExist",
    "errorMessage": "Resource is not in the state commandExecuted",
    "code": "ResourceNotReady",
    "message": "Resource is not in the state commandExecuted",
    "time": "2020-09-17T21:55:13.024Z",
    "requestId": "85ef8f8f-b6b3-4c13-a44a-b6263e38a9fe",
    "retryable": false,
    "statusCode": 400,
    "retryDelay": 5000,
    "stack": [
        "InvocationDoesNotExist: Resource is not in the state commandExecuted",
        "    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:690:12)",
        "    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

The api should wait till the command is finished or the waiter should account for this error and retry.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

Runtime
Node.js 12.x

**SDK version number**
Example: v2.466.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

aws-sdk@2.755.0 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

### code 
```
const AWS = require('aws-sdk');
// https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSM.html
const SSM = new AWS.SSM({region:'us-east-1'});
const COMMAND = `echo "Hello world"`;
const instanceId = 'i-XXXXXXXXXXXXXXXXX' //REPLACE WITH YOUR INSTANCE ID
exports.handler = async (event) => {

    console.log('instanceId: ', instanceId);
    //call ssm with command
    console.log('running command')
    let commandResult = await SSM.sendCommand({
        DocumentName: 'AWS-RunShellScript',
        DocumentVersion: '1',
        Targets: [{ 'Key': 'InstanceIds', "Values": [instanceId] }],
        Parameters: {
            commands: [COMMAND]
        }
    }).promise();
    console.log('command executed')
    //wait for command to finish
    let commandId = commandResult.Command.CommandId;
    console.log('commandId:', commandId);
    console.log('instanceId: ', instanceId);

    //wait for a few seconds for the command to exists as workaround
    // await new Promise((resolve, reject) => {
    //     setTimeout(function () { resolve() }, 1000);
    // });

    await SSM.waitFor("commandExecuted", {
        CommandId: commandId,
        InstanceId: instanceId,
    }).promise();

    //print out active node
    let command = await SSM.getCommandInvocation({
        CommandId: commandId,
        InstanceId: instanceId,
    }).promise();
    console.log(command.StandardOutputContent);
};

```

**Expected behavior**
 That the waiter or api would be smart enough to wait for the command to be created before waiting for the results of the command in ssm.

**Comment by ajredniwja** [comment]
Hey @jmp-aws, If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

You can import the latest version of SDK by following [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

Can you try bumping up the version and see if the issue still persists?

**Comment by jmp-aws** [comment]
I'm afraid that's not the case. I used a layer with the most recent node version. Please try it yourself

**Comment by ccampanale** [comment]
I was also seeing this in a project of mine which I manually updated to `2.766.0` after reading this issue. I noticed, upon checking the state of my commands, that they were processing or failed while waiting. While it's not clear/intuitive, I believe this error simply means that the command did not finish in the allotted time the `waitFor` method will monitor for (every 5 seconds for a total of 20 checks according to the documentation). If the command does finish I find that `waitFor` works as expected, resolving the promise, and continuing the execute.

My question is why is it that the available "Waiter Resource States" are limited to `commandExecuted` (which is not itself clearly documented as to what it means to have been "executed") instead of the valid states for commands started with `sendCommand`? It would seem much more intuitive to me of these states were: "Pending", "InProgress", "Success", "Cancelled", "Failed", "TimedOut", and "Cancelling".

**Comment by jmp-aws** [comment]
@ccampanale 
> It would seem much more intuitive to me of these states were: "Pending", "InProgress", "Success", "Cancelled", "Failed", "TimedOut", and "Cancelling".

it does that already
https://github.com/aws/aws-sdk-js/blob/b93c2e10e67c9aad0966b97fa057b46a53143e49/apis/ssm-2014-11-06.waiters2.json#L8-L55

this issue is regarding the SSM API which returns a command id but when the waiter requests it for its status the API states that it doesn't exist, even though it does exist. This results in the waiter failing because `InvocationDoesNotExist ` is not a status the waiter waits on.

**Comment by ccampanale** [comment]
@jmp-aws 

I seem to have misunderstood the issue here. After reading it again I see that this is more an issue with the eventual consistency of the command being waited on and not an issue with the state being waited on. While this hasn't been my experience thus far - commands seem to exist as soon as the promise has resolved - if this is happening (and I could see how it may be) I do agree it should be investigated and remediated.

> it does that already

Thanks for the link to the waiter configuration but you seem to have misunderstood. The waiter state `commandExecuted` is not a state of the command resource but rather a perceived state. My point is that it would be more intuitive if the available waiter states included the states of the command itself. For example: `commandPending`, `commandInProgress`, commandSuccess`, etc.. But this is not relevant to the issue at hand. Sorry to have crossed wires.

**Comment by Subham9418** [comment]
I am also facing the same issue,

**Code snippet:**
```
async.auto(
    {
      readfile: [
        (cb) => {

          let filePath = "/Users/random/test/check.ps1";
          fs.readFile(filePath, 'utf8', (err, command) => {
            if (err) {
              return cb(err);
            }
            cb(null, command);
          });

        }
      ],
      sendCommand: [
        "readfile", (results, cb) => {
          let params = {
            TimeoutSeconds: 360,
            MaxConcurrency: '1',
            MaxErrors: '10',
            Parameters: {
              commands: [results.readfile]
            },
            InstanceIds: ["i-xxxxxxxxxxxxx"],
            DocumentName: 'AWS-RunPowerShellScript'
          };
          ssm.sendCommand(params, (err, data) => {
            if (err) return cb(err);
            cb(null, data);
          });

        }
      ],

      waitForCommand: [
        "sendCommand",
        (results, cb) => {
          let params = {
            CommandId: results.sendCommand.Command.CommandId,
            InstanceId: "i-xxxxxxxxxxxxx"
          };
          ssm.waitFor("Success", params, (err, results) => {
            if (err) return cb(err);
            cb(null, results);
          });
        }
      ]


    }, (err, result) => {
      if (err) {
        return callback(err);
      }
      callback(null, result);
    }

  )
```
**Error:**
```
/Users/random/test/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

StateNotFoundError: State Success not found.
    at constructor.loadWaiterConfig (/Users/random/test/node_modules/aws-sdk/lib/resource_waiter.js:196:32)
    at new constructor (/Users/random/test/node_modules/aws-sdk/lib/resource_waiter.js:64:10)
    at features.constructor.waitFor (/Users/random/test/node_modules/aws-sdk/lib/service.js:252:18)
    at asyncjs.auto.waitForCommand (/Users/random/test/ssmsend.js:66:15)
    at runTask (/Users/random/test/node_modules/async/dist/async.js:1632:13)
    at /Users/random/test/node_modules/async/dist/async.js:1572:13
    at processQueue (/Users/random/test/node_modules/async/dist/async.js:1582:13)
    at taskComplete (/Users/random/test/node_modules/async/dist/async.js:1601:9)
    at /Users/random/test/node_modules/async/dist/async.js:1625:17
    at /Users/random/test/node_modules/async/dist/async.js:969:16
```
