### ISSUE TITLE
missing credentials file error

### ISSUE THREAD

**Issue by qcu** [aws/aws-sdk-js#3531]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using AWS SSO (with exported env variables) an error is thrown by `AWS.CredentialProviderChain();` if `~/.aws/credentials` file is missing, even though it isn't used or needed for the current authentication scheme.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v10.15.1

**SDK version number**
Example: v2.787.0

**To Reproduce (observed behavior)**
1. Configure aws sso by manually editing `~/.aws/config` and adding a profile.
2. Delete, or do not create, the `~/.aws/credentials` file.
3. Login with SSO.
4. Run app, which uses `new AWS.CredentialProviderChain();`

**Expected behavior**
Warning message re. missing credentials file, at most. Particularly since I am using AWS SSO (with exported env variables), which does not require any entries in the `~/.aws/credentials` file.

**Screenshots**
N/A

**Additional context**
The error was remediated after touching the `~/.aws/credentials` file.

```
For help, see: https://nodejs.org/en/docs/inspector
fs.js:115
	throw err;	at Object.openSync (fs.js:439:3)
	at Object.readFileSync (fs.js:344:35)
	at Object.readFileSync (/home/user/src/app/server/node_modules/aws-sdk/lib/util.js:95:26)
	at IniLoader.parseFile (/home/user/src/app/server/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
	at IniLoader.loadFrom (/home/user/src/app/server/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
	at Config.region (/home/user/src/app/server/node_modules/aws-sdk/lib/node_loader.js:101:36)
	at Config.set (/home/user/src/app/server/node_modules/aws-sdk/lib/config.js:514:39)
	at Config.<anonymous> (/home/user/src/app/server/node_modules/aws-sdk/lib/config.js:349:12)
	at Config.each (/home/user/src/app/server/node_modules/aws-sdk/lib/util.js:507:32)
	at new Config (/home/user/src/app/server/node_modules/aws-sdk/lib/config.js:348:19)
	at Object.<anonymous> (/home/user/src/app/server/node_modules/aws-sdk/lib/node_loader.js:111:14)
	at Module._compile (internal/modules/cjs/loader.js:689:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	at Module.load (internal/modules/cjs/loader.js:599:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[nodemon] app crashed - waiting for file changes before starting...
	^

Error: ENOENT: no such file or directory, open '/home/user/.aws/credentials'
```

**Comment by cisum-la** [comment]
This issue was recently fixed by  #3436.  When I tried it there was one more thing I needed to do - specify the AWS_REGION in my bash_profile after that it worked perfectly.
https://github.com/aws/aws-sdk-js/issues/3436#issuecomment-727284777

**Comment by ajredniwja** [comment]
Hey @qcu Thanks for opening the issue, @cisum-la is right about fixing this recently I would recommend to implement and check all the env variables, also as mentioned above make sure you have AWS_SDK_LOAD_CONFIG set to a truthy value.

**Comment by qcu** [comment]
thanks! I searched, but somehow missed #3436.

**Comment by qcu** [comment]
> also as mentioned above make sure you have AWS_SDK_LOAD_CONFIG set to a truthy value.

yes, I am specifying both `AWS_PROFILE` and `AWS_SDK_LOAD_CONFIG` via dotenv .envrc.

```
export AWS_PROFILE="..."
export AWS_SDK_LOAD_CONFIG="1"
```
