### ISSUE TITLE
Endpoint throws TypeError if imported from aws-sdk/lib/core

### ISSUE THREAD

**Issue by exoego** [aws/aws-sdk-js#3544]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Class `Endpoint` throws `TypeError` if imported from `aws-sdk/lib/core`.

```
Uncaught TypeError: Cannot read property 'parse' of undefined
    at Object.urlParse (/Users/cw-tatsuno/IdeaProjects/aws-sdk-scalajs-facade/node_modules/aws-sdk/lib/util.js:60:21)
    at new Endpoint (/Users/cw-tatsuno/IdeaProjects/aws-sdk-scalajs-facade/node_modules/aws-sdk/lib/http.js:58:36)
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
YES

**Details of the browser/Node.js version**
v14.15.1

**SDK version number**
v2.797.0

**To Reproduce (observed behavior)**

Run following script where `aws-sdk` installed.

```js
const core = require("aws-sdk/lib/core")
const customEndpoint = new core.Endpoint("http://localhost");
```

**Expected behavior**

Class `Endpoint` can be constructed as similar as when invoked as `AWS.Endpoint`.
I want to import `Endpoint` from `aws-sdk/lib/core` to minimize bundle size by tree shaking.

**Comment by exoego** [comment]
The below works for me.

```js
const coreOnlyAWS = require('aws-sdk/lib/node_loader');
const endpoint = new coreOnlyAWS.Endpoint('http://localhost');
```
