### ISSUE TITLE
ses config.update dose not update the region correctly

### ISSUE THREAD

**Issue by mustafaallam2** [aws/aws-sdk-js#3558]
**To Reproduce (observed behavior)**

```javascript
//create instance of the clas like this without passing any params
const AWSMailer = new AWSSES()

// update the config
AWSMailer.config.update({
      accessKeyId: '<accesKey>',
      secretAccessKey: '<secret>',
      region: 'us-west-2'
    })
// this will throw an error 
AWSMailer.sendRawEmail()
```
*error*
```
err UnknownEndpoint: Inaccessible host: `email.undefined.amazonaws.com'. This service may not be available in the `us-west-2' region.
    at Request.ENOTFOUND_ERROR (/mnt/c/Workspace/BAWQ/bawq-operator/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/mnt/c/Workspace/BAWQ/bawq-operator/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/mnt/c/Workspace/BAWQ/bawq-operator/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/mnt/c/Workspace/BAWQ/bawq-operator/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/mnt/c/Workspace/BAWQ/bawq-operator/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/mnt/c/Workspace/BAWQ/bawq-operator/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'UnknownEndpoint',
  region: 'us-west-2',
  hostname: 'email.undefined.amazonaws.com',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND email.undefined.amazonaws.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'email.undefined.amazonaws.com',
    region: 'us-west-2',
    retryable: true,
    time: 2020-11-29T13:31:40.105Z
  },
  time: 2020-11-29T13:31:40.105Z
}
```
**Expected behavior**
should send email fine after setting the config

**Additional context**
i solved this by manualy setting the new end point (after updating the config)
```javascript
    AWSMailer.endpoint.host = `email.${region}.amazonaws.com`
    AWSMailer.endpoint.hostname = `email.${region}.amazonaws.com`
    AWSMailer.endpoint.href = `https://email.${region}.amazonaws.com/`
```

**Comment by ajredniwja** [comment]
Hey @mustafaallam2 Thanks for opening this issue, can you try doing something like: 

```
var AWS = require('aws-sdk');

AWS.config.update({
    accessKeyId: 'xyz',
    secretAccessKey: 'zyx',
    region: 'us-west-2'
  })

const AWSMailer = new AWS.SES();
```

**Comment by mustafaallam2** [comment]
hi  @ajredniwja 
 the problem accrued when updating the config after create the instance of the class, i have a need for this in order to update the config during the run time.
as you can see the config updates fine but the region is not see the host name : email.undefined.amazonaws.com
if no region was provided before init an instance of the class it can never be updated knowing that the region is an optional parameter that should be updateable

**Comment by ajredniwja** [comment]
I  am able to reproduce it. I would need to do more digging on why it is behaving like that.

**Comment by eduardomourar** [comment]
I have the same problem and it seems to affect other services too (such SSO).

**Comment by eduardomourar** [comment]
Similar to the workaround presented by mustafaallam2, I was able to perform the update like this:
```javascript
      const region = 'us-east-1';
      const endpoint = `portal.sso.${sso_region}.amazonaws.com`;
      self.service.config.update({ region, endpoint });
      self.service.endpoint = new AWS.Endpoint(endpoint, self.service.config);
```

The SDK should be able to listen to the config update events and modify the endpoint whenever the region is changed for a particular service.
