### ISSUE TITLE
Dynamodb client query operation failing while everything is correctly defined. 

### ISSUE THREAD

**Issue by adnanshussain** [aws/aws-sdk-js#3592]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm using the v3 of the SDK and I tried the "query" operation of the dynamodb client. Below is the params object being sent to the query function
```
{
    "KeyConditionExpression": "surah_no = :s_no AND ayat_no = :a_no",
    "TableName": "Ayats",
    "ExpressionAttributeValues": {
        ":s_no": {
            "N": "12"
        },
        ":a_no": {
            "N": "3"
        }
    }
}

```
The exception thrown is as follows 
```
ValidationException: Either the KeyConditions or KeyConditionExpression parameter must be specified in the request.
    at deserializeAws_json1_0QueryCommandError (/home/storm/github-local/quranified/quranified-tools/node_modules/@aws-sdk/client-dynamodb/dist/cjs/protocols/Aws_json1_0.js:2983:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/storm/github-local/quranified/quranified-tools/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /home/storm/github-local/quranified/quranified-tools/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
    at async StandardRetryStrategy.retry (/home/storm/github-local/quranified/quranified-tools/node_modules/@aws-sdk/middleware-retry/dist/cjs/defaultStrategy.js:56:46)
    at async /home/storm/github-local/quranified/quranified-tools/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22 {
  __type: 'com.amazon.coral.validate#ValidationException',
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '0d6cdf39-22d7-463e-9057-54cf1fe51c9e',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}
```
However when I use the aws cli v2 and execute the following command 
```
aws --endpoint-url http://localhost:8000 dynamodb query \
--table-name Ayats \
--expression-attribute-values '{ ":sno": { "N": "12" }, ":ano": { "N": "4"}}' \
--key-condition-expression 'surah_no = :sno AND ayat_no = :ano'
```
It returns the result correctly !

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No. I'm running everything locally

**Details of the browser/Node.js version**
Node v12.19.0

**SDK version number**
@aws-sdk/client-dynamodb@3.1.0

**To Reproduce (observed behavior)**
Mentioned Above in Describe the Bug 

**Expected behavior**
A successful response.

**Comment by ajredniwja** [comment]
Transferring to the correct repo.
