### ISSUE TITLE
Cannot set headers after they are sent to the client, while S3 upload for file size more than 1 MB

### ISSUE THREAD

**Issue by bmmule** [aws/aws-sdk-js#3608]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Getting error when uploading file big than 1 MB

upload part error: NodeError: Cannot set headers after they are sent to the client
    at ClientRequest.setHeader (<node_internals>/_http_outgoing.js:470:11)
    at Function.Util.safeIncludeCorrelationHeader ({project_path}\node_modules\applicationinsights\Library\Util.ts:361:21)
    at Function.AutoCollectHttpDependencies.trackRequest ({project_path}\node_modules\applicationinsights\AutoCollection\HttpDependencies.ts:141:22)
    at clientRequestPatch ({project_path}\node_modules\applicationinsights\AutoCollection\HttpDependencies.ts:70:45)
    at Object.https.request ({project_path}\node_modules\applicationinsights\AutoCollection\HttpDependencies.ts:86:13)
    at features.constructor.handleRequest ({project_path}\node_modules\aws-sdk\lib\http\node.js:45:23)
    at executeSend ({project_path}\node_modules\aws-sdk\lib\event_listeners.js:348:29)
    at Request.SEND ({project_path}\node_modules\aws-sdk\lib\event_listeners.js:362:9)
    at Request.callListeners ({project_path}\node_modules\aws-sdk\lib\sequential_executor.js:102:18)
    at Request.emit ({project_path}\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit ({project_path}\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition ({project_path}\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo ({project_path}\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at {project_path}\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> ({project_path}\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> ({project_path}\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners ({project_path}\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at callNextListener ({project_path}\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at {project_path}\node_modules\aws-sdk\lib\event_listeners.js:247:9
    at finish ({project_path}\node_modules\aws-sdk\lib\config.js:386:7)
    at {project_path}\node_modules\aws-sdk\lib\config.js:404:9
    at Credentials.get ({project_path}\node_modules\aws-sdk\lib\credentials.js:127:7)
    at getAsyncCredentials ({project_path}\node_modules\aws-sdk\lib\config.js:398:24)
    at Config.getCredentials ({project_path}\node_modules\aws-sdk\lib\config.js:418:9)
    at Request.SIGN ({project_path}\node_modules\aws-sdk\lib\event_listeners.js:218:22)
    at Request.callListeners ({project_path}\node_modules\aws-sdk\lib\sequential_executor.js:102:18)
    at callNextListener ({project_path}\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at Request.discoverEndpoint ({project_path}\node_modules\aws-sdk\lib\discover_endpoint.js:365:7)

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
NO

**Details of the browser/Node.js version**
node version is 12.20.0

**SDK version number**
Example: v2.738.0

**To Reproduce (observed behavior)**
Try upload file (pdf, word document) which is more than 1MB to S3 using s3.upload()

**Expected behavior**
multipart upload should work

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment]
Hey @bmmule thanks for opening this issue, seems to be some kind of client side error, can you please share your use case and the code that you are using?

**Comment by bmmule** [comment]
I have been trying to upload different files like pdf, xls,xlsx,docx to s3 using aws-sdk. 

I can upload files less than 1 MB, but for file size greater than 1 MB, the same code gives error.

I am using nodejs as backend and below is my code snippet:

`AWS.config.update({ region: 'us-east-1' });
        let s3 = new AWS.S3(
            {
                accessKeyId: accessKeyId,
                secretAccessKey: secretAccessKey
            }
        );
        const readStream = fs.createReadStream(filePath);
        let params = {
            Bucket: bucketName,
            Key: key,
            Body: readStream
        }


            await s3.upload(params, (err, data) => {
                if (err) {
                    console.log(data);
                    return(err);
                } else {
                    readStream.destroy();
                    console.log(data);
                    return(data);
                }
            });`

**Comment by ajredniwja** [comment]
Hey @bmmule I used the exact same code and was successfully able to upload a 15mb file. You might wanna check if there is any race conditions that might be playing a role otherwise the upload function is working as expected.

**Comment by Vinoothna-CAW** [comment]
I am also facing the exact same issue. Any file more than 1 MB is not being uploaded to S3.

**Comment by ctrlaltdylan** [comment]
Same issue, happening intermittently on AWS us-east-1 while using version 2.1298.0 of the aws-sdk
