### ISSUE TITLE
ERROR Unhandled Promise Rejection  "errorType": "Runtime.UnhandledPromiseRejection" Table already exists

### ISSUE THREAD

**Issue by yeukfei02** [aws/aws-sdk-js#3621]
```
2021-02-05T03:18:44.062Z	1abd6db3-2523-4759-a9b6-4efb26d1bf14	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
    "reason": {
        "errorType": "ResourceInUseException",
        "errorMessage": "Table already exists: k11-open-api-record-time-prod",
        "code": "ResourceInUseException",
        "message": "Table already exists: k11-open-api-record-time-prod",
        "time": "2021-02-05T03:18:44.059Z",
        "requestId": "HD5AFEAVI78KITG8LEI8KKVRVVVV4KQNSO5AEMVJF66Q9ASUAAJG",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 110.1554075775096,
        "stack": [
            "ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
            "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
            "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)",
            "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
            "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
            "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
            "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)",
            "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: ResourceInUseException: Table already exists: k11-open-api-record-time-prod",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:495:21)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

I see is from `aws-sdk` in lambda, how to fix this?

**Comment by ajredniwja** [comment]
@yeukfei02 thanks for opening this issue, seems to be an issue with not using the promise or catching the exception, if you can fill out the issue template found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2C+needs-triage&template=---bug-report.md&title=), I can help you better.
