### ISSUE TITLE
The specified location-constraint is not valid : S3 bucket in US-East-1

### ISSUE THREAD

**Issue by MeRahulAhire** [aws/aws-sdk-js#3647]
Hi I'm trying to create bucket in `us-east-1` region and the sdk seemed to behave weirdly.

When you don't select any region as per follow code it by default creates bucket in North Virginia region 

```js
const AWS = require('aws-sdk');

const s3 = new AWS.S3({ signatureVersion: 'v4' });

var params = {
	Bucket: 'aws-bucket-101',
};

s3.createBucket(params, function(err, data) {
	if (err) console.log(err, err.stack);
	else console.log(data);
});
```
But if you add `LocationConstraint` in params as per following
```js
var params = {
	Bucket: 'aws-bucket-101',
	CreateBucketConfiguration: {
		LocationConstraint: 'us-east-1'
	}
};
```
you get this error
```sh
InvalidLocationConstraint: The specified location-constraint is not valid
    at Request.extractError (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\services\s3.js:700:35)
    at Request.callListeners (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'InvalidLocationConstraint',
  region: null,
  time: 2021-02-23T17:50:24.428Z,
  requestId: 'CCCF238B61F7DE69',
  extendedRequestId: 'gQjXGp4YoXGh3IAiG5HCARzQTLYv0J1QOQn/PFHhyjH8UBvxEYcfn/5MBRQwnLI66RTm4fVlsMs=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 65.88958024936602
} InvalidLocationConstraint: The specified location-constraint is not valid
    at Request.extractError (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\services\s3.js:700:35)
    at Request.callListeners (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\Rahul\Desktop\Image-upload-S3-dynamoDB\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
```
However it doesn't give this error if you try to create bucket in other region. So, Please fix this inconsistency

**Comment by ajredniwja** [comment]
Hey @MeRahulAhire, thanks for opening this issue, the [Developer Guide](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html) and the [API Reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createBucket-property). 

The default region is auto-populated here:
 https://github.com/aws/aws-sdk-js/blob/66ea51c59e393d01da738de21d3ca7b3c2553b26/lib/services/s3.js#L611

With that being said, I understand your concern but not mentioning the `LocationConstraint` in your code will only make your code shorter as mentioned in https://github.com/aws/aws-sdk-js/issues/1670#issuecomment-321009043

Since it is documented, I feel it is safe to not mention the region, what do you think?

**Comment by MeRahulAhire** [comment]
@ajredniwja I think you should give options to dev. It just makes the experience consistent. 
In my opinion you'll be just saving few lines of code which have nil effect on performance

**Comment by ajredniwja** [comment]
I'll mark this is as feature request.

**Comment by uhinze** [comment]
Stumbled here by accident. Isn't this just a typo and should be 'us-east1' instead of 'us-east-1'?

**Comment by Asiyah017** [comment]
Hi has this been fixed, I have this same exact issue a year after

**Comment by skharab-anaplan** [comment]
for most cases I think it doesn't save code rather add, because we would need to add an if condition to not set it if the region  is us-east-1

**Comment by danielrive** [comment]
agree with @skharab-anaplan , more code for a simple thing

**Comment by xuanyi-chen** [comment]
+1

**Comment by ma6153068** [comment]
If you use region **'us-east-1'** then the default location is **'None'**. If you want to create bucket in other region rather then **'us-east-1'** the you have to used **''LocationConstraint': regionName"**.

**Comment by oren-hecht** [comment]
here to say that this seem to not have been fixed yet. Our code has this ugly condition all over the place:

```
from mypy_boto3_s3 import S3Client
from mypy_boto3_s3.literals import BucketLocationConstraintType


def create_bucket(
    s3_client: S3Client, bucket: str, region: BucketLocationConstraintType | 'us-east-1'
) -> None:
    if region == "us-east-1":
        s3_client.create_bucket(Bucket=bucket, ACL="private")
    else:
        s3_client.create_bucket(
            Bucket=bucket,
            ACL="private",
            CreateBucketConfiguration={"LocationConstraint": region},
        )
```

I would like to support the request to make `"us-east-1"` work the same as any other region

**Comment by kellertk** [comment]
Greetings, we will not be making any changes to the v2 S3 client at this time. Please migrate to AWS SDK for JS v3.
