### ISSUE TITLE
s3.uploadPart fails with "done is not a function" under heavy load

### ISSUE THREAD

**Issue by keithmo** [aws/aws-sdk-js#3653]
AWS APIs are updating constantly, you might be calling a new API with an older version is SDK. In
    this case you should try installing the newest `aws-sdk` like: 

    `npm install aws-sdk@latest`

    If you are using the SDK in AWS Lambda, you are likely using old SDK version too. AWS Lambda bundled
    SDK version is shown in [this document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).
    You can import the latest version of SDK by following 
    [these guidelines](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html#nodejs-package-dependencies).

If you still like to open an issue, change [ ] to [x] below:
- [x] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

Environment:
OS: Mac 11.2.2
Node: 14.15.1
aws-sdk: 2.856.0

Stack:
```
TypeError: done is not a function
    at Request.requestBucketRegion (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/services/s3.js:736:14)
    at Request.callListeners (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/Users/keithmo/rivaliq/rivaliq-server/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Details:
This only seems to happen under heavy load (streaming multiple gigabytes). Smaller loads do not produce the error.

The problem is caused by `requestBucketRegion` getting registered as a non-async listener. `lib/services/s3.js:161` registers this handler with `request.onAsync()` (correct) but somewhere else it's getting registered with `request.on()`. I suspect something is calling `addListeners()` to bulk add or inherit a set of listeners and this fails to set the `_isAsync` flag.

Hacky workaround:
If, after calling `s3 = new AWS.S3(...)` I forcibly set `s3.requestBucketRegion._isAsync = true` then the problem goes away.

The long-term solution is to upgrade to the V3 NPM, but that's not a viable option at this time.

**Comment by ajredniwja** [comment]
Hi @keithmo thanks for opening this issue, I would have suggested the same workaround and a longterm solution to switch to V3 of the SDK. As for the code I believe that would have been done to run normal loads faster. Changing that now might cause latency issues now, what do you think?
