### ISSUE TITLE
Does STS require accessKey and Secretkey?

### ISSUE THREAD

**Issue by vsenapathy** [aws/aws-sdk-js#3670]
**Describe the question**
Hello,

I am testing aws-sdk for js and I trying to call STS without accessKey and secretkey. I am trying to use the role attached to the ec2-instance. Wanted to know if this will work. When I run my script i am getting the following error

`const aws = require('aws-sdk');
const sts = new aws.STS();
sts.getSessionToken({ DurationSeconds: 86400 }, (err, data) => {
  if (err) {
    console.log(err);
  } else {
    console.log(data);
  }
});`

I went through this page : https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#getSessionToken-property and it tells I can use it without the keys. The role has permission for GetSessionToken

Error message:

node test.js
AccessDenied: Cannot call GetSessionToken with session credentials
    at Request.extractError (/opt/portal/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/opt/portal/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/portal/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/portal/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/opt/portal/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/portal/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/portal/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/portal/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/portal/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/opt/portal/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'AccessDenied',
  time: 2021-03-23T01:05:14.311Z,
  requestId: 'e4455d7a-0818-462a-85f4-5f0041122c5b',
  statusCode: 403,
  retryable: false,
  retryDelay: 97.51838389676892
}

Thanks,

Vignesh

**Comment by vsenapathy** [comment]
Hello,

Can someone let me know about this?

Thanks,

Vignesh

**Comment by vudh1** [comment]
Hi @vsenapathy , thank you for reaching out. I was not able to reproduce the issue. As the error message suggests, session credentials cannot be used to initialize a new STS session via a getSessionToken call. Can you check what type of credentials are you using? You can check by issuing a getCallerIdentity call and printing the response before issuing your getSessionToken call.
