### ISSUE TITLE
The transcribe service's endpoint is wrong in cn-north-1 & cn-northwest-1 region

### ISSUE THREAD

**Issue by laputa7** [aws/aws-sdk-js#3681]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
The endpoint prefix should be cn.transcribe in cn-north-1 & cn-northwest-1 region，but now the prefix is transcribe.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Lambda Node Runtime 12.x

**SDK version number**
v2.804.0

**To Reproduce (observed behavior)**
Call any transcribe's function through the sdk in cn-north-1 & cn-northwest-1 region

**Expected behavior**
No error occurred however it throws
`UnknownEndpoint: Inaccessible host: `transcribe.cn-northwest-1.amazonaws.com.cn'. This service may not be available in the `cn-northwest-1' region.
    at Request.ENOTFOUND_ERROR (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20) {
  code: 'UnknownEndpoint',
  region: 'cn-northwest-1',
  hostname: 'transcribe.cn-northwest-1.amazonaws.com.cn',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND transcribe.cn-northwest-1.amazonaws.com.cn
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
    errno: 'ENOTFOUND',
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'transcribe.cn-northwest-1.amazonaws.com.cn',
    region: 'cn-northwest-1',
    retryable: true,
    time: 2021-03-26T03:43:46.520Z
  },
  time: 2021-03-26T03:43:46.520Z
}`

**Comment by ajredniwja** [comment]
@laputa7 thanks for opening this issue, can you share some more info on what API you are calling and share the code that you are using?
