### ISSUE TITLE
Cognito ListUsers error - Paging Marker is Invalid for Request

### ISSUE THREAD

**Issue by OliverLeighC** [aws/aws-sdk-js#3705]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

When calling cognitoIdentityServiceProvider.listUsers with a pagination token, it throws this error

```
Paging marker CAISsAIIARKJAggDEoQCALGJrChG2+SqN8L1jIe4hyChcRSXUkRNYiO3gS0txrfDeyJAbiI6IlBhZ2luYXRpb25Db250aW51YXRpb25EVE8iLCJuZXh0S2V5IjoiQUFBQUFBQUFCU2gyQVFFQjFKeG5FZEl4UUxTRzJyQlk0c2x0STFtT3JSQ3VYRUw2b3VjRElnQUpYV2xsYm1ZN3VabXV0cXZSdnZLeTNLN1d5OG5LNUFDQXdMcko0NXlqMHBqUWxzaTI2dURZOGJLdDBwbmdxS0tWbSthVW5vNjUxZmZjdFk3QnRyb0FBVHM9IiwicHJldmlvdXNSZXF1ZXN0VGltZSI6MTYxNzkyMDEyNjIzN30aIDAnfSxE+vCfATQ0/z78ChAo7lKnUNB3Bz4ZLRg10Niu is invalid for request adaa2d40-d1bd-4da4-ab5c-ed2a2e20b341
```

We have 4 users pools (2 in our dev account, 2 in production) because we are migrating to a pool with email case insensitivity. The exact same code works in 3 out of the 4 pools. In production, calling listUsers on the new pool fails with the above error. Calling listUsers on the old pool in production works, it's the same code, same AWS credentials, and the same congnitoServiceProvider configuration, the only difference is the UserPoolId. 

I have found one instance of someone with the same error (https://stackoverflow.com/questions/45941473/aws-cognito-list-users-error) but it was 4yrs ago and it was a bug with the AWS console, where as this is with the aws-sdk and only for a specific pool.  

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

node v12.22.0 (I also tried with v12.11.1)

**SDK version number**

v2.880.0 (I also tried with aws-sdk@2.883.0)

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

I can't share the full repo, but here's a gist with redacted files with the all the relevant functions (error is happening on line 17)
https://gist.github.com/OliverLeighC/67fa0f89cc4141533ab937ded34b3f23#file-postmigrationprocess-ts-L17

The file called migrateUsers.ts works fine, that uses the old pool id. postMigrationProcess.ts is where it fails, and that file calls listUsers twice, once with a filter and once without. They both use the same pagination function and they use the same function to configure the cognito service provider. If less than 60 users match the filter then that one passes and the second call (with no filter) will fail, if there are more than 60 users that match the filter that call will fail because it will have to pass the pagination token. 

**Expected behavior**

I expect listUsers to accept the pagination token returned from the previous call, and return the next 60 users from the pool. Or if it does fail, it would be helpful to have a more helpful error message because I have no idea why the pagination token would be invalid for the request. 

**Screenshots**

The stack trace: 
```
 InvalidParameterException: Paging marker CAISsAIIARKJAggDEoQCALGJrChG2+SqN8L1jIe4hyChcRSXUkRNYiO3gS0txrfDeyJAbiI6IlBhZ2luYXRpb25Db250aW51YXRpb25EVE8iLCJuZXh0S2V5IjoiQUFBQUFBQUFCU2gyQVFFQjFKeG5FZEl4UUxTRzJyQlk0c2x0STFtT3JSQ3VYRUw2b3VjRElnQUpYV2xsYm1ZN3VabXV0cXZSdnZLeTNLN1d5OG5LNUFDQXdMcko0NXlqMHBqUWxzaTI2dURZOGJLdDBwbmdxS0tWbSthVW5vNjUxZmZjdFk3QnRyb0FBVHM9IiwicHJldmlvdXNSZXF1ZXN0VGltZSI6MTYxNzkyNjM2OTA4M30aIFp/ViDwgpbttI/OcMoOyf2g45QNTADYCMn/iLktfqya is invalid for request c89cf013-a0b3-4266-89b3-a056f74e5fbc
    at Request.extractError (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/oliver.coley/rcg-repos/Impact_Maintenance_Scripts/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Paging marker CAISsAIIARKJAggDEoQCALGJrChG2+SqN8L1jIe4hyChcRSXUkRNYiO3gS0txrfDeyJAbiI6IlBhZ2luYXRpb25Db250aW51YXRpb25EVE8iLCJuZXh0S2V5IjoiQUFBQUFBQUFCU2gyQVFFQjFKeG5FZEl4UUxTRzJyQlk0c2x0STFtT3JSQ3VYRUw2b3VjRElnQUpYV2xsYm1ZN3VabXV0cXZSdnZLeTNLN1d5OG5LNUFDQXdMcko0NXlqMHBqUWxzaTI2dURZOGJLdDBwbmdxS0tWbSthVW5vNjUxZmZjdFk3QnRyb0FBVHM9IiwicHJldmlvdXNSZXF1ZXN0VGltZSI6MTYxNzkyNjM2OTA4M30aIFp/ViDwgpbttI/OcMoOyf2g45QNTADYCMn/iLktfqya is invalid for request c89cf013-a0b3-4266-89b3-a056f74e5fbc',
  code: 'InvalidParameterException',
  time: 2021-04-08T23:59:29.292Z,
  requestId: 'c89cf013-a0b3-4266-89b3-a056f74e5fbc',
  statusCode: 400,
  retryable: false,
  retryDelay: 89.73454471060973
}
```
**Additional context**

The pool configurations are the same for both the old pool and the new pool, the only change is email case insensitivity (the reason we are migrating) and the new pool has 530 users where as the old one has 550. This also works in our dev environment, exact same code, same docker image, just different pool id's and AWS credentials.

**Comment by OliverLeighC** [comment]
I was able to resolve the error by passing in the filter to the recursive pagination function, which makes sense but is weird because that wasn't an issue in our dev environment. Our dev pool does have over 100 users, but maybe at the time that I ran it, only 60 users matched the filter.
