### ISSUE TITLE
Error on running npm run start at demo

### ISSUE THREAD

**Issue by abhimanusharma** [aws/aws-sdk-js#3784]
I have studies all the documentations and followed each step thoroughly.
I am trying to run the demo in Ubuntu 18.04, default browser is Google Chrome Latest version.
Installed latest Ruby and node-sass and chown the required directories.

I am getting below error. I will also be attaching the log file.

```
/var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js/demos/browser$ npm run start

> amazon-chime-sdk-js-demos@0.1.0 start /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js/demos/browser
> npm run deps && npm install && npm run start:fast


> amazon-chime-sdk-js-demos@0.1.0 deps /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js/demos/browser
> cd ../.. && npm run build


> amazon-chime-sdk-js@2.10.0 prebuild /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js
> script/conditional-install

node_modules is up to date.

> amazon-chime-sdk-js@2.10.0 build /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js
> node script/barrelize.js && node script/generate-version.js && npm run tsc:src && npm run tsc:guides && npm run copy

Build description: {
  "hash": "3196df1",
  "raw": "v2.10.0",
  "semverString": "2.10.0"
}

> amazon-chime-sdk-js@2.10.0 tsc:src /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js
> tsc --build config/tsconfig.json


> amazon-chime-sdk-js@2.10.0 tsc:guides /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js
> tsc --build guides/tsconfig.json


> amazon-chime-sdk-js@2.10.0 copy /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js
> node script/copy-protocol.js


> amazon-chime-sdk-js@2.10.0 postbuild /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js
> tsc -p config/tsconfig.import.json

loadDep:amazon-chime-sdk- ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine amazon-chime-sdk-js@2.10.0: wanted: {"node":"^12 || ^14 || ^15 || ^1npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
loadDep:yeoman-generator  ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine log-symbols@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine execa@5.0.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npmloadDep:yeoman-generator  ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine got@11.8.2: wanted: {"node":">=10.19.0"} (current: {"node":"8.10.0",npm ERR! Linux 4.15.0-143-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
WARN engine yeoman-generator@4.13.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js/demos/browser/npm-debug.log

npm ERR! Linux 4.15.0-143-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start: `npm run deps && npm install && npm run start:fast`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start script 'npm run deps && npm install && npm run start:fast'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the amazon-chime-sdk-js-demos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run deps && npm install && npm run start:fast
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs amazon-chime-sdk-js-demos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls amazon-chime-sdk-js-demos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/chime_demo/aws-chime-sdk/amazon-chime-sdk-js/demos/browser/npm-debug.log
```

[npm-debug.log](https://github.com/aws/aws-sdk-js/files/6568171/npm-debug.log)

**Comment by abhimanusharma** [comment]
If someone else is facing similar issue:

I had to downgrade my npm version to 14.1.0 to run this demo. It is working fine for now.
