### ISSUE TITLE
CloudWatch Logs PutRetentionPolicy cannot set never expire

### ISSUE THREAD

**Issue by mobsense** [aws/aws-sdk-js#3831]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

**Is the issue in the browser/Node.js?**
Both. Tested in browser SDK.

**If on Node.js, are you running this on AWS Lambda?**

Yes.

**Details of the browser/Node.js version**
v14.17

**SDK version number**
aws-sdk@2.945.0

## Overview

The CloudWatch logs PutRetention API is meant to accept only a logGroupName and the retentionInDays is meant to be optional. However the SDK has retentionInDays as a required parameter. 

## Describe the bug

PutRetentionPolicy is always requiring a retentionInDays. 

However, the doc: https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html. says that omitting the retentionInDays should set the log group to never expire. However, The SDK requires this parameter so you can never set a log group to never expire.

## Expected Behavior
The API PutRetention without a retentionInDays should succeed.
```
{
    "logGroupName": "name"
}
```
## Current Behavior
Get this message:

```
MissingRequiredParameter: Missing required key 'retentionInDays' in params
    at ParamValidator.fail (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (webpack-internal:///./node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (webpack-internal:///./node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (webpack-internal:///./node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (webpack-internal:///./node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at eval (webpack-internal:///./node_modules/aws-sdk/lib/event_listeners.js:86:9)
    at finish (webpack-internal:///./node_modules/aws-sdk/lib/config.js:386:7)
    at eval (webpack-internal:///./node_modules/aws-sdk/lib/config.js:404:9)
```

## Possible Solution
The parameter should not be marked in the SDK as required.

## Workaround

Currently deleteRetentionPolicy is the only way to rest to never expire.

**Comment by ajredniwja** [comment]
Hey @mobsense thanks for opening this issue, the parameter is not marked required by the SDK but the service, I can reach out to them and see what more info they have on it. P55550143

**Comment by ajredniwja** [comment]
Apologies for a late reply but I believe a change to the docs was made please see: 
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutRetentionPolicy.html#API_PutRetentionPolicy_RequestSyntax
