### ISSUE TITLE
XMLParserError: Non-whitespace before first tag when retrieving object from s3 bucket

### ISSUE THREAD

**Issue by bitshiftnetau** [aws/aws-sdk-js#3893]
The following code will spit out an error about whitespace parsing:

```
                        const s3 = new AWS.S3({        
                            accessKeyId: process.env.ACCESS_KEY_ID,
                            secretAccessKey: process.env.SECRET_ACCESS_KEY,
                        });
                        var params = {
                            Bucket: "data-challenge-hackathon", //bucket name
                            Key: "SBIC.v2.tgz"  //file key
                        };
                        s3.getObject(params, function(err, data) {
                            if (err) {
                                console.log(err, err.stack); // an error occurred
                            } else {
                                //const file_buffer = fs.readFileSync(data);
                                //encode contents into base64
                                res.send(data);
                            }
                        })
```

Here is the full stack:

```Error [XMLParserError]: Non-whitespace before first tag.
Line: 0
Column: 1
Char: {
    at error (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:693:7)
    at beginWhiteSpace (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:967:7)
    at SAXParser.write (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:1019:11)
    at Parser.exports.Parser.Parser.parseString (/home/access/code/autackathon/server_webapp/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/access/code/autackathon/server_webapp/node_modules/xml2js/lib/parser.js:5:59)
    at NodeXmlParser.parse (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
    at Request.extractError (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/services/s3.js:700:39)
    at Request.callListeners (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/sequential_executor.js:78:10) {
  code: 'XMLParserError',
  retryable: true,
  time: 2021-09-21T10:05:45.470Z,
  statusCode: 500
} XMLParserError: Non-whitespace before first tag.
Line: 0
Column: 1
Char: {
    at error (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:693:7)
    at beginWhiteSpace (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:967:7)
    at SAXParser.write (/home/access/code/autackathon/server_webapp/node_modules/sax/lib/sax.js:1019:11)
    at Parser.exports.Parser.Parser.parseString (/home/access/code/autackathon/server_webapp/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/home/access/code/autackathon/server_webapp/node_modules/xml2js/lib/parser.js:5:59)
    at NodeXmlParser.parse (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
    at Request.extractError (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/services/s3.js:700:39)
    at Request.callListeners (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/access/code/autackathon/server_webapp/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
```

This happens with private or public buckets and various file types. 

For context I am using these keys and secrets for other services in this app and they work just fine.

**Comment by ajredniwja** [comment]
@bitshiftnetau hi there, not able to reproduce this, can you provide more details about your use case?

**Comment by bitshiftnetau** [comment]
Hi, this is possibly related to a permissions issue on the bucket. Which is odd because I have other buckets that were cloned from, which work to hold private keys. Very odd indeed but seemingly unrelated to this sdk.
