### ISSUE TITLE
UnknownEndpoint: Inaccessible host or InternalFailure: null

### ISSUE THREAD

**Issue by MatteoGioioso** [aws/aws-sdk-js#3906]
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
I am trying to push an image on ECR public repository from github actions using `configure-aws-credentials` plugin, however the the sdk does not seems to work with it, I would ask the maintainers about this error however the sdk throws an `InternalFailure: null` which does not give me any clue from where to start.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Running on Github actions

**Details of the browser/Node.js version**

```
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
```

**SDK version number**

```
aws-sdk@2.996.0
```

**To Reproduce (observed behavior)**

```
const AWS = require("aws-sdk");
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30'
})

await ecr.getAuthorizationToken().promise();

```

This is the error without specifying the endpoint: 

```
UnknownEndpoint: Inaccessible host: `api.ecr-public.ap-southeast-1.amazonaws.com' at port `undefined'. This service may not be available in the `ap-southeast-1' region.
    at Request.ENOTFOUND_ERROR (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/event_listeners.js:530:46)
    at Request.callListeners (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:688:14)
    at error (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/event_listeners.js:362:22)
    at ClientRequest.<anonymous> (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28) {
  code: 'UnknownEndpoint',
  region: 'ap-southeast-1',
  hostname: 'api.ecr-public.ap-southeast-1.amazonaws.com',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND api.ecr-public.ap-southeast-1.amazonaws.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3008,
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'api.ecr-public.ap-southeast-1.amazonaws.com',
    region: 'ap-southeast-1',
    retryable: true,
    time: 2021-10-01T01:42:23.452Z
  },
  time: 2021-10-01T01:42:23.452Z
}
```

As my understanding that endpoint does not exists, therefore I have fixed it in the config

```
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30',
  endpoint: new AWS.Endpoint(`https://api.ecr.ap-southeast-1.amazonaws.com`)
})
```

But I have this error:

```
InternalFailure: null
    at Request.extractError (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/runner/work/saml-proxy/saml-proxy/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InternalFailure',
  time: 2021-10-01T01:44:42.290Z,
  requestId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  statusCode: 500,
  retryable: true
}
```

**Expected behavior**
It should work

**Additional context**

This my Github actions workflow

```
name: My Deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-1
          role-to-assume:arn:aws:iam::000000000000:role/my-role-name
          role-session-name: GitHubActions
      
        ....

```

This is my trust relationship for that role:

```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::000000000:oidc-provider/vstoken.actions.githubusercontent.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringLike": {
          "vstoken.actions.githubusercontent.com:sub": "repo:Owner/my_repo_name:*"
        }
      }
    }
  ]
}
```

This is my OICD provider setup in IAM

![image](https://user-images.githubusercontent.com/43592430/135371310-7471b1bf-ca80-405b-b21b-ae0e9e4c35c4.png)

This is the policy of my role:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ecr-public:DescribeImageTags",
                "ecr-public:DescribeImages",
                "ecr-public:PutRepositoryCatalogData",
                "ecr-public:UploadLayerPart",
                "ecr-public:GetAuthorizationToken",
                "ecr-public:PutImage",
                "ecr-public:UntagResource",
                "ecr-public:ListTagsForResource",
                "ecr-public:TagResource",
                "ecr-public:CompleteLayerUpload",
                "ecr-public:GetRepositoryPolicy",
                "ecr-public:BatchCheckLayerAvailability",
                "sts:GetServiceBearerToken"
            ],
            "Resource": "arn:aws:ecr-public::00000000000:repository/my_repo_name",
            "Effect": "Allow"
        }
    ]
}
```

**Comment by MatteoGioioso** [comment]
Ok, my bad, ecr-public is only available in us-east-1, though the error could have been more descriptive
