### ISSUE TITLE
CodeBuild.createProject runs twice and attempts to create the project twice

### ISSUE THREAD

**Issue by FaresKi** [aws/aws-sdk-js#3974]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.x of the SDK

**Describe the bug**
The `CodeBuild().createProject()` method runs twice, thus attempting to create a CodeBuild project twice.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes.

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
v14.17.6
**SDK version number**
aws-sdk@2.1012.0

**To Reproduce (observed behavior)**
This is my code: 
```ts
let codeBuildParams = {
          name: codeBuildProjectName,
          source: {
            type: "S3",
            location: `${bucketName}/${sourceBucketKey}`,

            buildspec: "buildspec.yml",
          },
          artifacts: {
            type: "S3",
            location: outputBucketName,
          },
          environment: {
            type: "LINUX_CONTAINER",
            image: "aws/codebuild/standard:4.0",
            computeType: "BUILD_GENERAL1_MEDIUM",
            environmentVariables: [
              {
                name: "ARTIFACT_BUCKET",
                type: "PLAINTEXT",
                value: outputBucketName,
              },
              {
                name: "ARTIFACT_VERSION",
                type: "PLAINTEXT",
                value: `v${latestVersion}`,
              },
            ],
          },
          serviceRole: codeBuildRoleArn,
        }

console.debug(`Starting create project call with parameters - ${JSON.stringify(codeBuildParams)}`);
                await codeBuild
                    .createProject(codeBuildParams, (err) => {
                    if (err) {
                        console.error("[CREATE PROJECT] Unexpected error : ", err);
                    }
                })
                    .promise();
...
let startBuildParams = {
                projectName: codeBuildProjectName,
            };
            console.debug("Starting start build call with parameters - " + JSON.stringify(startBuildParams));
            await codeBuild
                .startBuild(startBuildParams, (err) => {
                if (err) {
                    console.error("[START BUILD] Unexpected error : ", err);
                }
            })
```
And this were the results from CloudWatch logs:
```
2021-11-24T13:35:30.815Z	8ddb9d11-ffe3-49e2-a946-5f2e42010486	DEBUG	Starting create project call with parameters - {
    ...
}
2021-11-24T13:35:31.124Z	8ddb9d11-ffe3-49e2-a946-5f2e42010486	DEBUG	Starting start build call with parameters - {
    "projectName": "xxxxxxxxxxx"
}

2021-11-24T13:35:31.133Z	8ddb9d11-ffe3-49e2-a946-5f2e42010486	ERROR	[CREATE PROJECT] Unexpected error :  ResourceAlreadyExistsException: Project already exists: arn:aws:codebuild:eu-central-1:xxxxxx:project/xxxxxxxxxxx
    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ResourceAlreadyExistsException',
  time: 2021-11-24T13:35:31.132Z,
  requestId: '8817e056-02c0-4e53-8e38-1cb96d86b9a1',
  statusCode: 400,
  retryable: false,
  retryDelay: 64.05346345251459
}

```
**Expected behavior**
I expected it to create the project so I can start the build using CodeBuild's `startBuild()` method. 

**Screenshots**

**Additional context**

**Comment by vudh1** [comment]
Hi @FaresKi thanks for reaching out. I am not able to reproduce your problem. Can you check if you are still experience this with the latest version of SDK? Also, please follow [this documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CodeBuild.html#createProject-property) with the code below to create new project, and make sure to call the `createProject` only once:

```js
import AWS from 'aws-sdk';

var codebuild = new AWS.CodeBuild({region: REGION});

var params = {
    //folow the documentation
};

codebuild.createProject(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```
