### ISSUE TITLE
Amazon DynamoDB - Remote DB Connection Issue - InvalidSignatureException: Credential should be scoped to a valid region, not 'eu-east-2'

### ISSUE THREAD

**Issue by saru2020** [aws/aws-sdk-js#4002]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x] This is an issue with version 2.1048.0 of the SDK

**Describe the bug**
**Code:**

> var AWS = require("aws-sdk");
> 
> AWS.config.update({
>     region: DynamoDBConfig.region,
>     endpoint: DynamoDBConfig.endpoint,
>     accessKeyId: DynamoDBConfig.accessKeyId,//process.env.AWS_ACCESS_KEY_ID,
>     secretAccessKey: DynamoDBConfig.secretAccessKey//process.env.AWS_SECRET_ACCESS_KEY
> });
> 
> var dynamodb = new AWS.DynamoDB.DocumentClient();

**Error:**

> err:  InvalidSignatureException: Credential should be scoped to a valid region, not 'eu-east-2'. 
    at Request.extractError (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/saravanan_vij/Documents/Personal/GitHub/Backtester/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidSignatureException',
  time: 2021-12-29T20:57:21.036Z,
  requestId: 'EAJ9ICHOME8MRILJ9FUB516SM3VV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 27.221431963227772
}

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
v14.15.5

**SDK version number**
aws-sdk@2.1048.0 

**Expected behavior**
AWS.DynamoDB() should work without any issues

**Additional context**
Note: The same code is working fine for Amazon DynamoDB Local, whereas the issue occurs only for the remote db!

**Comment by saru2020** [comment]
Also, i tried [this aws4 solution](https://github.com/aws/aws-sdk-js/issues/168#issuecomment-38233913), which is working, which means the issue exists in aws-sdk only? (I tried using different aws-sdk versions as well but still no luck in making it to work)

**Comment by saru2020** [comment]
the issue was occurring because of the typo in the region where I had this: 'eu-east-2' instead of this: ''us-east-2'

I got an input only [here](https://repost.aws/questions/QUK5A9Y_82SWGsdpE-c0AxGA/dyanamo-db-connection-issue-aws-sdk-for-node-js), looks like people are active only Amazon's repost.
