### ISSUE TITLE
SignatureDoesNotMatch: Signature expired

### ISSUE THREAD

**Issue by pvsrivathsa** [aws/aws-sdk-js#401]
Node.js version `0.10.25`

AWS SDK Version `latest - 2.0.23`

I have an app that is continuously listening to a Queue (SQS) and if there are messages posted in that queue the app will read the message and process it and save some data to S3. When I start the app after about 20 minutes I am getting the following error continuously. `Potentially unhandled rejection [160]` the number in the bracket indicates the number of times the error occurs. It goes on till like `20000` till I stop the app and restart it.

```
Potentially unhandled rejection [160] SignatureDoesNotMatch: Signature expired: 20141104T062952Z is now earlier than 20141104T062952Z (20141104T064452Z - 15 min.)
at Request.extractError (/myproject/node_modules/aws-sdk/lib/protocol/query.js:39:29)
at Request.callListeners (/myproject/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
at Request.emit (/myproject/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/myproject/node_modules/aws-sdk/lib/request.js:604:14)
at Request.transition (/myproject/node_modules/aws-sdk/lib/request.js:21:12)
at AcceptorStateMachine.runTo (/myproject/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /myproject/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/myproject/node_modules/aws-sdk/lib/request.js:22:9)
at Request.<anonymous> (/myproject/node_modules/aws-sdk/lib/request.js:606:12)
at Request.callListeners (/myproject/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

It is not an issue with my system time. My system time is in sync with the time of my EC2 instance. Why am I getting this error? Is it related to SQS or S3?

**Comment by binoculars** [comment]
It's a system time issue http://stackoverflow.com/questions/18295185/invalidsignatureexception-signature-expired-timestamp-is-now-earlier-than-t

**Comment by charitha-bridg** [comment]
I experienced this issue today, and fortunately, the AWS NodeJS SDK now has a config option to fix the clock offset by itself:

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property

**Comment by stephanebruckert** [comment]
Just type this in your terminal and it will be fine.

     sudo ntpdate ntp.ubuntu.com
