### ISSUE TITLE
apprunner createService from source code

### ISSUE THREAD

**Issue by FredericHeem** [aws/aws-sdk-js#4029]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [x ] This is an issue with version 2.x of the SDK

**Describe the bug**
Creation of an AppRunner Service with the `CodeRepository` option, the docker image `ImageRepository` options works fine BTW.

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`
node 16

**SDK version number**
2.1074.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

A [repo](https://github.com/FredericHeem/aws-sdk-2-apprunner) has been created to reproduce the error:

```sh
git https://github.com/FredericHeem/aws-sdk-2-apprunner
cd aws-sdk-2-apprunner
npm install 
node index.js
```

Given the payload:
```
const payload = {
  SourceConfiguration: {
    CodeRepository: {
      RepositoryUrl: "https://github.com/grucloud/grucloud",
      SourceCodeVersion: {
        Type: "BRANCH",
        Value: "main",
      },
      CodeConfiguration: {
        ConfigurationSource: "API",
        CodeConfigurationValues: {
          Runtime: "NODEJS_12",
          BuildCommand: "npm install;npm run bootstrap",
          StartCommand: "npm run start:mock",
          Port: "8089",
          RuntimeEnvironmentVariables: {
            NODE_CONFIG: "'{}'",
          },
        },
      },
    },
    AutoDeploymentsEnabled: false,
    ImageRepository: undefined,
  },
  InstanceConfiguration: {
    Cpu: "1024",
    Memory: "2048",
  },
  HealthCheckConfiguration: {
    Protocol: "TCP",
    Path: "/",
    Interval: 10,
    Timeout: 5,
    HealthyThreshold: 1,
    UnhealthyThreshold: 5,
  },
};
```

to [apprunner.createService](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AppRunner.html#createService-property) results in the following error:

```txt
Error [TypeError]: Cannot read properties of undefined (reading 'ImageIdentifier')
    at ParamValidator.validateStructure (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/param_validator.js:60:25)
    at ParamValidator.validateMember (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/param_validator.js:89:21)
    at ParamValidator.validateStructure (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/param_validator.js:76:14)
    at ParamValidator.validateMember (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/param_validator.js:89:21)
    at ParamValidator.validateStructure (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/param_validator.js:76:14)
    at ParamValidator.validateMember (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/param_validator.js:89:21)
    at ParamValidator.validate (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/Users/fredericheem/aws-sdk-2-apprunner/node_modules/aws-sdk/lib/sequential_executor.js:96:12) {
  code: 'TypeError',
  time: 2022-02-17T03:18:07.622Z
```

**Comment by vudh1** [comment]
Hi @FredericHeem thanks for reaching out. You are missing some variables in params for `ImageRepository`:
```js
ImageRepository: {
      ImageIdentifier: 'STRING_VALUE', /* required */
      ImageRepositoryType: ECR | ECR_PUBLIC, /* required */
      ImageConfiguration: {
        Port: 'STRING_VALUE',
        RuntimeEnvironmentVariables: {
          '<RuntimeEnvironmentVariablesKey>': 'STRING_VALUE',
          /* '<RuntimeEnvironmentVariablesKey>': ... */
        },
        StartCommand: 'STRING_VALUE'
      }
    }
```
Please refer to [this documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AppRunner.html#createService-property) also.

**Comment by FredericHeem** [comment]
There are 2 modes for the *createService* API, via *CodeRepository* or via * ImageRepository*: `You must provide either this member or ImageRepository (but not both).`
