### ISSUE TITLE
issue with aws service discovery javascript

### ISSUE THREAD

**Issue by Ravi-Rsankar** [aws/aws-sdk-js#4072]
Im developing a nodejs application that needs to register to the AWS service discovery on the app start. I'm using the @aws-sdk/client-servicediscovery lib in my node application. As a reference, I am using the code from here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-servicediscovery/index.html.

```
const { ServiceDiscoveryClient, CreateHttpNamespaceCommand } = require("@aws-sdk/client-servicediscovery");
const client = new ServiceDiscoveryClient({ region: "xxx" });
const params = {
    "ServiceId":"xxx",
    "InstanceId":"xxx",
    "CreatorRequestId":new Date(new Date().toUTCString()),
    "Attributes": {
        AWS_INSTANCE_IPV4: "xxx.xx.xx.xx",
        AWS_INSTANCE_PORT: xxx,
        service: "xxx",
      }
};

const command = new CreateHttpNamespaceCommand(params);
client.send(command).then(
    (data) => {
      console.log(data)
    },
    (error) => {
        console.log(error)
    }
  );

```
While running the app, getting these errors.
```
/application/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/slurpFile.js:5
const { readFile } = fs_1.promises;
        ^

TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.
    at Object.<anonymous> (/application/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/slurpFile.js:5:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/application/node_modules/@aws-sdk/shared-ini-file-loader/dist-cjs/loadSharedConfigFiles.js:8:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
I am new to the AWS SD so need some help registering my service to the service discovery. Thanks in advance!

**Comment by ajredniwja** [comment]
@Ravi-Rsankar thanks for opening the issue, transferring it to the correct repo. 
https://github.com/aws/aws-sdk-js-v3
