### ISSUE TITLE
InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'

### ISSUE THREAD

**Issue by openedhardware** [aws/aws-sdk-js#4097]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [ x] This is an issue with version 2.x of the SDK

**Describe the bug**
Here is a testing code:
```
const AWS = require('aws-sdk')

AWS.config.region = process.env.AWS_DEFAULT_REGION
AWS.config.accessKeyId = process.env.AWS_ACCESS_KEY_ID
AWS.config.secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY

const iot = new AWS.Iot({
    endpoint: process.env.AWS_MQTT_BROKER_ENDPOINT,
  }
)

const iotdata = new AWS.IotData({
  endpoint: process.env.AWS_MQTT_BROKER_ENDPOINT,
})

// This works
const things = await iot.listThings().promise()

// This doesn't work
const shadow = await iotdata.getThingShadow({thingName: "my_thing_name"}).promise()
```

**Is the issue in the browser/Node.js?**
Node.js: v16.14.2

**If on Node.js, are you running this on AWS Lambda?**
No

**SDK version number**
Example: v2.1122.0

**Error Message**
```
error:  - StatusCode: 500.. Stack: InvalidSignatureException: Credential should be scoped to correct service: 'execute-api'.
    at Object.extractError (E:\workspace\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.extractError (E:\workspace\node_modules\aws-sdk\lib\protocol\rest_json.js:49:8)
    at Request.callListeners (E:\workspace\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (E:\workspace\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (E:\workspace\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (E:\workspace\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\workspace\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\workspace\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\workspace\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\workspace\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (E:\workspace\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (E:\workspace\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (E:\workspace\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (E:\workspace\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\workspace\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\workspace\node_modules\aws-sdk\lib\state_machine.js:26:10

```

**Comment by ajredniwja** [comment]
Hi @openedhardware thanks for opening this issue, would you be able to share what the endpoint looks like. Should be something like: end.jobs.iot.us-west-2.amazonaws.com

**Comment by colinbr96** [comment]
For me, the issue was that I needed to pass `execute-api` as the service in the Sigv4 authorization. https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html#signing-request-intro

**Comment by larrasket** [comment]
STUCK
