### ISSUE TITLE
Invalid Argument null issue - AWS sdk - Digital Ocean spaces

### ISSUE THREAD

**Issue by veera-clarbloc** [aws/aws-sdk-js#4103]
Confirm by changing [ ] to [x] below:
- [ ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ ] This is an issue with version 2.x of the SDK

**Describe the question**

we have been working on digital ocean platform spaces. using AWS sdk only we can interact with spaces(S3). But, we got InvalidArgument  : null issue while uploading documents. Here I have attached the code and issue details. let us know If we have to do any changes there

### Code Details

```js
const aws = require('aws-sdk');
const express = require('express');
const multer = require('multer');
const multerS3 = require('multer-s3');

const app = express();

// Use our env vars for setting credentials.
// Remove lines 11-14 if using ~/.aws/credentials file on a local server.
aws.config.update({
accessKeyId: "",
secretAccessKey: ""
});

// Set S3 endpoint to DigitalOcean Spaces
const spacesEndpoint = new aws.Endpoint('https://sgp1.digitaloceanspaces.com/');

const s3 = new aws.S3({
endpoint: spacesEndpoint,
region : "sgp1"
});

// Change bucket property to your Space name
const upload = multer({
storage: multerS3({
s3: s3,
bucket: 'slaylewks-spaces',
acl: 'public-read',
key: function (request, file, cb) {
console.log(file);
cb(null, file.originalname);
},
contentType: function (req, file, cb) {
cb(null, `application/pdf`);
},
})
}).array('upload', 1);

// Views in public directory
app.use(express.static('public'));

// Main, error and success views
app.get('/', function (request, response) {
response.sendFile(__dirname '/public/index.html');
});

app.get("/success", function (request, response) {
response.sendFile(__dirname '/public/success.html');
});

app.get("/error", function (request, response) {
response.sendFile(__dirname '/public/error.html');
});

app.post('/upload', function (request, response, next) {
upload(request, response, function (error) {
if (error) {
console.log(error);
return response.redirect("/error");
}
console.log('File uploaded successfully.');
response.redirect("/success");
});
});

app.listen(3000, function () {
console.log('Server listening on port 3000.');
});



```

### Issue Details

```
InvalidArgument: null
    at Request.extractError (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/veerav/dev/nodejs/spaces-node-app/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'InvalidArgument',
  region: null,
  time: 2022-05-04T09:28:17.815Z,
  requestId: 'tx00000000000000319ce21-0062724731-1514f8f4-sgp1b',
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 58.08890611905157,
  storageErrors: []
}

```

**Comment by VigneshQikink** [comment]
it looks like the issue is mentioning the region. Try 'Singapore'. If you got solution post here
