### ISSUE TITLE
@aws-sdk/client-emr-containers cannot call describeJobRun

### ISSUE THREAD

**Issue by clhuang** [aws/aws-sdk-js#4107]
**Describe the bug**
parsing of createdAt and finishedAt job fields do not appear to work

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
@aws-sdk/client-emr-containers@3.87.0

**To Reproduce (observed behavior)**
```js
const { EMRContainers } = require('@aws-sdk/client-emr-containers');
(async () => {
  const VIRTUAL_CLUSTER_ID = 'xxxxxxxxxx';
  const jobRunId = 'xxxxxxx';

  const client = new EMRContainers({
    region: 'us-west-2',
  });
  const data = await client.describeJobRun({
    id: jobRunId,
    virtualClusterId: VIRTUAL_CLUSTER_ID,
  });
})();
```

receive the error:
```
/Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:32
    throw new TypeError(`Expected number, got ${typeof value}`);
          ^

TypeError: Expected number, got string
    at expectNumber (/Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:32:11)
    at deserializeAws_restJson1JobRun (/Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/dist-cjs/protocols/Aws_restJson1.js:1497:124)
    at deserializeAws_restJson1DescribeJobRunCommand (/Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/dist-cjs/protocols/Aws_restJson1.js:767:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /Users/calvinhuang/scale/scaleapi3/server/node_modules/@aws-sdk/client-emr-containers/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async /Users/calvinhuang/scale/scaleapi3/server/thingy.js:11:16 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

**Expected behavior**
no error is thrown, `data` contains job data

**Screenshots**

**Additional context**

**Comment by clhuang** [comment]
It appears the documentation is incorrect: https://docs.aws.amazon.com/emr-on-eks/latest/APIReference/API_DescribeJobRun.html

`createdAt` and `finishedAt` are stated as numbers, but when I make a HTTP call to the endpoint they're returned as ISO datestrings: 
![image](https://user-images.githubusercontent.com/1694228/168347375-13e73dff-0427-48e3-ac8c-e442c15686a2.png)
