### ISSUE TITLE
S3 Client file upload does not work with minio if the file name / key contains umlauts along with the same file name in the Metadata

### ISSUE THREAD

**Issue by Arun-KumarH** [aws/aws-sdk-js#4109]
### Describe the bug

We have an issue with file upload with minio, if the file name contains umlauts and same key name is used in Metadata then we get `SignatureDoesNotMatch` error.
(If we omit the Key name in the Metadata then the file upload works fine with umlauts).

S3 file upload (s3Upload.js) :
```js
const aws = require('aws-sdk');
const s3Client = new aws.S3({
  accessKeyId: "minioAccessKey",
  secretAccessKey: "minioSecretKey",
  endpoint: "http://127.0.0.1:9000",
  s3ForcePathStyle: true
});
async function uploadFile(bucket, key) {
  const result = await new Promise((resolve, reject) => {
    s3Client.upload({
      Key: key,
      Bucket: bucket,
      Body: 'test body',
      Metadata: {
        key
      }
    }, (err, data) => {
      if (err) {
        console.log('Error while storing object',
          {
            Key: key, Bucket: bucket, error: err, errStack: err.stack
          });
        resolve(err);
      } else {
        resolve(data);
      }
    });
  });
  console.log('Upload result', result);
}

uploadFile('test', 'ä_ü_ö.txt').then((err, data) => {
  if (err) {
    console.log('Error', err);
  }
  console.log('Data', data);
});
```

Minio Docker compose file (minio-docker-compose.yaml) :
```
   version: '3.7'
   services:
    minio:
      image: minio/minio:RELEASE.2022-05-19T18-20-59Z
      tty: true
      command: ["server", "/data", "--console-address", ":9001"]
      environment:
        MINIO_ROOT_USER: minioAccessKey
        MINIO_ROOT_PASSWORD: minioSecretKey
      ports:
        - 9000:9000
        - 9091:9001
```

### Expected Behavior

File upload with Metadata containing key name should have been successful

### Current Behavior

File upload fails with below stack:
```
  errStack: 'SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n' +
    '    at Request.extractError (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/services/s3.js:711:35)\n' +
    '    at Request.callListeners (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n' +
    '    at Request.emit (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
    '    at Request.emit (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/request.js:686:14)\n' +
    '    at Request.transition (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/request.js:22:10)\n' +
    '    at AcceptorStateMachine.runTo (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/state_machine.js:14:12)\n' +
    '    at /home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/state_machine.js:26:10\n' +
    '    at Request.<anonymous> (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/request.js:38:9)\n' +
    '    at Request.<anonymous> (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/request.js:688:12)\n' +
    '    at Request.callListeners (/home/akumar/github/ostorage-srv/node_modules/aws-sdk/lib/sequential_executor.js:116:18)'
}
```

### Reproduction Steps

1) Spin up the minio using the docker compose command
`docker-compose -f minio-docker-compose.yaml up`
2) Loginto minio and create a `test` bucket.
2) Execute file upload script:
`node s3Upload.js` - upload fails with signature mismatch error.
If Metadata containing Key is dropped, then file upload works fine.

### SDK version used

2.1141.0

### Environment details (OS name and version, etc.)

openSUSE Tumbleweed

**Comment by ajredniwja** [comment]
Hi @Arun-KumarH thanks for opening this issue, yes some of the special characters cause this when they are not encoded.
The workaround for the would be to use something like: 
```
    Metadata: {
        'key': encodeURIComponent("ä_ü_ö.txt")
    }
```

**Comment by aBurmeseDev** [comment]
Hi there - checking in here. Please let us know if there's any action item for SDK team to address here. If not, disregard this and feel free to reach out again.
