### ISSUE TITLE
Throttling: Rate exceeded error thrown

### ISSUE THREAD

**Issue by rclark** [aws/aws-sdk-js#412]
We've written a library that polls CloudFormation to determine a stack's status after a `createStack` or `updateStack` call. We've been encountering throttling errors like this one:

```
/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/request.js:32
          throw err;
                ^
Throttling: Rate exceeded
    at Request.extractError (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/protocol/query.js:39:29)
    at Request.callListeners (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /.../cfn-stack-event-stream/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/.../cfn-stack-event-stream/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

It appears that the error is not being handled in aws-sdk and so we can't handle it downstream with a back-off routine. I'm wondering why this error seems to be sneaking through aws-sdk?

Thanks!

**Comment by patrick-motard** [comment]
I'm getting this same error for Cloudwatch `putMetricAlarm`. Is this expected?

```
{ Throttling: Rate exceeded
    at Request.extractError (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:675:12)
    at Request.callListeners (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/han/code/aws-utilities/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/han/code/aws-utilities/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'Rate exceeded',
  code: 'Throttling',
  time: 2017-05-24T00:11:10.473Z,
  requestId: '7da27912-4015-11e7-a4b7-19825624989e',
  statusCode: 400,
  retryable: true }

```

**Comment by justinmchase** [comment]
I am getting this error from the `CloudSearch` api, would this need to be added for each api?
```
Error: Rate exceeded
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:678:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:680:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

The calling code:
```
import { CloudSearch, CloudSearchDomain } from 'aws-sdk'
// get domain and items then...
function send (domain, items) {
  let params = {
    contentType: 'application/json',
    documents: JSON.stringify(items)
  }
  domain.uploadDocuments(params, callback) // unhandled exception is thrown
}
```
