### ISSUE TITLE
`deleteObjects`: BadRequest: An error occurred when parsing the HTTP request POST at '/'

### ISSUE THREAD

**Issue by baptisteArno** [aws/aws-sdk-js#4137]
### Describe the bug

When calling `deleteObjects` like this:

```ts
const s3 = new S3({
    endpoint: new Endpoint("http://localhost:9000"),
  })

await s3
      .deleteObjects({
        Bucket: 'typebot',
        Delete: {
          Objects: [
          {
            Key: 'public/results/cl4sbjjl00230kq1a2boclkr0/cl45ojzs300092e6gkno525c4/api.json',
          },
        ],
        },
      })
      .promise()
```

It fails with the error:

```
builder:dx: BadRequest: An error occurred when parsing the HTTP request POST at '/'
builder:dx:     at Request.extractError (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/services/s3.js:711:35)
builder:dx:     at Request.callListeners (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
builder:dx:     at Request.emit (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
builder:dx:     at Request.emit (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/request.js:686:14)
builder:dx:     at Request.transition (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/request.js:22:10)
builder:dx:     at AcceptorStateMachine.runTo (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/state_machine.js:14:12)
builder:dx:     at /Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/state_machine.js:26:10
builder:dx:     at Request.<anonymous> (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/request.js:38:9)
builder:dx:     at Request.<anonymous> (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/request.js:688:12)
builder:dx:     at Request.callListeners (/Users/baptistearno/Dev/typebot-os/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
builder:dx:   code: 'BadRequest',
builder:dx:   region: null,
builder:dx:   time: 2022-06-24T10:50:11.665Z,
builder:dx:   requestId: null,
builder:dx:   extendedRequestId: undefined,
builder:dx:   cfId: undefined,
builder:dx:   statusCode: 400,
builder:dx:   retryable: false,
builder:dx:   retryDelay: 37.40754179823607
builder:dx: }
```

### Expected Behavior

No errors and successful delete.

### Current Behavior

Cf "Describe the bug"

### Reproduction Steps

1. Set up a local minio service
2. Connect the s3 lib to it
3. Call the `deleteObjects` method

### SDK version used

2.1152.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by yenfryherrerafeliz** [comment]
@baptisteArno sorry to hear about your issues. I see that you are using a custom endpoint, and the error itself could be coming from there. By using the correct s3 endpoint I get not issues. 
Please see below:
```js
import AWS from "aws-sdk";

const s3 = new AWS.S3({
    region: 'us-east-1',
    endpoint: new AWS.Endpoint('https://s3.amazonaws.com')
});
s3.deleteObjects({
    Bucket: process.env.TEST_BUCKET,
    Delete: {
        Objects: [
            {
                Key: 'public/results/cl4sbjjl00230kq1a2boclkr0/cl45ojzs300092e6gkno525c4/api.json'
            }
        ]
    }
})
.promise()
.then((response) => {
    console.log(response);
}).catch((err) => {
    console.log('Error: ', err);
});
```
Results:
```console
{
  Deleted: [
    {
      Key: 'public/results/cl4sbjjl00230kq1a2boclkr0/cl45ojzs300092e6gkno525c4/api.json'
    }
  ],
  Errors: []
}
```

I know sometimes we need custom endpoints, maybe for testing, etc. But in this case, could you please check your endpoint is able to handle the request correctly. 

Thanks!

**Comment by koorya** [comment]
According to [this](https://northflank.com/guides/connect-nodejs-to-minio-with-tls-using-aws-s3)  **forcePathStyle: true** shoud help.
```js
const { S3Client } = require(“@aws-sdk/client-s3”);
const s3 = new S3Client({
   credentials: {
       accessKeyId: process.env.ACCESS_KEY,
       secretAccessKey: process.env.SECRET_KEY,
   },
   endpoint: process.env.ENDPOINT,
   forcePathStyle: true,
});
```
