### ISSUE TITLE
aws-sdk related CI build error when building angular 13 app

### ISSUE THREAD

**Issue by DilsBlanco** [aws/aws-sdk-js#4147]
### Describe the bug

We are trying to build our angular app via the github CI. 
We are using the aws-sdk to send images to an S3 bucket.

### Expected Behavior

W expect the build to pass

### Current Behavior

The build breaks and we get this error 
(the /.../ is a long number the build returned but not sure if they are confidential to our account so took them out):
```
TypeError: region.split is not a function
    at generateRegionPrefix (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/region_config.js:6:22)
    at derivedKeys (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/region_config.js:13:22)
    at Object.configureEndpoint (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/region_config.js:38:14)
    at features.constructor.initialize (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/service.js:72:45)
    at features.constructor.Service [as constructor] (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/service.js:59:10)
    at features.constructor (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/util.js:637:24)
    at new features.constructor (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/util.js:637:24)
    at features.constructor.Service [as constructor] (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/service.js:50:17)
    at new features.constructor (/home/runner/.npm/_npx/..../node_modules/aws-sdk/lib/util.js:637:24)
    at _callee3$ (/home/runner/.npm/_npx/..../node_modules/s3-deploy/dist/deploy.js:406:22)
```

### Reproduction Steps

Build start automatically when we update developer in the github repo via CI.

### Possible Solution

I have noticed that in the region_config.js con file file the region.split function parses region details. This parsing compares the given region to a list of regions in the region_config_data.json file.
[https://github.com/aws/aws-sdk-js/blob/master/lib/region_config_data.json](https://github.com/aws/aws-sdk-js/blob/master/lib/region_config_data.json)
I noticed that he region we are using (eu-south-1) is not in the list (around line 51 on file above):
```
 "ap-south-1/ec2": "dualstackLegacyEc2",
    "eu-west-1/ec2": "dualstackLegacyEc2",
    "sa-east-1/ec2": "dualstackLegacyEc2",
    "us-east-1/ec2": "dualstackLegacyEc2",
    "us-east-2/ec2": "dualstackLegacyEc2",
    "us-west-2/ec2": "dualstackLegacyEc2"
```
Should the missing region be added to this list?

### SDK version used

2.1167.0

### Environment details (OS name and version, etc.)

angular 13, github account

**Comment by DilsBlanco** [comment]
Closing as it was fixed in another way, yaml code change sorted the build.
npm install was the issue.

**Comment by jmckie94** [comment]
@DilsBlanco what change did you make to fix the issue? I'm also getting this error for ap-southeast-2.

**Comment by SerafimOrlov** [comment]
same error for React+NextJs app, any solutions?
