### ISSUE TITLE
Unable to launch reactjs app with vite when importing Amplify.

### ISSUE THREAD

**Issue by xaguzman** [aws/aws-sdk-js#4239]
### Describe the bug

When I start my application with `vite dev` The app break as soon as I add `import Amplify from 'aws-amplify';` in one of my components.

here's the stack trace:
```
```
12:41:05 PM [vite] page reload src/main.jsx
✘ [ERROR] No matching export in "node_modules/@aws-amplify/datastore/lib-esm/types.js" for import "__modelMeta__"

    node_modules/@aws-amplify/datastore/lib-esm/sync/index.js:72:17:
      72 │ import { OpType, __modelMeta__, } from '../types';
         ╵                  ~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/@aws-amplify/datastore/lib-esm/types.js" for import "__modelMeta__"

    node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js:101:139:
      101 │ ...alarType, isSchemaModelWithAttributes, AuthModeStrategyType, isNonModelFieldType, isModelFieldType, __modelMeta__, isIdentifierObject, } from '../types';
          ╵                                                                                                        ~~~~~~~~~~~~~

12:41:06 PM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js:101:139: ERROR: No matching export in "node_modules/@aws-amplify/datastore/lib-esm/types.js" for import "__modelMeta__"
node_modules/@aws-amplify/datastore/lib-esm/sync/index.js:72:17: ERROR: No matching export in "node_modules/@aws-amplify/datastore/lib-esm/types.js" for import "__modelMeta__"
    at failureErrorWithLog (/files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:1566:15)
    at /files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:1024:28
    at runOnEndCallbacks (/files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:1438:61)
    at buildResponseToResult (/files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:1022:7)
    at /files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> (/files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/files/projects/serverless-inventory/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

```
```

### Expected Behavior

The app should launch normally

### Current Behavior

The dev server crashes and my application is unable to use aws-amplify library.

### Reproduction Steps

After having a backend configured via `amplify init`:

1. `yarn add aws-amplify`
2. Import Amplify into my main component (not even try to configure it yet):
    * `import Amplify from 'aws-amplify';`
3. `yarn dev`
4. Server crashes and the stacktrace above is printed

### SDK version used

 aws-amplify "aws-amplify": "^4.3.38"

### Environment details (OS name and version, etc.)

Arch Linux, amplify/cli v10.2.3, node 18.11.0; also happens on node  16.18.0

**Comment by xaguzman** [comment]
Apologies, I created this issue on the wrng tab in my browser, I meant to create it in [https://github.com/aws-amplify/amplify-js/](https://github.com/aws-amplify/amplify-js/).
