### ISSUE TITLE
IncompleteSignatureException - SSM

### ISSUE THREAD

**Issue by jeyarajcs** [aws/aws-sdk-js#4285]
### Describe the bug

The recent release `2.1262.0`, causes the  SSM parameter fetching issue and leads to container crashes.

I am attaching the traces below.
```
IncompleteSignatureException: Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization=AWS xxxxx:yyyyyyy
    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
```

   Everything was working fine till today morning, and we pushed some changes from our side, but then the containers started crashing. After spending an hour, we figured that the issue was from `aws-sdk@2.1262.0`. Now we reverted to `aws-sdk@2.1259.0` and things are working well. 

### Expected Behavior

The containers/code should work without any issues.

### Current Behavior

The containers/code crashes constantly. 

### Reproduction Steps

Try the new SDK version `2.1262.0`

### Possible Solution

I think the latest change in the SDK might contain some strict validation. Please add some backward compatibility. 

### SDK version used

2.1262.0

### Environment details (OS name and version, etc.)

Linux/Ubuntu

**Comment by kayman-mk** [comment]
Same here with the SES service.

**Comment by brainframe-me** [comment]
This is causing a lot of problems all over the serverless world
https://github.com/serverless/serverless/issues/11561

**Comment by Drilmo** [comment]
+1

**Comment by MehranJanfeshan** [comment]
+1

**Comment by BasilaryGroup** [comment]
+1

**Comment by trivikr** [comment]
@jeyarajcs @kayman-mk Do you have a minimal repro that we can use to reproduce this?

**Comment by ajredniwja** [comment]
Related to https://github.com/aws/aws-sdk-js/issues/4286, the team is working on pushing a fix.

**Comment by trivikr** [comment]
Closing as duplicate of https://github.com/aws/aws-sdk-js/issues/4286

Please comment with a minimal repro, or open a new [bug report](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug-report.yml&title=%28short+issue+description%29) if the issue continues to exist after `v2.1263.0` release.
