### ISSUE TITLE
Personalize Recommender minRecommendationRequestsPerSecond

### ISSUE THREAD

**Issue by gabrieleCutowl** [aws/aws-sdk-js#4315]
### Describe the issue

Trying to modify the minRecommendationRequestsPerSecond of a personalize recommender I'm always getting this error: 

`2023-01-04T16:08:34.439Z	e984d0bb-77cb-44b6-b903-4be77e02b54c	INFO	UnexpectedParameter: Unexpected key 'minRecommendationRequestsPerSecond' found in params.recommenderConfig
    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9 {
  code: 'UnexpectedParameter',
  time: 2023-01-04T16:08:34.438Z
}
`

This is the parameters used:
`{
  recommenderArn: 'arn:xxx',
  recommenderConfig: {
    itemExplorationConfig: { explorationWeight: '0.3', explorationItemAgeCutOff: '3' },
    minRecommendationRequestsPerSecond: 3
  }
}`

### Links

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Personalize.html#updateRecommender-property

**Comment by ajredniwja** [comment]
Hey @gabrieleCutowl thanks for opening this issue, can you mention the SDK version? 
Can you make sure it is > 2.1067.0 as I can see the param was added in that version.
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#210670

**Comment by gabrieleCutowl** [comment]
Hi @ajredniwja, you are right I was using the default SDK version that doesn't include the parameter.

After specifying a newer version of the SDK the behaviour was fixed.

Thank you!
