### ISSUE TITLE
Getting error: `TypeError: Cannot read properties of undefined (reading 'byteLength')` when requesting signed URL from MRAP

### ISSUE THREAD

**Issue by LawrenceWarren** [aws/aws-sdk-js#4321]
### The issue
I am trying to get a signed URL for an S3 object via a Multi-Region Access Point. I can fetch a signed URL for the object when trying to access directly from a bucket, but not when accessing through the MRAP. I can fetch other resources from an MRAP.

### Code

```typescript
import { everything_relevant } from '@aws-sdk/various-sdks';

const MRAP = 'arn:aws:s3::0123456789:accesspoint/my_mrap_id.mrap';
const BUCKET = 'my-bucket-name';

const CLIENT = new S3Client({
  region: 'eu-west-1',
  disableMultiregionAccessPoints: false,
  credentials: {
    accessKeyId: env.ACCESS_KEY_ID as string,
    secretAccessKey: env.SECRET_ACCESS_KEY_ID as string
  }
});

export async function get_s3_presigned_url(
  key: string,
  version: string | undefined = undefined,
  mrap: boolean = false
) {
  try {
    const get_obj = new GetObjectCommand({
      Bucket: mrap ? MRAP : BUCKET,
      Key: key,
      VersionId: version,
      ResponseCacheControl: CACHE_CONTROL_HEADER
    });

    let url = await getSignedUrl(CLIENT, get_obj, { expiresIn: 30 * 60 });
    console.log(`URL is ${url}`);
    return url;
  } catch (error) {
    console.error(error);
    return error as string;
  }
}
```

### Expected Behavior

If I call `get_s3_presigned_object_url('path/to/myobject.png', undefined, false)` _or_ call `get_s3_presigned_object_url('path/to/myobject.png', undefined, true)`, I get a valid signed URL to the object, regardless of whether the MRAP or S3 bucket is used. **Success 🎉**

(I'd like to stress, using the MRAP endpoint to actually call the `GetObjectCommand` does work, I do get the object. It is only when trying to get a presigned URL that it fails)

### Current Behavior

If I call `get_s3_presigned_object_url('path/to/myobject.png', undefined, false)`, the `GetObjectCommand` uses the bucket ID; I get a valid signed URL to the object. **Success 🎉**

If I call `get_s3_presigned_object_url('path/to/myobject.png', undefined, true)`, the `GetObjectCommand` uses the MRAP ID; I do not get a valid signed URL to the object, I get the error:

```
TypeError: Cannot read properties of undefined (reading 'byteLength')
    at fromArrayBuffer (~/docs/my_proj/node_modules/@aws-sdk/util-buffer-from/dist-cjs/index.js:6:60)
    at castSourceData (~/docs/my_proj/node_modules/@aws-sdk/hash-node/dist-cjs/index.js:29:51)
    at Hash.update ~/docs/my_proj/node_modules/@aws-sdk/hash-node/dist-cjs/index.js:12:26)
    at hmac (~/docs/my_proj/node_modules/@aws-sdk/signature-v4/dist-cjs/credentialDerivation.js:36:10)
    at getSigningKey (~/docs/my_proj/node_modules/@aws-sdk/signature-v4/dist-cjs/credentialDerivation.js:22:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

### Reproduction Steps

Copy/paste the code above, using your own correct values for an MRAP ID, S3 Bucket ID, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

### SDK version used

@aws-sdk/client-s3: "3.245.0", @aws-sdk/s3-request-presigner: "3.245.0", @aws-sdk/signature-v4-crt: "^3.226.0"

### Environment details (OS name and version, etc.)

MacOS 13.1, NodeJS v16.17.0

**Comment by ajredniwja** [comment]
Transferring to V3 repo
