### ISSUE TITLE
Unexpected key 'ServerlessV2ScalingConfiguration' found in params

### ISSUE THREAD

**Issue by CamilleINGOUF** [aws/aws-sdk-js#4326]
### Describe the bug

I have a shared DBClusterSnapshot from an aurora Serverless v2 DB Cluster.

I'm trying to restore a DB Cluster in a lambda from this snapshot using this code:
```js
import AWS from 'aws-sdk';
const rds = new AWS.RDS();
rds.restoreDBClusterFromSnapshot({
    DBClusterIdentifier: 'restorer-cluster',
    SnapshotIdentifier: snapshotARN,
    Engine,: 'aurora-mysql'
    DeletionProtection: false,
    EngineMode: 'provisioned',
    ServerlessV2ScalingConfiguration: {
      MinCapacity: 5,
      MaxCapacity: 128,
    },
  }, (err) => {
    if (err) {
      reject(err);
    }

    rds.createDBInstance({
          DBClusterIdentifier: 'restorer-cluster',
          PubliclyAccessible: true,
          DBInstanceIdentifier:  'serverless-instance',
          DBInstanceClass: 'db.serverless',
          Engine: 'aurora-mysql',
        }, (errCreateInstance, dataCreateInstance) => {
          if (errCreateInstance) {
            reject(errCreateInstance);
          }
    
          console.log(dataCreateInstance);
          resolve();
    });
});
```

But the same error occurs every-time.

### Expected Behavior

A serverless cluster and instance are instantiated from my snapshot.

### Current Behavior

I get this thrown error:

```json
{
  "errorType": "UnexpectedParameter",
  "errorMessage": "Unexpected key 'ServerlessV2ScalingConfiguration' found in params",
  "trace": [
    "UnexpectedParameter: Unexpected key 'ServerlessV2ScalingConfiguration' found in params",
    "    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)",
    "    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)",
    "    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)",
    "    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)",
    "    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)",
    "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)",
    "    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9",
    "    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:396:7)",
    "    at /var/runtime/node_modules/aws-sdk/lib/config.js:414:9"
  ]
}
```

### Reproduction Steps

1 - Create a Serverless lambda using the code above
2 - Give the needed to role to your lambda :
```yml
iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds:RestoreDBClusterFromSnapshot
            - rds:CreateDBInstance
```
- Error is thrown, no cluster is created

### Possible Solution

Looks like `ServerlessV2ScalingConfiguration` param isn't parsed properly when validating the call to `restoreDBClusterFromSnapshot`.

### Additional Information/Context

The Cluster from which the snapshot is created is also an aurora Serverless v2 cluster, with the same capacities given in the code above.

### SDK version used

^2.1287.0

### Environment details (OS name and version, etc.)

Executed on AWS Console

**Comment by ajredniwja** [comment]
Hey @CamilleINGOUF thanks for opening this issue can you make sure you are using a lambda layer as mentioned [here](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-layer-aws-sdk-latest-version/) to be on the latest version of the SDK. 
You can check by :
```js
import AWS from 'aws-sdk';
console.log(AWS.VERSION);
```
