### ISSUE TITLE
Deno port via esm.sh seems to have broken the AWS ec2 instance metadata credentials

### ISSUE THREAD

**Issue by soundstep** [aws/aws-sdk-js#4327]
### Describe the bug

I realise the following is not a NodeJS usage.

Using the AWS SDK with Deno using esm.sh: https://esm.sh/@aws-sdk/client-s3@3.254.0
We can't seem to be able to pick the [AWS ec2 instance metadata credentials](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html).

Do we need to [create a provider](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromcontainermetadata-and-frominstancemetadata) ourselves?

Any insights or help appreciated.

### Expected Behavior

To have the AWS SDK logged in automatically.

### Current Behavior

Throw an error:

```sh
00:00:02.791 Error: Credential is missing
00:00:02.791     at re.credentialProvider (https://esm.sh/v103/@aws-sdk/client-s3@3.254.0/deno/client-s3.js:4:179910)
00:00:02.791     at re.signRequest (https://esm.sh/v103/@aws-sdk/signature-v4@3.254.0/deno/signature-v4.js:3:522)
00:00:02.791     at re.sign (https://esm.sh/v103/@aws-sdk/signature-v4@3.254.0/deno/signature-v4.js:2:4709)
00:00:02.791     at sign (https://esm.sh/v103/@aws-sdk/signature-v4-multi-region@3.254.0/deno/signature-v4-multi-region.js:2:788)
00:00:02.791     at https://esm.sh/v103/@aws-sdk/middleware-signing@3.254.0/deno/middleware-signing.js:2:2366
00:00:02.791     at async https://esm.sh/v103/@aws-sdk/middleware-retry@3.254.0/deno/middleware-retry.js:2:5465
00:00:02.791     at async https://esm.sh/v103/@aws-sdk/middleware-logger@3.254.0/deno/middleware-logger.js:2:34
```

### Reproduction Steps

Create a deno file (`send-file.ts`) to execute some AWS actions:

```ts
import { S3Client } from 'https://esm.sh/@aws-sdk/client-s3@3.254.0';

const client = new S3Client({ region: 'eu-west-1' });

await client.send(
        new CopyObjectCommand({
            Bucket:'my-bucket',
            CopySource: `my-bucket/my-file`,
            Key: 'new-file',
            TaggingDirective: 'REPLACE',
        }),
    );
```

```sh
deno run -A send-file.ts
```

### Possible Solution

The only solution we found is that it seems to work this one:

```sh
import { S3Client } from 'https://deno.land/x/aws_sdk@v3.32.0-1/client-s3/mod.ts';
```

Repo source: https://github.com/christophgysin/aws-sdk-js-v3

But we get build errors from this repo, the esm.sh one should be more future-proof.

### Additional Information/Context

I've asked some question there as well:
https://github.com/christophgysin/aws-sdk-js-v3/issues/38

### SDK version used

3.254.0

### Environment details (OS name and version, etc.)

Linux / github actions / mac os 12.1

**Comment by soundstep** [comment]
I will re-open this in this repo: https://github.com/aws/aws-sdk-js-v3
