### ISSUE TITLE
Getting error "[RSLVR-01600] Access denied" with no additional information

### ISSUE THREAD

**Issue by phcs93** [aws/aws-sdk-js#4340]
### Describe the bug

When trying to run `route53resolver:AssociateResolverQueryLogConfig`, I get the error message:

`[RSLVR-01600] Access denied Trace Id: \"1-63e2b070-13920f5536703fc22b4a598f\"`

I have added all necessary policies to my role, but I can't figure out what is missing now due to the message not being clear.

### Expected Behavior

The error message should explain what is actually blocking the access. For example: a missing policie, missing kms configuration, etc.

### Current Behavior

The following exception is thrown:

```json
{
  "errorType": "AccessDeniedException",
  "errorMessage": "[RSLVR-01600] Access denied Trace Id: \"1-63e2b070-13920f5536703fc22b4a598f\"",
  "trace": [
    "AccessDeniedException: [RSLVR-01600] Access denied Trace Id: \"1-63e2b070-13920f5536703fc22b4a598f\"",
    "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
    "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
    "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
    "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
    "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
    "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
    "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
  ]
}
```

### Reproduction Steps

This is my full Lambda code (nodejs):

```js
const AWS = require("aws-sdk");

exports.handler = async (event) => {
    
    const route53ResolverClient = new AWS.Route53Resolver();
    
    const createResolverQueryLogConfigParams = {
        DestinationArn: "arn:aws:logs:sa-east-1:############:log-group:querylog:*",
        Name: "test-query-log-teste"
    };
    
    const createResolverQueryLogConfigResponse = await route53ResolverClient.createResolverQueryLogConfig(createResolverQueryLogConfigParams).promise();
    
    const associateResolverQueryLogConfigParams = {
        ResolverQueryLogConfigId: createResolverQueryLogConfigResponse.ResolverQueryLogConfig.Id,
        ResourceId: "vpc-#################"
    };
    
    await route53ResolverClient.associateResolverQueryLogConfig(associateResolverQueryLogConfigParams).promise();
    
};
```

These are the policies attached to my Lambda role:

```json
// AWSLambdaBasicExecutionRolePolicy
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "logs:CreateLogGroup",
            "Resource": "arn:aws:logs:sa-east-1:############:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:sa-east-1:############:log-group:/aws/lambda/*:*"
            ]
        }
    ]
}
// route53resolver
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "route53resolver:CreateResolverQueryLogConfig",
                "route53resolver:AssociateResolverQueryLogConfig"
            ],
            "Resource": "*"
        }
    ]
}
// CloudWatchLogs (required for CreateResolverQueryLogConfig)
// initially it asked only for "logs:CreateLogDelivery" but then it asked permission for "logs:*" explicitly, really weird but I allowed it and it worked...
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "logs:*",
            "Resource": "*"
        }
    ]
}
// IAM (required for CreateResolverQueryLogConfig)
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*"
        }
    ]
}
```

### SDK version used

2.1310.0 (js)

### Environment details (OS name and version, etc.)

AWS Lambda running Node.js 16.x

**Comment by phcs93** [comment]
I found out what it was after a lot of trial and error.

You need permission for `ec2:DescribeVpcs` in order to run `route53resolver:AssociateResolverQueryLogConfig`.

Just added that to my role policies and it worked.

Please add that to the docs or the error message from the SDK.

**Comment by ScottGuymer** [comment]
Thanks for this, just ran into this myself. No docs on this that I could find..

Why is it so hard to find the right docs from AWS themselves!
