### ISSUE TITLE
Cannot enable Point-In-Time Recovery using Dynamodb.createTable, but can via Cloudformation

### ISSUE THREAD

**Issue by paul-uz** [aws/aws-sdk-js#4371]
### Describe the bug

Cannot enable PITR using the createTable command. But you can when creating a table via Cloudformation.

### Expected Behavior

I should be able to set

```
PointInTimeRecoverySpecification: {
    PointInTimeRecoveryEnabled: true
}
```

When using `dynamodb.createTable()`

### Current Behavior

Trying to set PITR results in the error below

```
UnexpectedParameter: Unexpected key 'PointInTimeRecoverySpecification' found in params
    at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /var/task/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/var/task/node_modules/aws-sdk/lib/config.js:350:7)
    at /var/task/node_modules/aws-sdk/lib/config.js:368:9 {
  code: 'UnexpectedParameter',
  time: 2023-03-14T10:16:27.855Z
}
```

### Reproduction Steps

Write simple lambda to use `dynamodb.createTable()` and set the following in the params:

```
PointInTimeRecoverySpecification: {
    PointInTimeRecoveryEnabled: true
}
```

### SDK version used

2.458.0

### Environment details (OS name and version, etc.)

Lambda Node 14

**Comment by yenfryherrerafeliz** [comment]
Hi @paul-uz, thanks for opening this issue. While with CloudFormation you have the option to set point-in-time recovery enabled, when defining the table creation settings, this option is not part of the createTable operation, as you can confirm [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html), and that explains why you can not pass as a parameter to the createTable command object, because is not a valid one. However, with the SDK you would need to first create the table and then send a "updateContinuousBackups" to enable point-in-time recovery.

Example:
```js
import * as AWS from "aws-sdk";

const dynamodb = new AWS.DynamoDB({
    region: 'us-east-2',
});
// Create table
dynamodb.createTable({
    TableName: 'table',
    ...
});
// Enable point-in-time recovery
dynamodb.updateContinuousBackups({
    TableName: 'table',
    PointInTimeRecoverySpecification: {
        PointInTimeRecoveryEnabled: true
    }
});
```

Please let me know if you have any questions.

Thanks!

**Comment by paul-uz** [comment]
Yes, but why can't you do this via the SDK but you can via Cloudformation? 

Why is there no feature parity?

Yet another oversight from AWS in providing tools that are lacking.

**Comment by RanVaknin** [comment]
Hi @paul-uz ,

The simple answer to why the SDK doesn't have the PITR option as param in the `createTable` method is because the SDK is generated from the API model of the service, and the model doesn't specify `PointInTimeRecoveryEnabled` as a param. 

The reason why PITR can be enabled using CloudFormation but not with the `createTable` method of the SDK, is because of the declarative nature of Cfn and the functional nature of the SDK.

With Cfn, you declare the desired state of your infrastructure in a template, and it takes care of provisioning and configuring the necessary resources to match the desired state. Its mainly designed to provide a higher-level, declarative approach to managing AWS resources (just like CDK is another abstraction on top of that).

In contrast, the SDK is designed to provide programmatic ways to interact with the various services, giving you fine-grained control over the creation, modification, and deletion of resources.

Since this is not a bug, and not something we can change, I'm inclined to close this. If you have additional concerns / questions / suggestions - feel free to open a discussion and we'd be happy to chime in 😄 

Thanks,
Ran~
