### ISSUE TITLE
CreateFunction throws InvalidParameterValueException after many PutObject calls

### ISSUE THREAD

**Issue by fr-an-k** [aws/aws-sdk-js#4408]
### Describe the bug

When I create a function after I have written many s3 objects, it keeps throwing "InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.". However, the role is fine and the parameters are valid.

### Expected Behavior

The function should be created without error.

### Current Behavior

I use the official waiter function for the role to be created, but the error only stops occurring if I add another 5-20 seconds of delay before creating the function (it varies depending on the objects being put).

When I don't put objects on S3 first, the bug doesn't occur.

After the script failed, I can succesfully create the function using the same role through the CLI, but that's probably also due to the delay.

Stacktrace:
<details>

```
InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
    at de_InvalidParameterValueExceptionRes (***REDACTED***/node_modules/@aws-sdk/client-lambda/dist-cjs/protocols/Aws_restJson1.js:5213:23)
    at de_CreateFunctionCommandError (***REDACTED***/node_modules/@aws-sdk/client-lambda/dist-cjs/protocols/Aws_restJson1.js:1931:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ***REDACTED***/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async ***REDACTED***/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:14:20
    at async ***REDACTED***/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async ***REDACTED***/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async main (file:///***REDACTED***/test.js:102:2) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '***REDACTED***',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Type: 'User'
}
```

</details>

### Reproduction Steps

Minimal reproduction example derived from our code situation:
<details>

```js
import fs from 'fs'
import {
	LambdaClient,
	CreateFunctionCommand,
	PackageType,
	DeleteFunctionCommand,
} from '@aws-sdk/client-lambda'
import {
	IAMClient,
	CreateRoleCommand,
	AttachRolePolicyCommand,
	waitUntilRoleExists,
	DetachRolePolicyCommand,
	DeleteRoleCommand,
} from '@aws-sdk/client-iam'
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3'

// Please create a test bucket first or change the name here
const Bucket = 'test'

const lambda = new LambdaClient({ apiVersion: '2015-03-31' }),
	iam = new IAMClient({
		apiVersion: '2010-05-08',
	}),
	s3 = new S3Client({ apiVersion: '2006-03-01', signatureVersion: 'v4' }),
	FunctionName = 'test',
	RoleName = 'test'

export async function main() {
	// Remove created test function on each run, ignore errors of non-existence
	try {
		await lambda.send(new DeleteFunctionCommand({ FunctionName }))
	} catch (e) {}
	try {
		await iam.send(
			new DetachRolePolicyCommand({
				PolicyArn:
					'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
				RoleName,
			})
		)
		await iam.send(new DeleteRoleCommand({ RoleName }))
	} catch (e) {}

	const Body = fs.readFileSync('dummy.zip')
	console.log('putting s3')

	// Many S3 uploads before creating the function appear to trigger the bug
	for (let i = 0; i < 200; i++) {
		await s3.send(
			new PutObjectCommand({
				Key: 'dummy.zip',
				Body,
				Bucket,
			})
		)
	}
	console.log('s3 done')

	// Create a basic lambda execution role
	const role = await iam.send(
		new CreateRoleCommand({
			AssumeRolePolicyDocument: JSON.stringify({
				Version: '2012-10-17',
				Statement: [
					{
						Effect: 'Allow',
						Principal: {
							Service: 'lambda.amazonaws.com',
						},
						Action: 'sts:AssumeRole',
					},
				],
			}),
			RoleName,
		})
	)
	await waitUntilRoleExists({ client: iam }, { RoleName })
	await iam.send(
		new AttachRolePolicyCommand({
			PolicyArn:
				'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
			RoleName,
		})
	)

	const doSleep = false // set to true as workaround
	const doS3 = false // bug occurs either way

	// Sleeping for 10 seconds or so (or using the CLI) seems a workaround for the bug
	const ms = doSleep ? 10000 : 0
	console.log('sleeping', ms)
	await new Promise(resolve => setTimeout(resolve, ms))

	// Keeps throwing InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
	await lambda.send(
		new CreateFunctionCommand({
			FunctionName,
			Role: role.Role.Arn,
			Runtime: 'nodejs18.x',
			Handler: 'index.handler',
			PackageType: PackageType.Zip,
			Code: doS3
				? {
						S3Bucket: Bucket,
						S3Key: 'dummy.zip',
				  }
				: { ZipFile: fs.readFileSync('dummy.zip') },
		})
	)

	// Working CLI alternative after failure:
	//aws lambda create-function --function-name test --runtime nodejs18.x --role arn:aws:iam::<your account>:role/test --handler index.handler --code S3Bucket=<your bucket>,S3Key=dummy.zip
}

main()
	.then(() => {})
	.catch(console.error)
```

</details>

Also create a dummy.zip containing an empty handler (`exports.handler = () => {}`)

### SDK version used

latest: 3.321.1 (lambda 3.322.0)

### Environment details (OS name and version, etc.)

aws-cli/2.11.15 Python/3.11.3 Linux/5.15.90.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.22 prompt/off

**Comment by RanVaknin** [comment]
Hi @fr-an-k ,

waitUntilRoleExists takes in a client (which you have provided), but also `maxWaitTime` which is set to a 15s default. 
Can you try to provide a longer wait time for your waiter? Maybe creating a role takes longer than 15 seconds. 

Thanks,
Ran~

**Comment by fr-an-k** [comment]
Hi Ran,
I did not notice the additional options because the WaiterConfiguration page is not linked on the waitUntilRoleExists page.
However, the result is the same with maxWaitTime set to 60.

**Comment by fr-an-k** [comment]
It was caused by the AttachRolePolicy being eventually consistent: there is no way to wait until it has propagated.
Even if you wait for the AttachmentCount of GetPolicy (for the lambda execution policy) to increase.
The AWS lambda team denies this as a bug...

A better workaround is to keep calling CreateFunction until it no longer throws an exception with name InvalidParameterValueException (adding a delay when it does).
