### ISSUE TITLE
CERT_UNTRUSTED error on node 0.10.34

### ISSUE THREAD

**Issue by gregberge** [aws/aws-sdk-js#446]
It seems that node 0.10.34 breaks everything...

```
     Error: CERT_UNTRUSTED
      at SecurePair.<anonymous> (tls.js:1381:32)
      at SecurePair.emit (events.js:92:17)
      at SecurePair.maybeInitFinished (tls.js:980:10)
      at CleartextStream.read [as _read] (tls.js:472:13)
      at CleartextStream.Readable.read (_stream_readable.js:341:10)
      at EncryptedStream.write [as _write] (tls.js:369:25)
      at doWrite (_stream_writable.js:226:10)
      at writeOrBuffer (_stream_writable.js:216:5)
      at EncryptedStream.Writable.write (_stream_writable.js:183:11)
      at write (_stream_readable.js:602:24)
      at flow (_stream_readable.js:611:7)
      at Socket.pipeOnReadable (_stream_readable.js:643:5)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
```

**Comment by pburtchaell** [comment]
If you have node installed with homebrew just run `brew switch node 0.10.28` to rollback. This solved the issue for me.

**Comment by lsegal** [comment]
Also note that [0.10.35 has been released](http://blog.nodejs.org/2014/12/23/node-v0-10-35-stable/).

**Comment by garrows** [comment]
I had the same problem when I was on v0.10.34. 
I upgraded to v0.10.35 and instead i get:
```
{ [InvalidClientTokenId: The security token included in the request is invalid.]
  message: 'The security token included in the request is invalid.',
  code: 'InvalidClientTokenId',
  time: Mon Jan 05 2015 16:26:42 GMT+1000 (AEST),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 }
```
Not quite fixed but probably not your fault.

**Comment by garrows** [comment]
Turns out the access key was slightly wrong. Sorry.
