### ISSUE TITLE
InvalidSignatureException: Credential should be scoped to a valid region

### ISSUE THREAD

**Issue by Cristian-Pixtig** [aws/aws-sdk-js#4545]
### Describe the bug

I'm trying to use the library
@aws-sdk/client-cloudfront-keyvaluestore
but I am getting the following error:
InvalidSignatureException: The credential must be scoped to a valid region.
      at throwDefaultError (/var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
      in /var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
      at de_PutKeyCommandError (/var/task/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/dist-cjs/protocols/Aws_restJson1.js:369:20)
      in process.processTicksAndRejections (node: internal/process/task_queues:95:5)
      in async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
      in async /var/task/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
      in async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46
      in async /var/task/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
    '$failure': 'client',
    '$metadata': {
      httpStatus code: 403,
      Request ID: 'e2cdf39b-5828-4a6d-98ce-1f3b7217a564',
      ExtendedRequestId: undefined,
      cfId: undefined,
      attempts: 1,
      totalRetryDelay: 0
    }
}

code:
         const client = new CloudFrontClient({});
         const commandDescribe = new DescribeKeyValueStoreCommand({Name: String(process.env.ARN_KVS)});
         const responseDescribe = await client.send(commandDescribe);
         const input = {
             Key: sessionId,
             Value: sessionId,
             KvsARN: responseDescribe.KeyValueStore?.ARN,
             IfMatch: responseDescribe.ETag
         };
         const config: CloudFrontKeyValueStoreClientConfig = { region: "us-east-1", };
         const clientKVS = new CloudFrontKeyValueStoreClient(config);
         const command = new PutKeyCommand(input);
         return await clientKVS.send(command);
     }

It also does not allow me to describe keyvaluestore, but using the library @aws-sdk/client-cloudfront it does allow me to access the description of the space, this last library does not allow me to add a key to the space so I need to use the first library

### Expected Behavior

Key creation in space

### Current Behavior

InvalidSignatureException: Credential should be scoped to a valid region. 
    at throwDefaultError (/var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_PutKeyCommandError (/var/task/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/dist-cjs/protocols/Aws_restJson1.js:369:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /var/task/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:30:20
    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:31:46
    at async /var/task/node_modules/@aws-sdk/client-cloudfront-keyvaluestore/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 403,
    requestId: 'e2cdf39b-5828-4a6d-98ce-1f3b7217a564',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

### Reproduction Steps

         const client = new CloudFrontClient({});
         const commandDescribe = new DescribeKeyValueStoreCommand({Name: String(process.env.ARN_KVS)});
         const responseDescribe = await client.send(commandDescribe);
         const input = {
             Key: sessionId,
             Value: sessionId,
             KvsARN: responseDescribe.KeyValueStore?.ARN,
             IfMatch: responseDescribe.ETag
         };
         const config: CloudFrontKeyValueStoreClientConfig = { region: "us-east-1", };
         const clientKVS = new CloudFrontKeyValueStoreClient(config);
         const command = new PutKeyCommand(input);
         return await clientKVS.send(command);
     }

### SDK version used

@aws-sdk/client-cloudfront-keyvaluestore@3.468.0

### Environment details (OS name and version, etc.)

x86_64  -> Lambda -> Node.js 18.x

**Comment by Arno-Z** [comment]
Issue is still present in version @aws-sdk/client-cloudfront-keyvaluestore v3.470.0
