### ISSUE TITLE
AWS sdk is not accepting parameters as mentioned in the document

### ISSUE THREAD

**Issue by shubham-sp444** [aws/aws-sdk-js#4560]
### Describe the bug

I'm using this SDK.  https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#createEndpointAccess-property

to create the VPC endpoint, but i get an error saying `Unexpected key 'ownerAccount' found in params`, this is not working locally as well as calling from the lambda.

I've checked with the types and the property `ownerAccount` is not mentioned in the types as well.

<img width="380" alt="Screenshot 2023-12-26 at 7 11 53 PM" src="https://github.com/aws/aws-sdk-js/assets/33379213/e72a408f-50d0-4804-ad21-873b06cfe878">

I've used node 14 and 16 both , and currently running on MacOS Ventura 13.4 with Apple M1 Pro chip ( for local ).

Please have a look and help me with this issue. thanks

### Expected Behavior

It should accept the property as mentioned in the AWS document.

### Current Behavior

error: UnexpectedParameter: Unexpected key 'ownerAccount' found in params
      at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
      at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:78:14)
      at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:89:21)
      at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
      at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:166:42)
      at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:120:11
      at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:396:7)
      at /var/runtime/node_modules/aws-sdk/lib/config.js:414:9 {
    code: 'UnexpectedParameter',
    time: 2023-12-26T13:22:29.456Z
  },

### Reproduction Steps

Try to create an endpoint for the redshift serverless cluster using this SDK: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#createEndpointAccess-property

### SDK version used

v2 sdk version

### Environment details (OS name and version, etc.)

I've used node 14 and 16 both , and currently running on MacOS Ventura 13.4 with Apple M1 Pro chip ( for local ).

**Comment by aBurmeseDev** [comment]
Hi @shubham-sp444 - thanks for reaching out. 

In order for me to understand the issue better, can you share your code calling the operation? I wasn't able to reproduce using the code with params below. Please note that `ownerAccount` is not a required param, [per service API](https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateEndpointAccess.html).

```ts
var params = {
  endpointName: 'vpcEndpoint',
  subnetIds: [
    'subnetID',
  ],
  workgroupName: 'testWorkGroup',
};
```
Looking forward to hear back,
John

**Comment by shubham-sp444** [comment]
> Hi @shubham-sp444 - thanks for reaching out.
> 
> In order for me to understand the issue better, can you share your code calling the operation? I wasn't able to reproduce using the code with params below. Please note that `ownerAccount` is not a required param, [per service API](https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateEndpointAccess.html).
> 
> ```ts
> var params = {
>   endpointName: 'vpcEndpoint',
>   subnetIds: [
>     'subnetID',
>   ],
>   workgroupName: 'testWorkGroup',
> };
> ```
> 
> Looking forward to hear back, John

Hello @aBurmeseDev, 

the `params` are

const params = {
        endpointName: ,
        subnetIds: ,
        workgroupName: ,
        resourceOwner: 
        vpcSecurityGroupIds: [],
      };

Also please note that the `resourceOwner` is the **another AWS account** ( I've already added all the permissions ), this setup is done using [serverless privatelink setup with another account],(https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-connecting.html#serverless-cross-vpc), therefore i need to mention the another AWS account ( if the property is skipped, it checks for in my account ) i get a 404 as the `resourceOwner` is the customer's AWS account.

I've added all the permissions ( granted the permissions for all VPC in my account to access the Customer AWS account ), I can see a `workgroup` listed on my AWS console and i can create the endpoint from there , But when i use the SDK i get error.

Thanks for the reply, let me know if more details are required.

**Comment by zshzbh** [comment]
Hey @shubham-sp444 ,

Thanks for the response, as long as you are using the aws-sdk-js-v3, you have to follow the input param rules. 'resourceOwner' should not be put as a input parameter here. Could you please delete the 'resourceOwner' and try again?
Thanks! 
Maggie

**Comment by shubham-sp444** [comment]
Hello,

I need the 'resourceOwner' property to be passed.
As the redshift belongs to another AWS account and I want an endpoint to
access the redshift cross account.

**Comment by aBurmeseDev** [comment]
Appreciate your response. As previously mentioned, `resourceOwner` is invalid parameter in service API. We, SDK team , don't have control over service models and if this's something you'd like to be considered, we can pass it along to service team on your behalf.

**Comment by shubham-sp444** [comment]
Hello,

Sorry for the wrong key value.
The parameter is "owner account"
https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateEndpointAccess.html

Please check the API document , it mentions that it's a valid parameter.
The ownerAccount should be the value of the owner only, so in my case it's
required if I want to create an endpoint

**Comment by aBurmeseDev** [comment]
Please share your complete minimal code with response logs and also note that Lambda runtime for Node 16 was [deprecated](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-deprecated) on Jun 12, 2024. Upgrade your runtime and retry. 

`ownerAccount` is also optional, try making a call without it for troubleshooting purpose.

**Comment by shubham-sp444** [comment]
It's an optional field, but when I try without this field I get an error of
401 because the owner of the resource i.e. Redshift is in a different
account, but the endpoint needs to be created in my account for cross
access.
That's the reason I need to define this parameter

**Comment by aBurmeseDev** [comment]
Can you share your minimal code and response output so that we can further help and investigate? The output with `ownerAccount` param and one without it. Thanks!

**Comment by shubham-sp444** [comment]
Hello,

The error with ownerAccount is Unexpected key 'ownerAccount' found in
params.

The API I'm using mentions that one can pass this property:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#createEndpointAccess-property

I needed to enable private access, but the owner account is different
account so I need to pass this parameter, otherwise it picks up my account
by default if not passed.

Below is the link you can follow regarding the setup, but to create
endpoint via API is not possible due to API validation issues.

https://aws.amazon.com/blogs/big-data/enable-private-access-to-amazon-redshift-from-your-client-applications-in-another-vpc/

**Comment by aBurmeseDev** [comment]
Since the error comes from service API and need insights from Redshift, I'm going to reach out on your behalf and transfer this to our cross-sdk repo. We would still need your minimal repro code with both success and failed outputs.
