### ISSUE TITLE
MediaConnect addFlowOutputs

### ISSUE THREAD

**Issue by PatrickBichiou** [aws/aws-sdk-js#4627]
### Describe the bug

If I add a flow output without encryption my call to sdk work. If i add encryption the call fails with "ERROR: AccessDeniedException: Forbidden". The documentation does not say that i need more rights. The role I use has the right to pass a role and the mediaconnect rights. The secret and role to access the secret are in place to.

Inside the Encryption object, I pass the secret and role arn as well as "srt-password" as key type.

ERROR	ERROR: AccessDeniedException: Forbidden
    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:80:27)
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:688:12) {
  code: 'AccessDeniedException',
  statusCode: 403,
  time: 2024-04-10T06:49:32.224Z,
  requestId: 'b0c03681-f39d-48ca-8525-ef06dae0c3cd',
  retryable: false,
  retryDelay: 73.03762032936388

### Expected Behavior

Add flow output with encryption enabled.

### Current Behavior

Flow output is only set, if no encryption is used.

### Reproduction Steps

See describe the bug.

### SDK version used

2.1595.0

### Environment details (OS name and version, etc.)

Chrome on Windows 11

**Comment by PatrickBichiou** [comment]
Found issue via AWS Support. Was a role mismatch.
