### ISSUE TITLE
S3.upload with buffer larger than 5 MB

### ISSUE THREAD

**Issue by LinusU** [aws/aws-sdk-js#525]
I seem to get this error whenever I try to `.upload` a buffer that is larger than 5 MB.

```text
MissingRequiredParameter: Missing required key 'UploadId' in params
    at fail (/usr/src/app/node_modules/aws-sdk/lib/param_validator.js:115:37)
    at validateStructure (/usr/src/app/node_modules/aws-sdk/lib/param_validator.js:34:14)
    at validateMember (/usr/src/app/node_modules/aws-sdk/lib/param_validator.js:61:21)
    at validate (/usr/src/app/node_modules/aws-sdk/lib/param_validator.js:9:10)
    at Request.VALIDATE_PARAMETERS (/usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:88:32)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at callNextListener (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:90:14)
    at /usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/usr/src/app/node_modules/aws-sdk/lib/config.js:228:7)
    at /usr/src/app/node_modules/aws-sdk/lib/config.js:244:9
    at Credentials.get (/usr/src/app/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/usr/src/app/node_modules/aws-sdk/lib/config.js:238:24)
    at Config.getCredentials (/usr/src/app/node_modules/aws-sdk/lib/config.js:258:9)
    at Request.VALIDATE_CREDENTIALS (/usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:70:26)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:97:18)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```

Here is my call to `S3.upload`:

```javascript
S3.upload({
  ACL: 'private',
  Bucket: 'test-bucket',
  Key: 'test-key',
  Body: theLargeBuffer
}, cb);
```

It seems like there is a problem when S3 is deciding to use the multipart upload instead of regular one. For some reason the multipart-id isn't passed on the the function that actually uploads the parts.

**Comment by lsegal** [comment]
@LinusU can you provide more details about your use case? 

* What version of the SDK are you using (`AWS.VERSION` should tell you)?
* What environment is this in (Node.js, browser, etc.)?

**Comment by LinusU** [comment]
AWS version `2.1.16` running in Node.js `v0.12.0`.

**Comment by AdityaManohar** [comment]
I am unable to replicate the issue with SDK version `2.1.16` on Node.js `v0.12.0 stable` on OS X `10.9`.

```javascript
var file = fs.readFileSync('my/large/file');
s3.upload({
  ACL: 'private', 
  Bucket: 'foo', 
  Key: 'bar',
  Body: file
}, callback);
```
Would you be able to provide details about your operating system?

**Comment by lsegal** [comment]
@LinusU where is `theLargeBuffer` coming from? Can you provide details on that as well?

**Comment by LinusU** [comment]
I'm so sorry, I didn't realise that this just happens locally where we are using `fake-s3`. The issue really is with the `fake-s3` project.

Again, terribly sorry for wasting your time.
