### ISSUE TITLE
Cannot read property 'systemClockOffset' of undefined

### ISSUE THREAD

**Issue by irwin-implementations** [aws/aws-sdk-js#543]
I get this error on Ubuntu (it works when I run it on Windows)

```
/home/jonathonc/script-manager/node_modules/aws-sdk/lib/util.js:302
      if (AWS.config.systemClockOffset) { // use offset when non-zero
                    ^
TypeError: Cannot read property 'systemClockOffset' of undefined
    at Object.getDate (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/util.js:302:21)
    at EnvironmentCredentials.needsRefresh (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/credentials.js:95:37)
    at EnvironmentCredentials.get (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/credentials.js:120:14)
    at new EnvironmentCredentials (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/credentials/environment_credentials.js:43:10)
    at AWS.CredentialProviderChain.resolve.credentials (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/aws.js:35:28)
    at resolveNext (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:90:26)
    at CredentialProviderChain.resolve (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:104:5)
    at Config.AWS.util.update.credentials (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/aws.js:38:8)
    at Config.set (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/config.js:353:39)
    at Config.<anonymous> (/home/jonathonc/script-manager/node_modules/aws-sdk/lib/config.js:191:12)
```

**Comment by AdityaManohar** [comment]
Which version of the SDK and Node.js are you using?

**Comment by irwin-implementations** [comment]
aws-sdk 2.1.19
node v0.10.25

**Comment by irwin-implementations** [comment]
Sorry....I was being stupid. it works, it was on my end.
