### ISSUE TITLE
Lambda `FunctionZip` doesn't support a stream object

### ISSUE THREAD

**Issue by rclark** [aws/aws-sdk-js#552]
According to the documentation http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#uploadFunction-property

> FunctionZip: new Buffer('...') || 'STRING_VALUE' || streamObject, /* required */

This works fine as long as I provide a buffer object, but if I provide a stream (via `fs.createReadStream`), I get the following error:

```
TypeError: Not a string or buffer
        at Hash.update (crypto.js:240:17)
        at Object.util.crypto.hash (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/util.js:507:24)
        at Object.sha256 (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/util.js:461:26)
        at V4.hash [as hexEncodedHash] (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/signers/v4.js:172:28)
        at V4.hexEncodedBodyHash (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/signers/v4.js:181:19)
        at V4.canonicalString (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/signers/v4.js:126:21)
        at V4.stringToSign (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/signers/v4.js:113:41)
        at V4.signature (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/signers/v4.js:105:43)
        at V4.authorization (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/signers/v4.js:82:36)
        at V4.addAuthorization (/home/travis/build/mapbox/streambot/node_modules/aws-sdk/lib/signers/v4.js:35:12)
```

**Comment by lsegal** [comment]
The logic S3 uses to [sign payloads](https://github.com/aws/aws-sdk-js/blob/master/lib/services/s3.js#L205-L232) should probably be moved directly into the V4 signer so all services can make use of this logic.

A temporary workaround would be to do the following:

```js
var lambda = new AWS.Lambda();
var params = { ... };
lambda.uploadFunction(params).
    on('build', AWS.S3.prototype.computeSha256).
    send(function(data, err) {
  console.log(data, err);
});
```

Let me know if that works for you. Note that it uses a private API, so it should just be a *workaround*, not permanent code.

**Comment by rclark** [comment]
In my situation today using a buffer is totally reasonable (although #551 can be a problem with larger buffers), but thanks for the workaround. You suspect this logic will move into the v4 signer relatively soon?

**Comment by lsegal** [comment]
@rclark yea this should be a fairly easy refactor. I'm just not near my dev machine right now, but it should get looked at this week.
