### ISSUE TITLE
Error stacks thrown in callback lose the stack context

### ISSUE THREAD

**Issue by mdouglass** [aws/aws-sdk-js#639]
If you throw an error inside a callback from one of the DynamoDB APIs the original call stack and error type of the error is lost.

```javascript
var AWS = require('aws-sdk');
AWS.config.region = 'us-east-1';
var ddb = new AWS.DynamoDB();
ddb.listTables(function(err, data) {
  foo.bar(); 
});
```

**Actual Error:**
```
Error: foo is not defined
    at Request.callListeners (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/mdouglass/kixeye/km/server/kmservices/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```
**Expected:**
ReferenceError pointing to the line of code in my callback function, rather than to Request.callListeners

**Comment by AdityaManohar** [comment]
@mdouglass Thanks for the pull request! We would like to have each error preserve its own stack instead of appending to the original error stack. 

I've pushed up a fix that should resolve this issue as well as a related issue with error names. Thanks again for reporting, as well as the fix.

**Comment by mdouglass** [comment]
Thanks @AdityaManohar, just tried that out and it fixes what I was looking for.
