### ISSUE TITLE
EC2.CreateRoute has a documented ClientToken parameter that causes errors if used

### ISSUE THREAD

**Issue by mdouglass** [aws/aws-sdk-js#653]
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#createRoute

That documentation describes a ClientToken parameter that can be used to ensure idempotency of the CreateRoute command, but if specified, an error is returned:

```
var AWS = require('aws-sdk'),
var ec2 = new AWS.EC2();
var routeParams = {
    DryRun: false,
    DestinationCidrBlock: '10.0.0.0/24',
    RouteTableId: 'rtb-xxxxxxxx',
    ClientToken: 'test-client-token',
    VpcPeeringConnectionId: 'pcx-xxxxxxxx'
};
ec2.createRoute(routeParams, function(err, data) {
    console.log(err);
    console.log(data);
});
```

Results:
```
UnknownParameter: The parameter ClientToken is not recognized
    at Request.extractError (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/services/ec2.js:50:35)
    at Request.callListeners (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/mdouglass/kixeye/km/server/km-deploy/node_modules/aws-sdk/lib/request.js:37:9)
```

**Comment by AdityaManohar** [comment]
@mdouglass Thanks for for reporting this! I am able to reproduce the issue and it looks like the error is indeed being returned from the service.

I will try getting in touch with the EC2 team to report this issue. In the meantime, feel free to open an issue on the [EC2 Forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) letting them know about this issue.

**Comment by AdityaManohar** [comment]
@mdouglass 
I did receive confirmation from the EC2 team that the `CreateRoute` operation does not accept the `ClientToken` parameter. I'm working on fixing the documentation to reflect this.

Thanks again for reporting this issue!

**Comment by mdouglass** [comment]
Thanks @AdityaManohar for checking on that.
