### ISSUE TITLE
Error when update aws sdk

### ISSUE THREAD

**Issue by kimthangatm** [aws/aws-sdk-js#661]
Error log:
```
DevAPI/node_modules/aws-sdk/lib/api_loader.js:35
    serviceMap[identifier].versions = serviceMap[identifier].versions.sort();
                                                                     ^
TypeError: Cannot read property 'sort' of undefined
    at /home/MCCorpAPI/DevAPI/node_modules/aws-sdk/lib/api_loader.js:35:70
    at Array.forEach (native)
    at buildServiceMap (/home/MCCorpAPI/DevAPI/node_modules/aws-sdk/lib/api_loader.js:34:27)
    at Object.getServices [as services] (/home/MCCorpAPI/DevAPI/node_modules/aws-sdk/lib/api_loader.js:42:3)
    at Object.<anonymous> (/home/MCCorpAPI/DevAPI/node_modules/aws-sdk/lib/services.js:7:5)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/MCCorpAPI/DevAPI/node_modules/aws-sdk/lib/aws.js:14:1)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by lsegal** [comment]
Can you provide any more details on this, @kimthangatm? I cannot seem to reproduce any issues with `npm install aws-sdk` and a `require('aws-sdk')` call.

**Comment by kimthangatm** [comment]
Hi, code in my local run ok but service error. I use express, I think error with "bcrypt-nodejs": "0.0.3" in my package.json. When i change "bcrypt-nodejs": "0.0.3" to "bcrypt-nodejs": "~0.0.3" and npm update. Code run in server Ok.

**Comment by lsegal** [comment]
Seems like a dependency or environment issue, so I am going to mark this as closed. If you figure out the cause feel free to let us know!
