### ISSUE TITLE
scheduleLambdaFunctionDecisionAttribute does not validate

### ISSUE THREAD

**Issue by jwulf** [aws/aws-sdk-js#682]
`scheduleLambdaFunctionDecisionAttribute` is documented, but throws an error.

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SWF.html

```
[UnexpectedParameter: Unexpected key 'scheduleLambdaFunctionDecisionAttributes' found in params.decisions[1]]
  message: 'Unexpected key \'scheduleLambdaFunctionDecisionAttributes\' found in params.decisions[1]',
  code: 'UnexpectedParameter',
  time: Sun Aug 16 2015 01:56:50 GMT+1000 (AEST) } 'UnexpectedParameter: Unexpected key \'scheduleLambdaFunctionDecisionAttributes\' found in params.decisions[1]\n
    at fail (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:117:37)\n    at validateStructure (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:52:14)\n    
at validateMember (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:63:21)\n    
at validateList (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:78:12)\n    
at validateMember (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:65:21)\n    
at validateStructure (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:50:14)\n    
at validateMember (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:63:21)\n    
at validate (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/param_validator.js:9:10)\n
at Request.VALIDATE_PARAMETERS (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/event_listeners.js:88:32)\n    
at Request.callListeners (/Users/sitapati/workspace/JAWS/lib/node_modules/aws-sdk/lib/sequential_executor.js:105:20)'
```

**Comment by jwulf** [comment]
It's documented here: https://github.com/aws/aws-sdk-js/blob/c0ab39a7abd2672d05554f495aef8d39c9e09af4/apis/swf-2012-01-25.normal.json#L1737

**Comment by jwulf** [comment]
This works in aws-sdk@2.1.45
