### ISSUE TITLE
Unhandled "TypeError: Cannot read property 'message' of null"

### ISSUE THREAD

**Issue by jbuck** [aws/aws-sdk-js#708]
While using the AWS SDK v2.1.50 to delete a large number of files in S3 I sometimes encountered this error throwing from deep within the SDK

```
/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/util.js:612
      if (options.message)
                 ^

TypeError: Cannot read property 'message' of null
    at Object.error (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/util.js:612:18)
    at Request.callListeners (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:107:28)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

I looked at the [code in question](https://github.com/aws/aws-sdk-js/blob/7dd7d9b343a1a626cb907b257bc24e0c9ff70693/lib/util.js#L612) and I think it needs a null check, since `typeof null === 'object'`

**Comment by AdityaManohar** [comment]
@jbuck Thanks for reporting this! Do you have a minimal reproduction test case that I can use to replication the problem. This is an easy fix, but I'm more curious about the origin of the error.

**Comment by jbuck** [comment]
Sure! Here's the code that was throwing:

```
var async = require("async");
var AWS = require("aws-sdk");
var S3 = new AWS.S3();

var Bucket = process.argv[2];
var IsTruncated = true;
var KeyMarker;

async.whilst(function test() {
  return IsTruncated;
}, function workfn(callback) {
  var params = {
    Bucket,
    KeyMarker,
    MaxKeys: 1000
  };

  S3.listObjectVersions(params, function(list_error, data) {
    if (list_error) {
      return callback(list_error);
    }

    IsTruncated = data.IsTruncated;
    KeyMarker = data.NextKeyMarker;

    callback(null);
  });
}, function errfn(error) {
  throw error;
});
```

The bucket I was listing and deleting had around 400k objects, and I found that this error would occur more frequently near the end of the deletion run, after running for about 45 minutes. Only the listing code was throwing this error.

**Comment by jbuck** [comment]
@AdityaManohar I ran it again today, happens in about 5 minutes now:

```
(assume-aws-role everything)$ time node bin/s3-delete-everything.js popcorn.webmadecontent.org
/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/util.js:612
      if (options.message)
                 ^

TypeError: Cannot read property 'message' of null
    at Object.error (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/util.js:612:18)
    at Request.callListeners (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:107:28)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:115:18)

real	5m38.866s
user	1m26.354s
sys	0m2.013s
```

**Comment by AdityaManohar** [comment]
@jbuck I've pushed up a fix that should resolve this issue. Let me know if this works for you. 

Feel free to reopen this issue if you continue to have problems, and thanks for reporting!

**Comment by jbuck** [comment]
Exciting, a new error! :)

```
/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:30
            throw err;
            ^

Error: null
    at Request.callListeners (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jbuck/Documents/Github/s3-delete-everything/node_modules/aws-sdk/lib/request.js:595:14)
```

I can reproduce this with the same script as above; is there any other information I can add to assist in debugging this issue?

**Comment by jbuck** [comment]
@AdityaManohar would you like me to refile this as a new issue? It's definitely better than before, since I can actually catch and retry the command, but there's no information about the error.

**Comment by chrisradek** [comment]
@jbuck 
I was able to reproduce the new error you were seeing with the code you provided. It looks like the issue is actually with the callback function being supplied to `async.whilst`.  Once the final listing returns, the test function will return `false` and the callback function will be called with `null` provided as the argument.  Adding a check in the callback function for the existence of `error` before throwing it should (hopefully) resolve your issue.

Let me know if that helps!

**Comment by jbuck** [comment]
Well, I'm a moron :sob: 

Thanks for fixing the original issue though, happy that the second one is my fault!
