### ISSUE TITLE
DynamoDB.DocumentClient Missing region in config

### ISSUE THREAD

**Issue by rclark** [aws/aws-sdk-js#710]
```js
var AWS = require('aws-sdk');
var client = new AWS.DynamoDB.DocumentClient({ region: 'us-east-1' });
```

As soon as I use the client to make a request, I'm greeted with 

```
ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/Users/r/tmp/node_modules/aws-sdk/lib/event_listeners.js:81:45)
    at Request.callListeners (/Users/r/tmp/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/r/tmp/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/r/tmp/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/Users/r/tmp/node_modules/aws-sdk/lib/config.js:228:7)
    at /Users/r/tmp/node_modules/aws-sdk/lib/config.js:244:9
    at EnvironmentCredentials.get (/Users/r/tmp/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/r/tmp/node_modules/aws-sdk/lib/config.js:238:24)
    at Config.getCredentials (/Users/r/tmp/node_modules/aws-sdk/lib/config.js:258:9)
    at Request.VALIDATE_CREDENTIALS (/Users/r/tmp/node_modules/aws-sdk/lib/event_listeners.js:70:26)
```

It works as expected if instead I run

```js
var AWS = require('aws-sdk');
var dynamodb = new AWS.DynamoDB({ region: 'us-east-1' });
var client = new AWS.DynamoDB.DocumentClient({ service: dynamodb });
```

Is this the expected method for using the DocumentClient? [The documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#constructor-property) seems to suggest that `service` is optional, but I could be misundestanding:

> An optional pre-configured instance of the AWS.DynamoDB service object to use for requests.

**Comment by AdityaManohar** [comment]
@rclark I've pushed up a patch that should should fix this for you. Let me know if this works for you. Thanks for reporting!

**Comment by riseres** [comment]
I still got this problem.

I have to use from @rclark suggest to get works.

var AWS = require('aws-sdk');
var dynamodb = new AWS.DynamoDB({ region: 'us-east-1' });
var client = new AWS.DynamoDB.DocumentClient({ service: dynamodb });

**Comment by AdityaManohar** [comment]
@riseres This change hasn't been released to `npm` yet. You can use it by installing directly from GitHub

```sh
$> npm install git://github.com/aws/aws-sdk-js
```

**Comment by fsaldivars** [comment]
In current working with sdk-for-javascript and find solution in this doc:
[sdk-for-javascript](https://docs.aws.amazon.com/es_es/sdk-for-javascript/v2/developer-guide/setting-region.html)
And working on macOS High... 
**vim ~/.bash_profile**
And Add

> AWS_REGION="us-east-1"
> export AWS_REGION
