### ISSUE TITLE
DynamoDB.DocumentClient miss on response.nextPage()

### ISSUE THREAD

**Issue by rclark** [aws/aws-sdk-js#711]
The following code will gather one page of query results, then fail to send the second page of the query:

```js
var AWS = require('aws-sdk');
var dynamodb = new AWS.DynamoDB({ region: 'us-east-1' });
var client = new AWS.DynamoDB.DocumentClient({ service: dynamodb });

var request = client.query({
  TableName: 'my-table',
  ExpressionAttributeNames: {
    '#collection': 'collection'
  },
  ExpressionAttributeValues: {
    ':collection': 'my-collection'
  },
  KeyConditionExpression: '#collection = :collection'
});

(function getOnePage(request) {
  request
    .on('error', function(err) { throw err; })
    .on('success', function(res) {
      if (res.hasNextPage()) return getOnePage(res.nextPage());
    })
    .send();
})(request);
```

The error message indicates that the request parameters are not valid -- apparently looking for typed JS objects:

```
/Users/r/tmp/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
MultipleValidationErrors: There were 53 validation errors:
* InvalidParameterType: Expected params.ExclusiveStartKey['collection'] to be a structure
* UnexpectedParameter: Unexpected key '0' found in params.ExclusiveStartKey['collection']
* UnexpectedParameter: Unexpected key '1' found in params.ExclusiveStartKey['collection']
... etc ...
* UnexpectedParameter: Unexpected key '31' found in params.ExclusiveStartKey['id']
    at validate (/Users/r/tmp/node_modules/aws-sdk/lib/param_validator.js:16:30)
    at Request.VALIDATE_PARAMETERS (/Users/r/tmp/node_modules/aws-sdk/lib/event_listeners.js:88:32)
    at Request.callListeners (/Users/r/tmp/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/r/tmp/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/r/tmp/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/Users/r/tmp/node_modules/aws-sdk/lib/config.js:228:7)
    at /Users/r/tmp/node_modules/aws-sdk/lib/config.js:244:9
    at EnvironmentCredentials.get (/Users/r/tmp/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/r/tmp/node_modules/aws-sdk/lib/config.js:238:24)
    at Config.getCredentials (/Users/r/tmp/node_modules/aws-sdk/lib/config.js:258:9)
```

**Comment by AdityaManohar** [comment]
@rclark Thanks for reporting this! This syntactic sugar *may be* harder to support because the document client works by adding additional handlers to the lower level request. You can however use the following workaround:

```javascript
var AWS = require('aws-sdk');

var dynamodb = new AWS.DynamoDB({region: 'us-west-2'});
var dc = new AWS.DynamoDB.DocumentClient({service: dynamodb, params: {TableName: 'foobar'}});

var params = {
  ExpressionAttributeNames: {
    '#id': 'id'
  },
  ExpressionAttributeValues: {
    ':id': 'foo'
  },
  KeyConditionExpression: '#id = :id',
  Limit: 100
};

var request = dc.query(params);

(function getOnePage(req) {
  req
    .on('error', function(err) { throw err; })
    .on('success', function(res) {
      console.log(res.data.LastEvaluatedKey);
      if (res.hasNextPage()) {
        params.ExclusiveStartKey = res.data.LastEvaluatedKey;
        return getOnePage(dc.query(params));
      }
    })
    .send();
})(request);
```

Let me know if this works for you. And thanks again for reporting!

**Comment by rclark** [comment]
Thanks for this. This will make a great workaround, though it is a bummer to have this little gotcha lurking....

**Comment by rclark** [comment]
I haven't tried, but I suspect I would encounter the same problem with `request.eachItem` and `request.eachPage`?

**Comment by AdityaManohar** [comment]
@rclark 
>  I suspect I would encounter the same problem with request.eachItem and request.eachPage

Unfortunately yes, because these APIs rely on the `response.nextPage()` API. I'll keep this open while I take a closer look at trying to support these interfaces with the document client.

**Comment by AdityaManohar** [comment]
@rclark I've added a patch that should allow you to use the paginator interface directly. 

I've tested it with the following script:
```javascript
var AWS = require('aws-sdk');

var dc = new AWS.DynamoDB.DocumentClient({region: 'us-west-2', params: {TableName: 'foo-bar'}});

var params = {
  ExpressionAttributeNames: {
    '#id': 'id'
  },
  ExpressionAttributeValues: {
    ':id': 'foo'
  },
  KeyConditionExpression: '#id = :id',
  Limit: 100
};

var request = dc.query(params);

(function getNextPage(req) {
  req
    .on('error', function(err) { throw err; })
    .on('success', function(res) {
      if (res.hasNextPage()) return getNextPage(res.nextPage());
    }).send();
})(request);
```
Similarly, I've also been able to do:

```javascript
(function getEachPage(req) {
  var page = 1;
  req.eachPage(function(err, data) {
    if (err) return;
    console.log('Page: ', pages++, ' Data: ', data);
  });
})(request);
```
and
```javascript
(function getEachItem(req) {
  var items = 1;
  req.eachItem(function(err, data) {
    if (err) return;
    console.log('Item: ', items++, ' Data: ', data);
  });
})(request);
```

Let me know if you run into any issues when using `response.nextPage()`, `request.eachItem()`, and `request.eachPage()`

Thanks again for reporting!

**Comment by rclark** [comment]
Excellent! Thank you for the patch!
