### ISSUE TITLE
s3.getObject.createReadStream throws error even if it was handled

### ISSUE THREAD

**Issue by andreasherzog** [aws/aws-sdk-js#750]
Hi, 
on trying to download an object as Stream the awssdk throws an error that can't be handled if the key does not exist. I listen for the 'error' event of the Stream and handle occurring errors myself.

Code:
```
s3Stream = self.s3sdk.getObject(params).createReadStream()
            .on('error', function (err) {
                console.log('READSTREAM error ');
                console.log(err);
            })
            .on('end', function() { console.log('done.'); });
```

Output:
```
READSTREAM error
{ [NoSuchKey: The specified key does not exist.]
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  time: Sun Oct 11 2015 09:05:10 GMT+0000 (UTC),
  statusCode: 404,
  retryable: false,
  retryDelay: 30 }
/src/my_aws/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
NoSuchKey: The specified key does not exist.
 at Request.extractError (/src/my_aws/node_modules/aws-sdk/lib/services/s3.js:322:35)
    at Request.callListeners (/src/my_aws/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/src/my_aws/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/src/my_aws/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/src/my_aws/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/src/my_aws/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/my_aws/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/my_aws/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/src/my_aws/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/src/my_aws/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/src/my_aws/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/src/my_aws/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/src/my_aws/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/src/my_aws/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /src/my_aws/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/src/my_aws/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/src/my_aws/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/src/my_aws/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/src/my_aws/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/src/my_aws/node_modules/aws-sdk/lib/event_listeners.js:207:11)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

When I handle this error directly on the event, this exception should not be thrown.

Thank you for looking into this.

**Comment by jeskew** [comment]
Hi @andreasherzog,

What version of node and of the SDK are you currently using?

**Comment by andreasherzog** [comment]
Hi @jeskew,
I am using node 0.12.7 and aws-sdk 2.2.8.

**Comment by chrisradek** [comment]
@andreasherzog 
I switched to using node 0.12.7 and aws-sdk 2.2.8, and haven't been able to reproduce this issue yet. Only the error bound to the stream is being fired when I test. When you're testing, is it only with the code above? I'm curious if there's something else going on in the surrounding code that is causing this.

Here's the code I'm testing with (almost identical to what you've provided.)
```javascript
var AWS = require('aws-sdk');
var s3 = new AWS.S3();
var params = {
  Bucket: 'VALID_BUCKET',
  Key: 'not_a_real_key'
}
var s3Stream = s3.getObject(params).createReadStream()
      .on('error', function(err) {
          console.log('READSTREAM error');
          console.log(err);
      })
      .on('end', function(){});
```

**Comment by andreasherzog** [comment]
When I test with your code, the error event (and only this) is correctly fired. However, in my code I directly use the stream after creating it, causing the sdk to think that I did not handle the error event:

```
var archive = archiver('zip')
s3Stream = self.s3sdk.getObject(params).createReadStream()
                .on('error', function (err) {
                   console.log(err);
                })
                .on('end', function() {
                    console.log('finished');
                });

            archive.append(s3Stream, {
                name: item.title || item.fileKey
            });
```
Because it is a stream, I would like to be able to directly pass it on to my next function and let my on error function handle the errors.

**Comment by chrisradek** [comment]
@andreasherzog 
I ran some tests using `archiver`. It looks like the error being captured on the stream's `error` event is also getting captured by `archiver`, and then `archiver` emits an error event, causing the error you see to be thrown.

Instead of attaching the `error` event to the stream object returned by `createReadStream`, you can attach an `error` event directly onto your `archive` instance.

Something like this:
```javascript
var AWS = require('aws-sdk');
var archive = archiver('zip')
var s3 = new AWS.S3();
var params = {
  Bucket: 'VALID_BUCKET',
  Key: 'not_a_real_key'
}
var s3Stream = s3.getObject(params).createReadStream()
      .on('end', function(){});
archive.on('error', function(err) {
    console.log(err);
});
archive.append(s3Stream, {
    name: item.title || item.fileKey
});
```

Let me know if this helps!

**Comment by andreasherzog** [comment]
@chrisradek 
Yes, this solves this issue. I now just listen for the error event on archiver, and this solves the issue. Thank you very much for your help!
