### ISSUE TITLE
Cannot read property 'timestamp' of null

### ISSUE THREAD

**Issue by optimisme** [aws/aws-sdk-js#759]
After receiving the next error my server dies:

/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/request.js:30
            throw err;
            ^
TypeError: Cannot read property 'timestamp' of null
    at Request.callListeners (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/sequential_executor.js:107:43)
    at Request.emit (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/lib/openshift/5...2/app-root/runtime/repo/node_modules/aws-sdk/lib/request.js:595:14)
DEBUG: Program node server.js exited with code 1

This is using version 2.1.27 of aws-sdk for nodejs. Also, I am only using s3 related calls: getObject, upload, listObjects, deleteObject. It happens randomly.

**Comment by chrisradek** [comment]
@optimisme 
Can you share any code that reproduces this error?

**Comment by optimisme** [comment]
Ok, it was a problem with my server. Sorry for the inconveniences and thanks for your help.

**Comment by chrisradek** [comment]
@optimisme 
No problem, glad you got it working!
