### ISSUE TITLE
Service must be constructed with `new' operator

### ISSUE THREAD

**Issue by SirCameronMcAlpine** [aws/aws-sdk-js#782]
With the following code:

```
AWS.config.apiVersions = {
  sns: '2010-03-31'
};
var sns = AWS.SNS().client;
var sqq = AWS.SQS().client;

sns.subscribe({
    	'TopicArn': config.aws.sns.arn,
    	'Protocol': 'sqs',
    	'Endpoint': config.aws.sqs.arn
	},
	function (err, result) {
		if (err !== null) {
        	console.log(util.inspect(err));
        	return;
    	}

    	console.log(util.inspect(result));
	}
);
```

I get this error:

```
node_modules/aws-sdk/lib/service.js:23
      throw AWS.util.error(new Error(),
Error: Service must be constructed with `new' operator
at Object.Service (/srv/microservices/adjust.worker/node_modules/aws-sdk/lib/service.js:23:28)
at Object.features.constructor as SNS
at Object. (/srv/microservices/adjust.worker/index.js:12:15)
at Module._compile (module.js:425:26)
at Object.Module._extensions..js (module.js:432:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Function.Module.runMain (module.js:457:10)
at startup (node.js:136:18)
at node.js:972:3
```

I have looked around online and not found a working solution for this. Please help

**Comment by chrisradek** [comment]
@SirCameronMcAlpine 
With the JavaScript SDK, there usually aren't client classes for each service.  You simply need to instantiate an instance of a service.

To use SNS `subscribe`, you can do something like this:
```javascript
var sns = new AWS.SNS();
sns.subscribe({
    'TopicArn': 'ARN',
    'Protocol': 'PROTOCOL',
    'Endpoint': 'ENDPOINT'
}, function (err, result) {
    if (err) {
        console.log(err);
        return;
    }
    console.log(result);
});
```


Let me know if this helps.

**Comment by SirCameronMcAlpine** [comment]
Ok, thanks. Will give it a go.
