### ISSUE TITLE
S3 getObject fails internally (on Lambda)

### ISSUE THREAD

**Issue by CamJN** [aws/aws-sdk-js#814]
When I try and get an object from s3, in a lambda function more often than not the sdk throws an error.

The code:
```
var aws = require('aws-sdk'); 
var s3 = new aws.S3({ apiVersion: '2006-03-01' }); 
exports.handler = function(event, context) {
    var params = {
        Bucket: event.Records[0].s3.bucket.name,
        Key: decodeURIComponent(event.Records[0].s3.object.key.replace(/\+/g, ' '))
    };
    s3.getObject(params, function(err, data) {
        if (err) {
            console.log(err, err.stack);
            context.fail(err);
        } else {
            ...
        }
    });
};
```

The error from cloudwatch:
```
START RequestId: 26a775b4-92b6-11e5-afa6-0142977de9cf Version: $LATEST
2015-11-24T14:17:54.465Z	26a775b4-92b6-11e5-afa6-0142977de9cf	TypeError: Cannot read property 'subfolder' of undefined
    at Response.<anonymous> (/var/task/index.js:31:54)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:353:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:597:12)
END RequestId: 26a775b4-92b6-11e5-afa6-0142977de9cf
REPORT RequestId: 26a775b4-92b6-11e5-afa6-0142977de9cf	Duration: 694.61 ms	Billed Duration: 700 ms 	Memory Size: 128 MB	Max Memory Used: 16 MB	
Process exited before completing request
```

**Comment by chrisradek** [comment]
@CamJN 
 Do you have any examples of `Key`s that the `getObject` command is failing on? Is `subfolder` defined somewhere in your code?

**Comment by CamJN** [comment]
Sorry I meant to close this, I was jsut confused by the stack trace I got from my code. The sdk wasn't the problem.
