### ISSUE TITLE
TypeError  at trying to sending a email.

### ISSUE THREAD

**Issue by briandiaz** [aws/aws-sdk-js#817]
Hi i am trying to send a email but im getting this error.

```js
const options = {
    toAddresses: ['briandiaz@outlook.com'],
    body: 'Body message!!',
    subject: 'Testing AWS SDK',
    fromAddress: 'myemail@gmail.com',
  };
```
BTW: *I have valid credentials.*

```bash
TypeError: Cannot read property 'length' of undefined
      at [object Object].validateList (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/param_validator.js:75:31)
      at [object Object].validateMember (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/param_validator.js:63:21)
      at [object Object].validateStructure (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/param_validator.js:48:14)
      at [object Object].validateMember (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/param_validator.js:61:21)
      at [object Object].validateStructure (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/param_validator.js:48:14)
      at [object Object].validateMember (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/param_validator.js:61:21)
      at [object Object].validate (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/param_validator.js:9:10)
      at Request.VALIDATE_PARAMETERS (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/event_listeners.js:88:32)
      at Request.callListeners (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
      at callNextListener (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
      at /home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/event_listeners.js:75:9
      at finish (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/config.js:244:7)
      at /home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/config.js:260:9
      at EnvironmentCredentials.get (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/credentials.js:126:7)
      at getAsyncCredentials (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/config.js:254:24)
      at Config.getCredentials (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/config.js:274:9)
      at Request.VALIDATE_CREDENTIALS (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/event_listeners.js:70:26)
      at Request.callListeners (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
      at Request.emit (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
      at Request.emit (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/request.js:595:14)
      at Request.transition (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/request.js:21:10)
      at AcceptorStateMachine.runTo (/home/brian/instacarro/ic-api-sellers/node_modules/@instacarro/mailer/node_modules/aws-sdk/lib/state_machine.js:14:12)
```

**Comment by chrisradek** [comment]
@briandiaz 
What operation are you running to send an email?
If you're using SES, some of your parameters don't match what's listed in the documentation.
Take a look at the `sendEmail` documentation here:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendEmail-property

**Comment by chrisradek** [comment]
I'm closing this issue as it seems to be related to passing in incorrect parameters to the API call.  Feel free to re-open or comment if you still have questions.
