### ISSUE TITLE
Cannot send message to SQS queue

### ISSUE THREAD

**Issue by Alaneor** [aws/aws-sdk-js#823]
Hello,

I am receiving the following error while trying to send a message to an SQS queue:

```
TypeError: Cannot read property 'match' of null
    at Request.buildEndpoint (node_modules/aws-sdk/lib/services/sqs.js:127:54)
    at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
    at node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (node_modules/aws-sdk/lib/config.js:244:7)
    at node_modules/aws-sdk/lib/config.js:260:9
    at Credentials.get (node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (node_modules/aws-sdk/lib/config.js:254:24)
```

I am building my SQS instance using the following code:

```js
const AWS = require('aws-sdk')
const config =
      { accessKeyId: 'my-key'
      , secretAccessKey: 'my-secret'
      , apiVersions:
        { sqs: '2012-11-05'
        }
      , region: 'us-east-1'
      }

AWS.config.update(config)

const sqs = new AWS.SQS()

// Send the message
const params =
      { MessageBody: 'some-payload'
      , QueueUrl: 'https://sqs.us-east-1.amazonaws.com/123456/messages'
      }

sqs.sendMessage(params, (err, data) => {
  // err is the above-described error
})
```

Not sure if I need to provide additional configuration for the SQS service, this looks like all that the docs say is required.

Thanks for any help!

> aws-sdk version used: `2.2.20`

**Comment by chrisradek** [comment]
@Alaneor 
I don't see any issues with the code you've provided. The `QueueUrl` you provide gets parsed using the nodejs `url` module, and the error is indicating that `host` wasn't able to be extracted from the url. However, your url clearly contains a host. I haven't been able to reproduce the issue yet, can you share what version of node you are using?

**Comment by Alaneor** [comment]
Actually, you are right. :smile:

I had a custom function instead of the `url` parameter which was supposed to generate the queue URL based on some input. However, I used `path.join()` in it to construct the URL, but that messed up the protocol to be only `https:/`.

Switched to `url.resolve()` and all is well.

Sorry for this, my bad! And thanks for the fast response!
