### ISSUE TITLE
Presign.js: Unhandled rejection TypeError: Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by yarandoo** [aws/aws-sdk-js#834]
When trying to create a signedUrl for CreateMultipart upload operation in S3. The following stack trace can be found in the server. The original request from the clients fails with 504 timeout.

This issue started reproducing today, and previously we had no problems signing urls for multipart uploads.  We have not changed the Signer module in our system neither.

--------------------------------------------------
Elastic Beanstalk logs
--------------------------------------------------
Unhandled rejection TypeError: Cannot call method 'split' of undefined
    at Request.signedUrlSigner (/var/app/current/node_modules/aws-sdk/lib/signers/presign.js:56:43)
    at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /var/app/current/node_modules/aws-sdk/lib/event_listeners.js:163:9
    at finish (/var/app/current/node_modules/aws-sdk/lib/config.js:228:7)
    at /var/app/current/node_modules/aws-sdk/lib/config.js:244:9
    at /var/app/current/node_modules/aws-sdk/lib/credentials.js:123:23
    at /var/app/current/node_modules/aws-sdk/lib/credentials/ec2_metadata_credentials.js:66:7
    at callbacks (/var/app/current/node_modules/aws-sdk/lib/metadata_service.js:103:9)
    at /var/app/current/node_modules/aws-sdk/lib/metadata_service.js:116:15
    at IncomingMessage.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/metadata_service.js:74:45)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)

**Comment by chrisradek** [comment]
@yarandoo 
Can you share what version of the SDK you're on, if you're using v4 signing, and if possible, an example of the params being passed into the operation to create the signed url?

**Comment by yarandoo** [comment]
- SDK version: 2.1.33

**Comment by chrisradek** [comment]
@yarandoo 
Sorry for the late response. Can you share an example of the code you're using to presign the URL? It might also be worth trying the latest version of the SDK and seeing if the same issue presents itself.

**Comment by chrisradek** [comment]
Closing this issue due to lack of activity. Feel free to comment or reopen if you have further details!

**Comment by yarandoo** [comment]
Sorry for the late feedback. This issue was solved when we reviewed and fixed a credentials issue in our EBS application. No application code was changed. We were not able to reproduce the issue again.

Just wondering, would it be worth validating in presign.js line 56 that the variable where split is being invoked is not undefined? Or trying to understand why is being undefined in my scrnario?

**Comment by davidfurlong** [comment]
My secretKey credential was null & I got this error. I'd expect null credentials to throw an error when I do a new AWS.Credentials(key, secret) but at least when used/invoked and not this split nonsense
