### ISSUE TITLE
SyntaxError during parsing response of Lambda.listFunctions

### ISSUE THREAD

**Issue by kiwiholmberg** [aws/aws-sdk-js#846]
I have a lambda function that is trying to all list lambda functions. The function executes with admin permissions (for testing purposes). 

```
module.exports = {
    search: function(query, cb) {
        var lambda = new AWS.Lambda();

        lambda.listFunctions({}, function(err, data) {
            if (err) {
                console.log('Error listing lambda functions.', err.stack);
                return cb(err);
            }
            console.log('Response from list functions:', data);            
        });
    }
};
```

```
START RequestId: a0e5694b-a564-11e5-adb9-15af1ac48f84 Version: $LATEST
2015-12-18T08:52:12.525Z	a0e5694b-a564-11e5-adb9-15af1ac48f84	Error listing lambda functions. SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:29:18)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:37:9)
2015-12-18T08:52:12.526Z	a0e5694b-a564-11e5-adb9-15af1ac48f84	Error searching for lambda
2015-12-18T08:52:12.539Z	a0e5694b-a564-11e5-adb9-15af1ac48f84	{"errorMessage":"SyntaxError: Unexpected token <","errorType":"Error","stackTrace":["/var/task/aws_modules/stats/combine/handler.js:1:1032","Response.<anonymous> (/var/task/aws_modules/stats/combine/handler.js:1:4284)","Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:353:18)","Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)","Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)","Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:595:14)","Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:21:10)","AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)","/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10","Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:37:9)"]}
END RequestId: a0e5694b-a564-11e5-adb9-15af1ac48f84
REPORT RequestId: a0e5694b-a564-11e5-adb9-15af1ac48f84	Duration: 141.68 ms	Billed Duration: 200 ms 	Memory Size: 1024 MB	Max Memory Used: 20 MB	
```

**Comment by chrisradek** [comment]
@kiwiholmberg 
Could you log the raw body as well? You can do that by logging `this.httpResponse.body.toString()` from within the `listFunctions` callback. You should get a string representation of a well-formed JSON response.

Also, here's a very simple example of calling `listFunctions` from within lambda that is working for me that you can also test with:

```javascript
var AWS = require('aws-sdk');

exports.handler = function(event, context) {

    var lambda = new AWS.Lambda();
    lambda.listFunctions({}, function(err, data) {
        if (err) {
            context.fail(err);
        }
        context.succeed(data);
    });
};
```

**Comment by kiwiholmberg** [comment]
The body i get in the callback from listFunctions is 
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Page Not Found</title>
</head>
<body>Page Not Found</body>
</html>
```
Not sure if this should be possible to get as a response, since you would expect a JSON response.

I tried your minimal example and it works, so i guess that means I'm doing something wrong in how i use the SDK. I'll take another shot at it tomorrow and see if i can work it out.

Thanks for your time Chris, much appreciated!

**Comment by chrisradek** [comment]
Closing this issue since the minimal example worked. Feel free to comment, reopen, or create a new issue if you're still having issues!
