### ISSUE TITLE
Upgrade to 2.2.24 Caused An Issue with CloudFront

### ISSUE THREAD

**Issue by ftkendrakuhl** [aws/aws-sdk-js#848]
Here's the error message:

c:\SourceCode\openpd\src\server\node_modules\mlpi\node_modules\aws-sdk\lib\service.js:495
          throw AWS.util.error(err, {
                         ^
MODULE_NOT_FOUND: Could not find API configuration cloudfront-2015-07-27*git stat
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.load [as apiLoader] (c:\SourceCode\openpd\src\server\node_modules\mlpi\node_modules\aws-sdk\lib\api_loader.js:104:13)
    at Function.defineServiceApi (c:\SourceCode\openpd\src\server\node_modules\mlpi\node_modules\aws-sdk\lib\service.js:493:22)
    at getLatestServiceClass (c:\SourceCode\openpd\src\server\node_modules\mlpi\node_modules\aws-sdk\lib\service.js:80:19)
    at loadServiceClass (c:\SourceCode\openpd\src\server\node_modules\mlpi\node_modules\aws-sdk\lib\service.js:70:19)
    at Service (c:\SourceCode\openpd\src\server\node_modules\mlpi\node_modules\aws-sdk\lib\service.js:26:29)
    at new util.inherit.features.constructor (c:\SourceCode\openpd\src\server\node_modules\mlpi\node_modules\aws-sdk\lib\util.js:654:24)
    at Object.<anonymous> (c:\SourceCode\openpd\src\server\node_modules\mlpi\lib\util\StorageUtil.js:18:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

I reverted back to 2.2.22 and this fixed my problem. Here's the line that starts it all:
var cloudfront = new aws.CloudFront({apiVersion: '2014-01-31'});

**Comment by chrisradek** [comment]
@ftkendrakuhl 
Thanks for reporting this issue. I'll be pushing up a fix shortly.

**Comment by chrisradek** [comment]
@ftkendrakuhl 
A new version of the SDK has been released to fix this issue, version 2.2.25.  Thank you for reporting this!
