### ISSUE TITLE
Cloudformation: TemplateURL in parameters

### ISSUE THREAD

**Issue by synthe** [aws/aws-sdk-js#864]
When updating or creating stacks. I am unable to use an s3 url for deploying cloudformation templates.

I am not setting __TemplateBody__, and am setting __TemplateURL__. The exact same parameters work when I set TemplateBody and exclude TemplateURL. I have also tried the format "TemplateUrl" but that shows up as an unrecognized parameter error.

My Parameters:
```
{
  StackName: 'stack-name-1',
  OnFailure: 'ROLLBACK',
  Parameters: [{
    ParameterKey: 'AppEnvironmentType',
    ParameterValue: 'dev',
    UsePreviousValue: false
  }],
  Tags: [{
    Key: 'Owner',
    Value: 'email@example.com'
  }],
  Capabilities: ['CAPABILITY_IAM'],
  TemplateURL: 'https://s3-us-west-2.amazonaws.com/BUCKET/PATH/FILE'
}
```

Call: 
```
cf.createStack(cftParams, createCallback);
```

Error Received:
```
Message:
    Either Template URL or Template Body must be specified.
Details:
    code: ValidationError
    time: Wed Jan 06 2016 14:57:40 GMT-0800 (PST)
    requestId: e384ace4-b4c8-11e5-9191-8fbf647a32e8
    statusCode: 400
    retryable: false
    retryDelay: 30
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
ValidationError: Either Template URL or Template Body must be specified.
    at Request.extractError (/myapp/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/myapp/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/myapp/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/myapp/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/myapp/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/myapp/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /myapp/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/myapp/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/myapp/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/myapp/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

Node Version: 4.2.4
NPM Version: 2.14.7
aws-sdk module version: 2.2.27

**Comment by chrisradek** [comment]
@synthe 
I wasn't able to reproduce the issue you're seeing on my end using the parameters you provided. Could you add `logger: console` to the parameters passed in when initializing your CloudFormation client? This will cause the parameters that were used in the request to be logged to the console once the response comes back.

One thing to check is that the cloudformation stack you are creating is in the same region as your S3 bucket, otherwise you'll encounter issues as well.

**Comment by synthe** [comment]
Found my issue after logging output. I was checking TemplateUrl somewhere instead of TemplateURL.
