### ISSUE TITLE
RangeError: Maximum call stack size exceeded S3 PutObject in Browser

### ISSUE THREAD

**Issue by murilomothsin** [aws/aws-sdk-js#870]
Hello, i'm having the folowing error 
```
RangeError: Maximum call stack size exceeded
    at u.e (aws-sdk.min.js:6)
    at n.i [as runTo] (aws-sdk.min.js:7)
    at aws-sdk.min.js:7
    at u.e (aws-sdk.min.js:6)
    at n.i [as runTo] (aws-sdk.min.js:7)
    at aws-sdk.min.js:7
    at u.<anonymous> (aws-sdk.min.js:6)
    at u.<anonymous> (aws-sdk.min.js:6)
    at u.h [as callListeners] (aws-sdk.min.js:7)
    at s (aws-sdk.min.js:7)(anonymous function) @ angular.js:11655(anonymous function) @ angular.js:8596n.$apply @ angular.js:14567(anonymous function) @ angular.js:21571n.event.dispatch @ jquery.min.js:3r.handle @ jquery.min.js:3
2016-01-11 22:13:17.018 angular.js:11655 RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (native)
    at a (http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:6:25627)
    at u.e (http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:6:25849)
    at n.i [as runTo] (http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:7:22501)
    at http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:7:22715
    at u.e (http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:6:25931)
    at n.i [as runTo] (http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:7:22501)
    at http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:7:22715
    at u.e (http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:6:25931)
    at n.i [as runTo] (http://system.scopi.com.br/app/assets/js/aws-sdk.min.js:7:22501)(anonymous function) @ angular.js:11655(anonymous function) @ angular.js:8596n.$apply @ angular.js:14567(anonymous function) @ angular.js:21571n.event.dispatch @ jquery.min.js:3r.handle @ jquery.min.js:3
```

I was using your plugin inside angular, the error occurs in some cases. I don't know how to solve this.

My code is like this:

```
var bucket = new AWS.S3({ params: { Bucket: 'bucket_name/' + 'database_' + clientName } }); 
var params = {
      	Key: $scope.document.encrypted_file,
      	ContentType: $scope.document.type,
      	Body: $scope.file,
      	ContentDisposition: 'attachment; filename=' + $scope.document.file,
      	ServerSideEncryption: 'AES256'
      };

      bucket.putObject(params, function(err, data) {
        if(err) {
        	$scope.DocumentForm['file'].$invalid = true;
		$scope.DocumentForm['file'].$error[err.code] = err.message;
		return false;
        }else {
           console.log("ok");
        }
      });

```

Thanks

**Comment by chrisradek** [comment]
@murilomothsin 
Is this the same code that's causing the issue? Are you checking any objects for equality within the callback, or any function that gets called from the callback? It sounds like this issue usually happens in angular when two objects are compared for value and a circular reference is encountered.

**Comment by murilomothsin** [comment]
@chrisradek 
Hi, today i was testing, first updated the lib, my version was 2.0.9. After that i received a different error, "DOMException 12". So, the error occurs in line 1851, when the headers are set. I printed in the console the content. I have a key: "Content-Disposition" and value: "attachment; filename=Avaliação Encontro anual da visão Lojas Paty’s.doc". So with filenames without special characters the error not occurs, I will treat this. 

Thank you.
