### ISSUE TITLE
Package does not work with ES6 import

### ISSUE THREAD

**Issue by ffxsam** [aws/aws-sdk-js#907]
I'm using Meteor 1.3 with NPM packages just fine, except aws-sdk refuses to behave. I have the following:

    import AWS from 'aws-sdk';

And I get the following error:

```
/Users/samh/.meteor/packages/meteor-tool/.1.1.13-modules.8.jba49u++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
						throw(ex);
						      ^
ReferenceError: __dirname is not defined
    at meteorInstall.node_modules.aws-sdk.lib.api_loader.js (node_modules/aws-sdk/lib/api_loader.js:4:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.node_modules.aws-sdk.lib.aws.js (node_modules/aws-sdk/lib/aws.js:5:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.lib.collections.tracks.js (/Volumes/SuperData/Sites/project-new/.meteor/local/build/programs/server/app/app.js:223:15)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at /Volumes/SuperData/Sites/project-new/.meteor/local/build/programs/server/app/app.js:399:1
Exited with code: 8
```

**Comment by LiuJoyceC** [comment]
Hi @ffxsam 
What version of Node.js are you using? The `__dirname` variable is a global variable in Node.js and should not be undefined.

**Comment by ffxsam** [comment]
Never mind, closing. This is probably a Meteor issue, not an issue with this package.

**Comment by jeskew** [comment]
@ffxsam You might want to try [the browser version](https://aws.amazon.com/sdk-for-browser/) if you plan on using the SDK in a Cordova app.

**Comment by ffxsam** [comment]
It's not a Cordova app. It's just that Meteor is a different ecosystem (even though it's Node-based). And I'm trying to use the `aws-sdk` package server-side. I've filed a bug in the Meteor project for this.

**Comment by ffxsam** [comment]
For anyone else who stumbles upon this looking for help with Meteor:

https://github.com/meteor/meteor/issues/6285
