### ISSUE TITLE
Getting "TypeError: Cannot read property 'length' of undefined" in the web inspector console even when network logs a successful request

### ISSUE THREAD

**Issue by ruthienachmany** [aws/aws-sdk-js#977]
Hi,

I'm using the 2.3.5 version of the AWS Javascript SDK. When I run:

```
AWS.config.region = 'us-east-1';
var cognitoidentity = new AWS.CognitoIdentity();
var provider_url = MY_OIDC_PROVIDER_URL
var logins = {};
logins[provider_url] = MY_JWT_RETURNED_FROM_OIDC_PROVIDER;
var idparams = {
AccountId: MY_ACCOUNT_ID,
IdentityPoolId: MY_ID_POOL_ID,
Logins: logins
};
cognitoidentity.getId(idparams, function(err, data) {
if (err) console.log(err, err.stack);
else     console.log(data);
});
```

I get back this error in my web inspector console:
```
Error: Cannot read property 'length' of undefined(…) "TypeError: Cannot read property 'length' of undefined
    at i (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:1929)
    at a.SequentialExecutor.a.util.inherit.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:27756)
    at a.SequentialExecutor.a.util.inherit.emit (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:27465)
    at a.Request.s.emitEvent (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:15469)
    at e (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:11925)
    at a.runTo (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:24:27302)
    at https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:24:27509
    at .<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:12135)
    at .<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:15524)
    at a.SequentialExecutor.a.util.inherit.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.min.js:23:27862)"
```

From inspecting the stack trace, it seems to be caused by there being no body of the response (thus response.body.length fails).

However, when I inspect my network logs, I get back a JSON returning {IdentityId: 'MY_IDENTITY_ID'}, so it seems like the request was successful.

^ Similar thing happens when I call cognitoidentity.getOpenIdToken(params), posting the id token returned from the cognitoidentity.getId(params) call above, and when I take the token returned from the cognitoidentity.getOpenIdToken(params) call and post it to sts.assumeRoleWithWebIdentity (the only difference here is that when I inspect the logs for the STS call, the content-type request headers are 'application/x-www-form-urlencoded' and the request returns XML, versus the two CognitoIdentity calls which have content-type request headers of 'application/x-amz-json-1.1').

I'm not clear on how I can 1) get back the response I observe in the network logs so I can use the data from it - when I pass in a callback to return data, no data is returned from my request; and 2) how can I understand and prevent the error triggered by there appearing to be no body of the response (or whatever may be causing "TypeError: Cannot read property 'length' of undefined")?

Thanks for your help,
Ruthie

**Comment by LiuJoyceC** [comment]
Hi @ruthienachmany 
I was not able to reproduce your error with the code you provided above. It will help if you could temporarily replace the minified CDN with the non-minified version (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js) and then provide the same error stack trace as you did above, so that I can see exactly where in the code the error is coming from. Also, which browser are you getting this error in? Does this occur in multiple browsers?

**Comment by ruthienachmany** [comment]
Hey Joyce,

Thanks so much for your help.

After replacing the minified CDN with the non-minified version, here is my error stack trace for cognitoidentity.getId();

Here is the error I got on Chrome:
Error: Cannot read property 'length' of undefined(…) "TypeError: Cannot read property 'length' of undefined
    at Request.extractError (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3057:24)
    at Request.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4743:20)
    at Request.emit (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4717:10)
    at Request.emit (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3923:14)
    at Request.transition (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3705:10)
    at AcceptorStateMachine.runTo (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6563:12)
    at https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6575:10
    at Request.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3721:9)
    at Request.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3925:12)
    at Request.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4753:18)"

Here is the error trace I got on Safari:
TypeError: undefined is not an object (evaluating 'httpResponse.body.length') — aws-sdk-2.3.5.js:52910
"extractError@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3057:24
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4743:25
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4717:23
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3923:18
transition@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3705:14
runTo@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6563:16
https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6575:15
https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3721:13
https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3925:16
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4753:22
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4717:23
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3923:18
transition@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3705:14
runTo@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6563:16
https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6575:15
https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3721:13
https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3925:16
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4753:22
callNextListener@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4733:25
onEnd@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:1665:15
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:9339:21
finishRequest@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:2140:17
https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:2065:27
https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:8021
l@https://MYACCOUNTNAMEokta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10274
T@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10431
onreadystatechange@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10679"

Here is the one from Firefox:
TypeError: httpResponse.body is undefined
Stack trace:
extractError@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3057:1
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4743:11
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4717:5
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3923:5
[36]</</fsm.setupStates/transition@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3705:5
runTo@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6563:3
runTo/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6575:5
[36]</</fsm.setupStates/transition/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3721:9
emit/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3925:7
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4753:5
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4717:5
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3923:5
[36]</</fsm.setupStates/transition@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3705:5
runTo@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6563:3
runTo/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6575:5
[36]</</fsm.setupStates/transition/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3721:9
emit/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3925:7
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4753:5
callNextListener@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4733:7
onEnd@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:1665:11
[72]</EventEmitter.prototype.emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:9339:9
finishRequest@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:2140:5
handleRequest/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:2065:9
o/n[s]@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:8014
t[g]/l@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10270
t[g]/T@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10430
t[g]/I.onreadystatechange@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10678
 extractError@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3057:1
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4743:11
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4717:5
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3923:5
[36]</</fsm.setupStates/transition@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3705:5
runTo@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6563:3
runTo/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6575:5
[36]</</fsm.setupStates/transition/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3721:9
emit/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3925:7
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4753:5
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4717:5
emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3923:5
[36]</</fsm.setupStates/transition@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3705:5
runTo@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6563:3
runTo/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:6575:5
[36]</</fsm.setupStates/transition/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3721:9
emit/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:3925:7
callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4753:5
callNextListener@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:4733:7
onEnd@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:1665:11
[72]</EventEmitter.prototype.emit@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:9339:9
finishRequest@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:2140:5
handleRequest/<@https://sdk.amazonaws.com/js/aws-sdk-2.3.5.js:2065:9
o/n[s]@https://MYACCOUNTNAMEokta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:8014
t[g]/l@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10270
t[g]/T@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10430
t[g]/I.onreadystatechange@https://MYACCOUNTNAME.okta.com/js/sdk/okta-sign-in-1.1.0.min.js:230:10678

For now, I just ran the cognitoidentity.getOpenIdToken() and sts.assumeRoleWithWebIdentity() in Chrome, and did not get back an error but also did you receive any data back in my console though a successful response should have returned data such as a token back from STS or Cognito.

Hope that's helpful. Thanks! Please let me know if there's any other information I can provide.
-Ruthie

**Comment by ruthienachmany** [comment]
Hey,

I pulled the unminified AWS SDK code and putting a debugger in the extractError function - here is what I found:

1. The error is occurring because there an httpResponse with no body is not handled. Here is my httpResponse: 
HttpResponse {statusCode: undefined, headers: Object, body: undefined, streaming: false, stream: EventEmitter}

2. I also got this response with a more detailed stacktrace:
Error: An unknown error occurred. at Request.VALIDATE_RESPONSE (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:1631:37) at Request.callListeners (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:4745:20) at Request.emit (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:4719:10) at Request.emit (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:3925:14) at Request.transition (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:3707:10) at AcceptorStateMachine.runTo (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:6565:12) at https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:6577:10 at Request.<anonymous> (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:3723:9) at Request.<anonymous> (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:3927:12) at Request.callListeners (https://s3.amazonaws.com/MYBUCKET/js/aws_sdk.js:4755:18)

The only thing I can possibly think of here that might be going wrong is that the JWT which I am posting to Cognito does not use SSL server keys to sign their cert, they generate the keys this way: ```
JWKS_URI=`curl -s https://example.okta.com/.well-known/openid-configuration | egrep -o 'jwks_uri":"[^"]*' | cut -d '"' -f 3`;
curl -s $JWKS_URI | egrep -o '"x5c":\["[^]]*' | cut -d '"' -f 4 | tr -d '\' | base64 -D | openssl x509 -inform DER -pubkey -noout
``` . The developer evangelist on that team (which is Okta - specific details on their JWT setup here: https://github.com/jpf/okta-oidc-beta) suggested that that might be the issue, since the generate thumbprint for an OIDC provider instructions here (http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html) indicate that AWS generates the cert through `openssl s_client -showcerts -connect keys.example.com:443`. However, when I tried using the thumbprint generated via the former method, I got back this error in the browser console - "Invalid login token. OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint". When I tried using the thumbprint generated automatically from AWS and also generated when I ran the openssl command above, I did not receive that error, but I do receive the validation error described above. At the same time, this may not be the issue because as I described in a previous comment, when I preserve network logs, I see a successful response with a Cognito identity id which I can then use to post to CognitoIdentity.getopenidtoken and get back a successful response in the network logs (no browser console response) with an openid token I can post to STS and get back temporary credentials (also in the network logs) which I can then use to successfully access my AWS resources via API calls.

Hope that's helpful! Basically, given the relatively non-descriptive error messages, it's a little hard to tell whether there's some simple mistake in my setup or whether this is a bigger problem with OIDC setup and if there's any way I can get around it.

Thank you so much for your help!
Best,
Ruthie

**Comment by LiuJoyceC** [comment]
Hi @ruthienachmany 
If there was an issue with the JWT, then you would be receiving back an invalid login token error, as you mentioned above. The error should still be found in the `httpResponse.body`, so it doesn't seem like the JWT is what is causing your particular error.

The "unknown error occurred" that you are getting at Request.VALIDATE_RESPONSE is just the generic error the SDK initially attaches to the response when it does not get a successful response from the request, so that part is expected and it is not the error that is returned by the Cognito server. The Request.extractError step is normally where the SDK then extracts the error sent back by the server in `httpResponse.body` and replaces the generic "unknown error occurred" with the actual error, but it looks like in your case, the extractError step is not able to extract the error from `httpResponse.body` because it is undefined.

By the time you get to the Request.VALIDATE_RESPONSE step where you're getting the "unknown error occurred", is the `httpResponse.body` undefined already, or is it a buffer (even if it's a buffer of length 0) and it's somehow getting deleted by the time it gets to the extractError step? If the `httpResponse.body` is undefined by the time you get to the VALIDATE_RESPONSE

**Comment by ruthienachmany** [comment]
Hey @LiuJoyceC, was your response cut off here "If the httpResponse.body is undefined by the time you get to the VALIDATE_RESPONSE"? I'm looking into whether it's a buffer now.

**Comment by ruthienachmany** [comment]
Hey @LiuJoyceC,

This is the value of resp in validate_response:

for cognitoidentity.getid
![screen shot 2016-04-29 at 6 12 36 pm](https://cloud.githubusercontent.com/assets/4327442/14930993/03f8a47e-0e36-11e6-87f1-6f8ab0d8bd94.png)

for cognitoidentity.getopenidtoken
![screen shot 2016-04-29 at 6 05 40 pm](https://cloud.githubusercontent.com/assets/4327442/14930868/22ea0612-0e35-11e6-907a-c90edd0e7bb9.png)

The function HTTP_HEADERS is not getting run.

Thanks,
Ruthie

**Comment by ruthienachmany** [comment]
@LiuJoyceC The reason I think it may have to do with the JWT is that the thumbprint that I believe Cognito assumes to be the thumbprint to sign the OIDC (and there is no way in the UI to change this) is different than the thumbprint that Okta uses to sign their OIDC (not SSL server keys). I know that's not being messaged in the error, but it seems like a bug on AWS's end either way that when using the thumbprint AWS generates (but NOT the one that Okta actually uses), I am able to get back the Cognito id, Cognito Open ID token, and the STS temporary web identity credentials in the network logs, even while getting back these errors in the web inspector console. It may be an unrelated bug, but just because that's the only unusual part of my setup, I believe that may be related.

**Comment by LiuJoyceC** [comment]
Hi @ruthienachmany 
Sorry about the delay. You said that in your network logs, you can see that you're getting back a JSON in your response body. Are you getting back any response headers in your network logs? Since the `HTTP_HEADERS` callback is never getting called, it could be because no response headers were received.

**Comment by LiuJoyceC** [comment]
Also, could you enable the `logger` option on your Cognito Identity client and post your console logs here? To enable the logger, pass in your console when you instantiate the Cognito Identity client:
```
var cognitoidentity = new AWS.CognitoIdentity({logger: console});
```
Thanks.

**Comment by LiuJoyceC** [comment]
Closing due to inactivity.
