### ISSUE TITLE
Breaking change in patch level updates

### ISSUE THREAD

**Issue by justinmchase** [aws/aws-sdk-js#979]
I'm not sure which change broke us because we are using a dependency which is using `2.3.x` version of `aws-sdk`, but it happened sometime in the last two weeks. After updating and getting the latest version of this package I am now getting this error:

```
ValidationException: Member must satisfy enum value set: [B, N, S]
    at Request.extractError (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/request.js:596:14)
    at Request.transition (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/justin/code/snap-preview/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/request.js:598:12)
    at Request.callListeners (/Users/justin/code/snap-preview/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
```

Two things about this:

A) Any help in interpretting this would be helpful. What is an enum value for example? I'm not aware of using enum values at all so I'm not sure where to begin investigation.

B) Breaking changes should have Major version increments not Patch version increments. See definitions at [semver.org](http://semver.org/)

**Comment by justinmchase** [comment]
Nevermind, it's something else :-X my bad.

**Comment by justinmchase** [comment]
Turns out I had a range key in an index against a boolean field and this was causing the error. Somehow it was working and then wasn't... Not sure how that happened though, rolling back and trying every version of the aws sdk produced the same error. Must have had my DB in a weird state while it was working.
